### ISSUE TITLE
Weird Recipe Borders In JEI

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#100]
So in the latest version of JEI, borders were added to the separate recipes. Every GT machine's recipe box looks like this
![image](https://user-images.githubusercontent.com/25333164/41201420-dc1b4a82-6cb7-11e8-8317-d7a7e0c194d2.png)

**Comment by temp1011** [comment]
Looks like GUI is being drawn too large but it wasn't obvious until now.

**Comment by Archengius** [comment]
can't see any bug here

**Comment by temp1011** [comment]
Its off the bottom of the main screen. You can see the edge of the main screen at the edges.

**Comment by Rongmario** [comment]
What GUI setting are you using @EmosewaPixel?
This only occurs after build 4.10.0+ of JEI after the GUI refactoring.

**Comment by EmosewaPixel** [comment]
Automatic.

**Comment by Rongmario** [comment]
Can you try below 4.10.0+ JEI builds to see if this still occurs? @EmosewaPixel thank you.

**Comment by EmosewaPixel** [comment]
JEI didn't have any borders then.

**Comment by Archengius** [comment]
fixed probably
