### ISSUE TITLE
Liquid pipes or steam mechanisms do not work properly

### ISSUE THREAD

**Issue by WantaSanchez** [GregTechCE/GregTech#1001]
I just started to understand the mod, but when I tried to build the steam extractor, we connected directly to the boiler or through the pipes, after one operation it stopped working and I had to reinstall the unit. Also, i can't extract steam from tanks, why?

**Comment by Archengius** [comment]
steam vent side has to be open for a steam machine to operate
(it is indicated as a gray square on the back)
because tanks don't output anything automatically, you have to use pump cover

**Comment by WantaSanchez** [comment]
But vent side is open...

**Comment by Archengius** [comment]
if it works only for one operation, it means it can't vent steam double check it is not just open, but has air block.

**Comment by WantaSanchez** [comment]
I check, but nothing changed.

**Comment by WantaSanchez** [comment]
Maybe your mod is incompatible with some mod from my setup, or new forge?

**Comment by Archengius** [comment]
share full log please

**Comment by WantaSanchez** [comment]
[2020-01-07-3.log](https://github.com/GregTechCE/GregTech/files/4030399/2020-01-07-3.log)

**Comment by WantaSanchez** [comment]
Oh, thank's. Is working/
