### ISSUE TITLE
EBF aluminum recipe IllegalArgumentException

### ISSUE THREAD

**Issue by thePalindrome** [GregTechCE/GregTech#1008]
Log: https://pastebin.com/KhpT8aFB

A report from one of the IT3 players, the log indicates it's the latest GTCE, they note

> (the recipe was) aluminum, I read quest increased energy but get a crash after that the main unit disappears altogether
maybe I somehow did not build the structure correctly? , I as not tried to received a crash

Any thoughts on what to check for?

**Comment by thePalindrome** [comment]
Aha, update:
The issue arises if you manage to put down two input buses rather than an input and an output

**Comment by Archengius** [comment]
fixed in dev
