### ISSUE TITLE
[Suggestion] Add liquid physics

### ISSUE THREAD

**Issue by HonzaVinCZ** [GregTechCE/GregTech#1014]
Add liquid physics as flammability and consistency. Also change liquid texture when player dives into liquid ( If you dive into oil, the screen is still blue as under water, should be opaque )

**Comment by Archengius** [comment]
Flammability? Probably bad idea, remembering lags from burning Buildcraft oil sources

**Comment by HonzaVinCZ** [comment]
If it could be done better way than buildcraft had to not be laggy, it would be great. If I dismiss the flammability, what about the other things?
