### ISSUE TITLE
New Surface Nugget Models

### ISSUE THREAD

**Issue by MechanosG** [GregTechCE/GregTech#1019]
https://github.com/GregTechCE/GregTech/issues/854

Better late than never, eh?  Alright so I looked into making models myself, installed a couple model programs, but ended up never getting around to it.  But I did talk to the devs of the 2 previous mentioned mods with interesting models though.  I sent each dev a private message asking where they obtained their models, and specifically asked for permission for Archengius to use the surface sample models in Gregtech Community Edition.  Both devs replied saying they made the models themselves and are happy to let you use them, if you want.

First option, Simple Ore Samples made by Vaalerate
https://www.curseforge.com/minecraft/mc-mods/simple-ore-samples/screenshots
![Clipboard02](https://user-images.githubusercontent.com/4360512/73678615-91387f80-466d-11ea-98b0-940b698938e9.png)

Second option, Geolosys by oitsjustjose
https://www.curseforge.com/minecraft/mc-mods/geolosys/screenshots
![Clipboard03](https://user-images.githubusercontent.com/4360512/73678848-191e8980-466e-11ea-9f7f-0ad2199176c5.png)

Both sets of models have areas that can be color changed and are pretty nice looking in my opinion.  In my testing, Simple Ore Samples seemed to feel more immersive, and the slightly different model for gems is a nice touch.  I think the Simple Ore Samples models also have more exposed color, so they might get your attention more.  Anyway, I hope this helps.  I'd grab the models out of the jars for you, but I'm not 100% certain which files are needed, or if you still want them, etc.

**Comment by Archengius** [comment]
I'm fine with my own new model

**Comment by MechanosG** [comment]
I wasn't aware you had a new model and thought I was being helpful.  What's the new model look like?
