### ISSUE TITLE
workbench crash with FTBquesting

### ISSUE THREAD

**Issue by redgoblin88** [GregTechCE/GregTech#1020]
i have made a quest with FTB questing mod for a bronze ingot. it is already completed but whever i open the workbench GU, navigate to the chest/internal storage and left click bronze, i crash.

it appears when you left click an item in this mode, the item selected is automatically out inside without requiring you to manually move it, however this is what appears to cause FTB questing to crash

i have contacted Latvian modder on discord and his response is attached on the screenshot from "lat"

![image](https://user-images.githubusercontent.com/13396472/73688434-eef7b680-46c3-11ea-981a-e4a9c8595d6f.png)

versions:
Forge:  14.23.5.2847
GTCE:  1.9.0.481
FTBQ:  1.8.0.237

crashlog:
https://pastebin.com/5tS3inyA

**Comment by BraggestSage833** [comment]
Describe the bug:
I received the same error with FTB questing and GTCE, when manually placing an item in the secondary window of the crafting station.

Version:
Forge: 14.23.5.2854
FTBQuests: 1202.9.0.13
GTCE: 1.10.9.612

Modpack: none
Addons: None
Setup: Playing Solo
New world generated: Yes

Steps To Reproduce: 
Navigate to the secondary window/storage area of a Crafting station, and manually place/pick up any item in the station's inventory. 

Crash Log:
https://pastebin.com/8Y4NtGwh

**Comment by DStrand1** [comment]
I attempted to recreate this, and could not. I don't think this was fixed by FTBQuests in any way in ver. 14 or 15, but I don't know for certain (was not in the changelog anywhere).

Version:
Forge: 14.23.5.2847
FTBQuests: 1202.9.0.15
GTCE: 1.10.9.612

Modpack: Custom
Addons: Gregicality 0.21.1
Setup: Playing Solo
New world generated: Yes

**Comment by BraggestSage833** [comment]
Version:
Forge: 14.23.5.2854
FTBQuests: 1202.9.0.13
GTCE: 1.11.1.632

Modpack: none
Addons: None
Setup: Playing Solo
New world generated: Yes

Steps To Reproduce:
Navigate to the secondary window/storage area of a Crafting station, and manually place/pick up any item in the station's inventory.

Additional context: When placing any item in the secondary inventory window an error will be generated in the instance log.
