### ISSUE TITLE
Console Spam with Recipes

### ISSUE THREAD

**Issue by Osprey4444** [GregTechCE/GregTech#1021]
Outputs these two messages:
[12:28:26] [Server thread/ERROR] [gregtech]: Invalid amount of recipe outputs. Actual: 2. Should be between 1 and 1 inclusive.

and: https://hastebin.com/lelerofoxu.rb

**Comment by huneau** [comment]
Can you send your modpack ? 
I see that `outputs=[45xtile.glass@0, 4xitem.for.crafting_material@0]`
It seems one of your mod change the number of output from furnace recipe.

**Comment by fabrossmann** [comment]
Hey,
we have the same exact problem on our server:
https://pastebin.com/zMAW2E4h

We play the modpack Omnifactory 1.2.2 running on SpongeForge 1.12.2-2838-7.2.2. 

It is a pretty annoying bug, since our Logs went up to 200 MB after 6h, since 2 players used it constantly.

**Comment by LAGIdiot** [comment]
@fabrossmann from brief look at error I can tell that someone (most likely modpack author) is registering invalid recipes. Which GCTE is refuses to register/allow in its furnace. But it should not generate that much of logs to flood server. I will take a closer look at it later.

**Comment by ALongStringOfNumbers** [comment]
This issue in Omnifactory is specifically because we are using a very outdated version of GTCE, and has since been fixed in later GTCE versions. See the Omnifactory discord for a jar that contains a backported fix for this issue while we work on updating GTCE to the latest version, which should be ready after this latest release.

**Comment by fabrossmann** [comment]
Thanks for the fast update. We will look into the Fix!

**Comment by fabrossmann** [comment]
Hey the fixes are working perfectly thank you for your fast response!

**Comment by LAGIdiot** [comment]
I am closing this as data from opening comment are not available and issue for seconding reporter was solved.
