### ISSUE TITLE
Unknow reason cause game crash

### ISSUE THREAD

**Issue by fengeraien** [GregTechCE/GregTech#1023]
Unknow reason cause game crash,.
if players approch to the bug chunk, game will crash immediately.
this is full crash report below:

https://paste.ubuntu.com/p/fzQW4JyDmG/

**Comment by fengeraien** [comment]
It seems that pumps of gregtech extract liquid to immersiveengineering‘s fluid pipe cause the crash.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.2 (dev build on ee76c261078e4b7352893a2649e1ef71471cd6be)
Immersive Engineering: 0.12-98

**Enviroment:**
GTCE dev

**Outcome:**
Unable to reproduce, bug not confirmed.

**Additional notes:**
All places which would cause this kind of error are covered against generating it. No additional problems found.
