### ISSUE TITLE
[Suggestion]Balance the capacity of batteries

### ISSUE THREAD

**Issue by HoleFish** [GregTechCE/GregTech#1027]
The capacity of Lapotron Crystal is 4MEU, but the capacity of Energy Orb is 100MEU, one Energy Orb just costs 6 Lapotorn Crystals which is too cheap. Should the Energy Orb be more expensive or the Lapotron Crystal and low-level batteries contain more EU? I prefer latter.

**Comment by leagris** [comment]
Id suggest letting it as-is:
- Tech upgrade is not the sum of earlier tech.
- Minecraft crafting result has never been equals to the sum of ingredients, neither in volume, mass or even material units.

I see no reason to make it so the total capacity of The Energy Orb should be that of the total energy capacity of its Lapotron Crystals ingredients.

The huge leap in capacity is motivated by:
- The higher technological level of the Energy Orb.
- The incentive to upgrade rather than spam lower tech.

**Comment by HoleFish** [comment]
> Id suggest letting it as-is:
> 
> * Tech upgrade is not the sum of earlier tech.
> * Minecraft crafting result has never been equals to the sum of ingredients, neither in volume, mass or even material units.
> 
> I see no reason to make it so the total capacity of The Energy Orb should be that of the total energy capacity of its Lapotron Crystals ingredients.
> 
> The huge leap in capacity is motivated by:
> 
> * The higher technological level of the Energy Orb.
> * The incentive to upgrade rather than spam lower tech.



> Id suggest letting it as-is:
> 
> * Tech upgrade is not the sum of earlier tech.
> * Minecraft crafting result has never been equals to the sum of ingredients, neither in volume, mass or even material units.
> 
> I see no reason to make it so the total capacity of The Energy Orb should be that of the total energy capacity of its Lapotron Crystals ingredients.
> 
> The huge leap in capacity is motivated by:
> 
> * The higher technological level of the Energy Orb.
> * The incentive to upgrade rather than spam lower tech.

The problems are these:

1. Nano CPU and PIC are only the HV tech(at least player can get them in HV), however, they are the MAIN materials of the Energy Orb. The leap from HV to EV is acceptable(Lapotron Crystal is made from HV circuit), but I don't think the leap from HV to IV is.
2.As for the batteries from LV to EV, their capacity is four fold increaseing; the number is 10 for the batteries from IV to UV(SoG's responsibility?). EV to IV should be the transition, but the capacity growth is 25x.
English poor, so sorry about.
