### ISSUE TITLE
Solar Steam Boiler receives heat through the blocks of the other gregtech-machines

### ISSUE THREAD

**Issue by KenClaron** [GregTechCE/GregTech#103]
Solar Steam Boiler receives heat through the blocks of the other gregtech-machines
But not receive heat when another(no gregtech-machine) block is installed over the Solar Steam Boiler
![2018-06-10_15 17 40](https://user-images.githubusercontent.com/25456792/41201977-cbb1f458-6cca-11e8-890b-159f3956f58f.png)

**Comment by Archengius** [comment]
fixed
