### ISSUE TITLE
[Bug] Shutter Module not working properly

### ISSUE THREAD

**Issue by million09** [GregTechCE/GregTech#1030]
## Description
Shutter Module won't work properly in certain setup.

## To reproduce
1. Place these machines like the image below:
- HV Generator
- MV Machine (Input Hatch in the image)
- 4x MV Cables
- LV Machines with Shutter Module, preventing connection to cables
![image1](https://user-images.githubusercontent.com/61384207/75114650-42de3580-569b-11ea-8184-04367fd3809b.png)
2. Place HV Transformer (HV to MV).
3. Two of the LV Machines will explode.
![image2](https://user-images.githubusercontent.com/61384207/75114703-b5e7ac00-569b-11ea-8135-e2be39a695a3.png)

## Expected behavior
Won't explode due to Shutter Module.

## Version
gregtech-1.12.2-1.9.0.481.jar

**Comment by LAGIdiot** [comment]
Confirmed in 1.9.1. (dev build on commit 853ffbc44a239df957fbe4a434f2733810253e41).

Explosion occurs only on end of cables (connected to consumer/producer). Same problem with setup for higher voltage.

Working on fix...

**Comment by leagris** [comment]
Does it happens with other kind of covers?

**Comment by LAGIdiot** [comment]
There is none other cover that is supposed to prevent connection to machine right?

**Comment by leagris** [comment]
all plates, foils, unless configured to do so, computer screen, crafting table cover... To sum it up, all covers prevents electrical connection unless purposely allowed.

**Comment by LAGIdiot** [comment]
From when does GTCE have foils, computer screens, crafting table covers? I don't remember these and I don't see them in code.

**Comment by LAGIdiot** [comment]
And facades (that thing from plates and block) does not prevents electric connection

**Comment by Archengius** [comment]
facades are not meant to block them in first place
