### ISSUE TITLE
Incorrect output of Carbon Monoxide from Titanium Tetrachloride reaction

### ISSUE THREAD

**Issue by m2r1k5** [GregTechCE/GregTech#1035]
It should be 4B, instead of 2B.

The current reaction is 4B Chlorine + 2 Carbon Dust + 1 Rutile Dust -> 1B Titanium Tetrachloride + 2B Carbon Monoxide. By right the reaction is TiO₂ + 2C + 2Cl₂ -> 2CO + TiCl₄. Since 2B CO is made from 1B Oxygen and 1 Carbon Dust, only 1 Carbon and 1B Oxygen is reclaimed from the reaction - 2 each is the correct amount, so total 4B CO should be produced

**Comment by million09** [comment]
It seems it's intentional loss. Another example is here;
1B Titanium Tetrachloride + 2 Magnesium Dust -> 1 Hot Titanium Ingot + 2 Magnesium Chloride Dust
2 Magnesium Chloride Dust + 1 Sodium Dust -> 1.5 Magnesium Dust + 1.5B Chlorine

**Comment by pyure** [comment]
I believe you're right that its deliberate.  Closing this for now; you can remove/re-add the recipe independently via CraftTweaker if you wish.

**Comment by million09** [comment]
This was fixed in #1414.
