### ISSUE TITLE
[Suggestion] Add Extractor recipe for Beetroot

### ISSUE THREAD

**Issue by million09** [GregTechCE/GregTech#1037]
## Description
Poppy, Red Tulip, and Rose Bush have Extractor recipe. Add Beetroot to it;
Beetroot x1 -> Rose Red x2

**Comment by Agrax** [comment]
> ## Description
> Poppy, Red Tulip, and Rose Bush have Extractor recipe. Add Beetroot to it;
> Beetroot x1 -> Rose Red x2

Uh, use CraftTweaker?

**Comment by million09** [comment]
I know it. However, this recipe should exist in default, I think. Not everyone can write ZenScript.
