### ISSUE TITLE
[Suggestion] UniDict compatibility

### ISSUE THREAD

**Issue by MadRatSRP** [GregTechCE/GregTech#105]

**Comment by EmosewaPixel** [comment]
What exactly do you mean? GregTech already prioritizes other mods' items in its recipes.

**Comment by Rongmario** [comment]
GT already has unification.

Stop using Unidict, arguably the shittiest mod to ever exist.

**Comment by Zer0Lyfe** [comment]
sorry Rongmario but this is the shittest mod ever :P 
https://minecraft.curseforge.com/projects/poop

**Comment by Archengius** [comment]
i don't get what this issue means. GT can accept any ore dictionary item as it's inputs and outputs firstly registered ore dictionary item
