### ISSUE TITLE
Surface rock drops only Aluminium

### ISSUE THREAD

**Issue by LAGIdiot** [GregTechCE/GregTech#1050]
**Version:**
1.9.1 (dev build on 853ffbc44a239df957fbe4a434f2733810253e41)

**Environment:**
GTCE dev; new world generated

**Steps to reproduce:**
1. Find surface rock of any material (except Aluminium)
2. Brake it with pickaxe

**Expected:**
- surface rock is destroyed
- X tiny piles of material from which it was formed (copper for bornite vein as per bornite_vein definition) drops

**Actual:**
- surface rock is destroyed
- X tiny piles of Aluminium drops always

**Additional evidence:**
Before breaking
![2020-03-27_00 34 20](https://user-images.githubusercontent.com/3093101/77706736-7f1af380-6fc3-11ea-8525-05616dbe0cfe.png)
After breaking
![2020-03-27_00 34 41](https://user-images.githubusercontent.com/3093101/77706795-a70a5700-6fc3-11ea-984c-e95429a6532f.png)

**Comment by pyure** [comment]
Drops of surface rocks are generated by this code
```
    private ItemStack getDropStack(IBlockAccess blockAccess, BlockPos pos, IBlockState blockState, int amount) {
        Material material = getStoneMaterial(blockAccess, pos, blockState);
        return OreDictUnifier.get(OrePrefix.dustTiny, material, amount);
    }
```
Upon breaking a surface rock, **material** is always "aluminium".
Curiously, getDropStack is also called by getPickBlock which is called when you look at a surface rock.  And when you trigger it that way, "material" is actually the correct material.
So the problem is occurring when the block is mined for some reason.

**Comment by LAGIdiot** [comment]
I think that it is related to this part:

      @Override
      public Material getStoneMaterial(IBlockAccess blockAccess, BlockPos pos, IBlockState blockState) {
          TileEntitySurfaceRock tileEntity = getTileEntity(blockAccess, pos);
          if (tileEntity != null) {
              return tileEntity.getMaterial();
          }
          return Materials.Aluminium;
      }

Where `getTileEntity` returns null when surface rock is broken.

**Comment by pyure** [comment]
Yep it definitely does.  I'm guessing its a sort of race condition.  I wonder if we just need to sort out the drops before the tile entity is removed somehow.

**Comment by Archengius** [comment]
you need to do some hacking with using ThreadLocal and storing tile entity instance when breakBlock is called. See how it's done in BlockMachine.
