### ISSUE TITLE
[Question] How to add Chemical Formulas to other mod Items

### ISSUE THREAD

**Issue by whatsapp2** [GregTechCE/GregTech#1051]
What I'm trying to do is adding a chemical formula on a content tweaker item.
I'm trying to do the following:
var CuSO4 = <<contenttweaker:copper_sulphate>>;
CuSO4.chemicalFormula([<material:copper>*1, <material:sulfur>*1, <material:oxygen>*4]);
However minecraft gives me an error

**Comment by LAGIdiot** [comment]
Well that is not enough information to even start. So provide us with versions (MC, Forge, GTCE a Content Tweaker) and error you are getting. And I or anyone else may look at it.

**Comment by whatsapp2** [comment]
Minecraft Forge: 1.12.2-forge1.12.2-14-23-5-2838

Mod List:
gregtech-1.12.2-1.9.0.481
CraftTweaker2-1.12-4.1.19
ContentTweaker-1.12.2-4.9.1

My scripts:
Content Tweaker: https://pastebin.com/2ZWhGfRi
Gregtech: https://pastebin.com/sWKPiCQB
What I get on the chat [Copied from the Crafttweaker.log]: https://pastebin.com/h9V0STGr

**Comment by LAGIdiot** [comment]
This doesn't looks like a problem with this mode. As per message in log:
> [PREINITIALIZATION][CLIENT][ERROR] Gregtech And Content Tweaker.zs:18: Could not resolve \<contenttweaker : copper_sulphate\>

It looks like you are unable to load properly Copper Sulphate and put it to CuSO4 variable. Which means that when you call setChemicalFormula on CuSO4 it will fail as this variable is not set (is empty/null).

**Comment by whatsapp2** [comment]
So what should I do? Can you help me coding it?

**Comment by LAGIdiot** [comment]
I suggest that you go to CraftTweaker wiki and try to find anything about loading items registered in other scripts. Or you can jump to their Discord and ask questions there and someone may answer them.
As I said before this is not problem with this mode. If you find any problem regarding scripting features provided by GTCE feel free to come to GregTech CE Discord and ask in appropriate channel.

**Comment by pyure** [comment]
whatsapp2, you are welcome to hop into the discord channel to discuss specifics with GT crafttweaker.
