### ISSUE TITLE
Breaking 2x2 Tank is Lossy

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#1052]
(Master branch, adding as a reminder)

If 2x2 is broken, 3 tanks are left behind:
* Tank1: Full
* Tank2: 3/4 of (Tank1)
* Tank3: 3/4 of (Tank2)

If 2x2 is invalided by adding a 5th adjacent tank, similar result occurs except that you get 2 full tanks instead of 1.

**Comment by LAGIdiot** [comment]
**Version:**
1.9.1 (dev build on 8dc818b70e357b54ed90c965072caeb9bbe9c5dc)

**Environment:**
GTCE dev; new world generated

**Setup:**
2x2 Tank (Wooden - will use for calculation, Bronze) full of Liquid (Water, Nitro-Diesel).

**Steps to reproduce:**
1. Brake all tanks with pickaxe

**Expected:**
- 4 Tanks dropped, all full of liquid (4000 mb each), altogether 16000 mb

Case 1)
**Actual:**
- 4 Tanks dropped, 1. contains 6750 mb, 2. contains 3000 mb, 3. and 4. contains 3125 mb, altogether 16000 mb

Case 2)
**Actual:**
- 4 Tanks dropped, 1. contains 6750 mb, 2. contains 2250 mb, 3. and 4. contains 3500 mb, altogether 16000 mb

Case 3)
**Actual:**
- 4 Tanks dropped, 1. and 2. contains 4000 mb, 3. and 4. contains 2625 mb, altogether 13 250 mb

**Outcome:**
Bug confirmed

**Comment by pyure** [comment]
Problems seems connected to this:
`double fluidLevel = multiblockFluidTank.getFluidAmount() / (1.0 * multiblockFluidTank.getCapacity());`
Where we are determining fluid level as a percentage.  After you remove a tank from a 2x2, getFluidAmount() reports as 24000, but getCapacity() reports as 32000.  getCapacity() is just a getter for the capacity property.
