### ISSUE TITLE
Disassembler and MB Boiler

### ISSUE THREAD

**Issue by Aprax88** [GregTechCE/GregTech#1055]
hello dear mod creators!

I would like to know. will disassembler be added? as the game progresses, old mechanisms accumulate which cannot be further processed into resources or melted in an arc furnace.
I would also like to know. Will a mode of lowering steam production be added to multi-block boilers by reducing efficiency with the help of a microcircuit as it was in GT5?

**Comment by Archengius** [comment]
No, disassembler won't be added. There is similar feature called boiler throttle in dev.
