### ISSUE TITLE
JEI integer overflow with recipe

### ISSUE THREAD

**Issue by hjae78** [GregTechCE/GregTech#1068]
This occurs when the total required EU of a recipe exceeds int max. It can be fixed quite easily [here](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java) by simply casting the result of the multiplication to long.

**Comment by huneau** [comment]
![image](https://user-images.githubusercontent.com/9199240/80216693-bb7f5500-863e-11ea-81be-dec63cae790d.png)

**Comment by LAGIdiot** [comment]
Fixed in #1076.
