### ISSUE TITLE
JEI Recipe Category Conflict With IC2

### ISSUE THREAD

**Issue by TheLMiffy1111** [GregTechCE/GregTech#107]
Seems like the other issue didn't get any attention at all, opening a new one.
I was testing mods with both IC2 and GTCE installed in my runtime, and I wasn't able to view any categories of recipes added by IC2. After looking in the log, it says something like 'the recipe category "macerator" was already registered,' and this is a problem to me. This would be an issue on both sides though, but still, please don't ignore this.

**Comment by EmosewaPixel** [comment]
I think the simplest way to fix this would be adding gt_ to the start of the ids.

**Comment by Archengius** [comment]
fixed
