### ISSUE TITLE
Thorium Fuel Rods missing

### ISSUE THREAD

**Issue by armdn** [GregTechCE/GregTech#1073]
There is no Thorium Fuel Reactor rods... So the present of thorium itself is almost useless in mod then.

**Comment by LAGIdiot** [comment]
Thank you for reporting that. We are aware that we have few items without any use in current state of mod. Most of these are automatically generated for use in later features. 

Right now we can't remove them or hide them as it would produce compatibility issue with ad-dons or modpacks and possible braking them.

Of course there are plans for their use for example in #246 , but priorities are currently else where.
