### ISSUE TITLE
IC2 + GTech Power Cable compatibility issue

### ISSUE THREAD

**Issue by armdn** [GregTechCE/GregTech#1074]
There is a problem with connection between IC2 power sources to GTech devices. Cables are not connecting to transformers. Even energy transformers not sending energy (from IC2 to GT).

**Comment by Agrax** [comment]
That functionality is purposefull. GTCE is meant to not work with IC2 as they are 2 separate mods. Earlier versions of GT were a meaningful addon for IC2, but in this case energy incompatibility makes sense. You can still use CEU (addon for GTCE) to change IC2 eu vs GTCE eu. GTCE eu is a standalone energy unit that just happens to share the name w/ IC2's energy unit

**Comment by Archengius** [comment]
> GTCE is meant to not work with IC2 as they are 2 separate mods
