### ISSUE TITLE
Assembler recipes requiring liquids cover total EU 

### ISSUE THREAD

**Issue by Zeruel13** [GregTechCE/GregTech#1077]
Some recipes e.x. assembler recipes that require liquid in addition to items will cover the total EU required when viewing the recipe

![image](https://user-images.githubusercontent.com/63512252/81096751-e2f2df00-8ed4-11ea-80c8-7dbaecf53b0a.png)

**Comment by ALongStringOfNumbers** [comment]
I am seeing similar on version 1.9.1.505. I went through and checked on all the single block machines, and the assembler was the only place where I noticed this taking place, due to the layout of the liquid slots in relation to the position of the item slots.

**Comment by huneau** [comment]
Not an easy fix due to the auto-generated layout. This also cause me issue :/

**Comment by LAGIdiot** [comment]
Closed by: #1118
