### ISSUE TITLE
Electric pump not pumping

### ISSUE THREAD

**Issue by Hamsterotron9000** [GregTechCE/GregTech#1078]
Electric pumps do not pump more water than there is in the source from where they get it (if its a 3x3 source it will not give more than 9 buckets of water), steam pump working fine

**Comment by LAGIdiot** [comment]
Electric pumps are working correctly. It is design decision that thy don't support infinite water source pumping. Steam pumps that you are comparing it to are not even from GTCE.

**Comment by Hamsterotron9000** [comment]
Didnt know about it, whats sad, i guess i need to find anothet way to pump tons of water on skyblock

**Comment by LAGIdiot** [comment]
Closed as **design decision not a bug**.
