### ISSUE TITLE
[Suggestion] Toggle 'Module' Support

### ISSUE THREAD

**Issue by DarkAmbientNoise** [GregTechCE/GregTech#1084]
Great mod, but when running in large modpacks, (about 320 mods for a private server), not every feature is needed, and with how this mod auto-generates a lot of it's features, it would be nice to be able to disable some things like the tanks and cells in the config file as every new material generates it's own instance.

Due to this, this auto-generation makes up about 1/6th of all JEI instances in a large modpack for just the tanks and cells, and the entire mod is about 1/3 of all instances. Perhaps I'm missing something, but for those of us who aren't great with CraftTweaker and other such mods, it would be nice to be able to have a toggle switch for some of these items.

**Comment by Agrax** [comment]
Well, GTCE is certainly a mod that all others should be centered around IMHO... I'd rather drop other mods' tanks and cells in favor of their GTCE counterparts...

**Comment by pyure** [comment]
For stuff like cells and tanks, so long as there are no other dependencies (such as recipes that depend on cells or tanks) I don't see why it couldn't be done.

**Comment by Samrel556** [comment]
A config option to at least hide filled versions of all of the fluid containers would be amazing. Most other mods that add their own fluid containers have the option.
