### ISSUE TITLE
[Bug] Full 3-Dimensional Axis Viewing And Zoom Support In JEI's Multi-block Pattern Category / Text Overlap

### ISSUE THREAD

**Issue by DarkAmbientNoise** [GregTechCE/GregTech#1089]
I love that we can now see how to build the multi-block structures through JEI now, as I don't remember that being a feature around 2 years ago. However for some machines, it can be confusing, especially for newer users of the mod to know exactly how to build the machines.

Problem: The view-field that we get tends to be too zoomed in and only supports the X and Y axis for rotation, which is nice, but makes it impossible to see internal blocks of the structure for something like the Fusion Reaction Computers. Rotating around this block is also a little confusing to find where you left off at.

![FRC Full](https://user-images.githubusercontent.com/12950685/83263185-d1bf8a00-a183-11ea-81e9-2d7604601be8.png)

Layering the multi-block can help on some of these structures, but only where it is a taller one as it forces the rendered layer to have a somewhat top down view, closer to isometric rather than on one direct face, but on others like this one, it doesn't.

![FRC Layer 2](https://user-images.githubusercontent.com/12950685/83263310-003d6500-a184-11ea-9cdf-cc48912f37e1.png)

Expected Feature: Able to see a full 3-D version of the model, accessing the Z axis simply by clicking and dragging up or down. Zooming out with the scroll wheel while the mouse is in the 3-D view-port would severely help for larger structures along side the Z axis improvement. Removing text overlapping would also be convenient if possible.

Note: I checked the closed issues and there was one that was mentioning a few things about this and was primarily about missing the rendering of specific blocks, though it didn't seem to have much info aside from it being an issue with newer versions. (Issue #945). This is clearly a back-burner bug fix, as a stable mod is more important, but it would be nice.

**Comment by ALongStringOfNumbers** [comment]
Everything in this issue should now be done as of #1583. Please feel free to open a new issue if this is not the case.
