### ISSUE TITLE
machine goes invisible using optifine shaders 

### ISSUE THREAD

**Issue by tsukaerujuriki2** [GregTechCE/GregTech#1091]
[latest.log](https://github.com/GregTechCE/GregTech/files/4707032/latest.log)
I used the latest optifine and GTCE
It goes invisible when i place or break block close to surface rock
and in chat it saed CCL caught an exception and then most machine and tank goes invisible until restart

**Comment by huneau** [comment]
[12:53:15] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
I see that in the log, can you downgrade to 2848 plz and telling me if still an issue

**Comment by tsukaerujuriki2** [comment]
[latest.log](https://github.com/GregTechCE/GregTech/files/4757738/latest.log)
I downgraded forge but the same problem still occurs

**Comment by tsukaerujuriki2** [comment]
It happend when I enabled any shader pack and then placed/broke any block near the surface rock
I'm only using 
Forge 14.23.5.2847
CodeChicken Lib 1.12.2-3.2.3.358-universal
gregtech-1.12.2-1.9.1.507
OptiFine_1.12.2_HD_U_F5
And I tried using SESU-Renewed 1.0.1 and sildurs shader v1.27 It went invisible
 BSL_7.1.0.1.4 The machine texture went compleatly black

**Comment by tsukaerujuriki2** [comment]
![2020-06-13_12 41 33](https://user-images.githubusercontent.com/65273487/84558065-52c97480-ad73-11ea-9160-564695b1dbd2.png)

**Comment by huneau** [comment]
@tsukaerujuriki2 one of my guys have the same issue and finally, find a solution 
`turned "catchBlockRenderExceptions" false`

**Comment by tsukaerujuriki2** [comment]
I made it false then the game crashed while loading the world
[crash-2020-06-14_11.25.29-client.txt](https://github.com/GregTechCE/GregTech/files/4775733/crash-2020-06-14_11.25.29-client.txt)

**Comment by huneau** [comment]
@tsukaerujuriki2 can you try by creating a new world, remove surface rock for worldgen file ?
someone notice me that was working for him by removing surface rock

**Comment by tsukaerujuriki2** [comment]
It stopped making an error by removing the surface rock
But finding veins will be hard without it...

**Comment by huneau** [comment]
ok so the issue is somewhere surface rock now we can investigate correctly thx @tsukaerujuriki2

**Comment by LAGIdiot** [comment]
@tsukaerujuriki2 Thank you for providing us with valuable data regarding this problem. And also thank you for testing suggested workaround **removing surface rocks from world gen files**.

I am accepting this bug for fixing. That being said this is related to other mod with which we don't actively maintain compatibility and it does not affect big part of our player base. So priority from my point of view is low. Needles to say if someone provides PR fixing this issue I will be happy to review it.

**Comment by trushoff** [comment]
Still no fix?
