### ISSUE TITLE
[GTCE 1.9.1.505] Surface Rock error

### ISSUE THREAD

**Issue by whatsapp2** [GregTechCE/GregTech#1092]
Mod Version: 1.9.1.505
Forge version: 14.23.5.2854
Allocated Memory: 12 GB
List of mods: https://pastebin.com/QgPeD5du
Crash report: https://pastebin.com/RQDbwc4b
will this bug be fixed in the next version?

**Comment by LAGIdiot** [comment]
Known workaround: Downgrade Forge to 14.23.5.2847
Fixing it is on list with high priority but it is quite complex problem so I can't guarantee it will be fixed soon.
