### ISSUE TITLE
Light Gray Spray Can only accepts Light Gray Dye

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1096]
GTCE Version: 1.9.1.505

The Spray Can assembler recipe for the Light Gray Spray can only accepts Light Gray dye from GTCE, while all the other spray cans accept an oredict entry for their specific dye color. The Light Gray spray can recipe should be updated to be equal with all the other spray can recipes, and accept any oredicted Light Gray Dye.

**Comment by LAGIdiot** [comment]
**Version:**
1.9.1 (dev build on b528a73c02d85518a08d1d1eb827713fc50179e2)

**Environment:**
GTCE dev

**Test scope:**
JEI recipe checked. Construction of Spray Can (Light Gray) via Assembler.

**Outcome:**
Bug confirmed.

**Additional notes:**
There is problem in a way GTCE has registered Light Gray Dye which is not compatible with Vanilla MC Light Gray Dye. So other recipes like Light Gray Wool can't use is.

**Comment by LAGIdiot** [comment]
Fixed by #1098 in #1100.
