### ISSUE TITLE
[Suggestion for packdevs] Two more input slots for all Alloy-Smelter machines

### ISSUE THREAD

**Issue by Freebi85** [GregTechCE/GregTech#1103]
As the title says, it would be great if the alloy smelter could hold more than just 2 items. So you could create much more complex alloys and include as packmaker foreign alloys like signalum that needs 3-4 ingredients.

Cheers 😄

**Comment by LAGIdiot** [comment]
I think that current setup with only two input slots is adequate for it's task. As @Agrax mentioned for harder recipes (with more then two inputs) there is already solution how to combine them and that is Mixer or even standard Crafting Table.

**Comment by LAGIdiot** [comment]
I am closing this as wontfix because it bring us way too little benefits from implementing. As I stated before there already exist progression path which we recommend.
