### ISSUE TITLE
 The recipe does not work

### ISSUE THREAD

**Issue by mgun82** [GregTechCE/GregTech#1114]
The copper cable recipe in the assembly machine does not work. Without this cable I can not make the mv machine case.

**Comment by pyure** [comment]
Which specific recipe? (There may be a few)
Which modpack?  
Strongly suspect this issue is on your end (Everyone would have noticed this a long time ago)

**Comment by mgun82** [comment]
> "Which specific recipe? (There may be a few)"
![Assembler2](https://user-images.githubusercontent.com/67557649/85956875-74407800-b991-11ea-93e0-3f4323590ca9.png)
![JEI recipe](https://user-images.githubusercontent.com/67557649/85956877-7571a500-b991-11ea-9a35-18027dab2f7e.png)

> "Which modpack?"
![Mods](https://user-images.githubusercontent.com/67557649/85956929-a7830700-b991-11ea-8fc2-d22e6f829527.png)

> "Which version of GT-CE?"
gregtech-1.12.2-1.9.1.507

> "Strongly suspect this issue is on your end (Everyone would have noticed this a long time ago)"
I do not exclude

**Comment by pyure** [comment]
Did you configure that circuit to the correct number?  (Done by right-clicking the circuit in hand)

**Comment by mgun82** [comment]
You're right. I tried tuning in the assembly machine. Thank you
