### ISSUE TITLE
The steel chest is invisible!

### ISSUE THREAD

**Issue by Alendill** [GregTechCE/GregTech#1115]
The steel chest is invisible!
The steel chest is invisible!
The steel chest is invisible!

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue to us. But in way you reported there is not much we can do about it. If you want us to take a serious look at it please provide us with these additional information:

- What version of GregTech you are playing at?
- What version of Forge you are playing at?
- Do you use Optifine? If so provided us with it's version and configuration.
- Do you have this problem in modpack? If so provided us with it's name, (link to CurseForge) and version. And any modifications you applied on it.
- Does this happens every time or just under certain circumstances? Steps to reproduce would be handy.
- Does this happens only for this specific type of block or does it happens on other (GTCE chests, machines tanks) too?

**Comment by Alendill** [comment]
Thank you for your replying. 
MC Version: 1.12.2
Forge Version: 14.23.5.2847
GTCE Version: gregtech-1.12.2-1.9.1.507

**Comment by Alendill** [comment]
> Thank you for reporting this issue to us. But in way you reported there is not much we can do about it. If you want us to take a serious look at it please provide us with these additional information:
> 
> * What version of GregTech you are playing at?
> * What version of Forge you are playing at?
> * Do you use Optifine? If so provided us with it's version and configuration.
> * Do you have this problem in modpack? If so provided us with it's name, (link to CurseForge) and version. And any modifications you applied on it.
> * Does this happens every time or just under certain circumstances? Steps to reproduce would be handy.
> * Does this happens only for this specific type of block or does it happens on other (GTCE chests, machines tanks) too?

Thank you for your replying. 
MC Version: 1.12.2
Forge Version: 14.23.5.2847
GTCE Version: gregtech-1.12.2-1.9.1.507

**Comment by LAGIdiot** [comment]
If I understand correctly you changed GTCE mod file and everything works now correctly? Where did you get that problematic archive?

**Comment by Alendill** [comment]
> If I understand correctly you changed GTCE mod file and everything works now correctly? Where did you get that problematic archive?

I made a mod pack include gregtech-1.12.2-1.9.1.507.

**Comment by LAGIdiot** [comment]
So, is everything regarding this OK now? Or  do you need additional help?

**Comment by LAGIdiot** [comment]
I am closing this issue as stale. If there is still required any action from GTCE side then feel free to re-open this issue.
