### ISSUE TITLE
Invisible chests caused by Emerging Technology CO2 scrubbers

### ISSUE THREAD

**Issue by LordPINE** [GregTechCE/GregTech#1117]
When placing an Emerging Technology CO2 scrubber near GTCE chests, the chests turn invisible. Looking away from the scrubber makes everything go visible again. See attached images for an illustration of the issue.

![2020-06-25_10 31 48](https://user-images.githubusercontent.com/29479835/86037957-757cae00-ba40-11ea-9260-d7eb22d13322.png)
![2020-06-25_10 31 45](https://user-images.githubusercontent.com/29479835/86037959-77467180-ba40-11ea-838d-24d7806ccc8a.png)

Relevant info:
GTCE version: 1.9.1.507
Emerging Technology version: 1.3.25
Forge version: 14.23.5.2847

**Comment by LAGIdiot** [comment]
Well this looks like problem on Emerging Technology side. I am quite sure that they do something to rendering pipeline like (not resetting some properties) and then we are not able to render our chests. And by turning away from that block or by breaking it rendering pipeline gets reset to it's proper state.

Please report this problem to them as our chest are rendering correctly without interaction with them.

**Comment by LAGIdiot** [comment]
Was this problem reported to Emerging Technology team is there any response from them?

**Comment by LordPINE** [comment]
It was, and it is being worked on.
https://github.com/MoonManModding/EmergingTechnology/issues/99
