### ISSUE TITLE
an error on server 

### ISSUE THREAD

**Issue by zhangziming666** [GregTechCE/GregTech#1126]
[15:47:21] [Server thread/FATAL]: Seems like invalid recipe was found.
[15:47:21] [Server thread/FATAL]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[15:47:21] [Server thread/FATAL]: Ignoring invalid recipes and continuing loading
[15:47:21] [Server thread/FATAL]: Some things may lack recipes or have invalid ones, proceed at your own risk
[15:47:21] [Server thread/FATAL]: Report to GTCE github to get more help and fix the problem
[15:47:21] [Server thread/FATAL]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by LAGIdiot** [comment]
Thank you for informing us about this error. We would need full log, GTCE version, Forge version, and list of other mods installed (in case you are using modpack then it's name and version. Please provide us with these information and we will take a look what went wrong.

**Comment by zhangziming666** [comment]
My gtce version is 1.9.2.515. I use the catserver server. I don't know what the forge version is. How can I give you the mod screenshot and error log

> 感谢您通知我们有关此错误的信息。我们需要完整的日志，GTCE版本，Forge版本以及已安装的其他mod列表（如果您使用的是modpack，则需要提供其名称和版本。请向我们提供这些信息，然后我们会看看发生了什么问题。

My gtce version is 1.9.2.515. I use the catserver server. I don't know what the forge version is. How can I give you the mod screenshot and error log

**Comment by zhangziming666** [comment]
> Thank you for informing us about this error. We would need full log, GTCE version, Forge version, and list of other mods installed (in case you are using modpack then it's name and version. Please provide us with these information and we will take a look what went wrong.
I added ic2ex and gregicality, and that's what happened

**Comment by clienthax** [comment]
> > Thank you for informing us about this error. We would need full log, GTCE version, Forge version, and list of other mods installed (in case you are using modpack then it's name and version. Please provide us with these information and we will take a look what went wrong.
> > I added ic2ex and gregicality, and that's what happened

server.log needed

**Comment by LAGIdiot** [comment]
I am not sure how "catserver" is different from pure Forge server so I am going to use names of folders from pure Forge and hope they are same. 

1. List of file names in **root** folder of modpack instance on server (this should give us Forge version)
2. List of names from **mods** folder
3. Logs from **logs** folder specifically **latest.log** and **debug.log**

For first two screenshot is acceptable. For last one please pack it to zip as it may be quite large.

**Comment by LAGIdiot** [comment]
I am closing this issue as stale. If there is still required any action from GTCE side then feel free to re-open this issue.
