### ISSUE TITLE
Running into powered 16x wires does not damage player

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1132]
GTCE version: 1.9.2.515

Running into powered 16x wires does not damage the player, while running into powered wires of any other size does damage the player. I would expect this to happen for the 16x wire as well, however I am able to stand on a bare 16x wire and not be damaged.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.2 (dev build on 9749e0bacf1d6b4ac5e287904cd519badbcaf779)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Additional notes:**
Current implementation is using onEntityCollidedWithBlock which is not called for full size blocks (which is case for 16x wires).

**Comment by ALongStringOfNumbers** [comment]
One possible solution to this issue would be to reduce the hitbox of the 16x wires and cables somewhat, so they are no longer full blocks, which would allow the event to work for these cables/wires.

**Comment by LAGIdiot** [comment]
@ALongStringOfNumbers  I was thinking along same lines. I would even go that far to make all wires little bit thinner so when they got insulated they would look more thicker which will be closer to reality.

Do you plan to PR this?

**Comment by eutropius225** [comment]
I might potentially, but I don't really want to get too close to CCL's rendering pipeline thing.

**Comment by LAGIdiot** [comment]
Well it is open for now, if no one takes it in like 6 hours I will. If someone takes it just leave comment here.

**Comment by ALongStringOfNumbers** [comment]
I would not be able to start on it for a day or two, so I will leave it up to you or Eutro.
