### ISSUE TITLE
Facade conflict with EnderIO and Chisel

### ISSUE THREAD

**Issue by Kortako** [GregTechCE/GregTech#1134]
**Mods Installed**
GTCE: 1.9.2.515
EnderIO: 5.2.59
Chisel: 1.0.2.45
CTM: 1.0.2.31

**Issue**
EnderIO Conduit Facades painted with Chisel blocks are invisible and do not render correctly, and it seems like the error lies with some conflict with facades from GTCE (see stack trace).  Removing GTCE from my testing environment seems to alleviate the problem.

Let me know If there's anything else I can do to help debug, or if I need to move this over to EnderIO instead.

**Stacktrace**
https://hastebin.com/egamucitec.cs

**Example**

![2020-07-09_01 40 55](https://user-images.githubusercontent.com/5300243/87018840-abc7d500-c186-11ea-8808-3f6acfba529c.png)
![2020-07-09_01 40 38](https://user-images.githubusercontent.com/5300243/87018850-af5b5c00-c186-11ea-8002-64604596a009.png)

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue to us. I have done some testing and these are my findings:

**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.2 (dev build on d2ba34422f92de7c5018d9545241d7c387d18861)
CTM: 1.0.2.31
EnderIO: 5.2.59
Chisel: 1.0.2.45
CodeChickenLib: 3.2.3.358

**Enviroment:**
GTCE dev

**Outcome:**
Issue confirmed. But in my testing there was no direct connection between reported problems and GTCE. In reported case GTCE method appearing in stacktrace was only coincidence as I was able to reproduce problem without GTCE being mention in it [Error stack trace](https://gist.github.com/LAGIdiot/a1ec029928f51d256edcd1df6ba0694a). I also confirmed that by removing GTCE will fix problem so in a way there is something to it, probably in use of CodeChickenLib which handles some rendering for us.
And what more I was able to catch problem in another way which may prove useful for additional investigation: 
[CCL caught exceptions](https://github.com/GregTechCE/GregTech/files/4908344/latest.log)

But I think that this issues should be investigated from Ender IO side as owners of blocks therefor responsible for it's rendering (well in this case it is quite controversial as it is Chisel look like block). Needles to say that if they require our help I would be glad to offer it. So if you want to pursue this problem further please create issue on Ender IO side and link this one in.

**Additional notes:**
It seems that different combinations of facades are broken every time. As can be seen below in screenshots taken from different game launches.
![2020-07-12_11 52 54](https://user-images.githubusercontent.com/3093101/87243874-e1481900-c439-11ea-95f5-cb5b81f7ac63.png)
![2020-07-12_11 56 52](https://user-images.githubusercontent.com/3093101/87243876-e2794600-c439-11ea-93fe-6e5bb632baed.png)
![2020-07-12_12 26 08](https://user-images.githubusercontent.com/3093101/87243989-e35ea780-c43a-11ea-9655-63eb8032dddd.png)

**Comment by Kortako** [comment]
Thanks for looking into that @LAGIdiot!  I will see if I can bring this up on the Ender IO side then.

**Comment by HenryLoenwind** [comment]
You are including a very invalid version of CTM's IFacade class.

https://github.com/GregTechCE/GregTech/blob/master/src/main/java/team/chisel/ctm/api/IFacade.java

**Comment by tterrag1098** [comment]
Please do not shade APIs, and this is why!

**Comment by LAGIdiot** [comment]
Thank you for reaching to us regarding this problem and pointing us to area which causes this problem.
