### ISSUE TITLE
[Suggestion] Add dimensional numbers to world generation configuration

### ISSUE THREAD

**Issue by MrEyeballs29** [GregTechCE/GregTech#1136]
Hello and I looked at the dimension generation restrictions and it seems like it needs a number option. The problem with the name option and the class options is sometimes it will generate more than one dimension. Some modded dimensions use biome registry name more than once. However the ids are always used once. Example:
<pre>{
  "weight": 80,
  "density": 0.5,
  "min_height": 40,
  "surface_stone_material": "tin",
  "dimension_filter": ["id:0"],
  "generator": {
    "type": "ellipsoid",
    "radius": [17, 19]
  },
  "filler": {
    "type": "simple",
    "value": {
      "type": "weight_random",
      "values": [
        {
          "weight": 60
          "value": "ore:tin"
        },
        {
          "weight": 40,
          "value": "ore:cassiterite"
        }
      ]
    }
  }
}
</pre>
That tin vein only generates in dimension number 0 which in that case the overworld. It would be a great feature to have, plus the numeric ids are hard-coded with -1, 0, and 1. So far this mod is excellent.

**Comment by Saereth** [comment]
this already exists
`"dimension_filter": ["dimension_id:0"], `
is the syntax you're looking for

**Comment by MrEyeballs29** [comment]
Yes but the documentation does not even says that. All I could see in that documentation are names. class provider, and surface_world or nether.

**Comment by LAGIdiot** [comment]
Thank you for providing this suggestion. As @Saereth already pointed out this feature is already implemented and ready to use. I have also updated relevant wiki page to include this information.
