### ISSUE TITLE
unable to get Rubber Bar

### ISSUE THREAD

**Issue by xcpooo** [GregTechCE/GregTech#1140]
Rubber Bar needs Fluid Solidifier, Fluid Solidifier needs Rubber Bar

**Comment by Shattered2909** [comment]
The Fluid Solidifier does not need a Rubber Bar. Tin Cables are insulated with Carpets (by default) and the Pump can be made with Paper instead of Rubber. This might be changed if you are playing a specific modpack.

**Comment by xcpooo** [comment]
> The Fluid Solidifier does not need a Rubber Bar. Tin Cables are insulated with Carpets (by default) and the Pump can be made with Paper instead of Rubber. This might be changed if you are playing a specific modpack.

Thanks!! That helps me a lot

**Comment by LAGIdiot** [comment]
@Shattered2909 thank you for answering that question.

I think question in this issue was answer as best as it could be so I will close this issue as resolved. If the there are additional questions regarding this issue please visit our Discord or re-open this.
