### ISSUE TITLE
[Suggestion] Config Option for Food to Methane Centrifuging

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1146]
I am a little bit annoyed by all the recipes generated for centrifuging Food into Methane, it is clutter and I don't want this to be viable. It is so many recipes that removing them with Crafttweaker would take days, so maybe you can add a config option to just not generate these recipes?

**Comment by Agrax** [comment]
I’ve seen someone doing it w/ one loop iirc. But other than that... Only allowing some foods to be centrifuged is highly inconsistent and not at all coherent. By disallowing all foods to be centrifuged you break an integral fuel option in GTCE

**Comment by Shattered2909** [comment]
That is why I am asking for a config option to disable all of it.

**Comment by Agrax** [comment]
`// Automatically generated compost outputs for every food type.
for mod in loadedMods {
 for item in mod.items {
   var food_value = 0; 

   for itemstack, fluidamount in custom_compost_map {
        if (itemstack.definition.name == item.definition.name) {
         // If the item is in the custom entries above, use that provided value instead of automatically generating one.
         print("\t\t CUST: " ~ item.displayName);    
         food_value = fluidamount as int; // Even though the value is int, we need to typecast 
      } else if (item.getSaturationModifier() + item.getHealAmount() > 0) {
         print("\t\t AUTO: " ~ item.displayName); 
         food_value = 20 + (30 * (item.getSaturationModifier() + item.getHealAmount()));      
      }
   }

   if (food_value > 0) {
     mixer.recipeBuilder()
       .fluidInputs([<liquid:water> * food_value])
       .inputs([item * 1])
       .fluidOutputs([<liquid:liquid_compost> * food_value]) // pyure: switch back to compost
       .duration(240)
       .EUt(9)
      .buildAndRegister(); 
   }         
 }
}`

Im more than sure that you can use smth KIND of similar to that script to turn off all the recipes. Just make a custom map that includes only the things containing the saturation value and use that to remove the recipes

**Comment by Agrax** [comment]
> That is why I am asking for a config option to disable all of it.

Wish you don’t get it, but *shrug*, who knows

**Comment by LAGIdiot** [comment]
Thank you for requesting this feature. But there is already config option for it:
![2020-07-15_13 41 31](https://user-images.githubusercontent.com/3093101/87542112-b44a6f00-c6a2-11ea-848d-fabf9ef7f8bf.png)
