### ISSUE TITLE
Liquids have no texture when placed in world

### ISSUE THREAD

**Issue by KyleBeep427** [GregTechCE/GregTech#1147]
When placing a liquid in the world, the liquid just has a pink and black texture. This could be a shadows of Greg issue however

**Comment by LAGIdiot** [comment]
Can you please be more specific regarding this issue. What version of Forge, GTCE and other mods are you using? Which liquids have problematic texture all of them or specific category?

**Comment by KyleBeep427** [comment]
The other issue is exactly what is happening to me. I was using the newest version of forge and GTCE and only Shadows of Greg. I think that the potions are the only issue with this mod alone and the other missing textures were from shadows of Greg because they were all textures that could be put in a tinkers smeltery. Sorry for the late reply.

**Comment by LAGIdiot** [comment]
Duplicate of #1085
