### ISSUE TITLE
Converting GT energy to IC2 or RF

### ISSUE THREAD

**Issue by mgun82** [GregTechCE/GregTech#1149]
Is there any possibility to power an electric motor from IC2 from a GTCE power source. I am looking for an opportunity to supply energy to the forestry multi-farm.

**Comment by Agrax** [comment]
https://www.curseforge.com/minecraft/mc-mods/ceu/files

It can transform GTeu to FE and vice versa

**Comment by mgun82** [comment]
Many thanks! It helped.

**Comment by LAGIdiot** [comment]
Thanks @Agrax for answering this one. Just to be exact regarding this, GTCE does not support taking IC2 or FE energy. And support for this is not planned as there are already mods that provides this functionality and CEU is one of them.
