### ISSUE TITLE
Facades and object pipes.

### ISSUE THREAD

**Issue by mgun82** [GregTechCE/GregTech#1154]
Are the facades and object tubes still in this GT version?

**Comment by LAGIdiot** [comment]
Thank you for reaching to us. If you join us in our Discord you can get answers quicker.

Anyway let me answer your questions. Facades are currently available, all except one are hidden from JEI but they are craftable and recipe is as follow.
![2020-07-25_16 08 08](https://user-images.githubusercontent.com/3093101/88458832-0ce2ee80-ce91-11ea-962a-86d45d7c2d09.png)

Regarding object tubes, right now GTCE does not have any item pipes or similar blocks for item transport.
