### ISSUE TITLE
Inconsistency with Bone Meal and Blaze Powder

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1158]
The "rods" should output a lot more in a Macerator and the Bone Meal Dust Item should not even exist, just add Bone Meal oredict to the vanilla one.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

I can confirm that Bone material has zero uses and it's dust is not even compatible with Vanilla MC Bone Meal. But I would rather not remove it as we don't know if any one is using it. We could just not crate our Bone Meal dust but use one from Vanilla MC (same mechanic as with Blaze). We should also mark Bone (material) as `MORTAR_GRINDABLE`. This will remove one item but I will tolerate this incompatibility as that item was useless.

Regarding "rods" forms of Blaze and Bone and their macerating output. Blaze is using standard formula for macerating and Bone will (after updating it as suggested in upper paragraph). We definitely should up the output to be at least same as for mortar or even better.
