### ISSUE TITLE
Machines can ignore existing machine controller settings

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1161]
GTCE version: 1.9.2.515

Machines can ignore existing redstone control via a machine controller when another machine controller is added to the machine.

To Reproduce:
- Have a machine, powered, and forced into a not working state via a machine controller (This was done via a lever next to machine controller in testing, and a default setting machine controller was used)
- Add items to the input of the machine and see that it does not work.
- Add another machine controller on a different face than the one with a current machine controller, and do not provide it with a redstone signal
- Observe that the machine will turn on, and ignore the redstone control of the first machine controller, even though that controller was supposed to be forcing it off
- Remove the second machine controller, and observe that the machine is still working, even though there is only 1 machine controller left, which should be forcing the machine into a not working state
- This situation will continue until you toggle the first redstone signal (which was a lever) on and back off again

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.3 (dev build on 5780bfd7aabc56c7fa4039ce29ee726fa099fb08)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed
