### ISSUE TITLE
[Suggestion] Large Boiler Changes

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1164]
Maybe they should generate less Steam with normal Water and the current value with Distilled Water?

Should make this a config option to be honest....

**Comment by LAGIdiot** [comment]
Thank you for suggesting this change. But I don't see any value in changing current Large Boiler setup to take both water types and generate different amount of steam based on which was used. Also from "realistic" point of view there is no reason for Distilled water being better in generating Steam then normal Water. Other thing would be suggesting feature regarding calcification.
