### ISSUE TITLE
GregTech Community Edition's Saltwater overrides TFC's

### ISSUE THREAD

**Issue by mechobree** [GregTechCE/GregTech#1166]
When playing with both tfc and gtce, tfc's saltwater is forcibly replaced by gtce's and the colours do not match at all. 
It was not possible to change the texture of gtce's salt water and call it a day as it doesn't even have a texture file in it's resources.
![javaw_29-07-2020-22 03](https://user-images.githubusercontent.com/29335214/88826393-b3333a80-d196-11ea-9f90-d692cdbe3032.png)

Note: TheOneProbe says that it's tfc's salt water, but it is not. Tfc's varient is not listed in jei and only gtce's is listed.

I made an issue on tfc's issue page as well.
https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1508

Mod Versions:
GregTech Community Edition 1.12.2-1.9.2.515 (though I think any version will have the same issue)
TFC Version: 1.12.2-0.5.5.155

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. But this is **intended behavior** of Forge fluid registration system. What is happening here is that two mods are trying to register same fluid. In this case we were first requesting registration so our color schema is used.

As you already found out we are not using texture files for every fluid but you can still change color for Salt water (or any other material) via CraftTweaker.

Bug regarding ownership of fluid please report to TheOneProbe mod.

**Comment by mechobree** [comment]
> 
> 
> Thank you for reporting this issue. But this is **intended behavior** of Forge fluid registration system. What is happening here is that two mods are trying to register same fluid. In this case we were first requesting registration so our color schema is used.
> 
> As you already found out we are not using texture files for every fluid but you can still change color for Salt water (or any other material) via CraftTweaker.
> 
> Bug regarding ownership of fluid please report to TheOneProbe mod.

Yeah I figured out the first bit, I was just wondering if there was any way tfc's version could be made the primary. But oh I didn't know I could use crafttweaker to change colours of fluids! Thank you very much, that was the exact answer I was after!
