### ISSUE TITLE
Registering materials with numbers in their name causes them to not be registered in oredict

### ISSUE THREAD

**Issue by hjae78** [GregTechCE/GregTech#1167]
I had a material with the unlocalized name "zeron_100" and it's generated items did not have any recipes generated because OreDictUnifier's get method failed to retrieve the corresponding itemstack. For reference I had a material with the unlocalized name "cinobite_a243" which did work.

**Comment by hjae78** [comment]
Also just to confirm, yes, changing the name to "zeron_a100" made recipes be registered.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue but this is **not a bug** but a **limitations** of GTCE unification system. As we are using `CaseFormat` which is not able to correctly handle entries which are having number right after underscore character.
