### ISSUE TITLE
Workbench JEI integration looks accidentally disabled

### ISSUE THREAD

**Issue by talchas** [GregTechCE/GregTech#1168]
JEI integration for the "Crafting Station"/MetaTileEntityWorkbench is coded and (almost completely) works, but isn't active because the CraftingSlotWidget used to communicate with ModularUIGuiHandler is added as a widget to a WidgetGroup for the tabs, and ModularUIGuiHandler doesn't recursively scan inside of groups for IRecipeTransferHandlerWidgets. Moving it to be added to the top level Builder instead "works", but renders the crafting output on the storage screen as well. 

The other bug is that CraftingRecipeResolver.setCraftingGrid expects the recipe ingredients to be in 0-8 for the 9 slots, while JEI provides them in 1-9 (and the output in 0 iirc); at some point there just needs to be a -1 added and it all works.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue, but you are mistaken regarding current functionality of Crafting Station. Crafting Station is not using Crafting Slots for input (which normally would be wired to JEI) but it is using Phantom Slots which allows you to drag items from JEI without owning them (works only if JEI does not have Cheat Mode active) to grid. Right now that Phantom overlay is little bit off but that can be fixed.

![2020-08-01_11 57 15](https://user-images.githubusercontent.com/3093101/89099245-2b476d80-d3ee-11ea-9ef0-689c8d8dfb21.png)
![2020-08-01_11 57 17](https://user-images.githubusercontent.com/3093101/89099247-2c789a80-d3ee-11ea-8093-eecefdd6638c.png)

Also ModularUIGuiHandler exposes all widgets as flat structure so it will be visible for needs of JEI's `transferRecipe` but that is not this case.

**Comment by talchas** [comment]
I'm aware of that function, but there is also code in there to handle the JEI transferRecipe; [ModularUIGuiHandler.transferRecipe](https://github.com/GregTechCE/GregTech/blob/cc61b8f4370fa8159a088288f0dc9d0d698de95c/src/main/java/gregtech/api/gui/impl/ModularUIGuiHandler.java#L42) attempts to find and call into [CraftingSlotWidget.transferRecipe](https://github.com/GregTechCE/GregTech/blob/cc61b8f4370fa8159a088288f0dc9d0d698de95c/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java#L110), which then calls [CraftingRecipeResolver.setCraftingGrid](https://github.com/GregTechCE/GregTech/blob/cc61b8f4370fa8159a088288f0dc9d0d698de95c/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java#L48). 

ModulerUIGuiHandler only exposes all widgets directly added to the Builder, which does not include all the children of a TabGroup. Builder.widget does not check for AbstractWidgetGroup and recurse into its children, and neither does ModularUIGuiHandler (all the normal handlers on AbstractWidgetGroup do the recursion themselves).

This patch is enough to activate the code, and only has the issue that of course now the crafting slot is displayed ignoring tabs, so it still shows up in the storage view.
```diff
diff --git a/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java b/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java
index 32a7c0e8..07215c0c 100644
--- a/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java
+++ b/src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java
@@ -40,7 +40,7 @@ public class CraftingSlotWidget extends SlotWidget implements IRecipeTransferHan
             int ingredientAmount = buffer.readVarInt();
             try {
                 for (int i = 0; i < ingredientAmount; i++) {
-                    ingredients.put(buffer.readVarInt(), buffer.readItemStack());
+                    ingredients.put(buffer.readVarInt() - 1, buffer.readItemStack());
                 }
             } catch (IOException exception) {
                 throw new RuntimeException(exception);
diff --git a/src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java b/src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
index 3db5ef42..9593edd9 100644
--- a/src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
+++ b/src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
@@ -173,7 +173,6 @@ public class MetaTileEntityWorkbench extends MetaTileEntity {
         CraftingRecipeResolver recipeResolver = getRecipeResolver();
 
         widgetGroup.addWidget(new ImageWidget(88-13, 44-13, 26, 26, GuiTextures.SLOT));
-        widgetGroup.addWidget(new CraftingSlotWidget(recipeResolver, 0, 88-9, 44-9));
 
         //crafting grid
         for(int i = 0; i < 3; ++i) {
@@ -225,6 +224,7 @@ public class MetaTileEntityWorkbench extends MetaTileEntity {
         tabGroup.addTab(new ItemTabInfo("gregtech.machine.workbench.tab.item_list", new ItemStack(Blocks.CHEST)), createItemListTab());
         builder.widget(tabGroup);
 
+        builder.widget(new CraftingSlotWidget(getRecipeResolver(), 0, 88-9, 44-9));
         return builder.build(getHolder(), entityPlayer);
     }
 }
```

**Comment by LAGIdiot** [comment]
Thank you for providing us with your analysis and even with diff for fixing this issue. But I can accept it as it would degraded current function of that block.

I have already posted question regarding usage of Crafting Station to our Discord and will determine how to fix/change it based on feedback.

**Comment by talchas** [comment]
Yeah, that patch is just an example that the core integration is already written; a proper fix that doesn't result in the crafting slot showing up over other tabs is what I expect you'd want.

**Comment by LAGIdiot** [comment]
I have seen some feedback regarding this in comments under direwolf20 FTB Interactions series. It is quite a thorn in heel for some that this block does not have "proper" JEI integration. And I think that switching to standard model of crafting button in JEI putting items in grid is our best bet.
