### ISSUE TITLE
Zombies spawn with nano sabers

### ISSUE THREAD

**Issue by NewTech32** [GregTechCE/GregTech#1169]
[Used Google Translate]
It's funny to watch when a zombie kills you with one hit ... We need to remove the possibility of spawning mobs with a nano saber in their hands.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue but it is intended behavior. Zombies on HARD difficulty can spawn with Nano Sabers (chance is about 3%, may be less with other mods installed).
