### ISSUE TITLE
concurrent sorts when scanned by Thaumcraft Thaumometer

### ISSUE THREAD

**Issue by alskkjj** [GregTechCE/GregTech#1170]
Game crashed when I **SCANED** an object in World named "Tiny pile of Gold Dust", it's a kind of material indicator of mines under ground.

The **SCANNER** is an item from Thaumcraft named Thaumometer, you guys may already noticed this little boy.

Seems like there are absence of lockers for methods or shared resources.

Details are here:
[bug_report.txt](https://github.com/GregTechCE/GregTech/files/5011052/bug_report.txt)

Also there is a bug report from [pastebin bug_report.txt](https://pastebin.pl/view/bbc47e54)

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.3 (dev build on 5780bfd7aabc56c7fa4039ce29ee726fa099fb08)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed
