### ISSUE TITLE
Blocks going invisible

### ISSUE THREAD

**Issue by SlipperyPotatoes** [GregTechCE/GregTech#1171]
Hello, this is my first post so please tell me if I am doing anything wrong. Whenever lighting updates all blocks in both gregtech and shadows of greg go invisible. You can still interact with them but they are completely see through. They are also invisible in jei. It's pretty easy to replicate, all you have to do is push a machine with a piston. In this case I pushed a simple steam boiler.
![image](https://user-images.githubusercontent.com/69117179/89127631-3fbf5f00-d4ef-11ea-8be7-85683f097e4d.png)
**Modpack:** Ftb Interactions
**Gregtech version:** 1.12.2-1.8.3.418

**Comment by eutropius225** [comment]
Normally, machines (and other tile entities) cannot be pushed with pistons. Given the modpack, I believe this functionality is provided by Quark.

**Comment by SlipperyPotatoes** [comment]
> Normally, machines (and other tile entities) cannot be pushed with pistons. Given the modpack, I believe this functionality is provided by Quark.

Do you know of a fix? It's quite annoying

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. But I am going to close this one straight of as you are using **version which is more then year old** please updated to newest version of GTCE. And if problems will be still happening feel free to reopen this issue.

**Comment by lamoyrl90** [comment]
Still happens, LAG. Unfortunately, I can't find anything useful in my game logs. I'm gonna try and investigate.
