### ISSUE TITLE
The steam age is not balanced. Energy production to consumption is incorrect.

### ISSUE THREAD

**Issue by NewTech32** [GregTechCE/GregTech#1172]
[Used Google Translate]
I believe that it is wrong that 1 charcoal in a small steam boiler produces about 64'000 mB of steam, which can be used for a lot of different operations on steam machines (200+ operations, compared to a conventional stove, in which only 8 operations)

**Comment by Shattered2909** [comment]
It is intentional that Steam Technology is more efficient than a Vanilla Furnace. Do remember that a Boiler needs to heat up and constantly eats fuel at that time without giving you anything. You cannot stop/start Steam production at any time.

And guess what, the Multi Smelter is even better, a lot better.

**Comment by NewTech32** [comment]
[Used Google Translate]
Yes, the higher the technology, the cooler it should be. But! Within a reasonable.

But is it right that you only need 16 charcoal to go through the Bronze Age (that is, from the Stone Age to the Electric Age).

**Comment by Shattered2909** [comment]
16 Charcoal is not nearly enough to power Steam Machines and you need waaaaaaaaaaaaaaay more to make Steel.

**Comment by NewTech32** [comment]
[Used Google Translate]
Of course, yes, a blast furnace requires a lot of coal. Didn't take this into account in the comment earlier.

I mean more consumption when using steam engines.

**Comment by Shattered2909** [comment]
Furnace Smelting is pretty much free in Modded these days, so why bother. Other machines take a lot more power.

**Comment by NewTech32** [comment]
Watching your current progress in the game, you get the feeling of the Bronze Age, and as I already guess in the future, that fuel has almost no value.

[Используется Google Translate]
Comparing the times of simple IC2 and GregTech Unofficial. I had to think not only about resources, but also about having enough energy to process them.

And with the current production of steam in small boilers and the consumption of coal in them, even in the first stages of electrification, I will hardly think about the fact that I may not have enough electricity. As if reducing to the fact that due to almost free fuel, a significant part of the gameplay is lost.

Unfortunately, I cannot describe and explain all this in more detail, since I do not know English well, and the translator will translate it into an incomprehensible mess.

**Comment by Shattered2909** [comment]
You don't have to think about having enough energy while saying 16 Charcoal is enough to get through the Steam Age? That is ridiculous and makes no sense.

**Comment by LAGIdiot** [comment]
Even if this one is already closed I am gonna add my opinion to this. In my eyes balance is magical creature of which everyone is talking but nobody really saw it.

Anyway back to topic. Comparing steam age (Steam Boiler + any steam machine) to Furnace is not correct as both works on different principle. For Furnace you just put fuel in an you can cook. If you are not using it there is no fuel consumed. And all items are smelled for same amount of fuel (time). For Steam Boiler you need fuel and water plus infrastructure to deliver steam. There is period of time when no steam is produced but fuel is consumed. Also even if steam is not used fuel is still being consumed at same rate. Amount of fuel (time) is vastly different between items. Also there are dangers regarding steam use like heated pipe and steam exhaust which can kill careless players. Also automation is more challenging and there are scaling problems. And last but not least player needs to take care of it from time to time which is quite costly too. As already mentioned steam age should be more OP to "stone age" and I think GTCE is on good track with it.
