### ISSUE TITLE
Crystal battery capacity buff

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1174]
Change this:

Energy Crystal Capacity 1,000,000 -> 4,000,000
Lapotron Crystal Capacity 4,000,000 -> 10,000,000
This makes the Energy Crystal better than the HV Batteries (which it should be...) and also makes the jump from Lapotron Crystal to Lapotronic Orb (holds 100,000,000) more consistent. At the moment the 2 Crystals are kinda bad.

**Comment by LAGIdiot** [comment]
Proposed changes sounds reasonable. This should give boost to usage of these items not just for crafting purposes.
