### ISSUE TITLE
Is nuclear or thermonuclear power implemented in GTCE?

### ISSUE THREAD

**Issue by mgun82** [GregTechCE/GregTech#1175]
Found nothing in JEI so the question arose

**Comment by Shattered2909** [comment]
There is an addon called Gregicality that has Nuclear Power.

**Comment by LAGIdiot** [comment]
Thank you for asking. GTCE currently does not have any Nuclear or Thermonuclear power system implemented in. But there are addons such us Gregicality which add it.
