### ISSUE TITLE
Recipe error allowing duping.

### ISSUE THREAD

**Issue by Flame500** [GregTechCE/GregTech#1182]
Using tiny piles in the Borosilicate glass pulp recipe causes a net gain in base materials.
![Screenshot (327)](https://user-images.githubusercontent.com/66292601/89613797-b5596100-d848-11ea-84c3-40b4430b9268.png)
GTCE version 1.9.3.531

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. First of all I would like to point out that we have new template specifically for bug reports. Also I am not seeing any possible net gain. Can you please be more descriptive?

**Comment by Flame500** [comment]
My error, I read tiny dusts instead of small dusts. Loving the mod, keep up the great work!
