### ISSUE TITLE
[BUG] Back Conversion from screw to bolt recipes

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1187]
**Describe the bug**
A screw of any material can be crafted with a file and two bolts of the same material. However, a single bolt of any material can also be crafted with two screws of the same material and a file. Therefore, there is a recipe difference where material loss is possible in the crafting recipes. 

**Versions**
Forge: 14..23.5.2847
GTCE: 1.9.3.531
_Addons:_ Shadows of Greg 2.13.0 was also present

**Setup**
Playing Solo

**Steps To Reproduce**
1) Boot up game and observe the recipes and usages for a screw of any material

**Expected behavior**
I would expect behavior similar to that in GT5 versions, where you can craft a screw with two bolts and a file, but you cannot craft a both with two screws and a file, and instead the recipe with a saw and a rod, which already exists. Beyond that, I would not expect a recipe to be present that offers a back conversion from screw to bolt, even if it is at a loss of materials

**Screenshots**
![2020-08-09_01 39 59](https://user-images.githubusercontent.com/31759736/89728333-672b9580-d9e1-11ea-9ffa-0f68add06349.png)
Image of two screws to a bolt (gold, though it is for any material)

![2020-08-09_01 40 10](https://user-images.githubusercontent.com/31759736/89728342-83c7cd80-d9e1-11ea-87e0-83d3d7b1248c.png)
Image of two bolts to a screw

**Comment by LAGIdiot** [comment]
Thank you for creating this issue. As you mentioned when **hand** crafting bolts to screw and back there will be loss. 

**Decision:**
I think that it is absolutely OK to have recipes which works like that and I don't feel need to change it in any way.

**Reasoning:**
Bolt and Screw has same material size. And for that they are convertible between themselves but for that is needed precise equipment (machines). That means there is machine recipes for it (Lathe for making Screws from Bolts and Cutting Saw making Bolts from Screws). But with crude tools we can't expect to be able to do it without any loss so we are counting (for most cases) with two times material needed. That is why you can make one Rod from Ingot using File. And you need two Bolts to create one Screw using File and same goes vise versa. Of course removing revers recipe would prevent heedless players from loosing material but in same time they will be stuck with Screws without use before they will get to machines to turn them to something useful.

**Comment by LAGIdiot** [comment]
In case of any question regarding this matter feel free to re-open.
