### ISSUE TITLE
[BUG] Disabling Rubber Tree generation also disabled Abandoned Base generation

### ISSUE THREAD

**Issue by Prunoideae** [GregTechCE/GregTech#1201]
**Describe the bug**
It's redundant and misleading if you wrap both the rubber tree generation code and the abandoned base generation code into one if statement, since setting abandoned base chance to 0 already disabled the generation of base.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.9.4.540

**Setup**
https://github.com/GregTechCE/GregTech/blob/a3e6fdca2893c19e97d23f5d2f682830e5fb57b2/src/main/java/gregtech/GregTechMod.java#L143-L146

**Expected behavior**
Please move the register code out of the if statement.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.0 (dev build on a3e6fdca2893c19e97d23f5d2f682830e5fb57b2)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed
