### ISSUE TITLE
[BUG] Chinese translation mistake about fluid extractor

### ISSUE THREAD

**Issue by Jerry4116** [GregTechCE/GregTech#1206]
The advanced fluid extractor (HV and EV version) has been translated to "进阶流体灌装机" II and III, which actually means fluid canner. It should be "进阶流体提取机" II and III. The translation of LV and MV fluid extractor is right.
https://github.com/GregTechCE/GregTech/blob/a3e6fdca2893c19e97d23f5d2f682830e5fb57b2/src/main/resources/assets/gregtech/lang/zh_cn.lang#L1964-L1974

**Comment by LovelyCatHyt** [comment]
I think he is right, and made a PR at once.
XD
