### ISSUE TITLE
Missing/not in JEI machine recipes

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#121]
- [x] Fluid Extractor recipes (melting blocks, ingots, nuggets, rods, tool heads,...)
- [x] Oil refining recipes in the Distillery and Distllation Tower
- [x] Arc Furnace and Plasma Arc Furnace recipes
- [x] Cracker recipes (the actual machine is missing (in JEI at least))
- [x] Scanner recipes (with the actual Scanner not being implemented yet)
- [x] Brewery recipes
- [x] Fluid Canning Machine recipes (filling up Cells)
- [x] Compressor recipes (making Blocks (and disabling block crafting recipes))
- [x] Implosion Compressor recipes (making most gems from their dusts)
- [x] Chemical Bath recipes (coloring Wool, Glass and Terracotta)
- [ ] Fusion Reactor (the entire thing is unimplemented)

**Comment by EmosewaPixel** [comment]
I suspected that some of them were just not in JEI

**Comment by Archengius** [comment]
they won't be in JEI for canner, it fills any fluid containers.

**Comment by EmosewaPixel** [comment]
Some mods' machines that fill up fluid containers are in JEI, but fair enough.

**Comment by EmosewaPixel** [comment]
Yeah, most people would probably be able to guess that that's what it does anyways.

**Comment by Rongmario** [comment]
4th is done. Considering doing Fusion.

**Comment by Archengius** [comment]
will close it for now
