### ISSUE TITLE
CCl rendering Bug with GTCE machines

### ISSUE THREAD

**Issue by EuFugs** [GregTechCE/GregTech#1216]
![2020-08-28_00 55 15](https://user-images.githubusercontent.com/67364966/91502919-81161500-e8c9-11ea-8f12-d8363a62079e.png)
![2020-08-27_19 51 06](https://user-images.githubusercontent.com/67364966/91502922-84110580-e8c9-11ea-81d3-ce9a65be047a.png)
As seen in the images above ive encountered some weird rendering glitches on my machines once i step out of my base.
It happens with every shader i tried so far and also with just optifine enabled :/ Help would be appreciated =)

**Comment by EuFugs** [comment]
![2020-08-28_12 40 32](https://user-images.githubusercontent.com/67364966/91552192-b3f0f500-e92b-11ea-9268-61eea2d63a88.png)
Pretty sure i narrowed to down to these things ;/ at least the log says these trigger the CCL error; unfortunately i have no idea how to disable the spawn of them, if thats even possible :c

**Comment by LAGIdiot** [comment]
I am sorry there is not enough information to go about in this issue. Please rework it using bug reporting template and include all required information from it. So we at least now where to start with it.

**Comment by SpeeeDCraft** [comment]
I know about this bug, I have already met it and tried to figure it out, the problem is when you generate the world and suddenly comes across a nugget of ore that spawns on the surface, then all GTCE textures break and become transparent or black
