### ISSUE TITLE
[BUG] Basic Air Collector Import setup conflicting with other mods and causing Console-Spam, assuming it's a GTCE Specific Bug.

### ISSUE THREAD

**Issue by XIPure** [GregTechCE/GregTech#1217]
**Describe the bug**
https://i.imgur.com/TW8WfM0.png <- This image shows what is being spammed in the MC-Console literally >EVERY SECOND< (As shown in the image) after having added an AE2 import bus onto a Basic Air Collector (In My Overworld Base which is actively chunkloaded). I had noticed this error message spam in the MultiMC Client Console whilst I was checking My farms in My RFTools Dimension (Which is also actively Chunkloaded/Powered (RF)) meaning that I was NOT standing near any GregTech(CE) Machines. At all.

Furthermore, after having added the import bus on the Basic Air Collector, I've noticed that for some very odd reason, My IndustrialForegoing Plant Gatherers have decided to stop auto-outputting into an item conduit, which then goes into an Ender Chest then into another chest which then goes into the AE2 System via an import bus as well. I can neither confirm nor deny that this is GregTech(CE)'s Fault or if it's IndustrialForegoing's Fault or if it's RFTools' Fault, so yeah.. I'm not sure what's causing this and that's why I'm here, lol.

**Versions**
Forge: 14.23.5.2847 (1.12.2 Minecraft)
GTCE: 1.9.4.541
_Modpack:_ N/A - This is My own pack/instance that I made.
_Addons:_ N/A - This is My own pack/instance that I made.

**Setup**
Solo / Single Player World

**Steps To Reproduce**
I'm not sure if this is 100% reproducible or this is just like a one off kind of issue but anyways, here's what I did:
I added the import bus onto a Basic Air Collector, went AFK irl to get some lunch, came back 20 or so minutes later, came back to My PC, travelled to My RFTools Dimension, saw that the Plant Gatherers had stopped auto-outputting, checked the MC-Console to see if IndustrialForegoing had perhaps mentioned anything at all and that's when I noticed the constant error message spam (Image linked above) from GregTech(CE) / Bad One Probe.

**Expected behavior**
I expected the import bus to import Air into the system which it did.... whilst spamming the MC-Console at the same time. I had also expected the Plant Gatherers to not get affected causing them to stop auto-outputting =(

**Screenshots**
https://i.imgur.com/MvOJXaS.png <- Confirmation/Proof to show that the import bus is connected/online to the Basic Air Collector in My Overworld Base.
https://i.imgur.com/lycsVR6.png <- Confirmation/Proof to show that the Air is in fact going into the AE2 System.
https://i.imgur.com/rpZVKDe.png <- Confirmation/Proof to show how the items are being collected (Left side of the image) and how they are being extracted via the Plant Gatherer(s) (Right side of the image) throughout all of My farms in the RFTools Dimension.

Hopefully *fingers crossed* that I have explained this clearly enough, I'm not good at explaining normally. So yeah, I'm assuming that this is a bug and so is LAGIdiot because He said it's the first He's seen this (In the GTCE Discord) and also because He recommended that I post it here, haha.

Thanks all! Hopefully You can help Me out and confirm whether it's a bug or not!

**Comment by XIPure** [comment]
Hello again, this is an update following on from the original post above:
So after having changed some configs, re-adding GTCE amongst some other mods for the past few hours, I think I found the issue as to why the Plant Gatherers were getting affected and as result of doing so.., this issue is no longer happening.

**However**....., the console-spam is still active when the import bus is attached to the Basic Air Collector. I'm writing this comment at roughly 02:00AM here in the UK whilst playing Minecraft (Obviously) and here is another picture uploaded to Imgur to confirm that it is indeed spamming the console for whatever reason: https://i.imgur.com/kIt6xuv.png

So... with all this being done and said, I personally would class this as a bug, but I'm gonna leave the final decision up to the Mod Devs =)

**Comment by LAGIdiot** [comment]
Thank you for creating issue as requested.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.0
AE2: rv6-stable-7
EnderIO: 1.12.2-5.2.59

**Enviroment:**
Modpack created on Twitch launcher

**Setup:**
![2020-08-29_09 06 00](https://user-images.githubusercontent.com/3093101/91631066-fae7f480-e9d6-11ea-91d1-f322115a7d9d.png)

**Outcome:**
Unable to reproduce

**Additional Info:**
Can you please provide us with log from moment this started (probably when you place your AE2 import bus)? As there may be some information which could help us.
Information regarding all mods version which come to this case is required. Namely: AE2, EnderIO, OneProbe and (mod for that block on right of Air Collector which I don't recognize).

**Comment by XIPure** [comment]
Ok so, I've just woke up, booted up Minecraft, loaded into the world, gone to My RFTools Dimension, walked very closely to the Plant Gatherers (Aka one block away) and found that's when it starts to spam the console with the Bad One Probe Implem error message (Refer to 1st link in My original post above). I didn't notice this yesterday but have just noticed it today and can confirm it does spam the console.

However..... another discovery I have just made is this: Instead of standing right next to the Plant Gatherer and when You're standing approximately 10 blocks (North/South/East/West, doesn't matter which direction) from the Plant Gatherer as shown in this pic: https://i.imgur.com/z5CZCDe.png, then it doesn't spam the console, I can confirm this because I have MultiMC's Console open on My other monitor.

In reply to Your other questions above:
It happens when the import bus is Online (Device online on the tooltip) and when I go and stand next to the Plant Gatherer as explained above -^

     My mod versions are:
     > Forge: 14.23.5.2847 (1.12.2 Minecraft)
     > GTCE: 1.9.4.541
     > AE2: RV6-Stable-7
     > Ender-IO: 5.2.59
     > The One Probe: 1.12-1.4.28
     > Flux Networks: 1.12.2-4.0.15-32
          > The block on the right side of the Basic Air Collector by the way is a Flux Point from the Flux Networks mod
          > https://i.imgur.com/AftuChB.png <- Confirmation/Proof of the block You were referring too above =)

**Comment by LAGIdiot** [comment]
Thank you for answering my questions. 

I am kind of lost here because I am not able to get Flux Networks transfer energy. On their CurseForge page they are mentioning that they support EU but I don't think that it means native support for GTCE EU. Because if it was I would have it working for me right now. So there is probably some piece to this puzzle that I am not seeing...

**Comment by LAGIdiot** [comment]
Ah never mind I figure Flux Networks out.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.0
AE2: rv6-stable-7
EnderIO: 5.2.59
The One Probe: 1.4.28
Flux Networks: 4.0.15-32

**Enviroment:**
Modpack created on Twitch launcher

**Setup:**
![2020-08-30_11 05 00](https://user-images.githubusercontent.com/3093101/91655421-a9ac3380-eab0-11ea-891f-2a7db47aeb51.png)

**Outcome:**
Unable to reproduce

**Comment by XIPure** [comment]
Hmmm... interesting 🤔. Alright well in that case if it can't be reproducible in Your test world (Image(s) above) then I guess I'll just have to deal with the console spam lol; not that it affects Me or the gameplay in any way, but still.

**Comment by LAGIdiot** [comment]
When I am looking back to this I think it is related to #1283 and it is caused by Gregicality and logged under GTCE because they are using our logging capabilities.

**Comment by XIPure** [comment]
Hey :)
I just woke up and saw the new request, many thanks @LAGIdiot 👍 I'll be sure to keep an eye out for more updates from both the GTCE Team and Gregicality Team on Github/Discord! <3
