### ISSUE TITLE
[Question] Will item pipes implemented in this mod?

### ISSUE THREAD

**Issue by yanhaozhe** [GregTechCE/GregTech#1219]
In most technical mods, item pipes are necessary for automation. I want to know if this mod will contain item pipes in the near future? 
I found it is inconvenient to transfer items between machines because I can only use chests instead.

**Comment by LAGIdiot** [comment]
I have changed title for this issue as it felt odd. Anyway to you question.

We (mostly just me) are considering adding item pipes (or similar mechanic) in to GTCE. But right now it is not even on drawing board. And given our manpower it won't be implemented in near future as long as priorities does not change drastically.
