### ISSUE TITLE
[Suggestion] Show Fluid Canner bucket/cell filling recipes in JEI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1220]
**Is your feature request related to a problem? Please describe.**
Some people do not know that you can fill buckets or cells with fluids in the fluid canner machine, and think that the fluid canner machine only will fill batteries. This is because there is no JEI information about filling these items in the fluid canner

**Describe the solution you'd like**
Add JEI information demonstrating that the Fluid Canner can fill buckets and cells

**Comment by LAGIdiot** [comment]
Thank you for creating this issue.

**Status:**
Accepted

**Comment by idcppl** [comment]
Can this be a config option? Don't feel like they are that important to show on default.

**Comment by LAGIdiot** [comment]
Sure make it configurable sounds reasonable. Acceptation comment updated.

**Comment by fmarceau** [comment]
@ALongStringOfNumbers, @LAGIdiot should this be a JEI Info (addIngredientInfo) for Buckets and Cells or a special tab for Fluid Canner Machine (which seems more complex to implement) ?

**Comment by ALongStringOfNumbers** [comment]
I think this should be a info tab for the Fluid Canner Machine, as there is a config option for GTCE to hide their filled buckets and cells, which would make the players miss the Info tab if it was on the buckets. As this would move to an information tab, I believe the desire for a config option mentioned in the original issue could be discarded, because it would simply be added information tabs to a couple machines. 

As for how to add the information tab, I know it is possible with CraftTweaker via a method that JEI exposes ( the `addDescription` method). It may be possible to use this method, or something similar, just to add a simple information tab to the Fluid Canner machines.

**Comment by LAGIdiot** [comment]
I too think this should be **info page for Fluid Canner**.  Which also means that config option for removing it is **not necessary**.

Regarding implementation. I don't think there is way how to implement this easy way as it is not `Ingredient` so `addDescription` or it's not deprecated version is not available. This has to be probably done through JEI's `IRecipeCategory` and `IRecipeWrapper`. But that is where my knowledge of this ends. If I was one implementing it I would probably start from other GTCE JEI page which has similar feel.

I don't think this is good introduction like issue to GTCE, and I would rather not see @fmarceau burn out on first try. But if you still feel like working on it feel free.

**Comment by fmarceau** [comment]
That was exactly my problem @LAGIdiot... I couldn't find a way to make it work with addIngredientInfo. I agree with you that it might not be the best introduction to modded minecraft but since I started I will try to keep going. Thanks guys
