### ISSUE TITLE
[Suggestion] new methods for Material type

### ISSUE THREAD

**Issue by idcppl** [GregTechCE/GregTech#1224]
**Is your feature request related to a problem? Please describe.**
A method(s) for turning Materials to its extended material types(i.e. FluidMaterial, DustMaterial, ect.). This would allow you to add cables, pipes, and change some properties. 

**Describe the solution you'd like**
This could either be done through the Material type with a method(s) or through Material Bracket Handler. You'd just put the material type you want as the prefix.

**Comment by LAGIdiot** [comment]
Thank you for creating this issue.

I don't quite understand what you are trying to request here. Can you please elaborate more. If possible with some real use case.

**Comment by idcppl** [comment]
As of right now calling for the material isn't that useful besides maybe getting it's color and stuff to do with flags. It's mostly filled with unused logic or logic that not really relevant to modpack devs.

While these material types can get,
FluidMaterial, GemMaterial, and RoughSolidMaterial are all pretty useless, but would still need them for some syntax.
DustMaterial: Should be able to change oreByProduct, remember arch saying it was possible. Just it never actually was.
SolidMaterial: Would allow you to add types of enchantment to the tools.
IngotMaterial: Would allow you to add pipes and cables to a material without making a placebo material.

An example of code in crafttweaker would be, 
```
#loader gregtech
import mods.gregtech.material.MaterialRegistry;
import mods.gregtech.material.Material;
import mods.gregtech.material.IngotMaterial;

/* If there was a method to make a Material an IngotMaterial. */

var makeMeAPipe = <material:holmium>.makeIngot();
makeMeAPipe.setFluidPipeProperties(9001, 9001, true);


/* If there was a bracket handler to get IngotMaterial. */

var makeMeAPipe = <ingotmaterial:holmium>;
makeMeAPipe.setFluidPipeProperties(9001, 9001, true);


/* There also a third way, which is somehow allowing upcasting. */

var makeMeAPipe = <material:holmium> as IngotMaterial;
makeMeAPipe.setFluidPipeProperties(9001, 9001, true);
```
