### ISSUE TITLE
[Suggestion]Allow copper cable to be replaced by annealed copper cable

### ISSUE THREAD

**Issue by GlodBlock** [GregTechCE/GregTech#1229]
**Is your feature request related to a problem? Please describe.**
The copper cable cannot be replaced by annealed copper cable in most recipes.
Similarily,rubber cannot be replaced by silicon rubber and styrene butadiene rubber as well.
**Describe the solution you'd like**
Maybe you can add an extra oredict for them.

**Comment by LAGIdiot** [comment]
Thank you for requesting this feature.

Possibility to use Annealed Copper instead Copper sounds interesting as they are nearly same item. Regarding Rubber I don't think that it is good idea as there are quite different.

Problem is that GTCE does not support this behavior from get go. And implementing it would be way too time consuming (as it would mean touching core parts of mod) for how small advantage it will provide.
