### ISSUE TITLE
[Suggestion]Allow block cutting machine to support Forestry and Extra Tree log

### ISSUE THREAD

**Issue by GlodBlock** [GregTechCE/GregTech#1233]
**Is your feature request related to a problem? Please describe.**
The cutting machine can't cut logs of Forestry and Extra Tree into plank

**Describe the solution you'd like**
Could you allow cutter to accept Forestry logs?

**Comment by LAGIdiot** [comment]
Thank you for requesting this feature. This should be easily doable as we already support this behavior for our saw tools.

**Comment by LAGIdiot** [comment]
Just small extension to my previous comment there is already https://github.com/GregTechCE/GregTech/blob/a53edbe7d1cf42fd101464f50c580a3d73349015/src/main/java/gregtech/loaders/recipe/WoodMachineRecipes.java#L69 which should handle this situation but for some reason it is not able to find Forestry recipes. Further investigation required.

**Comment by fmarceau** [comment]
I will have a look

**Comment by fmarceau** [comment]
The way the code has been written, it seems to think like most non-vanilla Logs do not generate plank and so it is excluding them. For example: Log name: Larch Wood, Plank name: Air, Output: 0.
Upon further investigation, the process is essentially about iterating through the item from CraftingManaging.REGISTRY and it seems like Forestry is not using it hence why Forestry's logs aren't taken into account.

**Comment by GlodBlock** [comment]
Do you mean that the problem lies in Forestry and you cannot fix it?

**Comment by fmarceau** [comment]
> Do you mean that the problem lies in Forestry and you cannot fix it?

No, I think the problem resides with GTCE using the wrong list of recipes or relying on order of initialization... or both. I need to keep investigating...

**Comment by fmarceau** [comment]
I can confirm that, for some reasons, Forestry initializes **after** GTCE even if state otherwise in GTCE's @Mod definition. I will keep investigating.

**Comment by fmarceau** [comment]
@LAGIdiot at this point, I see two solutions here:
1- We move WoodMachineRecipes.init() down the initialization chain and put it to be executed when FMLInitialization runs which would be sad as RegistryEvent is the proper way to do it according to the doc
2- We add some custom code to add Forestry woods to the list of recipes

Any other idea?

**Comment by LAGIdiot** [comment]
> Here's what is happening:
> 
> 1- GTCE CommonProxy.registerRecipesLowest runs and tries to find all wood-related recipes for the Wood Machines
> 2- GTCE FMLPreInitializationEvent runs
> 3- Forestry FMLInitializationEvent runs and registers its wood types
> 
> I will keep investigating.

I think that list is incorrect. And it should be:
1. GTCE FMLPreInitializationEvent runs
2. GTCE CommonProxy.registerRecipesLowest - here we are looking for wood recipes
3. Forestry FMLInitializationEvent - here wood recipes are registered
4. GTCE FMLInitializationEvent runs

Can you please check it once more for correctness? Also this should cover Extra Trees so we should found out when that one is loaded.

I am seeing implementation for this as custom function which will run after Forestry & Extra Trees and it will run only if they are present. Which would mean some changes to how `processLogOreDictionary` works.

**Comment by fmarceau** [comment]
You were correct, GTCE PreInit runs before CommonProxy. Extra Trees runs after Forestry which explains why both of these aren't considered as wood recipes for GTCE machines. I will try to figure a way to process them during Initialization or Post-Initialization as a custom function.
