### ISSUE TITLE
[BUG] Optifine and GTCE throws CCL Exceptions

### ISSUE THREAD

**Issue by DarkAmbientNoise** [GregTechCE/GregTech#1236]
**Describe the bug**
Running Optifine with shaders, no texturepack required, immediately throws CCL Rendering Exceptions for "Block Class: class gregtech.common.blocks.surfacerock.BlockSurfaceRockNew" the second a world is loaded.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.12.2-1.10.1.557
CodeChicken Lib 1.8.+: 1.12.2-3.2.3.358
**Modpack:** None: Minimum to run GTCE and attempt to catch this bug.
**Addons:**
JEI 1.12.2-4.16.1.301
Optifine 1.12.2-_HD_U_F5
ProjectLUMA -v1.32 shaders. (Direct Link) https://dedelner.net/download/projectluma-v1-32/

**Setup**
Playing Solo Default World. New World as a testing environment.

**Steps To Reproduce**
1) Load any world with GTCE and Optifine running shaders.
2) Done. Immediate Results.

**Expected behavior**
Not having CCL Render errors spammed in logs and displayed as an error in-game.

**Screenshots**
![2020-09-07_21 16 27](https://user-images.githubusercontent.com/12950685/92426518-bb947300-f14f-11ea-8959-b2a7213fed15.png)

**Log**
With Shaders. [latest.log](https://github.com/GregTechCE/GregTech/files/5185709/latest.log)
Without Shaders, just removed Optifine. (No CCL errors) [latest.log](https://github.com/GregTechCE/GregTech/files/5185748/latest.log)

**Additional context**
Possible Additional Info https://github.com/GregTechCE/GregTech/issues/1216

**Comment by eutropius225** [comment]
Optifine and shaders can't really be fully supported, given that they are closed source, and thus diagnosing and fixing these bugs is either impossible or very difficult.

CCL most likely has an option to disable errors being logged and spamming chat.

**Comment by DarkAmbientNoise** [comment]
I was aware of the option to disable the errors for CCL errors, but thanks! I didn't realize Optifine was closed source. That's kind of a shame, but thanks for the information on it. This technically has a workaround for the end user, but all that logging does cause performance dips in the end, and I'm always in favor for improvements!

Although it does puzzle me how CTCE seems to be the only mod I've come across that really throws tons of these errors, so I'm sure there is some kind of fix, hopefully without completely redoing the graphical pipeline for the mod. However, I'm not the one who can answer or solve that. I only know enough to look semi-competent, but that's about it.

**Comment by LAGIdiot** [comment]
Thank you for reporting this bug. We are aware of this type of issue. As was already mentioned this type of bugs is really hard for us to investigate and fix. Currently I can just suggest you either turn off errors reporting or complete removal of surface rocks (from world gen files and world itself). I will link this with other related errors.
