### ISSUE TITLE
[Suggestion] Machine in Rain goes boom

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1238]
I was wondering how people feel about bringing back this feature from GT5U, I know Arch did not like it and many others don't either but I would like to see it as an optional thing (config option that is disabled by default)

It adds a little bit of immersion to the game which for me as the pack of a Hardcore pack is nice.

**Comment by Saereth** [comment]
I mean its not too hard to do as a config, but generally speaking yeah its so incredibly immersion breaking and stupid I'm glad arch left it out. I run my washing machine outside in a rain storm and it'll work fine, at worst it'll short out. It wont blow up my garage. Mechanically all it does is force a block to be placed over it, it adds no challenge whatsoever and offers no game play improvement, it shouldn't even exist in gt5u because it's just as stupid there and hanging onto it is purely putting nostalgia over user friendliness.

**Comment by Shattered2909** [comment]
That's true, my point is mostly nostalgia =P

...and being an ass to players *wink*

**Comment by eutropius225** [comment]
In this case I think arguing for realism doesn't make sense, given the existing, similar feature of overvoltage causing explosions.

**Comment by Saereth** [comment]
Yeah sure arguing for realism is a lost cause because they just dont translate well into a game many times, some elements sure, but the rain thing is just unintuitive as well. Regardless it really is a pretty easy bit of code to add so meh rain go boom away :P

**Comment by idcppl** [comment]
The only good thing about this is that it usually incentivises people to build a base. Would need to have some logic to it, like a splash zone. So that they don't just build a random roof above the machine(s).

**Comment by LAGIdiot** [comment]
I agree that it is easy to implement but I also feel that it is empty mechanic. Some time ago I was proposing this but right now I don't feel like supporting it. If someone is able to extend idea of  "Machines go boom when rain falls on them when they are working" to something more immersive then why not. For now leaving open for discussion.

**Comment by Saereth** [comment]
tbh my only real objection is added performance hit. You'd have to check if the block can see the sky and all blocks around it for your buffer zone every few ticks for every single gregtech machine... maybe there is a more performant solution idk, might check out gt5u did it

**Comment by galyfray** [comment]
why not only checking if it rain and the config is enable first ? If it doesn't rain we only add an if it should be light enough for not impacting fps/tps too much.

**Comment by galyfray** [comment]
raining on machines can make an efficiency loos ? like shot circuit causing ticks to drain power but not work ? it would need a small tweak here :  
https://github.com/GregTechCE/GregTech/blob/59cf924550f97635e1f576bf68309adcb8bface9/src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java#L119
simply adding a protected method for checking if it rain near the meta tile and if config is ok with this in the class the implementation should be easy and the concept more immersive.

**Comment by Archengius** [comment]
Please let's not add features that introduce nothing new into the gameplay except annoyance and punish the players for no reason, even as configuration options disabled by default. GTCE was designed with an idea of NOT punishing players unreasonably and intentionally leaving out annoying things of GT5U. That's just against the spirit of the mod to have that feature, even as an configuration option.
