### ISSUE TITLE
[BUG] Crafting Station Crashes and dupes items when ingredients are split between inventories

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1241]
**Describe the bug**
When the ingredients for a craft are split among several inventories, the crafting station only consumes the items from one of the inventories to complete the craft and then crashes (Catchable by Vanillafix). If VanillaFix is installed, adding additional items to the inventory and then removing items through the storage tab will result in an item dupe and another crash

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.1.557
_Modpack:_ Omnifactory development version on the updateGregTechCE branch
_Addons:_ SoG 2.14

**Setup**
Playing Solo (Only tested solo)
_New world generated_ Yes

**Steps To Reproduce**
1) Place a Crafting Station down, and two vanilla chests on the left and right side of the crafting station
2) Add a recipe for a Vanilla Crafting workbench to the Crafting Station (made from 4 planks)
3) Add two planks to either chest on the sides of the Crafting Station.
4) Crafting the Vanilla Workbench and notice the crash and that 2 of the planks are still in one of the chests
For the second crash and dupe:
5) After noticing that there are two planks remaining in one of the chests, add 4 more planks to the chests, with at least one of the planks being put in the chest that did not have the previously duped planks
6) Go to the storage tab of the crafting station and pull out the items in the tab. Notice the second crash, and that there are some items remaining in the storage tab even though you just pulled out all available items. The amount of items remaining is equal to the number of items that were in the chest with the originally duped planks..
7) Pull out these items as well

**Expected behavior**
No crash and no items being duped. For the Crafting Station to pull all required items from surrounding inventories, not leaving any behind

**Screenshots**
Setup Picture
![2020-09-16_11 13 41](https://user-images.githubusercontent.com/31759736/93377768-50623500-f810-11ea-97d8-5f6c06e99afe.png)

**Additional context**
Crash 1: [https://pastebin.com/yC6aZVb6](https://pastebin.com/yC6aZVb6)

Crash 2: [https://pastebin.com/Xf8xPT8N](https://pastebin.com/Xf8xPT8N)

**Comment by Exaxxion** [comment]
I was the one who mentioned this issue to ALSON, and I'll add that the type of inventory doesn't seem to matter, so long as it permits bidirectional movement (i.e. doesn't run into #1239).

When I came across it I was using AA small crates.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

**Outcome:**
Bug confirmed. Based on provided logs.
