### ISSUE TITLE
[Suggestion] Nano Saber Damage Config Option

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1242]
At the moment, the Nano Saber is really expensive for what it does and some Modpacks mess with the Stats of Mobs, also Mods like Abyssalcraft have harder Mobs than Vanilla, so it would be nice to be able to tweak the damage of the Nano Saber in the Config. Maybe also a config option to allow it to ignore Armor? Maybe a number between 0 and 100 to ignore % of the Armor.

**Comment by Saereth** [comment]
yeah this would be great, I know I woulda buffed it for interactions for sure

**Comment by Shattered2909** [comment]
It's far better than the 1.7 one but still not even close to something like Draconic.

**Comment by LAGIdiot** [comment]
Thank you for requesting this change. Nano Saber has enchantibility of Gold item so that can be used as an advantage for it. But sure we can have this special weapon have configurable damage.
