### ISSUE TITLE
[BUG] Issues with Thaumcraft golems and block placing

### ISSUE THREAD

**Issue by Volk101** [GregTechCE/GregTech#1243]
**Describe the bug**
Trying to use TC6 golems to block place GT ores for starlight transmutation (early way of ore doubling).

Golem is retrieving GTCE magnetite ore from vanilla chest (through advanced provider seal) and trying to place ore at a nearby use seal. The ore is shown with a missing texture while being held by the golem (I believe this is normal issue for TC6). Golem is unable to place ore and will continue to retry until it is stopped through use of golemancer's bell. (Not sure if there is a perm issue stopping the golem, fakeplayer set to 'ally' which should allow placing, but may be a separate perm for TC6 that I'm unaware of)

When golem is shift right clicked, it is dropped into the world along with the ore it was carrying (still missing texture). Once the ore is picked up, MC crashes (client crash). Player is unable to log into server (continues to crash on inventory load).

If using an NBT editor on player.dat, the offending ore can be seen and removed, after which point no further issues occur.

Playing FTB Interactions 2.0.9 with GTCE 1.6.0 and Thaumcraft 6.1-B26

**Versions**
MC 1.12.2, FTB Interactions 2.0.9 with GTCE 1.6.0 and Thaumcraft 6.1-B26
Forge 14.23.5.2847

**Setup**
Multiplayer server

**Steps To Reproduce**
1) Used golem to try to place GTCE ore, is unable to
2) Shift right click to retrieve golem
3) Picked up ore that golem was previously holding, client crash
4) Can not log in to server until player.dat updated to remove offending GTCE ore

**Expected behavior**

**Screenshots**

**Additional context**
Crash report attached
[crash-2020-09-23_06.38.22-client.txt](https://github.com/GregTechCE/GregTech/files/5264823/crash-2020-09-23_06.38.22-client.txt)

Someone else on Disc mentioned -
> I've crashed my game in FTB interactions by:
> - Picking up a roost with a portal gun
> - Dollying a gregtech machine
> - **Specifying only oredict on a golem seal creating a glitched block that the golem created**
@gold_me#7702 

_Please fill in as much useful information as possible. Also please remove all unused sections._

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

If I understand correctly there are two problems. One is Thaumcraft golem unable to place our ore block (or any block at all?) and game crashing after ore from golem is picked. Is that right?

Are you sure about reported version? I am getting different information from crash log.
Can you please provide malformed `player.dat` file.
Also can you please provide log from game when golem is performing task of placing ore as data may be already malformed at that time.

**Comment by LAGIdiot** [comment]
I am closing this issue as stale. If there is still required any action from GTCE side then feel free to re-open this issue.
