### ISSUE TITLE
[BUG] Crash when attempting to Auto Output to an inventory through a shutter upgrade

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1246]
**Describe the bug**
When attempting to auto output to an inventory (tested with a vanilla chest and a storage drawer) through a shutter upgrade, the game crashes and it becomes impossible to load back into the save

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.2.557
_Modpack:_ None. Minimal Reproducing environment used
_Addons:_ None

**Setup**
Playing Solo (Only tested Solo)
_New world generated_ if applicable: Yes

**Steps To Reproduce**
1) Place down a machine, in this case it was an LV lathe powered by a battery buffer
2) Add a shutter cover to the left side of the machine
3) Enable Auto Output in the Machine GUI
4) Place an inventory on the left side of the machine (tested with a storage drawer and a vanilla chest)
5) Use a GTCE Wrench to change the output side of the machine to the left side
6) Crash

**Expected behavior**
No crash. The machine runs but does not output due to the shutter cover

**Screenshots**
Minimal Reproduction case before the inventory is added and the output side is changed
![2020-09-23_13 37 24](https://user-images.githubusercontent.com/31759736/94066993-18279d00-fda2-11ea-9225-21c5b7d443c1.png)

**Additional context**
Crash with Storage Drawer: https://pastebin.com/UkA2Z5kP
Crash with Vanilla Chest: https://pastebin.com/KSy4YbRZ

**Comment by phantamanta44** [comment]
inventory handler retrieved from the cover [here](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L887) should be null-checked before trying to do anything with it

(for that matter, the same thing in the [sister method](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L906) also has the same issue)

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

**Outcome:**
Bug confirmed. Based on provided logs and source code.
