### ISSUE TITLE
[Suggestion] Separate to some modules

### ISSUE THREAD

**Issue by ym1025** [GregTechCE/GregTech#1249]
**Is your feature request related to a problem? Please describe.**
I wonder that why isn't GTCE separate modules?

**Describe the solution you'd like**
Please separate to some modules. Ex) material module, energy module, machine module, and etc

**Additional context**
Modpack makers and mod developers can use only material module, and make contents with many realistic materials.
It will be a big change to Tech-mod developers.(I wanna be a mod developer :D)

**Comment by LAGIdiot** [comment]
Thank you for requesting this feature. I completely agree that having modularization in GTCE could bring us many advantages. But in current state of mod thanks to it's complexity, size and many hacks in implementation (mostly inherited parts for older MC versions) it is not realistic to undergo such big change as it would totally wreck compatibility and and would cost us way too much manpower (which we currently don't have). Of course I will have this in mind when designing new features and think if they could be made as separate module.
