### ISSUE TITLE
[BUG] Trying to compile the code from source does not work

### ISSUE THREAD

**Issue by bulldog98** [GregTechCE/GregTech#1250]
**Describe the bug**
I tried to compile the 

**Setup**

**Steps To Reproduce**
1) Do a new git clone
2) Compile it and notice that chickenlib does not get downloaded

**Expected behavior**
ChickenLib should get downloaded, but it seems that the version is no longer in the maven repro

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.
But I am not able to reproduce it. I am able to download CodeChichenLib normally. Also link to its maven works as expected: http://chickenbones.net/maven/codechicken/CodeChickenLib/1.12.2-3.2.3.358/ .
Maybe there was some problem at time you tried but for me it is OK now. So can you try again please and let me know how it goes?

**Comment by bulldog98** [comment]
Yes it work's now. But I think it would be a good idea to provide a wiki page or something on how to start developing on the project. Because, for example I'm unable to get the genIntellijRuns to work it throws a NullPointerException every time.

**Comment by LAGIdiot** [comment]
I don't think that there is anything special needed for developing on GTCE but I suppose I could throw some page together which will mention basics.
Problem you are experiencing is in method implemented by Forge and probably is not even related to GTCE dev setup. Or it can be even environmental problem. But of course if you are interested in developing GTCE please come to our Discord and we may try to help you with that problem.
