### ISSUE TITLE
[Suggestion] GemMaterial and RoughSolidMaterial not having a zenclass

### ISSUE THREAD

**Issue by idcppl** [GregTechCE/GregTech#1251]
**Is your feature request related to a problem? Please describe.**
You cannot check if a material is an instanceof either of these since they lack a zenClass.

**Describe the solution you'd like**
Give them zenclasses, even though there will be no methods for either.

**Additional context**
Kind of related to #1232 and #1224

**Comment by LAGIdiot** [comment]
Thank you for requesting this feature.
This seems reasonable and can be done quite easily and if it is any use for CT scripters then why not. Accepted.
