### ISSUE TITLE
[BUG] A Crafttweaker method doesn't exist even though it's in the code.

### ISSUE THREAD

**Issue by idcppl** [GregTechCE/GregTech#1261]
**Describe the bug**
The method called `generationFlagsRaw` in Material doesn't actually work. Doesn't even exist in `/ct dumpzs html`.

**Versions**
1.10.2 - aka current

**Additional context**
https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/unification/material/type/Material.java#L168  
Was expecting to be able to be able to get all the flags in one step, instead of calling methods over and over.

**Comment by LAGIdiot** [comment]
Thank you for creating this issue.

That value is `protected` so it should not be available through CT at all. And even if I expose it as getter I am not sure if it really covers your expectation. As you would still need to do bit-wise operations to find out which flags are included.

**Comment by idcppl** [comment]
Yeah, realized you can't really do much with a long that is a bunch of or's. Turns it all into one number.
