### ISSUE TITLE
[BUG] Crash with Covers when TileEntities lose their capabilities

### ISSUE THREAD

**Issue by PrototypeTrousers** [GregTechCE/GregTech#1263]
**Describe the bug**
 Placing two Gregtech tanks ( not quantum tanks ) with pumps facing each other in import mode will crash the game on world load.

**Versions**
Mods:
CodeChickenLib-1.12.2-3.2.3.358-universal
gregtech-1.12.2-1.10.2.566
jei_1.12.2-4.16.1.301
MouseTweaks-2.10-mc1.12.2

**Setup**
Playing Solo
New world generated

**Steps To Reproduce**
1)Place 2 tanks adjacent to each other
2)Place pumps on the tanks, facing each other
3)set them to import
4)Save and quit
5)try to load the world

**Expected behavior**
Placing 2 tanks touching will form a multiblock
Placing one pump will visually show the multiblock not forming anymore.
Placing the second one will work as usual.
Setting the pumps to import
Save and quit
Restart world. Crash.

Crash Report
https://pastebin.com/t2ERFTDJ

**Screenshots**
tanks placed down
![1](https://user-images.githubusercontent.com/11739607/95140036-431bd480-0744-11eb-8404-b494c036b1cd.jpg)
pump installed on right tank
![2](https://user-images.githubusercontent.com/11739607/95140037-43b46b00-0744-11eb-9202-6b365acc602d.jpg)
placing water will fill both tanks
![3](https://user-images.githubusercontent.com/11739607/95140039-444d0180-0744-11eb-9974-bc7112a32d9d.jpg)
saving and reloading will show the multiblock formed again
![4](https://user-images.githubusercontent.com/11739607/95140038-444d0180-0744-11eb-91de-4ffd8db60b07.jpg)
installed pump in the left tank, set as export
![5](https://user-images.githubusercontent.com/11739607/95140040-444d0180-0744-11eb-807f-0b625e735e43.jpg)
reload world ( if theres still water on both during the save it will crash on load too
![6](https://user-images.githubusercontent.com/11739607/95140041-44e59800-0744-11eb-8462-d45de8be1a98.jpg)
setting both pump to import will crash the world on load

**Comment by PrototypeTrousers** [comment]
broke between gregtech-1.12.2-1.8.8.440 and gregtech-1.12.2-1.8.9.457 so i guess since multiblock tanks is a thing

**Comment by LAGIdiot** [comment]
**Version:**
GTCE: 1.10.2

**Outcome:**
Bug confirmed based on provided crash-log

**Additional information:**
This is definitely related to multiblock tanks. It seems that multiblock was formed in same time as Pump Cover started working (on load) which lead to loosing `FluidHandlerDelegate` which was then used by Pump Cover. But this situation should not happened as multiblock tank should not be formed when there is cover.

**Implementation notes:**
Check code for multiblock tank forming and prevent it in case that cover is present on side which would be **in**.

**Comment by PrototypeTrousers** [comment]
From java/gregtech/api/metatileentity/MetaTileEntity.java
`public final <T> T getCoverCapability(Capability<T> capability, EnumFacing side) {`
       `          boolean isCoverable = capability == GregtechTileCapabilities.CAPABILITY_COVERABLE;`
       ` CoverBehavior coverBehavior = side == null ? null : getCoverAtSide(side);`
       ` T originalCapability = getCapability(capability, side);`
       ` if (coverBehavior != null && !isCoverable) {`
           ` return coverBehavior.getCapability(capability, originalCapability);`
        `}`
       `return originalCapability;`
    `}`

from what i have seen, `CAPABILITY_COVERABLE` is a tile capability, so it should not be checked here?
`getCoverCapability` gets ticked before `getCapability`, where `CAPABILITY_COVERABLE` is cast to the tile entity.

So, `boolean isCoverable = capability == GregtechTileCapabilities.CAPABILITY_COVERABLE;` always evaluates to false on the first time its ticked.
`T originalCapability = getCapability(capability, side);` will be null, since `CAPABILITY_COVERABLE` is not yet cast to the entity.
that explains why it crashes on reload, but not while the world is running.

removing `boolean isCoverable = capability == GregtechTileCapabilities.CAPABILITY_COVERABLE;` and `&& !isCoverable`, fixes the crash but the multiblock still forming with the covers installed persist.

**Comment by PrototypeTrousers** [comment]
from gregtech/common/covers/CoverPump.java
`@Override`
`    public <T> T getCapability(Capability<T> capability, T defaultValue) {`
`        if (capability == CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY && defaultValue != null) {`

adding the null check avoids the crash but not solves the issue completely, the case being defaultValue should never been null since we check for the capability before even placing the cover.

**Comment by PrototypeTrousers** [comment]
Managed to crash a brewery by installing a conveyor, then wrenching its output side to the conveyor. (brewery only has fluid_item_capability on sides other than output, so defaultValue becomes null). crashes after trying to place anything with capability on the same side (conduits,pipe from logistics pipes,etc)

**Comment by LAGIdiot** [comment]
Closing as this one was already fixed
