### ISSUE TITLE
[BUG] Machine controllers display too high of redstone level

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1268]
**Describe the bug**
The machine controller minimum redstone strength slide bar goes from 1 to 16, despite vanilla redstone going from 0 to 15

**Versions**
Forge: 
GTCE: 1.10.1.557
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo/Multiplayer/Both: Solo, only tested solo
_New world generated_ if applicable: yes

**Steps To Reproduce**
1) Place a machine and then add a machine controller as a cover
2) Acess the machine controller gui and see that the slider goes from 1 to 16

**Expected behavior**
I am unsure if the machine controller should have a signal strength of 0 as an option, as that does not make sense. So starting at 1 is fine for the machine controller, but it should be capped at 15 like the maximum vanilla redstone strength.

**Screenshots**
![level](https://user-images.githubusercontent.com/31759736/95667460-61eee200-0b1b-11eb-9547-68ad9f729b91.PNG)

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.2 (dev build on f49c3f6427eb9b02a4797c31aa16bbfa875a7d2f)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Implementation notes:**
Set maximum of `SliderWidge` to 15.
Set value loaded from NBT to 15 if it is above it.

**Comment by PrototypeTrousers** [comment]
boolean shouldAllowWorking = getRedstoneSignalInput() < minRedstoneStrength;
if(isInverted) shouldAllowWorking = !shouldAllowWorking;

shouldnt this be <= ?
as it is setting the maximum of the slider to 15 will make the machine controller either on or off permanently.

**Comment by ALongStringOfNumbers** [comment]
Hm, having to change the < to a <= will change the current behavior of the machine controllers, by decreasing required redstone levels by one. However, not changing the comparison will lead to maximum redstone level of 15 being ignored. This might have been the reason that the machine controllers originally went to a level of 16.
