### ISSUE TITLE
[BUG] Machines total EU is not correct in recipes

### ISSUE THREAD

**Issue by idcppl** [GregTechCE/GregTech#1272]
**Describe the bug**
Machines actually use 1 less tick of total eu. So the last tick doesn't actually do anything.

**Versions**
Forge: 2847
GTCE: 1.10.2

**Setup**
Single player.

**Expected behavior**
To use the proper amount of EU.

**Additional context**
Just messing around with my addon, and noticed that I wasn't generating the last tick of EU from a generator I was making. Then I decided to test if it also happened to processing recipes.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. I think this is going to be simple +-1 problem which should not be hard to be fixed. Further investigation pending.

**Comment by huneau** [comment]
@LAGIdiot 
Found the issue I think.
When a recipe is setup the progressTime start at 1 here: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java#L272
and do not consume EU
After that and on each tick you increment the progressTime and after you check the max progress time here:
https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java#L122
Multiple solution to fix this 
```java
            if (++progressTime > maxProgressTime) {
                completeRecipe();
            }
```
or
```java
            if (progressTime++ >= maxProgressTime) {
                completeRecipe();
            }
```
or ...

**Comment by LAGIdiot** [comment]
@huneau Thank you for looking for it. That is correct place but I am not sure about that proposed fix. Personally I don't like that progress timer starts on 1. I will take this one myself and think about better solution for this.
