### ISSUE TITLE
[BUG] Manganese vein is not generated

### ISSUE THREAD

**Issue by soyo-mai** [GregTechCE/GregTech#1276]
**Describe the bug**
Manganese vein is not generated.

**Versions**
Forge: 1.12.2-14.23.5.2854
GTCE: gregtech-1.12.2-1.10.3.569
othermod:
Baubles-1.12-1.5.2
ChainDestruction-1.12.0-1.5.5
CodeChickenLib-1.12.2-3.2.3.358-universal
CoFHCore-1.12.2-4.6.6.1-universal
CoFHWorld-1.12.2-1.4.0.1-universal
CraftingEX_1.12-v1.2.0
EnderCore-1.12.2-0.5.76
EnderIO-1.12.2-5.2.59
forestry_1.12.2-5.8.2.387
Forgelin-1.8.4
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
GasConduits-1.12.2-1.2.3
GrimoireOfGaia3-1.12.2-1.7.2
HeatAndClimateLib_1.12.2-3.4.1
HeatAndClimateMod_1.12.2-3.4.1
Hwyla-1.8.26-B41_1.12.2
ImmersiveEngineering-0.12-98
immersivepetroleum-1.12.2-1.1.9
InventoryTweaks-1.63
ItemDelocalizer-1.12.2-0.7.1b
jei_1.12.2-4.15.0.291
journeymap-1.12.2-5.7.1
JustEnoughPetroleum-0.1
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
MekanismTools-1.12.2-9.8.3.390
MicdoodleCore-1.12.2-4.0.2.280
Nutrition-1.12.2-4.6.1
OptiFine_1.12.2_HD_U_F5
RedstoneFlux-1.12-2.1.1.1-universal
refinedstorage-1.6.16
Shadows_of_Greg-1.12.2-2.14.0
ThermalDynamics-1.12.2-2.5.6.1-universal
ThermalExpansion-1.12.2-5.5.7.1-universal
ThermalFoundation-1.12.2-2.6.7.1-universal

**Setup**
Playing Solo

**Steps To Reproduce**
1) delete the file in .minecraft\config\gregtech\worldgen\overworld except manganese_vein.json, and generate world.
2) then i found no gtce vein is generated.

**Screenshots**
![2020-10-17_15 44 31](https://user-images.githubusercontent.com/70464230/96330517-bb618e80-1090-11eb-9a28-3001e993e206.png)
(generated vein is other mod's)

**Additional context**
end manganese vein is also not generated.
i'm japanese, and excuse my imperfect english.

**Comment by ALongStringOfNumbers** [comment]
This sounds similar to an issue we were having in our modpack. There is an analysis done here: https://github.com/OmnifactoryDevs/Omnifactory/pull/490 but the short of it is that the minimum height generation is too high to actually generate the ore. I am not sure if this is the case with default veins, as I am unsure if the veins used in our pack for the ores mentioned were the default ones. 

A quick fix is to change the minimum height of the vein to 10, if the current file specifies max: 30 min: 20 as in our case. Although, it would be nice for some logging in the case of ore generation to log the fact that the vein is given an invalid generation specification.

**Comment by soyo-mai** [comment]
@ALongStringOfNumbers 
Thank you for your advice!
Finally I get manganese vein!
It seems two issues is occurred.
One is your issue, and another is my fault.
I changed manganese vein's surface_stone_material into "manganese", and this did wrong.
Changing it into "pyrolusite", it went well.
I didn't notice it until looking log!
