### ISSUE TITLE
[Question] Do red granite exists?

### ISSUE THREAD

**Issue by ecr99** [GregTechCE/GregTech#1278]
I see that those base structures with a vault and a cobalt hammer inside have some stones that aren't generated in game. IE: Red granites and that block stone.   

Is this a bug of my game? Or those stones arent implemented in the world gen yet?

Thanks in advance , have a nice day!

**Comment by LAGIdiot** [comment]
All GTCE stone materials should be generated. Generation of Red Granite is handled by `red_granite_sphere.json` in <game directory>/config/gregtech/overworld and as long as it was deployed it should spawn. We are not aware of any bug that could prevent spawning of this right now. All GTCE stones are not required for progression.
