### ISSUE TITLE
[BUG] Robot arm filter configured to Keep Exact with a ItemStack size >127 does not persist on reload

### ISSUE THREAD

**Issue by PrototypeTrousers** [GregTechCE/GregTech#1280]
**Describe the bug**
Setting a robot arm to keep 512 cobblestone on its item filter, will work until a world reload, when its gone from the item filter.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.3

**Setup**
Playing Solo
New world generated

**Steps To Reproduce**
1) Configure arm to Keep Exact
2) Place a filter on the arm
3) Place a item on the filter
4) Shift right click on the item until it goes over 127
5) Save world and reload
6) Check arm and see item gone from the filter slots

**Expected behavior**
I expect the item filter to keep its configured item amount on reload.

**Additional context**
Forge casts item count as byte when writing NBT.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.4 (dev build on 59cf924550f97635e1f576bf68309adcb8bface9)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Additional Info:**
Robotic Arm allows to specify amount via Item Filter for it's mods how much Items should be transferred/kept. That is handled by ItemStack (in ItemStackHandler) which is root of problem as ItemStack allows to specify any size as long it is integer but it stores it in NBT as Byte (for F sake).

I will take this item myself as I already have some idea how to handle this.
