### ISSUE TITLE
[BUG] Filler rocks not oredicted

### ISSUE THREAD

**Issue by DoctorWeirdGuy** [GregTechCE/GregTech#1285]
**Describe the bug**
Several rocks such as red/black granite, marble and basalt have not been oredicted.  As a result you cannot macerate these into their respective dusts. 

**Versions**
Forge: 14.23.5.2854
GTCE: 1.10.2.566
_Modpack:_ Custom pack with default configs. 
_Addons:_ None that would change base GTCE behaviour. 

**Setup**
Playing Solo

**Steps To Reproduce**
1) Look at the list of named rocks
2) Check for their oredict entries

**Expected behavior**
Properly oredicted blocks, so that their macerator recipes get generated properly.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.4 (dev build on 59cf924550f97635e1f576bf68309adcb8bface9)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed and accepted

**Additional notes:**
Properly oredict all Blocks based on `StoneBlock`.
