### ISSUE TITLE
[Suggestion] Separate vanilla granite from red/black granite

### ISSUE THREAD

**Issue by DoctorWeirdGuy** [GregTechCE/GregTech#1286]
**Is your feature request related to a problem? Please describe.**
Rather than macerating vanilla granite blocks into black/red granite dusts, give vanilla granite its own dust counterpart so it's more consistent as andesite and diorite also have their own dust counterparts. 

**Describe the solution you'd like**
Add a vanilla granite dust and change the macerator recipe to give that instead of black/red granite dust. 

**Additional context**
Somewhat OCD that andesite and diorite have dust variants but vanilla granite does not.

**Comment by LAGIdiot** [comment]
Thank you for requesting this change. I took a look at it and it does not make sense to "cast" Vanilla MC Granite to our Black Granite. And I think this is probably mistake which happened when porting mod to this version. Granite should be definitely it's oven material with similar stats to Andesite and Diorite.

I will take this one for myself.
