### ISSUE TITLE
[BUG] Crash-to-desktop on loading world with Gtech pumps exporting into ImTech pipes.

### ISSUE THREAD

**Issue by CelestialPhoenix** [GregTechCE/GregTech#1289]
**Describe the bug**
When using a Gregtech pump cover to export fluids into Immersive Technology pipes the game crashes to desktop when re-opening that world.

This specifically happens with the pump cover exporting into the ImTech pipe. 
Using the machine's auto-export works perfectly fine, and no issues with other mod machines when testing the full pack.
Pumping into other mod pipes does not cause a crash.

**Versions**
minecraft            | 1.12.2       | minecraft.jar              
mcp                  | 9.42         | minecraft.jar     
FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar 
 forge                | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar     
 codechickenlib       | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar 
 jei                  | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar       
 gregtech             | 1.10.3.569   | gregtech-1.12.2-1.10.3.569.jar   
 immersiveengineering | 0.12-98      | ImmersiveEngineering-0.12-98.jar   
(issue isolated down to the above list, full pack list [available here](https://www.curseforge.com/minecraft/modpacks/blood-sweat-and-gears))

**Setup**
Singleplayer

**Steps To Reproduce**
Place a Gtech pump cover on the side of a tank/machine, and set it to export.
Connect a ImEng Fluid Pipe to the pump, and add some fluid to the system.
Close and reload the game, then log back into that world.

**Other notes**
Lost access to my Mojang login before I could verify the issue on latest Gtech update. Changelog does not mention pumps- so its likely to effect the latest version too.
I asked on the Gtech discord if anyone could verify it as was asked to drop it here.

**Comment by PrototypeTrousers** [comment]
related to #1263

**Comment by LAGIdiot** [comment]
Thanks for reporting this issue. This does look like it is related to #1263 and investigation will continue there. I will leave this one open so w can retest solution for this too and for case that we would need additional info.
