### ISSUE TITLE
2 cents

### ISSUE THREAD

**Issue by Ezoteric** [GregTechCE/GregTech#129]
Integrated circuit no config recipe
Cant change it with the solderingiron :)

Also the Texture from the cell is messed up:
![2018-06-15_14 52 26](https://user-images.githubusercontent.com/14137626/41468968-f6db2ad4-70ab-11e8-91ae-3591ea821e44.png)

**Comment by EmosewaPixel** [comment]
You right-click it to change the configuration.

**Comment by Archengius** [comment]
>Cell texture is fucked up
It was said 10000000000000000 times.
>Integrated circuit no config recipe
It has GUI, did you know?

**Comment by Ezoteric** [comment]
ow wait soz didnt know about both 🗡
