### ISSUE TITLE
[BUG] Crafting Station can void items from crafts

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1291]
**Describe the bug**
The crafting station can void items from crafts that have multiple numbers of the output item depending on which mouse button is used to take the item. It seems like the functionality to right click and take half of a stack is being combined with a click to take outputs from the output slot.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.4.574
_Modpack:_ tested in minimal environment
_Addons:_ None

**Setup**
Playing Solo (only tested solo)
_New world generated_ if applicable: yes

**Steps To Reproduce**
1) Place a crafting station down and enter the vanilla recipe: 1 log -> 4 wood planks
2) Left click on the output slot and receive 4 wood planks, as expected
3) Right click on the output instead and receive 2 wood planks, which is half of the expected output. 

**Expected behavior**
Receive all items from crafts that output multiple of the same item.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.4 (dev build on 59cf924550f97635e1f576bf68309adcb8bface9)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed and accepted.

**Additional notes:**
This behavior looks like default behavior of right click. Maybe crafting slot has to be somehow marked that it should convert right click to left?

**Comment by ALongStringOfNumbers** [comment]
This seems to happen because of a combination of methods in `CraftingSlotWidget#onItemTake()` 

First of all, a minor issue, but `CraftingRecipeResolver#handleItemCraft()` will take in the stack, but then look up the recipe against its catched recipe map without checking the amount of the passed stack. This results in an incorrect number being added to `this.itemsCrafted`. This is a minor issue overall, but could be resolved here by checking the stack passed to the method, instead of the catched recipe.

Next, `CraftingRecipeResolver#refreshOutputSlot()` will be called, which will ignore the fact that there is a remainder from the performed recipe (In the case of the reproduction example, the remainder is 2 planks) and instead set the output slot to the output of the catched recipe, effectively voiding the output items.

At this time, I don't know how the call to `CraftingRecipeResolver#performRecipe()` affects things, I still have to look into this method more. 

The easiest solution would simply be to treat the right click as the left click, although this would be someone hard, as when the `CraftingSlotWidget#onTakeItem()` method is called, the halved stack from the right click is what is passed to the method. It might be possible to find out what mouse button was used, and then double the passed in ItemStack if it was a right click, although I don't know if this would be possible or cause any desync issues or anything like that.

**Comment by LAGIdiot** [comment]
Thanks for analysis. When I think back about this issue that handling of right click is same as in inventory but output slot should not behave as standard inventory slot. So best fix would be to make slot used in Crafting station to behave in same way as one Crafting table.
