### ISSUE TITLE
[BUG] Accidently removed quartz block decompressing recipe

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1292]
**Describe the bug**
In #1188, the decompressing and compressing recipes for many vanilla blocks were removed. However, the decompressing recipe for quartz blocks -> quartz was removed, which does not exist in vanilla MC. It would be preferable if this recipe was restored, as it does not conflict with vanilla recipes

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.4.574
_Modpack:_ minimal environment
_Addons:_ none

**Setup**
Playing Solo (only tested solo)
_New world generated_ if applicable: yes

**Steps To Reproduce**
1) Search quartz block in JEI and see that it is missing a decompression recipe

**Expected behavior**
Since this recipe did not conflict with a vanilla recipe, I would expect this recipe to still be added by GTCE

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.4 (dev build on 59cf924550f97635e1f576bf68309adcb8bface9)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed, accepted.

**Additional notes:**
I am taking this one for myself as I broke it.
