### ISSUE TITLE
Wrong error Message

### ISSUE THREAD

**Issue by galyfray** [GregTechCE/GregTech#1294]
https://github.com/GregTechCE/GregTech/blob/59cf924550f97635e1f576bf68309adcb8bface9/src/main/java/gregtech/api/recipes/RecipeMap.java#L191

You use `recipe.getChancedOutputs().size()` for the test and `recipeBuilder().getChancedOutputs().size()` for the error this conclude in weird message errors like here : 
```
[16:25:52] [Client thread/ERROR] [gregtech]: Invalid amount of recipe outputs. Actual: 0. Should be between 1 and 24 inclusive.
```
where I tried to add 48 outputs not 0 ...

**Comment by LAGIdiot** [comment]
Accepted based on source code check.
