### ISSUE TITLE
[Suggestion] Allow Smart Filter matching to ignore required fluid inputs

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1300]
**Is your feature request related to a problem? Please describe.**
When the smart filter attempts to match the recipe for tungstate dust, it fails because tungstate dust requires a fluid input, and the smart filter does not handle matching fluid inputs, just the item inputs.

**Describe the solution you'd like**
The ability for the smart filter to ignore the required fluid inputs in a recipe when attempting to match a dust recipe for transfer. Currently, this will only apply to tungstate dust, as it is the only dust that requires a fluid input as well as the dust, but it could be useful for addons that add dust + fluid recipes

**Comment by LAGIdiot** [comment]
Thanks for creating this suggestion. As stated it won't do much for us but it could be good addition for addons/modpacks. So it is accepted.

**Implementation notes:**
Add Button to Smart Filter GUI which will allow ignoring fluid part of recipe.
This info needs to be saved in NBT.
Matching logic for recipes will need adjustments to able to work with this.

**Comment by galyfray** [comment]
Is adding a `partialMatch` and `partialFindRecipe` methods to the `Recipe` class and use it a good way for implementing this ? Or overloading existing methods better way ?

**Comment by LAGIdiot** [comment]
I think that overloading for this is right way to go. Also using supplier for resolving recipes could be a thing but I will leave implementation details to person who takes this case. Are you interested?

**Comment by galyfray** [comment]
it doesn't looks too difficult for me I will work on it i think
