### ISSUE TITLE
[BUG] Ice drops and also places water when broken with saw

### ISSUE THREAD

**Issue by rhgngle** [GregTechCE/GregTech#1314]
**Describe the bug**
Title

**Versions**
Forge: 14.23.5.2854

GTCE: 1.10.5.582
CodeChickenLib: 3.2.3.358

**Setup**
New instance with only GTCE and CodeChickenLib, tested on new singleplayer world

**Steps To Reproduce**
1) Break ice with saw in survival mode

**Expected behavior**
The ice to drop and no water appearing when broken with a saw

**Comment by datcat31** [comment]
I will verify this bug then get back to you

**Comment by datcat31** [comment]
Bug is confirmed can some1 change the tag?

**Comment by LAGIdiot** [comment]
Bug was confirmed by @datcat31 and we are looking for solution.

**Comment by datcat31** [comment]
![image](https://user-images.githubusercontent.com/62666721/99561443-cce1d300-297b-11eb-8160-7f2ca91c2ab8.png)
this is the code for GTCE where the glitch occurs. @LAGIdiot can we add a line that says "if (block == ice) { remove tileEntity} or something

**Comment by LAGIdiot** [comment]
I was expecting something different when I asked for pointing to code. You know it is quite hard to orient yourself from one picture. I think that pointing to code should be done like this: 
Here is how Ice is harvested and dropped by our Saw https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/tools/ToolSaw.java#L59-L64

Anyway I see that here https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/tools/ToolSaw.java#L62 we replace block in world with Air, can you check why this does not work?

**Comment by datcat31** [comment]
i would think that vanilla minecraft replaces the air then with water after GTCE makes it air @LAGIdiot

**Comment by LAGIdiot** [comment]
Can you confirm it? And if so why it is doing? Some later call which does not know that it got replaced? Some state did not get changed? Entity is lying on that position?

Right now we need to know what is **exactly** happening (no guessing) so we can properly solve this. @datcat31  are you up for it?

**Comment by LAGIdiot** [comment]
No further analysis required as there is PR already for this.
