### ISSUE TITLE
Make normal dust sortable with ore dict filter with wildcard

### ISSUE THREAD

**Issue by madmacf** [GregTechCE/GregTech#1315]
I'm trying to sort my dusts in an ore processing chain.

I can sort tiny dust and small dust using wildcard symbols like dustSmall* and so on in the ore dict filter.
The problem is sorting normal dusts, is impossible since they have no "prefix".
Writing dust* moves every type of dust, also tiny, small, crushed and so on.

A solution could be to name normal dust something like dustNormalRuby instead of dustRuby.

**Comment by pyure** [comment]
Shouldn't need to actually "change" that oredict name (which would likely break some compatibility) so much as add another one, which is what I did for my own modpack.  So Tin Dust would belong to both dustTin and to dustNormalTin (I think this is a good idea for GT to implement)

As a temporary workaround you might find the below useful (if you're making your own pack or playing single player).  Note that the benefit of new oredicts such as "allTinyDust" is that not all in-game filters can use StartsWith prefixes, but need an entire oredict name.  Also: the naming convention is terrible, don't steal that.



```
// This generates some logistical oredicts.  In particular allRegularDust might be useful
for entry in oreDict {
  if entry.name.startsWith("dustTiny") {
   <ore:allTinyDust>.addAll(entry);
  } else if entry.name.startsWith("dustSmall") {
   <ore:allSmallDust>.addAll(entry);
  } else if entry.name.startsWith("dustPure") {
   <ore:allPureDust>.addAll(entry);
  } else if entry.name.startsWith("dustImpure") {
   <ore:allImpureDust>.addAll(entry);
  } else if entry.name.startsWith("dust") {   
   <ore:allRegularDust>.addAll(entry);
  } else if entry.name.startsWith("crushedPurified") {
   <ore:allPurifiedOre>.addAll(entry);
  } else if entry.name.startsWith("crushedCentrifuged") {
   <ore:allCentrifugedOre>.addAll(entry);
  } else if entry.name.startsWith("crushed") {
   <ore:allCrushedOre>.addAll(entry);
  }
}  
```

**Comment by madmacf** [comment]
I'm just a casual gamer playing the FTB Interactions pack :-)

Gems and crushed ore is the same thing. A regular prefix here would be nice too.

I guess I can sort by pulling everything else through oredict filter with higher priority with enderIO conduits and lowest with no filter could be normal dust.

**Comment by LAGIdiot** [comment]
Thank you for creating this suggestion. This did not ever occurred to me but you are correct it is not possible to get **(normal size) Dust** through **Ore Dictionary Filter** without pulling something else with it. All other dust sizes have it in it's oredict entry (example: dustTinyIron) but not this one.

As already mentioned we can't just change oredict for it as it would be breaking change but we could add another oredict entry for it which should solve this issue.

**Status:**
Accepted

**Implementation notes:**
Add additional oredict for **(normal size) Dust** something like `dustRegular<material>`
