### ISSUE TITLE
[BUG & SOLUTION] Rollback to the old surface rock texture for Shaders compatibility 

### ISSUE THREAD

**Issue by Akiraca** [GregTechCE/GregTech#1320]
**Describe the bug**
A previously investigated bug (#1091 #1216 #1236 ) indicates that GTCE machines go invisible when both surface rocks and Shaders of any type from Optfine are turned on. One walkaround suggested was to turn off the surface rocks worldgen. However, the absence of surface rocks could be detrimental to locating veins.

Therefore, I suggest a rollback to the older version of surface rock textures and shapes (which has been working fine with Shaders last year) for compatibility. Alternatively, add a config setting to restore the old textures at least.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.10.5.582

**Expected behavior**
GTCE machines don't go invisible with Shaders and surface rocks on.

**Screenshots**
![2020-11-22_21 26 54](https://user-images.githubusercontent.com/23720781/99951936-f747ec00-2dd2-11eb-9f38-9969ae64e229.png)

**Comment by LAGIdiot** [comment]
Thank you for this suggestion but it is not that easily applicable as whole Surface rock system was changed. This is not just about texture but whole rendering pipeline. Also it was changed as part of bigger set and there were already done changes to it so cherry picking of changes or reverting is out of sane options. But we are aware of this problem.

**Comment by Akiraca** [comment]
>  This is not just about texture but whole rendering pipeline. Also it was changed as part of bigger set and there were already done changes to it so cherry picking of changes or reverting is out of sane options.

Thank you for the clarification. Will it work to make GTCE ignore the rendering errors and do NOT disable all machine renderings but only the affected blocks (which are the surface rocks)? All machines going invisible would be frustrating, only the affected block going invisible is tolerable.

Otherwise, is it possible to just re-do the rendering of surface rocks and fix the problem directly?

**Comment by LAGIdiot** [comment]
Rendering pipeline is not something we can't touch lightly. There is not much documentation for it and as this is old version of MC we can't get help from Forge guys that may know something about it. Also given that Shaders are closed source there is not much we can get from them also they don't work in debug mode which does not help. So in the end it is us with broken rendering and little to none information how to fix it.

If I had to choose where to pour resources (if we had any spare) I would use it for whole rendering not just surface rocks as it is only small part of problem.
