### ISSUE TITLE
[BUG] Fluid Canner stopped operating

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1325]
**Describe the bug**
After updating to 1.10.6.591, it was noticed that the fluid canner has stopped filling and draining cells and buckets

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.6.591
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Place down a powered Fluid Canner and fill the fluid input with water
2) Place both cells and buckets in the item input and notice that neither are filled with water
3) Place down another powered Fluid Canner and place a water bucket in it and see that the water bucket is not emptied

**Expected behavior**
For the Fluid Canner to correctly perform filling/draining recipes.

**Comment by ALongStringOfNumbers** [comment]
This can be solved by adding the addition `MatchingMode` parameter in https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java#L30 to overwrite the new `findRecipe` method introduced in #1308

**Comment by Exaxxion** [comment]
Can confirm that the canning machine refuses to fill both steel cans and buckets.

![2020-11-24@142348](https://user-images.githubusercontent.com/11907282/100166220-07160d80-2e71-11eb-9a6f-c6df6400c5cb.png)
