### ISSUE TITLE
[Suggestion] Pulverize wool to string

### ISSUE THREAD

**Issue by w3ricardo** [GregTechCE/GregTech#1328]
I'm playing with GregTech and a few mods like JEI and journeymap. The only way to get string is hunting spiders in the night. It would be cool if I could turn wool into 2 or 3 strings.

I found an abandoned mine, but no cave spider spawn. And GregTech uses a lot of string in the beginning.

**Comment by ALongStringOfNumbers** [comment]
If you have LV power and have found oil, you can consider using Polycaprolactam as a source of string. But in addition, a recipe for pulverizing wool into string already exists in GTCE.

**Comment by LAGIdiot** [comment]
Thank you for this suggestion but there is already recipe you are looking for:
![2020-11-28_21 28 24](https://user-images.githubusercontent.com/3093101/100525454-4752f400-31c1-11eb-9463-a31160e8258c.png)

And it can be used even in steam age.
