### ISSUE TITLE
[Suggestion] Small wood pipe crafts 4 instead of 6

### ISSUE THREAD

**Issue by Akiraca** [GregTechCE/GregTech#1330]
**Is your feature request related to a problem? Please describe.**
All other handcraft recipes give 4 small pipes instead of 6 small pipes. Wood is an exception so it looks inconsistent with the rest.

**Describe the solution you'd like**
Every craft gives 4 small wood pipes instead of 6.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.7 (dev build on c522be46d8646596b1da859c69f688ca0f70f075)

**Enviroment:**
GTCE dev

**Outcome:**
I am not sure exactly where are coming from with this problem as I can't see it present in pure GTCE. Our recipes provides 4 Small Pipes for any material. Are you sure this is not functionality added by our addons (if you are using any) or by modpack (if you are using any).

**Comment by Akiraca** [comment]
Sorry, I looked over the recipe which is made by Gregcality. I'll closed the issue.
