### ISSUE TITLE
[BUG] Multismelter can void items due to coil bonus

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1332]
**Describe the bug**
The Multismelter can void items due to the coil bonus and having only a single output slot open.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594
_Modpack:_ None
_Addons:_ SoG 2.15

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Create a multismelter. I used IV input and output buses to get a large enough output slot. Additionally, I used fusion coils since they have a very large item smelting bonus to easily reproduce this issue.
2) Using Sand (or any other smeltable item), smelt it in the mutlismelter to fill the output bus with glass.
3) Add in two stacks of sand to the input bus of the multismelter.
4) Remove one stack of glass from the item output bus of the multismelter. 
5) See that the multismelter consumes both of the stack of sand in the input bus (due to the coil bonus) but only 1 stack gets put in the output bus, due to only having space for 1 stack.

**Expected behavior**
For the Multismelter not to function if there is not enough room in the output bus for all items smelted, including those added by the coil bonus

**Additional Information**
Attached GIF to demonstrate the issue

![2020-12-02_17-46-44](https://user-images.githubusercontent.com/31759736/100949281-1f1c0b80-34c7-11eb-86b7-4fe23b33a909.gif)

**Comment by PrototypeTrousers** [comment]
from `MetaTileEntityMultiFurnace`
in `findRecipe(long maxVoltage, IItemHandlerModifiable inputs, IMultipleTankHandler fluidInputs)`
we have
```
if (!outputStack.isEmpty()) {
outputStack.setCount(outputStack.getCount() * overclockAmount);
recipeOutputs.add(outputStack);
}
```
looks like we can set one slot to be bigger than a stack.
and since we only check for the total of output slots in `setupAndConsumeRecipeInputs`, the recipe is valid but we may not be able to fit everything else

**Comment by LAGIdiot** [comment]
Accepted based on provided evidence and RP.
