### ISSUE TITLE
[BUG] Lapotron Crystals craft to wrong maximum charge.

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1336]
**Describe the bug**
In #1189, the maximum charge of the Lapotron Crystals was increased to 10M EU. However, the crafting recipe still crafts to Lapotron crystals with 4M EU Maximum charge.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.596
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Look at the Lapotron crystal recipe in JEI and see that it has 10M EU max charge.
2) Look at the crafting recipe and see that it crafts to one with 4M EU max charge

**Expected behavior**
To craft to 10M EU maximum charge

**Comment by Exaxxion** [comment]
The three lapotron crystal recipes (`gregtech:lapotron_crystal_lapis`, `gregtech:lapotron_crystal_lazurite`, and `gregtech:lapotron_crystal_sodalite`) all produce an item with an NBT tag that appears as such from `/ct hand`:
`<gregtech:meta_item_2:32213>.withTag({MaxCharge: 4000000 as long})`.

The result is that the lapotron crystals have the same capacity as the HV energy crystals. This seems unintentional but if so, I'm not sure why the tag is being applied at all.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. This is definitely not intended and should be fixed. From quick look at code I can see https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java#L36 which does something with max capacity at craft time so probably starting there is best place.

**Comment by ALongStringOfNumbers** [comment]
After some analysis of the `fixOutputItemMaxCharge` method, I see that it takes the sum of all the electric items in the recipe, and uses that sum to set the maximum charge of the item in the recipe. This is why the recipe for the lapotron crystal was showing at 4m EU in the output of the recipe.

However, there are only a couple recipes in GTCE that have more than 1 Electric Item in their recipe, that being the Rebreather, whose recipes exist in code, but don't show up in game at all. All other recipes have 1 Electric Item in their recipe, such as the Jackhammer, Drill, Lapotron, or the Scanner.

Therefore, I propose the whole summing of the charge of the input items be removed, since it only applies to one recipe, which is not currently in the game, and just using a fixed number for the charge. This fixed number can come in several ways.

For a non-breaking change, the maximum charge of output item can be used, which could look something like this in the `fixItemOutputCharge` method:

```
        long totalMaxCharge = 0L;
        if(output.getCapability(GregtechCapabilities.CAPABILITY_ELECTRIC_ITEM, null) != null) {
            IElectricItem electricItem = output.getCapability(GregtechCapabilities.CAPABILITY_ELECTRIC_ITEM, null);
            totalMaxCharge = electricItem.getMaxCharge();

            if (totalMaxCharge > 0L && electricItem instanceof ElectricItem) {
                ((ElectricItem) electricItem).setMaxChargeOverride(totalMaxCharge);
            }
        }
```

Or, the `ShapedOreEnergyTransferRecipe` function could have another parameter added to it, simply being a Long value for the maximum charge of an item. This could allow similar behavior as before, where the sum of the capacity of the electric items in the recipe is used as the maximum charge, but in cases where this is not cared about, the maximum charge value of the output item could be passed in. This might allow for removal of the `fixOutputItemMaxCharge` function, as the maximum charge could simply be set from the passed in variable.

**Comment by LAGIdiot** [comment]
I think same function is used for creating Electric tools so I would rather not touch it. So better fix from my point of view is adding new function for this use case.
