### ISSUE TITLE
[Suggestion] Sifter mode for the Smart Filter

### ISSUE THREAD

**Issue by Ar4093** [GregTechCE/GregTech#1338]
**Is your feature request related to a problem? Please describe.**
In ore processing, especially in some modpacks, gem ores (Diamond, Emerald, Topaz, etc.) need to be treated differently than other ores when processing them. There is currently no good way to filter the purified ores that can go into the Sifting Machine vs those that can't, 

**Describe the solution you'd like**
A Sifter mode for the Smart Filter that filters Crushed Purified Ores based on whether they have a recipe in the Sifting Machine.

*Alternative solution:* Add new ore prefixes, e.g. oreGem\*, crushedPurifiedGem\*, ... to all gem ores to enable filtering via the Ore Dictionary Filter

**Comment by LAGIdiot** [comment]
Accepted as new Smart Item Filter option
