### ISSUE TITLE
[Question] Can I use GTCE to power Applied Energistics?

### ISSUE THREAD

**Issue by w3ricardo** [GregTechCE/GregTech#1339]
I have tried to connect cables and transformers to both the Energy Acceptor and the Energy Cell and it didn't work.

**Comment by Irgendwer01** [comment]
@w3ricardo No, u can only power it with RF use this mod to convert EU to RF https://www.curseforge.com/minecraft/mc-mods/ceu

**Comment by LAGIdiot** [comment]
No you can't with pure GTCE power other mods which does not support our energy. But as already mentioned you can use our addon CEU which converts GTCE EU to RF and then power it.
