### ISSUE TITLE
Missing recipe for a superconductor wire

### ISSUE THREAD

**Issue by Archengius** [GregTechCE/GregTech#134]

**Comment by temp1011** [comment]
Recipes here: https://github.com/Blood-Asp/GT5-Unofficial/blob/ce4d0b705d682e85412741ac4e087413b75637ef/src/main/java/gregtech/loaders/postload/GT_CraftingRecipeLoader.java#L407-L410. If no one else wants to add these I will.

**Comment by Archengius** [comment]
fixed
