### ISSUE TITLE
[BUG] Option Nerfwoodcrafting doesn't nerfes Forestry wood

### ISSUE THREAD

**Issue by Irgendwer01** [GregTechCE/GregTech#1341]
**Describe the bug**
Option Nerfwoodcrafting doesn't nerfes Forestry wood so it gives 4 instead of 2

**Versions**
Forge: 14.23.5.2854
GTCE: 1.10.7.594
_Addons:_ Gregicality 0.20.9-hotfix.8

**Setup**
Singleplayer world

**Steps To Reproduce**
1) Activate Nerfwoodcrafting in Gregtech Config
2) Look in JEI and search for any Forestry wood and see problem

**Expected behavior**
Forestry wood gives 2 instead of 4

**Comment by hjae78** [comment]
You should try without Gregicality and see if it persists before coming to GTCE

**Comment by Irgendwer01** [comment]
already tried still same

**Comment by LAGIdiot** [comment]
Thank you for creating this issue. I think this problem is similar to #1233 when Forestry registers it's trees way too late and our function for trees does not catch it.
