### ISSUE TITLE
[Suggestion] Coil tier indication in JEI

### ISSUE THREAD

**Issue by Ar4093** [GregTechCE/GregTech#1342]
**Is your feature request related to a problem? Please describe.**
For Blast Furnace recipes, it would be nice to quickly see what coil tier (at the minimum) is needed

**Describe the solution you'd like**
Similar to the power tier indicator, add the coil tier after the temperature, e.g. **Temperature: 2900K (Nichrome)**

**Comment by LAGIdiot** [comment]
Thank you for suggesting this. I think it is cool idea which would help other players.

Rendering of this is currently handled here: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java#L118-L121 . And it supports only showing of string values from recipe.

To support more than that it would require full reimplementation. But we could make it more versatile so it supports any similar concept as coils for temperature. There is probably not much more usage for GTCE alone right now but addons could make killing on this.
