### ISSUE TITLE
[BUG] NullPointerException when placing shutter and facades

### ISSUE THREAD

**Issue by PrototypeTrousers** [GregTechCE/GregTech#1343]
**Describe the bug**
NullPointerException when placing down shutter and facades.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594

**Setup**
Playing Solo
New world generated

**Steps To Reproduce**
1) place down 3x3 wall of wires or machines.
2) have a stack of shutters/facades in hands
3)hold right mouse button while circling the wall
4)notice log full of null point exceptions

**Expected behavior**
Clean log

method `rayTraceCoverableSide` in ICoverable.java may return null, which leads to `coverable.getCoverAtSide(coverSide)` to get a cover for a 'null' side, leading to the NPE.
`rayTraceCoverableSide` calls for `retraceBlock` which is part of chickenlib.

I sugest a `coverSide == null` check before calling `coverable.getCoverAtSide(coverSide)`

**Comment by LAGIdiot** [comment]
Thank you for reporting this bug.

I think we should handle this by updating implementation of `getCoverAtSide` to handle passed nulls in it as we can't prevent everyone from passing it in.

**Comment by eutropius225** [comment]
I don't think `getCoverAtSide` should have to handle nulls, the code that calls it should be responsible for ensuring that it's non-null.

Having investigated, it seems this specific null comes from [this](https://github.com/GregTechCE/GregTech/blob/22a594d9f945c2281a354e8de4aef84d94a895bd/src/main/java/gregtech/api/cover/ICoverable.java#L134) case here, as the player is no longer looking directly at the block.

**Comment by LAGIdiot** [comment]
I would rather be more defensive regarding this matter.
`@Nonnull` annotation is nice but it does not prevent null from being passed in. And in this case it even makes sense as "no side" can't have any cover on it.
