### ISSUE TITLE
[Suggestion][Texture] Make differing input/output overlays on buses/hatches

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCE/GregTech#1344]
**Is your feature request related to a problem? Please describe.**
When building, and, of course, working with multiblock structures, it's sometimes annoying pointing at buses and hatches, taking a look at The One Probe at the corner of the screen, to finally tell one from another. Not a big problem but it's undoubtedly doing a minus to the gaming experience.

**Describe the solution you'd like**
So, I'm hoping for a texture change to solve the annoying little issue. That is to say, make four overlay textures (input/output bus/hatches), each differs a liitle bit from others, to replace the grey square overlays existing now.

**Comment by LAGIdiot** [comment]
Thank you for creating this suggestion. I think it is good idea to make these blocks look distinct.

**Comment by ALongStringOfNumbers** [comment]
This is done as of #1607
