### ISSUE TITLE
Superconductor>Fusion Reactor>Neutronium>

### ISSUE THREAD

**Issue by C14X** [GregTechCE/GregTech#1346]
You need neutronium to craft superconductor wire, but you need superconductor wire to craft fusion reactor computers II and III, which you need to make neutronium.

GTCE: Version 1.6.6.374
This was done in the GregBlock modpack

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue but it is invalid from our point of view. You are reporting problem for block which does not belong to GTCE. Also you are on quite archaic version for which we don't support anymore, just so you know.
