### ISSUE TITLE
[BUG] Overlapping tooltips in machine GUI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1347]
**Describe the bug**
It is possible to get overlapping tooltips in a machine GUI. Note: this was only tested with the HV Electrolyzer, but it could happen in multiple machines.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594
_Modpack:_ Omnifactory, on development branch
_Addons:_ SoG: 2.15

**Setup**
Playing Solo
_New world generated_ No

**Steps To Reproduce**
1) Place down an HV eletrolyzer and put something in the item input slot
2) Mouse over the item input and then slowly move your mouse towards the fluid input slot.
3) Near the dividing line between the two slots, it can be seen that the tooltips overlap

**Expected behavior**
For the Tooltips to not overlap

**Screenshots**
![2020-12-12_22 34 55](https://user-images.githubusercontent.com/31759736/102004093-d6383400-3cca-11eb-917e-e90ac8ecffff.png)

**Comment by LAGIdiot** [comment]
Accepted based on provided screenshot. Tooltips should not overlap.
