### ISSUE TITLE
[Suggestion] The ability to set input allowed on the output side via the machine grid

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1350]
**Is your feature request related to a problem? Please describe.**
I would like the ability to set "Allow Input from Output Side", which is done using a screwdriver, using the machine grid. Currently, you have to use the screwdriver on the actual output side of the machine to enable this option, which gets cumbersome when placing a lot of machines. This is because you have to either temporarily move the output, hit the output with a screwdriver, and the move the output back, or walk to the other side of the machine.

**Describe the solution you'd like**
Right Clicking the screwdriver on the machine grid on the side that the output is on should toggle the "Allow Input from Output Side" option.

**Comment by LAGIdiot** [comment]
This sounds as reasonable and could be good quality of life improvement.

**Comment by ALongStringOfNumbers** [comment]
After some thinking on this, there would need to be some priority system in place for the case where there is a cover on the output side. Will the screwdriver access the cover, or will it set input allowed, this is something that will need to be thought about.

**Comment by DStrand1** [comment]
I think it would make sense to follow in vanilla fashion. In your situation, i would suggest the screwdriver accesses the cover on right-click, and sets allowed input on shift-right-click

**Comment by LAGIdiot** [comment]
Both ideas priority system and using Shift seems valid. It would be good to have usage synchronize through all our tools. Which means we would need to analyze them first. Opening this for discussion till we have resolution.

**Comment by DStrand1** [comment]
I'm not sure for other tools, but giving it more thought, I think I have a decent idea. If you have the screwdriver in hand, and are looking at a machine, you will NOT see the machine parts overlay, and simply right-clicking it anywhere will toggle allow input from output. Then, if you hold shift, the machine parts overlay turns on, and you can access your covers. When holding shift, you wouldn't be able to toggle allow input from output at all.

Sound reasonable?

**Comment by Archengius** [comment]
So you are basically suggesting to make process of setting up covers, which happens much more often than "toggle input on output" feature is used, more tedious? Doesn't sound like a decent idea to me.

**Comment by DStrand1** [comment]
Then maybe have machine grid come up always, and if right click on a part where a cover is, access that cover. If right click anywhere a cover is not placed, it toggles allow input from output. That way it really doesn't change current behavior, except it allows you to toggle input from output on any side, addressing the main issue.

**Comment by DStrand1** [comment]
Some of my thoughts for this are because GT5U allows you to click anywhere on a machine with a screwdriver to allow input from output side.

**Comment by ALongStringOfNumbers** [comment]
Since the Wrench also has a shift + rclick mechanic, which is to rotate the front face of the machine, in addition to its regular right click mechanic of rotating the output side, I feel like using Shift for setting Input Allowed from Output side would be fine. 

So the Screwdriver behavior would be: 
Right click: Access Cover on side
Shift Right Click on the output side: Set Input Allowed from output side

There could be some discussion of if right clicking/shift right clicking anywhere there is not a cover would set Input Allowed from Output side, but I think that could be relegated to a different issue
