### ISSUE TITLE
[Suggestion] Distribute expensive ticks more evenly

### ISSUE THREAD

**Issue by trishume** [GregTechCE/GregTech#1356]
**Is your feature request related to a problem? Please describe.**
I've heard people say but haven't profiled that using many covers (or many machines) can be laggy. I read the cover source code and noticed that it will tend to do expensive things on every 20th or 5th tick. If all the covers/machines in a chunk or large area load in after a reload on the same tick then load on the server will be concentrated and every 20th tick will be slower than other ticks.

This doesn't reduce total load but makes it a more smooth lower level of load rather than regular large lag spikes. I noticed at least LogisticsPipes has code to evenly distribute expensive ticks like I'm suggesting.

**Describe the solution you'd like**
Change https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/TickableTileEntityBase.java to start `timer` from a random number per block, or from a number based on the hash of the tile entity position or ID.

**Additional context**
This may be even a 3 line change. I'd have done it myself already except that I've never set up a mod dev environment before so I'd need to learn how to build and test mods first, and I'm not sure if I'll ever get around to that.

It's possible I missed some distribution in how entities are loaded that effectively does this already, in which case sorry about that.

**Comment by Archengius** [comment]
Many things rely on first machine tick having timer value of zero to set up internal state, and I'm pretty sure addons are following that trend too. I don't think it's something that we can change easily now. Sure, we could use some kind of workaround like doing first tick with zero timer value and then increasing it to random number, but that would be pretty dirty.

**Comment by Archengius** [comment]
Actually, I think we can just record initial timer offset and change GetTimer() to return timer value without offset applied, then deprecate it and add a new offset-aware method updated machines would be using. That way, we keep compatibility with addons and actually gain the benefits of timer value randomisation.

**Comment by LAGIdiot** [comment]
Suggestion provided by Archengius seems reasonable and would cover this without causing problems regarding setting initial state. And I am OK with implementing it in that way.
