### ISSUE TITLE
[BUG] Adding a material and adding both GENERATE_FLUID_BLOCK and GENERATE_PLASMA flags crashes the game

### ISSUE THREAD

**Issue by hjae78** [GregTechCE/GregTech#1358]
**Describe the bug**
When generating a material and giving it both the tags GENERATE_FLUID_BLOCK and GENERATE_PLASMA the game will not launch.

**Versions**
GTCE: Latest

**Setup**
Dev environment

**Steps To Reproduce**
1) Generate material and give it both GENERATE_FLUID_BLOCK and GENERATE_PLASMA flags.
2) Try to launch game.

**Expected behavior**
That the game should launch with a plasma for the material to be generated.

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. I think that crashlog or at least log should be provided for this type of error.

Anyway problem is related to way we register this fluids.
We call https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/MetaFluids.java#L166 twice first time for fluid version and second time for plasma version. And if flag GENERATE_FLUID_BLOCK is set we will generate two FluidsBlocks with same name https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/MetaFluids.java#L191 which is obviously not allowed. 

Now we should not crash game. Which means this should be fixed. But GTCE did not ever expected need for place able plasma liquid block.

So do you need place able plasma block?

**Comment by hjae78** [comment]
No, my intention was not to generate a placeable plasma block, i simply added plasma to a pre-existing material that had the fluid block flag.

**Comment by LAGIdiot** [comment]
I understand your intention and what happened.

Right now we don't have any use for placeable plasma blocks. So there is no need to generate placeable variant of it. If we need it later we can add it.
