### ISSUE TITLE
[BUG] The Furnace recipe map accepts a list of inputs, but only tests the first item in the list

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1360]
**Describe the bug**
In `RecipeMapFurnace`, its override of the `findRecipe` method accepts a list of ItemStacks as input, but only searches for a recipe for the first Itemstack in the list. This can cause issues some times, especially in the addon mod Shadows of Greg, in which the Processing Array, which requires machines in the input buses as well as the recipe inputs, can return a null recipe if a set of Electric Furnaces is the first item in the input bus and recipe inputs after. This is because the `findRecipe` method only checks the first entry in `inputs`, which is the Electric Furnace, which will return null for the recipe check.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.8.599
_Modpack:_ none
_Addons:_ SoG 2.15

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Join a wolrd with SoG and GTCE.
2) Build a Processing Array with 1 input bus and put electric furnaces into the first input slot in the input bus
3) Add ingredients from the GTCE furnace recipe map and see that nothing happens

**Expected behavior**
For the recipe to function, because a correct set of inputs were provided. This can be done by checking all members of inputs, and returning the first existing recipe, or null if none exist.

**Comment by LAGIdiot** [comment]
Accepted based on provided fix.
