### ISSUE TITLE
[BUG] CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by SegoItCh** [GregTechCE/GregTech#1363]
CCL has caught an exception whilst rendering a block

**Versions**
Forge: 1.12.2
GTCE: gregtech-1.12.2-1.10.8.599

**Setup**
Playing Solo
_New world generated_

**Steps To Reproduce**
Create world

[13:46:43] [Chunk Batcher 8/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:74, y:69, z:329
  Block Class:   class gregtech.common.blocks.surfacerock.BlockSurfaceRockNew
  Registry Name: gregtech:surface_rock_new
  Metadata:      0
  State:         gregtech:surface_rock_new
 Tile at position
  Tile Class:    class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
  Tile Id:       gregtech:surface_rock
  Tile NBT:      {x:74,y:69,UndergroundMaterials:["quartzite"],z:329,Material:"quartzite",id:"gregtech:surface_rock"}

**Comment by eutropius225** [comment]
Are you playing with Optifine?

**Comment by SegoItCh** [comment]
Yes it caused by internal shaders
