### ISSUE TITLE
[BUG] Surface Rocks can generate in (under) water

### ISSUE THREAD

**Issue by SegoItCh** [GregTechCE/GregTech#1365]
![unknown (1)](https://user-images.githubusercontent.com/45370592/102939067-3478ca00-44b6-11eb-914a-aa509104f7a8.png)
![unknown](https://user-images.githubusercontent.com/45370592/102939068-3478ca00-44b6-11eb-86db-4a8badbc36fe.png)

**Comment by Hero9909** [comment]
i can confirm this behaviour
GTCE  10.7.594 & 10.8.599
MC 1.12.2 
forge 14.23.5.2854
observed in 4 worlds
even in rivers , about 4 blocks down

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.8 (dev build on 22a594d9f945c2281a354e8de4aef84d94a895bd)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Implementation notes:**
We should not generate surface rock under liquids (if they don't support it).

**Additional notes:**
Check if SurfaceBlockPopulator can support blocks with "in liquid state".
