### ISSUE TITLE
[Suggestion] Multiblock's should have their own OrientedOverlayRenderer's

### ISSUE THREAD

**Issue by idcppl** [GregTechCE/GregTech#1370]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but streamline multiblock controllers to have their own OrientedOverlayRenderer's like single block machines have. Would help resource pack makers.

**Additional context**
If this is to be accepted, I'll make the PR for it.

**Comment by idcppl** [comment]
I'd still leave the old OrientedOverlay, since addon's use them and wouldn't wanna break those.

**Comment by LAGIdiot** [comment]
I am not sure if I am getting what you are trying to say here. Can you please provide example how exactly could this be used?

**Comment by idcppl** [comment]
Currently all Multiblock controllers share the same [OrientedOverlayRenderer](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java#L160). If you changed it to each having their own, it would allow for texture pack artist to change how each one looks. It's not like we need new textures, just put the same textures into different OrientedOverlayRenderer's.

**Comment by LAGIdiot** [comment]
I think I understand now. Sure we can go with it. For now we will use same textures for all but we can update them in feature.
