### ISSUE TITLE
[BUG] Crash with hybrid server

### ISSUE THREAD

**Issue by KorewaLidesu** [GregTechCE/GregTech#1375]
**Describe the bug**
GTCE failed to patch class.

**Versions**
Forge: 1.12.2-14.23.5.2847
GTCE: 1.12.2-1.10.1.557
ProjectE: 1.12.2-PE1.4.1

**Setup**
Playing Multiplayer

**Steps To Reproduce**
1) Install [Magma](https://github.com/magmafoundation/Magma) (Hybrid server) 
2) Install GTCE and ProjectE (other mods that also has same patch)
3) Start server and crash

**Additional context**
Server *can* run with 1 of 2mods on, but wont run if there is both of them

**Comment by LAGIdiot** [comment]
Thank you for posting this issue.

What is probably happening is that GTCE and ProjectE have provided patches for same file and patching system is not able to apply both together.

But GTCE does not have official support for servers different from Forge. It may work or may not but we don't invest resources for these compatibilities.

That being said if you are not able to reproduce this on pure Forge server and provide us with logs/crash report from it. We will not start investigating this.

**Comment by KorewaLidesu** [comment]
Oh, thank for the reply. Very appreciate.
~~Actually not only ProjectE, but other mods with provided same file also broke the server up.~~
