### ISSUE TITLE
Steam Alloy Smelter venting is not working

### ISSUE THREAD

**Issue by Kyks20** [GregTechCE/GregTech#138]
![image](https://user-images.githubusercontent.com/38229160/41563777-5582f986-7359-11e8-9c16-bc8b745af1c3.png)

my machine venting side is airblock so it should work and i have full tank of steam but still no output. 
![image](https://user-images.githubusercontent.com/38229160/41563842-8fe59e44-7359-11e8-9720-a347ff763aa0.png)

gregtech-1.12.2-0.2.0.2

**Comment by Archengius** [comment]
fixed
