### ISSUE TITLE
[Suggestion] Add a Locked Safe related config

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCE/GregTech#1380]
The Locked Safe in the abandoned bases should be fully customizable, both for their contents and things to unlock them. Maybe we can have a config to set the items, and their amount and rarities etc., and the key to open, for the Locked Safes.

**Comment by Archengius** [comment]
Locked safes use loot tables for loot generation, so you can already customize them. You cannot customize required items now though.

**Comment by LAGIdiot** [comment]
I don't feel like there is need to create fully customizable "loot generator" there are already mods for it. There is not much for us to get from this suggestion.

And as already Archengius mentioned you can change content of loot table that Safe is using.
