### ISSUE TITLE
[Suggestion] Allow changing the material registry limit

### ISSUE THREAD

**Issue by Charnuz** [GregTechCE/GregTech#1381]
**Is your feature request related to a problem? Please describe.**
Currently due to addons, the registry is full and I cannot add custom materials via CT. All IDs below 1000 are used, and 1000+ cannot be used.
https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/unification/material/type/Material.java#L32

**Describe the solution you'd like**
Ideally, there would be a setting in the config to set the max limit. I could see a method for changing it could have some use for addon developers too

**Comment by idcppl** [comment]
Metaitem would have to be changed as a whole for this to happen though. As Metadata can only go up to 32767. A work around would be to have 16 oredict entries per Metaitem and raise limit to 2k. But that would be world breaking. Could have overflow to another metaitem Id.

**Comment by idcppl** [comment]
Eh actually overflowing sounds like a bad idea. Could end up even more world breaking.

**Comment by Archengius** [comment]
are you sure it's full and you're just not trying to register something in addon claimed ranges?
but yeah, unfortunately changing registry size is not possible because of metaitem design.

**Comment by Charnuz** [comment]
ah, didnt know metadata was a short... hmm, is registering a material that generates no items possible? then i can just create the items with some other method
