### ISSUE TITLE
[Suggestion] Make Plunger a fluid container

### ISSUE THREAD

**Issue by Archengius** [GregTechCE/GregTech#1389]
**Is your feature request related to a problem? Please describe.**
Would be great if Plunger was usable as an always empty infinite sized fluid container. That way it would be more usable in GTCE machine UIs for example through clicking with it on exact tanks to clear them, which is a nicer solution than just blindly clicking with it on the machine block in world and hoping that it would void fluid from the right tank.

**Describe the solution you'd like**
Implement fluid handler item capability on it.

**Comment by LAGIdiot** [comment]
This seems reasonable and great addition for GTCE.
