### ISSUE TITLE
More inconsistency

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#139]
- [x] There are lots of Blocks added by GTCE which do not make sense, including things like Block of Netherrack (from 9 dust) or Block of Nether Quartz (from 9 Quartz) or Block of Ice.

- [x] Pulverizing Netherrack has only 1 Output: a 5% chance to get a Gold Nugget. There should be Netherrack Dust, Sulfur and Gold Nuggets.

- [x] Same thing for Endstone: Pulverizing it has a 5% chance to get a Tiny Pile of Tungsten Dust. No Endstone Dust.

- [x] Red Alloy Wires have no loss per Block, even when uninsulated. Should be changed to make insulation even worth doing.

- [x] Can you add a config to disable Flint tools?

- [x] Theres a recipe for a Wooden Soldering Iron

- [x] The Extruder allows players to turn Wrought Iron, Pig Iron and Magnetic Iron into Iron Ingots. Intended or not?

Just updated my version, now I got those issues:
- [x] Banded Iron Plates still exist (Normal and Dense)

**Comment by Exidex** [comment]
Instead of 'There are lots of ...' please state  what blocks. It willa make fixing things easier.

**Comment by Shattered2909** [comment]
Blocks that should definitely be removed:
Bone
Nether Quartz
Raw Rubber
Obsidian
Clay
Ice

**Comment by Archengius** [comment]
F I X E D
