### ISSUE TITLE
[Suggestion] /gt util hand should copy the meta id to clipboard

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1391]
**Is your feature request related to a problem? Please describe.**
After running the command `/gt util hand`, the metaitem name is output into the chat, after which you still have to type out this metaitem name into a script.

**Describe the solution you'd like**
It would be nice if the usage of the `/gt util hand` command could copy the item's metaname into your clipboard, similar to the `/ct hand` command from Crafttweaker. This would save having to type out the item's metaitem name into the script, and instead simply paste the name into the script

**Comment by LAGIdiot** [comment]
Thank you for this suggestion. It seems reasonable and given that it is easily doable (no Seppuku) then we can provide it.
