### ISSUE TITLE
[Suggestion] The ability to save items to the JEI favorites list from the multiblock preview

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1393]
**Is your feature request related to a problem? Please describe.**
When looking at the preview of multiblocks, you have to remember the component parts of the multiblock when exiting the screen. This can be somewhat solved when the list of component items introduced in #1211 is implemented, but before then there are not many good solutions

**Describe the solution you'd like**
I would like the ability to add items from the multiblock preview to the JEI favorites list, preferably with the JEI favorite button, `a`. This would be implemented best by sending the item that you are hovering your cursor over to the favorite list when pressing `a`.

**Additional context**
An additional improvement that could be done is pulling up the recipes for items when `r` is pressed while hovering over the item in the preview. And then going back to the preview screen after pressing the back button from the recipe.

**Comment by LAGIdiot** [comment]
Thank you for this suggestion. This one maybe harder then imagine as when we are rendering these previews blocks in them are not "JEI items" so there is no JEI functionality available. I think it is still worth it investigating but ultimately I would like to see #1211
