### ISSUE TITLE
Add ingame manual

### ISSUE THREAD

**Issue by Exidex** [GregTechCE/GregTech#14]

**Comment by john01dav** [comment]
Until this gets added, is there some other documentation for this mod? Browsing through JEI, it seems like a really nice mod, but I can't use it if there is no documentation.

**Comment by KrisBigK** [comment]
Some of the GT5 tutorials still apply

**Comment by Archengius** [comment]
don't think it will ever be a thing

**Comment by Exidex** [comment]
Here's lib worth looking into https://github.com/Vazkii/Patchouli

**Comment by Archengius** [comment]
lib is not a problem, problem is writing all that documentation

**Comment by Rongmario** [comment]
Could pull some information from FTB wiki, but shouldn't be priority.

**Comment by RenanVieira88** [comment]
make for achievements
