### ISSUE TITLE
[BUG] Duplicate extruder recipes for rods

### ISSUE THREAD

**Issue by hjae78** [GregTechCE/GregTech#1410]
**Describe the bug**
There are duplicate recipes for rods.
**Versions**
GTCE: Latest

**Setup**
Dev

**Steps To Reproduce**
1) Look at recipes for Iron Rod
2) See two, duplicate recipes

**Expected behavior**
See one recipe

https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/loaders/oreprocessing/MaterialRecipeHandler.java#L200

https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/loaders/oreprocessing/PartsRecipeHandler.java#L263

Duplicate code sources.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.9 (dev build on d84ad93df178f0b00bdc17a1f9417650e6e46deb)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed
