### ISSUE TITLE
[BUG] Multiple Fluid Extractor recipes for seeds.

### ISSUE THREAD

**Issue by thecodingchicken** [GregTechCE/GregTech#1412]
**Describe the bug**
7 Recipes exist in the fluid extractor to make seed oil.  
Currently, two recipes exist that make 10mb from <minecraft:wheat_seeds>, <minecraft:melon_seeds> give both 10mb and 3mb, and <minecraft:pumpkin_seeds> give both 10mb and 6mb.
The one other vanilla seed in the list, <minecraft:beetroot_seeds> give you 10mb.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.109.612
_Modpack:_ GTCE Testing Environment, the only other mods added are JEI(4.16.1.301) and CodeChicken Lib(3.2.3.358)
_Addons:_ None

**Setup**
Playing Solo
_New world generated_

**Steps To Reproduce**
1) Lookup the recipes for seed oil in jei, and multiple recipes that use said seeds can be seen.  

**Expected behavior**
4 recipes for seed oil should exist, given the 4 vanilla seeds being used.  

**Screenshots**
![Wheat seeds](https://user-images.githubusercontent.com/29822509/105119942-493d8300-5a9f-11eb-91d3-78451c9f52a2.png)
![Melon seeds](https://user-images.githubusercontent.com/29822509/105119966-55c1db80-5a9f-11eb-9b3c-5212bc8b5d90.png)
![Pumpkin Seeds](https://user-images.githubusercontent.com/29822509/105120017-70945000-5a9f-11eb-8648-6b1d91508d2b.png)

**Comment by LAGIdiot** [comment]
Accepted, based on provided description and PR.
