### ISSUE TITLE
[Question] Fusion Reactor?

### ISSUE THREAD

**Issue by armdn** [GregTechCE/GregTech#1423]
Hello.

Is there a plan to add Fusion Reactor?? As i see it is not available...

**Comment by DStrand1** [comment]
At the moment, no. These are included in addon mods like Shadows of Greg or Gregicality, and there is no intention currently to add them to GTCE.

**Comment by armdn** [comment]
Oh... Thank you!

**Comment by LAGIdiot** [comment]
@DStrand1 Thank you for answering this question. I will just add that we are working toward end game which should include Fusion reactor but there is way too much ground to cover.
