### ISSUE TITLE
[Suggestion] Rotor Holder is Dependent on Controller to Function

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1425]
**Is your feature request related to a problem? Please describe.**
Since the current implementation of the rotor holder is only for use in turbines, the code for it is heavily dependent on the turbine controller, rather than the controller simply interfacing with the rotor holder to get and set its speed values.

**Describe the solution you'd like**
Open up an interface for the rotor holder so that the speed up/speed down values aren't hardcoded and allow for it to be used in other multiblocks.

**Additional context**
This would allow us to do much more flexible things with the rotor holder, since right now, it is hard coded to increment by 1 and decrement by 3, and depends on the turbine controller. By opening this up, we could have secondary conditions that effect rotor speed, can allow rotor holders to be used in other multiblocks (including MBT), and maybe even use the rotor speed as a secondary condition to recipes like how EBF coils are (though this is a big step).

Relevant section of code: https://github.com/GregTechCE/GregTech/blob/4dd77f6d1f9d8a848a1836f3c7a2fb812880a748/src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java#L69-L87

This code is changed slightly with PR #1422, but the same problems described here are still present.

**Comment by LAGIdiot** [comment]
Thank you for your suggestion. This seems like good idea which could help GTCE in future and addons maybe even right now. We should be able to implement it.

**Comment by DStrand1** [comment]
I plan on addressing this issue, but since PR #1422 is modifying the same code, I either want to wait to implement this until that PR is merged, or include it as part of that PR. Either way works for me, if you would like I can include it in that PR, otherwise I will wait.

**Comment by LAGIdiot** [comment]
I would rather see this as separate PR so let's leave this for future release

**Comment by DStrand1** [comment]
Adding this here mostly so that I do not forget when it comes time to work on this issue.

Turbine Rotor's themselves seem to only take durability damage when the rotor speed is changing. When it is at maximum speed, no damage will ever be taken.

**Comment by ALongStringOfNumbers** [comment]
This should have been mostly address in #1527. Was there anything in this issue that was not addressed in that PR?

**Comment by DStrand1** [comment]
Closing since this was addressed in PR #1527 but this issue was not linked to it
