### ISSUE TITLE
[BUG] Spraycan won't change the coke oven front textures

### ISSUE THREAD

**Issue by DoctorWeirdGuy** [GregTechCE/GregTech#1430]
**Describe the bug**
I've just found out that you can change the color of most blocks in GTCE and wanted to try it out on several blocks. Meanwhile I've accidentally found that it doesn't work on the front face of the coke oven or primitive blast furnace.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.10.9.612

**Setup**
Playing Solo

**Steps To Reproduce**
1) Place a coke oven controller or EBF. 
2) Use any non-white spray can on it.

**Expected behavior**
I expect the front face to also change colors.

**Screenshots**
![2021-01-26_22 47 20](https://user-images.githubusercontent.com/69853450/105910022-9e8e0d00-6028-11eb-8cd9-ceb8218c71a3.png)

**Additional notes**
Could the spray cans also be made applicable to machine casings blocks, including the bricks for the coke oven and PBF as well as other parts used in multiblock structures?

**Comment by LAGIdiot** [comment]
Thank you for reporting this bug. You should be able to color them.
