### ISSUE TITLE
Wrong fuels & fuel values for diesel generator and gas turbine

### ISSUE THREAD

**Issue by Archengius** [GregTechCE/GregTech#144]

**Comment by Rongmario** [comment]
Diesel Generator's values have been fixed in https://github.com/GregTechCE/GregTech/pull/147

Gas coming up

**Comment by Rongmario** [comment]
Done: https://github.com/GregTechCE/GregTech/pull/150

**Comment by Archengius** [comment]
F I X E D by ANIME
