### ISSUE TITLE
[BUG] Magic energy absorber not ouputing energy from end crystals

### ISSUE THREAD

**Issue by loannnnn** [GregTechCE/GregTech#1440]
**Describe the bug**
The Magic Energy Absorber is not collecting energy from end crystals with or without dragon egg on top

**Versions**
Forge: 14.23.5.2854
GTCE: 
_Modpack:_None
_Addons:_ Shadows_of_Greg-1.12.2-2.15.0

**Setup**
Playing Solo
_New world generated_yes

**Steps To Reproduce**
1) Place down the Magic Energy Absorber and 1 end crystal next to it
2) The Magic Energy Absorber doesnt output any energy

**Expected behavior**
The Magic Energy Absorber should output energy into its internal storage

**Screenshots**
![sadasdasd](https://user-images.githubusercontent.com/78416563/106591746-35a31980-6581-11eb-9c64-f8d2cc155d81.png)

**Comment by warjort** [comment]
Did you place it in the end?

Looking at the code, it only works when the world gen is done by net.minecraft.world.WorldProviderEnd which is the end dimension.

**Comment by loannnnn** [comment]
Oh I didn't know it needs to be in the end. Sorry for the inconveniences. it should work now

**Comment by LAGIdiot** [comment]
As already answered this works only from inside of End
