### ISSUE TITLE
[Suggestion] Better JEI integration for metal frames

### ISSUE THREAD

**Issue by Ar4093** [GregTechCE/GregTech#1443]
**Is your feature request related to a problem? Please describe.**
When getting recipes from JEI, especially for AE/RS, for anything using a metal frame (e.g. casings or mainframes) it's a bit annoying to have to cycle through or find the "blank" metal frames for a recipe.

**Describe the solution you'd like**
Either of the following would help:

1. Display the uncoloured frame's recipe for every coloured frame in addition to the coloring recipe (this is for example done for chisel blocks), like it is for the "white" frames
2. Add a tooltip to the frames like "Can be coloured when surrounding a dye", then hide all colour variants and their recipes in JEI.

**Comment by DoctorWeirdGuy** [comment]
It's indeed quite annoying when JEI gets filled with hundreds of dying recipes like that. The same applies to the various fused glass and quartz blocks in EnderIO. Personally I removed all crafting table dying recipes for the frames (and EIO fused glass/quartz blocks) and only kept the recipes for the base frames. Then I hid all the colored variants in JEI. It not only clears up space in JEI but also reduces the amount of unnecessary crafting table recipes that you have to flip over to find the base recipe. 

A hidden 'dying recipe' would be a better solution. But I preferably would use the spray can to dye them in-world.

**Comment by LAGIdiot** [comment]
There is already #1264 which has approved and recommended way to solve this issue. But was not yet implemented

**Comment by DStrand1** [comment]
Closing as duplicate since approved change is stated in #1264
