### ISSUE TITLE
The rotor holder of multi-block machine only have HV, LuV and MAX Tiers

### ISSUE THREAD

**Issue by yanhaozhe** [GregTechCE/GregTech#1444]
In the game, I built up a large steam turbine, with HV tier rotor holder. However, on my server, it cost 9600mB of steam each tick to generate electricity. In fact, there is no such pipe that can hold so huge steam flow. Is it possible to craft LV and MV rotor holders? That I can use less steam to make it work.

GTCE version: 1.10.9.612
mc version: 1.12.2

**Comment by Archengius** [comment]
Rotor holder tier controls small efficiency bonus, and nothing more. LV or MV tiers won't change much.
