### ISSUE TITLE
[BUG] Ore Byproduct page fails in some circumstances

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1448]
**Describe the bug**
In some circumstances the ore byproduct page fails in that it does not display the output material in the output slots, but instead in the final slot in the second machine processing row.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.11.1.632
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Open JEI
2) Look at the byproducts page of Oilsands

**Expected behavior**
The final output to be in the output slots of the ore byproduct page

**Screenshots**
Oilsands
![2021-02-06_00 36 29](https://user-images.githubusercontent.com/31759736/107112279-a3667400-6813-11eb-9b9b-cc8736cef92c.png)

Bismuth
![2021-02-06_00 42 59](https://user-images.githubusercontent.com/31759736/107112363-49b27980-6814-11eb-9195-3b971a9d5e10.png)

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue.

**Comment by warjort** [comment]
The issue here seems to be that oilsands and bismuth match the rules for a byproduct page, i.e. they have a dust material and an ore. But none of their dusts or ores have any by products.

This seems to confuse it.

By not generating the byproduct recipe for this type of material, bismuth now correctly displays as a byproduct of Cassiterite.
And oilsands no longer has a byproduct page. It has no byproducts and it is not a byproduct of something else. So this seems correct.

Here is the patch:
````
diff --git a/src/main/java/gregtech/integration/jei/GTJeiPlugin.java b/src/main/java/gregtech/integration/jei/GTJeiPlugin.java
old mode 100644
new mode 100755
index 8a47b9dd..6b0cf4bc
--- a/src/main/java/gregtech/integration/jei/GTJeiPlugin.java
+++ b/src/main/java/gregtech/integration/jei/GTJeiPlugin.java
@@ -151,7 +151,9 @@ public class GTJeiPlugin implements IModPlugin {
         List<OreByProduct> oreByproductList = new CopyOnWriteArrayList<>();
         for (Material material : Material.MATERIAL_REGISTRY) {
             if (material instanceof DustMaterial && OreDictUnifier.get(OrePrefix.ore, material) != ItemStack.EMPTY) {
-                oreByproductList.add(new OreByProduct((DustMaterial) material));
+                OreByProduct byProducts = new OreByProduct((DustMaterial) material);
+                if (!byProducts.getOutputs().isEmpty())
+                    oreByproductList.add(byProducts);
             }
         }
         String oreByProductId = GTValues.MODID + ":" + "ore_by_product";
diff --git a/src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java b/src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java
old mode 100644
new mode 100755
index c8521684..8833dc39
--- a/src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java
+++ b/src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java
@@ -67,6 +67,10 @@ public class OreByProduct implements IRecipeWrapper {
 		outputs.addAll(byProductIngredients);
 	}
 
+     public List<ItemStack> getOutputs() {
+         return this.outputs;
+     }
+
 	@Override
 	public void getIngredients(IIngredients ingredients) {
 		ingredients.setInputLists(ItemStack.class, this.matchingInputs);
````
