### ISSUE TITLE
[BUG] FluidTankList can prevent other mods from draining in certain situations

### ISSUE THREAD

**Issue by hjae78** [GregTechCE/GregTech#1449]
**Describe the bug**
I'm trying to passively craft a chemical from Gregicality. The recipe I'm using outputs two fluids, the first fluid output I would like to buffer in the machine while the second fluid output is Hydrogen, which I would like to import back to my system. I am using an MV Chemical Reactor and Refined Storage as my digital item storage mod. I have an importer attached to my machine which is whitelisted to import Hydrogen. The issue is that since [drain](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/capability/impl/FluidTankList.java#L141) always returns the fluid in the first FluidTank in the FluidTankList which is then passed to Refined Storage's [code](https://github.com/refinedmods/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/network/node/NetworkNodeImporter.java#L114). Since this fluid doesn't match the filter it stops and doesn't import anything, jamming my machine. It looks like this could be a bug in AE2 as [well](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/fluids/parts/PartFluidImportBus.java#L111). I am wondering if a PR would be accepted where I find a way to randomize the order of [fluidTanks](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/capability/impl/FluidTankList.java#L146) to prevent this issue.

**Comment by hjae78** [comment]
![image](https://user-images.githubusercontent.com/54247183/107128823-1d086b80-68c1-11eb-8d5a-95eb68fcbbb7.png)
![image](https://user-images.githubusercontent.com/54247183/107128826-21348900-68c1-11eb-943a-5e44935f172c.png)
This is an image of the recipe I am trying to process for reference

**Comment by Archengius** [comment]
This is the problem on RS side. If you actually care which fluid you want to drain, use getTankProperties and FluidStack-sensitive drain method. Or you could *at least* try and import FluidStack that is whitelisted for example.

**Comment by Archengius** [comment]
Correct way of draining fluids can be seen here for example:
https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/util/GTFluidUtils.java#L19
