### ISSUE TITLE
[BUG] Crafting with empty tank in crafting station

### ISSUE THREAD

**Issue by kugo12** [GregTechCE/GregTech#1451]
**Describe the bug**
Can craft with empty GTCE tanks using GTCE crafting station

**Versions**
Forge: 14.23.5.2855
GTCE: 1.10.9.612
_Modpack:_ GSE 5.0.14QF2 https://www.curseforge.com/minecraft/modpacks/gregicality-skyblock-edition

**Steps To Reproduce**
1) Fill GTCE tank with any fluid required for recipe
2) Craft with this tank in GTCE crafting station

**Expected behavior**
Can't craft without fluid in tank.

**Video**

https://user-images.githubusercontent.com/15050771/107158916-40005180-698d-11eb-8e4e-38fb84eacf35.mp4

**Comment by LAGIdiot** [comment]
Thanks for reporting this issue.

Bug accepted based on provided video.

Crafting station should not allow crafting recipe which requires fluids with empty tank.
