### ISSUE TITLE
Scanner, Natural Gas

### ISSUE THREAD

**Issue by mgun82** [GregTechCE/GregTech#1454]
Good day, I have 2 questions:
1 - how to use the ore scanner? Does it work?
2 - in "jei" saw natural gas, how to get it?

**Comment by LAGIdiot** [comment]
Good day to you too.
1) Scanner works only for scanning surface rocks provided by GTCE and will let you know what ore to expect in given chunk.
2) Natural gas is block which is spawned by default GTCE ore gen. It can be found only in "sandy" biomes. It is fluid (gas) so you should be able to gather it with bucket or pump.
