### ISSUE TITLE
[Suggestion] Allow walking over surface rocks

### ISSUE THREAD

**Issue by warjort** [GregTechCE/GregTech#1455]
**Is your feature request related to a problem? Please describe.**
It is annoying you have jump to get over the indicator surface rocks.

**Describe the solution you'd like**
Change the bounding box to be half a block tall, like a slab.
````
diff --git a/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java b/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
old mode 100644
new mode 100755
index dcd9ec68..267c0089
--- a/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
+++ b/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
@@ -25,7 +25,7 @@ import java.util.Random;
 
 public abstract class BlockSurfaceRock extends Block {
 
-    private static final AxisAlignedBB STONE_AABB = new AxisAlignedBB(0.0, 0.0, 0.0, 1.0, 12.0 / 16.0, 1.0);
+    private static final AxisAlignedBB STONE_AABB = new AxisAlignedBB(0.0, 0.0, 0.0, 1.0, 8.0 / 16.0, 1.0);
 
     public BlockSurfaceRock() {
         super(net.minecraft.block.material.Material.ROCK);
````

**Additional context**
The current bounding box is .75 of a block which is greater than the .6 limit for having to jump.
If you look at the gregtech.common.render.StonePileModelGenerator, the actual size of the stone piles is between 4/16 and 7/16 of a block.
````
            int stoneHeight = 4 + random.nextInt(4);
````

**Comment by LAGIdiot** [comment]
This seems reasonable and should be changed.

Can you please create PR for it when you already have patch?
