### ISSUE TITLE
[Suggestion] XP for smelting

### ISSUE THREAD

**Issue by warjort** [GregTechCE/GregTech#1456]
**Is your feature request related to a problem? Please describe.**
All gregtech smelting recipes currently give you zero experience from the vanilla furnace.

**Describe the solution you'd like**
Defining this for every material is probably too much to ask?
But a configuration could be added to define a default amount.

Something like:
In gregtech.api.recipes.ModHandler
````
-recipes.addSmeltingRecipe(input, output, 0.0f);
+recipes.addSmeltingRecipe(input, output, ConfigHolder.smeltingXP);
````
then in gregtech.common.ConfigHolder
````
    @Config.Comment("Specifies the amount of xp for smelting GTCE items in the vanilla furnace. Default: 0.1")
    @Config.RequiresMcRestart
    public static float smeltingXP = 0.1F;
````
**Additional context**
0.1 is the lowest vanilla xp amount you get for smelting things like cobblestone or netherrack.

**Comment by Archengius** [comment]
if we're giving such recipes an experience reward, dust smelting recipes shouldn't give any, because otherwise you could just smelt it, macerate, and then smelt again to get experience from nothing.

**Comment by warjort** [comment]
You can do that with stone/cobblestone. :-)
It still takes fuel or pick axe durablity if you want to grind it out.
I guess that's why its only 0.1 xp?

**Comment by thecodingchicken** [comment]
Given that you normally only use a vanilla furnace for the relatively short amount before you transition to machines, I think that you should get experience from ores, but not from any processed form of ores(crushed, purified, centrifuged, impure, pure, or just the dust).

But if we want to implement it with some of those, we might as well avoid any way to get more experience by macerating and smelting again, in which case I would say to have experience given for impure dusts and the dust.  I'm looking at gold ore currently, so I would add an experience reward when you smelt it for $oreGold and $dustImpureGold.  I would avoid $dustGold, as that can be macerated as said above.

**Comment by warjort** [comment]
You guys are such kill joys. :-)

With any other tech mod, by the time you've smelted up the ores from the first couple mining runs you are ready to do your first level 30 enchant. 

With GTCE the only thing you get is a small amount of xp for smelting glass to make vacuum tubes for your first circuit. You don't even get xp for mining GT coal or redstone ores.

But you are worried about somebody that wants to use all their coal or chop down a tonne of trees to use a furnace as an xp farm? If somebody is going to do that kind of thing, disallowing this change won't stop them. There are more efficient ways to do it anyway.

**Comment by PrincessOfEvil** [comment]
Wouldn't it be easier to just make the ore recipes, silky ores and, if
you're willing to look through them, non-reversible recipes give exp?

**Comment by LAGIdiot** [comment]
I don't feel like this mesh good with current GTCE principles. We are not providing any machines which gives experience for work they do.

In first place it is strange to get experience for things you don't do but machine does automatically for you. And even if Vanilla MC does it we are not Vanilla MC.

So it is rejected.
