### ISSUE TITLE
In con sis ten cy

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#146]
- [x] There is a Compressor recipe to turn Chad into Paper. (Not intended cuz Chemical Bath)

- [x] Many (if not all) Bolt and Rod recipes in the Extruder have duplicates.

- [x] Both Rutile and Ilmenite Dusts can be electrolyzed into Titanium Dust which allows players to skip the Titanium Tetrachloride processing. Maybe those Electrolyzer recipes should require at least EV power?

- [x] Frames from these materials do not have recipes, some of those probably should not exist:
Red Alloy
Graphite
Graphene
Gadolinium
Gallium
Holmium
Indium
Lanthanum
Lithium
Lutetium
Manganese
Molybdenum
Polytetrafluoroethylene
Sodium
Strontium
Tantalum
Tellurium
Terbium
Thorium
Thulium
Uranium 238
Vanadium
Yttrium
Zinc
Nickel
Niobium
Rubidium
Samarium
Scandium
Silicon
Ytterbium
Barium
Beryllium
Bismuth
Caesium
Calcium
Carbon
Cadmium
Cerium
Cobalt
Dysprosium
Erbium

- [x] Rubber Pulp can be compressed into Plates, definitely not intended.

- [x] Same thing for Glowstone. Can conflict with the recipe to compress Glowstone Dust into Glowstone.

- [x] As far as I remember, compressing Wood Pulp into a Wood Plank should require 8 instead of 1.

- [x] The Titanium Firebox Casing has a different Texture on the top. Other Firebox Casings have the same texture on all sides.

- [x] Why is there a Ruby fluid, but none for other gems?

**Comment by Archengius** [comment]
F I X E D
