### ISSUE TITLE
[BUG] Chest closes by itself after 10 seconds in Single Player

### ISSUE THREAD

**Issue by CrafterKolyan** [GregTechCE/GregTech#1469]
**Describe the bug**
Open chest, wait 10 seconds, chest will close by itself.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.11.3

**Setup**
Playing Solo

**Steps To Reproduce**
1) Open GregTech Chest
2) Wait 10 seconds
3) Stand **NOT** in the **east-west** quarter
3) Find out that chest was closed

**Expected behavior**
Chest wouldn't be closed until a player closes UI.

**Comment by CrafterKolyan** [comment]
New information: This actually triggers when you are standing not in the **east-west** quarter of map

**Comment by LAGIdiot** [comment]
Accepted base on provided PR.
