### ISSUE TITLE
[BUG] Chest is not rendered correctly if integrated server saves world

### ISSUE THREAD

**Issue by CrafterKolyan** [GregTechCE/GregTech#1472]
**Describe the bug**

**Versions**
Forge: 14.23.5.2847
GTCE: 1.11.3

**Setup**
Playing Solo

**Steps To Reproduce**
1) Open Chest
2) Close Chest
3) Repeat these one for about 30 seconds
4) At some point the chest won't be closed or opened due to the local server saves. You will see this line on the local server:
```
[13:16:43] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
```

P.S. Even though the sounds are working correctly which means that `MetaTileEntityChest.lidAngle` is actually working fine.

**Expected behavior**
Chest rendered correctly (opening and closing)

**Comment by CrafterKolyan** [comment]
Maybe #1470 actually fixes it

**Comment by LAGIdiot** [comment]
I was not able to reproduce this on GTCE: 1.12.0 so I expect it to be fixed as areas which could affect this were modified
