### ISSUE TITLE
[BUG] Wrong sorting order in chest

### ISSUE THREAD

**Issue by CrafterKolyan** [GregTechCE/GregTech#1476]
**Describe the bug**
Items in chest are sorted by their amount in increasing order rather than descending.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.11.3

**Setup**
Playing Solo

**Steps To Reproduce**
1) Open chest
2) Put 1.5 stack of stone
3) Press sort button
4) See that in first slot only 32 pieces of stone and in the second 64

**Expected behavior**
Items should be sorted by their amount in descending order

**Screenshots**
![image](https://user-images.githubusercontent.com/9883873/107958333-e7dfd580-6fb2-11eb-8736-7c59020cea21.png)

**Comment by LAGIdiot** [comment]
Sorting in descending order is more sensible
