### ISSUE TITLE
Weird Oredic with Concrete | Chromite Smelting recipe

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#149]
I have both GTCE and Chisel installed, now there are 2 recipes in the Fluid Solidifier, one using 144 mb to make GT Light Concrete and the other one using 1296 mb to make Black Concrete from Chisel. Both use the Block Mold. You can turn it back into Fluid as well. The GT one does not have any Concrete OreDic.

Another issue I just found: I can smelt Chromite Ore into Chrome Ingots. Should not be a thing.

**Comment by EmosewaPixel** [comment]
There's nothing weird there. Both have the same ore dict entry and GT prioritizes other mods' ore dict entries. No other mod has light concrete, so its recipe is the same.

**Comment by Rongmario** [comment]
*Prioritises FIRST registered OreDict entry.

**Comment by Shattered2909** [comment]
Those are conflicting tho!

**Comment by EmosewaPixel** [comment]
That's compatability, the opposite of conflicting.

**Comment by Archengius** [comment]
fixed
