### ISSUE TITLE
[BUG] I can't hydro-crack sulfuric fuel/gas/naptha

### ISSUE THREAD

**Issue by yusuke1217** [GregTechCE/GregTech#1493]
**Describe the bug
 I can't hydro-crack sulfuricfuel/gas/naptha
**Versions**
Forge: 14.22.5.2854
GTCE: 1.11.3.649

**Setup**
Playing Solo

**Steps To Reproduce**
1) I tried to hydro-crack sulfuricfuel/gas/naptha
 in chemical reactor
2) And then there aren't recipe for these ,so I can't hydro-crack sulfuricfuel/gas/naptha

**Comment by Archengius** [comment]
You cannot crack *sulfuric* gas/naptha/fuel. You need to remove sulfur from them first using chemical reactor recipes with hydrogen.

**Comment by yusuke1217** [comment]
I can't remove sulfur from them because recipes for them don't exist. I'm sorry for not-enough explain
