### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yusuke1217** [GregTechCE/GregTech#1497]
**Describe the bug**
I can't remove sulfur from sulfuric naptha/heavy fuel/light fuel/gas with hydrogen

**Versions**
Forge: 14.23.5.2854
GTCE:1.12.2-1.11.3.640
_Addons:_ Shadow of greg:1.12.2-1.6.3.26

**Setup**
Playing Solo

**Steps To Reproduce**
1) I tried to remove sulfur from sulfuric naptha/heavyfuel/lightfuel/gas with hydrogen in chemical reactor.
2) And then I can't do this progress because recipes for them don't exist.

Remarks
I can do this in gregtech ce 1.12.2-1.10.9.612.
Other mods are same version.

**Comment by Exaxxion** [comment]
As a current maintainer of SoG, I would suggest you verify your reported version as it is either incorrect, or so old that it could not possibly be expected to work with GTCE 1.11.3.

**Comment by DStrand1** [comment]
I am not able to reproduce this in a solo-GTCE environment. I see recipes for all desulfurization processes, and all function normally.

![image](https://user-images.githubusercontent.com/10861407/108906317-5db4f400-75e6-11eb-9b30-8795283ec8ba.png)
