### ISSUE TITLE
Overclocking Button Enhancement

### ISSUE THREAD

**Issue by Andrakax** [GregTechCE/GregTech#1498]
**Is your feature request related to a problem? Please describe.**
You cannot choose what overclocking voltage a machine runs at, only current tier voltage and base speed with no overclocking. When dealing with machines like the centrifuge, a higher tier machine gives a higher chance at bonus/chance based resultant products, which further exacerbates the issue of not being able to pick the voltage tier a machine can run at.

**Describe the solution you'd like**
What would be nice is replacing the overclocking toggle switch with a button that cycles through available voltage tiers for that machine (much like EnderIO conduits and their channel colors), possibly including a popup text field that indicates what voltage tier it is set to and/or the voltage range.  This would minimize UI space used, while providing more functionality.

**Comment by LAGIdiot** [comment]
This sounds interesting. Currently when overclocking is allowed then recipe is overclocked by maximal voltage machine can use (there are exception like recipe time getting way too short). But with this idea we could just overclock "a bit".

Your idea for GUI seems solid, I was thinking about additional tab for it. But this may look good too. I think we can iterate on this idea.

**Comment by Andrakax** [comment]
I realized a possible issue: with this feature, its would be possible to change the voltage tier to be lower than required by a recipe.  For instance, if I put Naquadah Dust in an EV Centrifuge, but have it currently set for MV voltage tier, it won't run.  I'm not sure if it would try to run and waste power or not.  

I would image you'd want to set it to operate similarly to how putting Naquadah Dust in an MV Centrifuge simply does nothing.

**Comment by warjort** [comment]
Overclocking doesn't change what recipes can run.
It changes the energy and time for recipes of lower tiers.

Having an EV machine clamped at MV voltage for overclocking would not change its ability to run MV, HV or EV recipes at normal energy/speed. It would just mean it can run LV recipes at overclocked MV energy/speed.

**Comment by Andrakax** [comment]
Oh, that's a different way of looking at it than I had originally assumed, though probably better than my idea.  I had assumed that, when changing the overclocking level via this button, you were actually changing the voltage tier the machine would run at.  

I think I like your idea better, in that the button would limit how much the machine could overclock, while still being able to run all the higher tier recipes as needed.  Given the way the button _currently_ works, I'd guess this would be an easier change too.

**Comment by Andrakax** [comment]
Gonna throw this out there: currently we can't do any sort of overclocking management on multiblock machines.  Adding this feature to a multiblock machine controller would be nice too.

**Comment by warjort** [comment]
I would suggest creating a different issue for that.

That change is more complicated because there is no current UI for it and the multiblock UIs vary between machines.

**Comment by Andrakax** [comment]
While it not be quicker, another possibility would be to add a UI (I know, I'm cringing at the thought too) to the hatch instead.  This would be less impactful to the existing GUI, though I have no idea how it would impact a multiblock structure as is.

Currently the steam boilers have a psuedo-underclocking option in the UI.  Is it potentially simple to write something like that in for other multiblock systems?  

I don't have any experience in coding, so I'm just trying to throw out ideas to see if any might stick.

**Comment by galyfray** [comment]
That sounds liké a really good Idea but I have a small problem/question : should really this new overcloaking system allow downcloacking ? As far as i Knox thé current system didn't allow downcloacking ...
Downcloacking could be a fine addition but sometime there is some logical reason behind power consumtion of recipes like for electrolizer ...

**Comment by Andrakax** [comment]
> That sounds like a really good Idea but I have a small problem/question : should really this new overcloaking system allow downcloacking ? As far as i know the current system didn't allow downcloacking ...
> Downcloacking could be a fine addition but sometime there is some logical reason behind power consumtion of recipes like for electrolizer ...

Based on Warjot's idea for implementing this feature, the machines would not downclock, but instead limit how much a lower voltage recipe can overclock to.  An EV machine can still do EV recipes at the EV rate/speed/power consumption, however a LV recipe might be limited to only overclocking up to, say, MV speeds.
