### ISSUE TITLE
[BUG] Barium ingots cannot be formed

### ISSUE THREAD

**Issue by 2223773911** [GregTechCE/GregTech#1507]
**Describe the bug**
In electric blast furnace, barium oxide and aluminum powder cannot produce barium ingot and barium aluminate correctly, but aluminum powder can produce aluminum ingot
![QQ图片20210228163714](https://user-images.githubusercontent.com/79786469/109413552-f3b19b80-79a5-11eb-9fa7-3f0a5d1bb46e.png)

**Versions**
Forge: 
GTCE: 
_Modpack:_ if applicable add link to modpack (CurseForge preferred), version and any modification applied
_Addons:_ if applicable add all addon names and corresponding versions

**Setup**
Playing Solo/Multiplayer/Both
_New world generated_ if applicable

**Steps To Reproduce**
1) I did X
2) And then Y

**Expected behavior**

**Screenshots**

**Additional context**

_Please fill in as much useful information as possible. Also please remove all unused sections._

**Comment by DStrand1** [comment]
This is not a recipe added by GTCE, it is added by Gregicality. But, it was also fixed for them already.

**Comment by 2223773911** [comment]
thanks
