### ISSUE TITLE
[BUG] TOP - Fuelable Provider Error Message

### ISSUE THREAD

**Issue by Andrakax** [GregTechCE/GregTech#1508]
**Describe the bug**
Looking at a GTCE machine that uses a fuel (Steam Turbine, Diesel Generator, Large Boilers, etc), TOP shows an error message: "Error: gregtech:fuelable_provider"  This appears to be just a TOP display issue and does not appear to affect gameplay

**Versions**
Forge: 14.23.5.2854
GTCE: 1.12.0.662
Addons: The One Probe: 1.4.28

**Setup**
Multiplayer Server, custom lightweight modpack

**Steps To Reproduce**
I viewed Steam Turbine, Diesel Generator, Large Boiler, Gas Turbine and confirmed all are showing the same message.  Confirmed that the message shows up with or without fuel in the machine.  

**Screenshots**
![image](https://user-images.githubusercontent.com/79467032/109537878-68133a00-7a8d-11eb-916d-bbdafd7ec856.png)

**Comment by warjort** [comment]
The issue is that it is using the minecraft I18n  class to translate the fuel information.
But it is trying to do this on the server. That class doesn't exist on the server. 

But it shouldn't be trying to do the translation on the server anyway, it should be using the client's language.

**Comment by warjort** [comment]
You are correct, this is purely a "cosmetic" problem.

**Comment by Andrakax** [comment]
So, is this something I need to fix on my end, GTCE code, TOP code, or simply not really fixable?

**Comment by warjort** [comment]
I am fixing it so the translation is done on the client.
