### ISSUE TITLE
[BUG] sulfuric gas/heavy fuel/light fuel/naphtha can be used only in diesel generator or gas turbine.

### ISSUE THREAD

**Issue by yusuke1217** [GregTechCE/GregTech#1515]
**Describe the bug**
Sulfuric gas /heavy fuel/light fuel /naphtha can be used only in diesel generator or gas turbine.
I can`t remove sulfur from them with hydrogen.
**Versions**
Forge:1.12.2forge- 14.23.5.2854
GTCE: 1.12.2-1.12.0.662
_Addons:_ shadow of greg : 1.12.2-2.15.0

**Setup**
Playing solo

**Steps To Reproduce**
1) I tried to remove sulfur from sulufric gas/heavy fuel/light fuel/naphtha.
2) But. I was not able to do so. recipe of them don`t exist in NEI.

**Comment by warjort** [comment]
Please stop opening and closing the same issue. Leave it open until it is resolved.

Here are the example steps for creating Light Fuel.

In a basic distillary:
1 x Oil + integrated circuit with configuration 1 -> Sulfuric Light Fuel

In a basic chemical reactor:
2 x Hydrogen + 12 x sulfuric light fuel -> 1 x hydrogen sulfide + 12 x light fuel

Other recipes are similar, distill the oil and then use hydrogen in a chemical reactor to remove the sulfur.

All of these recipes exist in JEI. e.g.
![2021-03-04_22 02 36](https://user-images.githubusercontent.com/275258/110036746-64a1dc00-7d35-11eb-861c-c0e350d1bd1f.png)

If this recipe really isn't visible can you post your log/latest.log so we can see if there are any errors.

**Comment by warjort** [comment]
If this recipe really isn't visible can you post your log/latest.log so we can see if there are any errors.

**Comment by ALongStringOfNumbers** [comment]
See this issue: https://github.com/Shadows-of-Fire/Shadows-of-Greg/issues/105, it is not a GTCE issue. While waiting for the release of SoG with the fix, you can add back the recipes with crafttweaker.

**Comment by warjort** [comment]
You might want to add an example CT script to that SoG issue?

**Comment by yusuke1217** [comment]
I can't fill chemical reactor with sulfuric light fuel.

**Comment by DStrand1** [comment]
The Chemical Reactor will only accept fluids it has recipes for. SoG removes the recipe by mistake, and will be patched in the next version of the mod.

**Comment by yusuke1217** [comment]
Thank you for answering.
I'm sorry for the poor english.

**Comment by LAGIdiot** [comment]
As @ALongStringOfNumbers mentioned this issue is not our side. I tagged this issue with corresponding tag and will close it when SoG release fix for it.
