### ISSUE TITLE
latest version crashes at start 

### ISSUE THREAD

**Issue by Kyks20** [GregTechCE/GregTech#152]
https://pastebin.com/b3hpYPEe

here is pastebin whit crash report

**Comment by 3036Macloud** [comment]
I'm getting the same error on start up. Was there a fix? Why did you close issue.

**Comment by Kyks20** [comment]
It is fixed in the new patch

**Comment by Kyks20** [comment]
Crash was cos forestry is not in my pack and it needed it but they fixed it in next patch

**Comment by 3036Macloud** [comment]
Thanks
