### ISSUE TITLE
[BUG] Material's blastFurnaceTemperature not exposed to CraftTweaker

### ISSUE THREAD

**Issue by KaktuszSok** [GregTechCE/GregTech#1526]
**Describe the bug**
blastFurnaceTemperature should be exposed to crafttweaker but it is not.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.11.1.632
_Addons:_ CraftTweaker2 1.12-4.1.20.574

**Setup**
Both solo and multiplayer

**Steps To Reproduce**
1) Try do this in a CraftTweaker script:
if(MaterialCasting.toIngot(mat).blastFurnaceTemperature > 0) {}
2) Get an error as blastFurnaceTemperature is not exposed to CraftTweaker.

**Expected behavior**
returns the corresponding blastFurnaceTemperature field of the material.

Thanks!

**Comment by DStrand1** [comment]
There are other fields that should be exposed as well, as was discussed in the Discord. One example: SolidMaterial#toolAttackDamage

Im sure there are many more, so discussion on this would be great.
