### ISSUE TITLE
JFrog Bintray is ending

### ISSUE THREAD

**Issue by LAGIdiot** [GregTechCE/GregTech#1528]
JFrog Bintray platform where we are hosting our packages is ending as stated in https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

We should found new place to upload our packages so they are available to other.

I think we should use GitHub so we don't have dependency on other platform (which could go away).

**Comment by warjort** [comment]
There is always mavencentral
https://blog.sonatype.com/dear-bintray-and-jcenter-users-heres-what-you-need-to-know-about-the-central-repository

See also: https://blog.gradle.org/jcenter-shutdown

Need to change the build and check all the things still work.

````
buildscript {
    repositories {
-        jcenter()
        maven {
            name = "forge"
            setUrl("http://files.minecraftforge.net/maven")
        }
    }
````

BTW: This website lets you use curseforge as a kind of maven repository:
https://www.cursemaven.com/

**Comment by ALongStringOfNumbers** [comment]
Building with Github Actions and then having the releases stored on github is another option as well. It would allow for storage of builds at the same place as the code is housed.

Also, to comment on what warjot has said with needing to change 

```buildscript {
    repositories {
-        jcenter()
        maven {
            name = "forge"
            setUrl("http://files.minecraftforge.net/maven")
        }
    }
    ```
    
    Both SoG and Gregicality have changed the declarations of `jcenter()` to `mavenCentral()` and there were no issues fetching dependencies for anything that Forge or MC uses. It would still need checking for GTCE, but a simple change there may be possible.
