### ISSUE TITLE
IC2 integration

### ISSUE THREAD

**Issue by zayats1** [GregTechCE/GregTech#153]

**Comment by zayats1** [comment]
Gregtech5  and IC2 --

**Comment by Archengius** [comment]
which kind of integration do you want exactly?

**Comment by zayats1** [comment]
Crafts, maashines  ...

**Comment by Archengius** [comment]
no, there won't be any machine or craft-related integration with IC2.

**Comment by zayats1** [comment]
I  am Ukrainian?  and  dont  know Englis?  but  I want  help  you  in testing mod!

**Comment by Exidex** [comment]
discord channel is in README
