### ISSUE TITLE
[BUG] Remove/fix recipes that are not craftable

### ISSUE THREAD

**Issue by Andrakax** [GregTechCE/GregTech#1536]
There are several recipes in the mod that are not craftable, at least not without addons/CraftTweaker.

GTCE: 1.12.0.662

**Setup**
Playing Multiplayer

QBit CPU wafer using superconductor cables
![image](https://user-images.githubusercontent.com/79467032/111839741-a7d18280-88d1-11eb-966b-6d6ebe09c496.png)
Superconductor cables
![image](https://user-images.githubusercontent.com/79467032/111839766-b1f38100-88d1-11eb-9c65-5c0ac39a7a98.png)
Assemblers and laser engravers can't reach above 8192 EU/t to craft the following:
![image](https://user-images.githubusercontent.com/79467032/111839982-10206400-88d2-11eb-972e-746ca74b74cc.png)
![image](https://user-images.githubusercontent.com/79467032/111840004-19a9cc00-88d2-11eb-9ffe-e75ee55c6a0e.png)
![image](https://user-images.githubusercontent.com/79467032/111840022-20d0da00-88d2-11eb-95d4-20f75ecbeb90.png)
![image](https://user-images.githubusercontent.com/79467032/111840042-28907e80-88d2-11eb-808f-0410c6fdbd50.png)
![image](https://user-images.githubusercontent.com/79467032/111840060-2f1ef600-88d2-11eb-929f-be30528f05f6.png)
![image](https://user-images.githubusercontent.com/79467032/111840074-37773100-88d2-11eb-81ae-506e5cbc0a6a.png)
![image](https://user-images.githubusercontent.com/79467032/111840112-4827a700-88d2-11eb-84e2-ed45eca03f86.png)

**Comment by DStrand1** [comment]
I would be in favor of removing these recipes, and even maybe removing some of the items. Though we have to be careful, as modpacks and addons could very well be using these items and recipes, so perhaps it is best to leave them as-is.

**Comment by Andrakax** [comment]
Another option would be to add the LuV and ZPM variants of these machines in.  There's already several LuV and ZPM variants for hatches/buses/battery buffers that viable but not much else.  Is there any plans to expand this to support some of these recipes?

Regarding superconductor cables, is there no intention of making them craftable?  Seems odd to have them in the game outside of creative mode.

**Comment by warjort** [comment]
The higher tiers have not yet been fully implemented in GTCE.

There are however addon mods that do implement them:

https://www.curseforge.com/minecraft/mc-mods/gregicality
https://www.curseforge.com/minecraft/mc-mods/shadows-of-greg

**Comment by Exaxxion** [comment]
I can vouch that these items are used by modpacks, as we use every single one of those items in Omnifactory. We have Shadows of Greg in the pack which makes use of them directly for higher tiers of machinery, as well as some custom recipes we add.

GTAdditions is a now defunct mod that built on GTCE, Shadows of Greg is a fork of GTAdditions, and Gregicality is a fork of Shadows of Greg. Both of the latter mods are actively maintained and provide higher tiers of machines (at least through UV). My dev team maintains SoG and @DStrand1 is involved with Gregicality.

It would be highly disruptive to GTCE+Addon packs to remove those items.
