### ISSUE TITLE
Issues!

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#154]
- [x] Smelting Soldering Alloy Dust into Ingots requires a Blast Furnace. Not intended.

- [x] The EV Diesel Gen (Turbo Diesel Generator II) does not have a recipe. Same for the Turbines.

- [x] Is it intended that Nuclearcraft overwrites and replaces GT fluids in recipes now?

- [x] Items with missing textures: Cinnabar Gem and all non-normal Lignite Coal Gems

- [ ] The Electrolyzer has 5 recipes. BIG BUG!!

- [x] Is it intended that I can use the Implosion Compressor to make:
- Nether Star
- Eye of Ender
- Glass Crystal
- Coal
- Ender Pearl
- Lignite Coal
- Charcoal

**Comment by Archengius** [comment]
![image](https://user-images.githubusercontent.com/36846151/41800083-2cc0c2c4-769e-11e8-83ae-e9afa5977a73.png)

**Comment by Archengius** [comment]
fixed other things
