### ISSUE TITLE
[BUG] Phosphor has Wrong Chemical Formula or Name

### ISSUE THREAD

**Issue by coolian1223** [GregTechCE/GregTech#1566]
**Describe the bug**
The name phosphor is wrong for chemical formula Ca₃(PO₄)₂

**Versions**
https://www.curseforge.com/minecraft/modpacks/omnifactory
GTCE: gregtech-1.12.2-1.8.4.419

**Expected behavior**
It should be named tricalcium diphosphate as phosphor describes any type of luminescent material

**Comment by MrEyeballs29** [comment]
Actually it is technically called tricalcium phosphate in Wikipedia.

**Comment by DStrand1** [comment]
Thanks for reporting this issue. Thanks to some research by @Exaxxion, I believe this is simply a lang issue. Though I will have to look into it further when I am reviewing other chemistry things later.

Can you update the title to something more reflecting of the reported issue? It would help greatly to ensure this issue doesn't get lost.

**Comment by redcreeper14385** [comment]
Is this still looking for a fix? If you just want a lang file change I'm happy to contribute it.

**Comment by redcreeper14385** [comment]
I'll take that as a yes! :)

**Comment by Exaxxion** [comment]
PR #1659 which addressed this issue appears to have renamed the wrong items.

The ore and items related to Ca₃(PO₄)₂ were renamed to Phosphor Ore, and those pertaining to PO₄ were renamed to Tricalcium Phosphate. This is the reverse of what should have happened.

**Comment by redcreeper14385** [comment]
Guess I screwed that one up then :pensive:
