### ISSUE TITLE
Cannot furnace-process iron-based ores

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#157]
**Crash report**: N/A
**GT**: gregtech-1.12.2-0.4.5.9.jar
**Forge**: 2705

I don't see some of the traditional methods of processing iron-derivative ores.
- Cannot smelt them into one iron
- I cannot crush them into Dirty Dust and smelt that into Iron

This applies (so far) to:
- Brown Limonite
- Yellow Limonite
- Banded Iron

Note that I CAN get 8 iron nuggets by crushing them and smelting the crushed ore (suggesting it is only **ingot** recipes that are problematic)

**Comment by EmosewaPixel** [comment]
Strange, works fine for me
![image](https://user-images.githubusercontent.com/25333164/41820840-39b6f2c4-77d8-11e8-9b11-edfdaa578c0b.png)
![image](https://user-images.githubusercontent.com/25333164/41820842-45554e28-77d8-11e8-82e7-e80c3e8c84f0.png)
![image](https://user-images.githubusercontent.com/25333164/41820848-54b4e4c8-77d8-11e8-9559-637ecd31ba4a.png)

**Comment by pyure** [comment]
Thanks PIxel.  Same version?  

If so, its my side, and I'll start ripping out mods to find out what silly thing I've done.

**Comment by EmosewaPixel** [comment]
Yeah, the same version from CurseForge.

**Comment by pyure** [comment]
Hm.  This appears to not be a bug, or even a mod-conflict.  I think it **might** be a broken script causing other recipemaps to fail to process.  Maybe.

I'm closing this as irrelevant.  If I observe the recipemaps thing in better detail I'll create a new ticket for that.  Thanks for quick feedback @EmosewaPixel.
