### ISSUE TITLE
[Optimization] Multiblock Previews Do Unnecessary Work

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1571]
**Description**
When JEI multiblock previews are created for JEI, a lot of unnecessary things are happening. For example, `initializeAbilities()` will be called for each multiblock. Ultimately, if we could get these previews down to just rendering the blocks, and forcing the multiblock parts to have the proper casing texture applied, we would save some time on launch.

**Additional context**
This is an extremely small issue, and the efficiency gain would be equally small. I am posting this only because I had some strange GC overhead limit exceeded errors when doing certain things inside of a multiblock controller's `initializeAbilities` method, though I was able to work around it.

**Comment by eutro** [comment]
Is this really a bug?

Anyway, the way it is currently allows for checking whether a multiblock's preview lines up with the actual pattern, since the preview visibly won't form if it's invalid, which is quite useful.

**Comment by DStrand1** [comment]
Sorry, I used the bug report issue template to start this issue, I didn’t mean to call this a bug, just a potential source of optimization. 

I agree with you that it is useful to see if it properly forms. However, I do still think that in some cases, being able to pass some context to stop abilities from being set up, such as ItemHandlers and Fluid Handlers, could be a worthwhile optimization potentially.
