### ISSUE TITLE
A new BUG about Gregtech:item_collector.lv(基础物品收集器)

### ISSUE THREAD

**Issue by LSSwwwwwww** [GregTechCE/GregTech#1578]
Gregtech:item_collector.lv has a serious issue about shot time to copy a lot of items.
If four Gregtech:item_collector.lv build together and give them electricity and restone signal,then throw the items in the four Gregtech:item_collector.lv' centre.then it will copy item.
四个方块放在一起，供电，然后通上红石信号，把物品丢四个基础物品收集机器中间就能无限复制东西.

**Comment by Yefancy** [comment]
CODE: https://github.com/GregTechCE/GregTech/blob/d3e9f17afe622bb4d68d62305ca87176fd85660c/src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityItemCollector.java#L136-L161

should check `entityItem` is `isEntityAlive` before collecting
