### ISSUE TITLE
Crushed Ore + Hammer => Impure Does fails with enchanted hammer

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#158]
**Crash report**: N/A
**GT**: gregtech-1.12.2-0.4.5.9.jar
**Forge**: 2705

Can produce dusts with unenchanted hammers.  Cannot produce dusts with hammers that come with an enchantment.

To reproduce: Craft a iron hammer (innate: Sharpness).  Will not work with crushed ores.
Inverse: Craft a Cupronickel hammer (no innate).  Will work with crushed ores.

**Comment by pyure** [comment]
Possibly related: unenchanted mortars don't process gravel apparently (brought to my attn by testers)

**Comment by gerb82** [comment]
unenchanted mortars don't work, or enchanted mortars don't work?

**Comment by Archengius** [comment]
probably fixed, if not, re-open this

**Comment by TedKnudsen** [comment]
acknowledged
