### ISSUE TITLE
Stone type of Granite is registered as GraniteBlack

### ISSUE THREAD

**Issue by tomasbrod** [GregTechCE/GregTech#1589]
Causing inconsistency in harvest levels.

https://github.com/GregTechCE/GregTech/blob/0983830269bb63290391cf5d18a5e84f822a454f/src/main/java/gregtech/api/unification/ore/StoneTypes.java#L25

**Comment by ArchitektRadim** [comment]
Can confirm

**Comment by warjort** [comment]
I am guessing this is a typo introduced during this refactoring a long time ago and the material should be Materials.Granite

https://github.com/GregTechCE/GregTech/commit/695097ef48b75415fcdc59656e93fae8c0aea18c#diff-20e691d6c95655a0f08b746b8d42d0b37cbe74f0fd757844ae686de84a34f68f

The two materials are not equivalent:
````
    public static DustMaterial Granite = new DustMaterial(449, "granite", 0xCFA18C, ROUGH, 2, of(), NO_SMASHING);
    public static DustMaterial GraniteBlack = new DustMaterial(251, "granite_black", 0x0A0A0A, ROUGH, 3, of(new MaterialStack(SiliconDioxide, 4), new MaterialStack(Biotite, 1)), NO_SMASHING);
````

AFAICT, the only use of this configuration is in BlockOre where it uses it to determine the tool level for mining 
````
    @Override
    public int getHarvestLevel(IBlockState state) {
        StoneType stoneType = state.getValue(STONE_TYPE);
        if (material != null) {
            int toolQuality = material.harvestLevel;
            return Math.max(stoneType.stoneMaterial.harvestLevel, toolQuality > 1 ? toolQuality - 1 : toolQuality);
        }
        return 1;
    }
````

BlackGranite is 3, while normal Granite is 2 - which is the subject of this bug report.

This seems to be a popular area for complaints, cf  
id shift #1549, 
dust byproducts #1553, 
tool harvest level #1567

**Comment by tomasbrod** [comment]
Moreover, the vanilla stone has the same harestLevel as vanilla granite, which is 1, but Granite material is registered as harestLevel 2. Which, although inconsistent, is IMO fair.
https://github.com/GregTechCE/GregTech/blob/0983830269bb63290391cf5d18a5e84f822a454f/src/main/java/gregtech/api/unification/material/Materials.java#L348
