### ISSUE TITLE
Galena furnaces into Galena Dust

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#159]
**Crash report:** N/A
**GT**: gregtech-1.12.2-0.4.5.9.jar
**Forge**: 2705

Probably shouldn't have a furnace recipe at all.

**Comment by EmosewaPixel** [comment]
All dust ores smelt into dusts.

**Comment by pyure** [comment]
Any idea if that's intentional? (Should I close this issue?)

**Comment by EmosewaPixel** [comment]
Well, they have it so if there isn't an ingot or gem, you get a dust output, so yes, it's probably intended.

**Comment by Archengius** [comment]
fixed
