### ISSUE TITLE
[Suggestion] Type Filter

### ISSUE THREAD

**Issue by RealRedCraft86** [GregTechCE/GregTech#1597]
Is the Type Filter from GT5 coming to this mod?
If not, would you consider adding it?

**How it works**: Basically its a block that allows you to filter between items by their type (Dust, Tiny Dust, Ingot, etc...)
https://ftb.fandom.com/wiki/Type_Filter

**Comment by Archengius** [comment]
no, it is not coming, neither it is needed because Ore Dictionary Filter supersedes it

**Comment by RealRedCraft86** [comment]
Fair Enough
