### ISSUE TITLE
[BUG?] Surface rocks not generated on snow

### ISSUE THREAD

**Issue by tonby** [GregTechCE/GregTech#1599]
**Describe the bug**
Apparently, surface rocks are not generated on snow (tile form, not block form).
It makes the early game very difficult when a player spawns in a snow-covered biome.
Is it intended?

**Versions**
Forge: forge-14.23.5.2855
GTCE: gregtech-1.12.2-1.14.1.705
CodeChickenLib-1.12.2-3.2.3.358-universal
NaturesCompass-1.12.2-1.8.5 (for testing)

**Setup**
Playing Solo, New world generated

**Steps To Reproduce**
1) generate a world
2) find snow biome (I used Nature's Compass for testing)
3) few surface rocks are generated

**Expected behavior**
Snow tiles are replaced into the surface rocks, which indicate the vein under the place.

**Comment by warjort** [comment]
The code finds the lowest air block from the top of the world, then checks if the block beneath it is solid.
It won't place rocks on top of non-solid blocks, there is no logic to replace blocks other than air.

In the case of snow, it is not considered solid unless its state has at least 8 "layers", i.e. it occupies the full block.

In the past it did replace fluid blocks (e.g. water) if they were 1 deep, but that was considered a bug.
That fix #1420 suggested using Block.isReplaceable() as an additional check but it was left as a future task. 
Layered snow is replaceable, like grass or vines.
