### ISSUE TITLE
The Plate and Ring Shape have the same recipe

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#160]
As the title suggests, the Ring and Plate Shape have the same crafting recipe.
![image](https://user-images.githubusercontent.com/25333164/41894247-970c4b8a-791e-11e8-9c53-fd921f88f339.png)
![image](https://user-images.githubusercontent.com/25333164/41894266-a6b69608-791e-11e8-8204-6c0e340f06a2.png)
 Now, they don't look the same until you realize that they are mirrored recipes.
 I think the easiest way to fix this is by making them not be mirrored (because most people wouldn't know or care about that anyways) or use this recipe for the ring
![image](https://user-images.githubusercontent.com/25333164/41894336-e3f28234-791e-11e8-9798-7b78e28ee945.png)

**Comment by Archengius** [comment]
fixed
