### ISSUE TITLE
[Suggestion] Assembler Recipes for components

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1605]
## Main Idea

I am opening this issue as a request for feedback before I take a look at implementing this feature in GTCE, so any feedback on my proposed idea and possible recipes would be appreciated.

This idea came about due to the fact that both addon mods SoG and Gregicality currently implement Component (Robot arm, Motor, etc) recipes in the Assembler, although the recipes added by both SoG and Gregicality could use some revamping (As agreed upon both both dan and I). Currently, the only component that has an Assembler recipe in GTCE is the Field Generator.

While talking about the potential revisions that could be made to the recipes, I brought up the fact that it might be better to have these recipes in GTCE directly, so that they can stop being added through addon mods, unless they want to modify the recipes.

Some things that were brought up in the discussion were:

- The speed of the recipe has to compete with Molecular Assemblers, to be favored over just a plain crafting recipe.

Currently, aside from component recipes with tools, Molecular Assemblers (or the Refined Storage equivalent) can make these recipes pretty fast. Therefore, to be competitive, the assembler recipes should be somewhat fast as well. The currently agreed upon time is a flat 5 seconds per component. This is the main point that needs to be revised from both addon mods, as currently the recipes take a flat 30 seconds.

- Recipes should have on-tier power requirements to make their components.

To incentivize progressing to the assembler for each tier, the component recipes should have power requirements in the assembler matching the tier that they are. EG. MV component takes MV power. This would allow for GTCE to implement recipes for up to IV components, which matches well with both addon mods, because components of the LuV tier and higher are required to be made in the Assembly line in both addon mods.

- Assembler Recipes should be somewhat different from the Crafting Table recipe

For example, the Pump Recipe. Currently the recipe takes rubber rings (Both regular rubber and Styrene Butadiene rubber can be used, and SoG adds a recipe with Silicone Rubber). When transitioned to an Assembler recipe, these rings could be replaced with fluids of the respective type, Rubber, SBR, and Silicone Rubber. (However, the recipe with paper rings in LV would be left as crafting table only). In addition, it might be possible to drop the required cable or some other part in the assembler recipe (Here is where I am looking for some feedback)

Another example is the Motor recipe. Currently, the motor requires increasing sizes of copper (Annealed copper for EV and IV) wires. These copper wires could be transitioned to a fluid component in the assembler recipe.

Another example is that the Emitter recipes could have their rods transferred to fluids of the same material.

### Summary

I am opening this issue to gather feedback on implementing Component recipes in the assembler, and possible recipes for them. These recipes should be somewhat different from the regular crafting table recipes, I and have stated some possible recipes for a few components in the section above.

Edit:
As an addition to adding recipe for components, I feel like the assembler recipes for Field Generators should be updated and brought in line with the added recipes, namely so they do not take 90 seconds (These component recipes are added by GTCE).

**Comment by DStrand1** [comment]
I think that these recipes should be added like this:
- 5s, with on-tier voltage (30, 120, 480, 1920, 7680)
- Recipes should all be the same inputs, except for 2 cases:
    - Pump, rings of rubber should be replaced with fluid
    - Conveyor, sheets of rubber should be replaced with fluid
In my opinion, I think that having something like fluid Copper for motors would make the recipe worse to complete

**Comment by galyfray** [comment]
I don't think changing the copper cable requirement to liquid is logical but maybe changing for only using thinnest copper wire (the x1 not the fine ones).
I also think some cost reduction would be neat as in some recipes added in addons, this would make this way more attractive.
