### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Emperorsking** [GregTechCE/GregTech#1606]
Is there any way to make the metal produced by the machine in GT, such as the metal ingots from smelting ore powder in the industrial blast furnace, be replaced by the metal ingots in TFC without producing the metal ingots in GT?

**Comment by warjort** [comment]
Just change the recipes using CraftTweaker.

Here's some examples from OmniFactory:
https://github.com/OmnifactoryDevs/Omnifactory/blob/dev/overrides/scripts/BlastFurnace.zs

**Comment by Emperorsking** [comment]
Do all recipes need to be changed? If all the metals produced by GTCE are converted to TFC metals, it will be a very large workload. Maybe I should delete the Oredictionary of GTCE, so that it can recognize the Oredictionary of TFC and replace it. Is that the right thing to do?Please~

**Comment by warjort** [comment]
I don't think I understand your question? The ore dictionary is used for recipe ingredients not the outputs.

Maybe the ore dictionary **unification** processing in config/gregtech.cfg is what you are talking about?
````
    # Specifies priorities of mods in ore dictionary item registration. First ModID has highest priority, last - lowest. Unspecified ModIDs follow standard sorting, but always have lower priority than last specified ModID.
    # For this to work "useCustomModPriorities" has to be set to true.
    S:modPriorities <
     >

    # Whether to use modPriorities setting in config for prioritizing ore dictionary item registrations. By default, GTCE will sort ore dictionary registrations alphabetically comparing their owner ModIDs. Default: false
    B:useCustomModPriorities=false
````

Try setting that flag to true and adding TFC to the mod priorities to see if it gives you want?
It will only work where GTCE and TFC have matching ore dictionary names.

**Comment by Emperorsking** [comment]
The thing is, in general, GTCE and TFC have some similar parts and Ores and mental can generally be used together. However, in most cases, the ingot from the ore processed by GTCE's machine is the ingot within the GTCE mod, and when I integrate TFC and GTCE, TFC has the metal to match it. For example, TFC copper ingot can be shared with GTCE copper ingot, which can be used as the same input material for many operations.The effect I want to achieve is: the ingot produced by any GTCE machine is changed to TFC ingot, not GTCE ingot.
Intuitively,
Original formula flow chart:
GTCE Ore (Powder) -- (Input) -- >GTCE Machine -- (Output) -- >GTCE Metal Ingots
Expected recipe flow chart:
GTCE Ore (Powder) -- (Input) -- >GTCE Machine -- (Output) -- >TFC Metal Ingots
Besides, I remember that there is a set of mod priorities in the Config of GTCE as you mention （useCustomModPriorities）,what is it for? Can you give me an example to help me understand and use it better?Please~~~

**Comment by Emperorsking** [comment]
The thing is, in general, GTCE and TFC have some similar parts and Ores and mental can generally be used together. However, in most cases, the ingot from the ore processed by GTCE's machine is the ingot within the GTCE mod, and when I integrate TFC and GTCE, TFC has the metal to match it. For example, TFC copper ingot can be shared with GTCE copper ingot, which can be used as the same input material for many operations.The effect I want to achieve is: the ingot produced by any GTCE machine is changed to TFC ingot, not GTCE ingot.
Intuitively,
Original  recipe flow chart:
GTCE Ore (Powder) -- (Input) -- >GTCE Machine -- (Output) -- >GTCE Metal Ingots
Expected recipe flow chart:
GTCE Ore (Powder) -- (Input) -- >GTCE Machine -- (Output) -- >TFC Metal Ingots
Besides, I remember that there is a set of mod priorities in the Config of GTCE as you mention （useCustomModPriorities）,what is it for? Can you give me an example to help me understand and use it better?Please~~~

**Comment by warjort** [comment]
> Can you give me an example to help me understand and use it better?

The idea of the ore dictionary unifier is that GTCE prefers another mod's items in recipe outputs.
This is based on them having the same ore dictionary name.

So assuming you add TFC's mod id to the mod priorities; 

If both GTCE and TFC have items with ore:ingotCopper it will prefer TFC's item.
When TFC doesn't have an item with an ore dictionary entry, it will use the GTCE item.

NOTE: GTCE's items are still in the game and will be accepted as ingredients to recipes that specify ore dictionary names.

Like I said above "suck it and see". Only you can tell whether it does what you want.

**Comment by Emperorsking** [comment]
OK, I see what you mean, so how do I get the TFC mod ID?

**Comment by Emperorsking** [comment]
OK, I see what you mean, so how do I get the TFC mod ID?Thank you.

**Comment by warjort** [comment]
It should be on the tooltip of the mods items, something like
tfc:copperIngot
so the mod id is "tfc"

From their source code I can see "tfc" is  actually the correct value:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/0029a016f486f342704a24b6890e2b890f9311e3/src/main/java/net/dries007/tfc/TerraFirmaCraft.java#L59

**Comment by Emperorsking** [comment]
Thank you very much.Could you please tell me whether "TFC" refers to the ID of the whole mod? I just input "TFC" into the add bar. Or does this mod have the ID of each item and need me to input all of it?

**Comment by warjort** [comment]
It is just a namespace prefix. A mod can use whatever it likes for its items, but traditionally they use their mod id.
If tfc is being used for all its items (the normal case) then you only need that one entry in the configuration.
If tfc has another prefix, e.g. there is some tfc addon mod with different items you want to use then you will need to enter that prefix as well.
Just look at the item ids on the tooltips.

Additionally, the namespace is always lower case. It must be "tfc" not "TFC".

Finally, I am not sure what you mean by "add bar".
If you are trying to change this configuration in game using the mod config panel, that won't work as you expect.
The game needs to be restarted for these changes to take effect.

**Comment by Emperorsking** [comment]
![A2CD4452-FE6B-4543-954C-3FA78821CB1E](https://user-images.githubusercontent.com/84236816/118669840-aae0e480-b828-11eb-8e93-efc716691da2.png)
First of all, thank you very much for your patience to answer my question~~~
This image shows the configuration item as you mentioned. When you click on it, there will be a configuration box that allows you to enter. This is what I call "Add Bar". The original TFC itself didn't have as many metal types as the original GTCE, but the additional TFCM mod (TFC:Metallum) added enough metal types for the original TFC. Can I understand that the Mod ID can represent the entire Mod, as long as I add the Mod ID of TFC and TFCM to the configuration (no need to specify the item ID and enter it one by one? For example, if I need TFC's copper ingots to be produced in GTCE's machines, I have to accurately prioritize the "copper ingots" item? But based on my understanding of what you've said, that doesn't seem to be necessary.）

**Comment by Emperorsking** [comment]
![Uploading F8BB4068-AE03-4648-8423-D0A61570E821.jpeg…]()
First of all, thank you very much for your patience to answer my question~~~
This image shows the configuration item as you mentioned. When you click on it, there will be a configuration box that allows you to enter. This is what I call "Add Bar". The original TFC itself didn't have as many metal types as the original GTCE, but the additional TFCM mod (TFC:Metallum) added enough metal types for the original TFC. Can I understand that the Mod ID can represent the entire Mod, as long as I add the Mod ID of TFC and TFCM to the configuration (no need to specify the item ID and enter it one by one? For example, if I need TFC's copper ingots to be produced in GTCE's machines, I have to accurately prioritize the "copper ingots" item? But based on my understanding of what you've said, that doesn't seem to be necessary.）

**Comment by Emperorsking** [comment]
![FA223714-9DAE-4F4A-9D69-8D2539D89756](https://user-images.githubusercontent.com/84236816/118674211-33ad4f80-b82c-11eb-8fdb-cdd775326df5.jpeg)
First of all, thank you very much for your patience to answer my question~~~
This image shows the configuration item as you mentioned. When you click on it, there will be a configuration box that allows you to enter. This is what I call "Add Bar". The original TFC itself didn't have as many metal types as the original GTCE, but the additional TFCM mod (TFC:Metallum) added enough metal types for the original TFC. Can I understand that the Mod ID can represent the entire Mod, as long as I add the Mod ID of TFC and TFCM to the configuration (no need to specify the item ID and enter it one by one? For example, if I need TFC's copper ingots to be produced in GTCE's machines, I have to accurately prioritize the "copper ingots" item? But based on my understanding of what you've said, that doesn't seem to be necessary.）

**Comment by Emperorsking** [comment]
![22B19175-1EB7-446D-BACB-9395766DBBF2](https://user-images.githubusercontent.com/84236816/118674539-6e16ec80-b82c-11eb-9999-c852415c0ce7.jpeg)
First of all, thank you very much for your patience to answer my question~~~
This image shows the configuration item as you mentioned. When you click on it, there will be a configuration box that allows you to enter. This is what I call "Add Bar". The original TFC itself didn't have as many metal types as the original GTCE, but the additional TFCM mod (TFC:Metallum) added enough metal types for the original TFC. Can I understand that the Mod ID can represent the entire Mod, as long as I add the Mod ID of TFC and TFCM to the configuration (no need to specify the item ID and enter it one by one? For example, if I need TFC's copper ingots to be produced in GTCE's machines, I have to accurately prioritize the "copper ingots" item? But based on my understanding of what you've said, that doesn't seem to be necessary.）Is this understanding right?

**Comment by warjort** [comment]
You don't specify individual items, just the namespaces (in practice the mod ids).

In your case it is "tfc" and "tfcmetallum".

I found the other mod id here:
https://github.com/TFC-Metallum/TFC-Metallum/blob/master/src/main/java/tfcmetallum/TFCMetallum.java

The way it actually works in detail is you have an ore dictionary name like "ore:ingotCopper".
Gregtech then sees it has 2 items in that dictionary
"tfcmetallum:copper_ingot" and "gregtech:copper_ingot"

Normally it would use the "gregtech" version, but your config change tells it to use the one starting with "tfcmetallum" as a priority.

I still believe you will get a better understanding by experimenting with it rather than asking questions about the theory.

**Comment by Emperorsking** [comment]
I am honored to get your professional answer, I will try, if I still don't understand, I will come up again for help, if successful, I will still come back to prove that your conclusion is correct.Thank you very much for your patient explanation!

**Comment by Emperorsking** [comment]
You were right! Your guess is exactly right. I got the effect I wanted. Thank you so much indeed!
