### ISSUE TITLE
Integrated Circuit Configuration is ignored

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#161]
It seems that machines that use Integrated Circuits completely ignore them and just do the first available recipe. For example here I have Oil and a Circuit with configuration 1, it's supposed to be making Sulfuric Naphta, but instead it's making Sulfuric Heavy Fuel which is the first recipe in JEI.
![image](https://user-images.githubusercontent.com/25333164/41897465-b6f942dc-7927-11e8-8a20-1e3dcb8b5729.png)
![image](https://user-images.githubusercontent.com/25333164/41897469-bcf5ff9a-7927-11e8-943e-2460a0e3c1a1.png)
![image](https://user-images.githubusercontent.com/25333164/41897470-bf902596-7927-11e8-943b-1595bb230e13.png)
![image](https://user-images.githubusercontent.com/25333164/41897476-c258d6ec-7927-11e8-88a1-aed020d26304.png)
![image](https://user-images.githubusercontent.com/25333164/41897508-cf2e9834-7927-11e8-8c82-d2a1643cc279.png)
![image](https://user-images.githubusercontent.com/25333164/41897512-d41cd2b6-7927-11e8-8350-a5e499af02c1.png)
![image](https://user-images.githubusercontent.com/25333164/41897583-043533bc-7928-11e8-93c1-c53a68651159.png)
![image](https://user-images.githubusercontent.com/25333164/41897591-06659294-7928-11e8-9c6b-2f780f92ebd2.png)

**Comment by Archengius** [comment]
fixed
