### ISSUE TITLE
[BUG] ZenProperties that are final are not settable

### ISSUE THREAD

**Issue by Charnuz** [GregTechCE/GregTech#1615]
**Describe the bug**
This has been discussed in the [discord before](https://discordapp.com/channels/432092648724103190/432560981898559498/694227934436655185) with the assumption that CT would set final values despite them being final, but instead it does not create the setter for the field. A lot of these final fields are ones that changing the value could be important to someone, like material color.

For example this will cause [an error](https://pastebin.com/iPXeGJnW):
```zs
#loader gregtech

import mods.gregtech.material.Material;
import mods.gregtech.material.MaterialCasting;
import mods.gregtech.material.MaterialRegistry;

<material:salt_water>.color = 215205;
```
**Versions**
Forge: 14.23.5.2855
GTCE: 1.15.0.721

**Comment by warjort** [comment]
I don't know about the discord discussion but see #1567 and #1568

It's certainly not a bug, it takes a deliberate choice to make a field final.

**Comment by Charnuz** [comment]
Wasn't sure if this was known since I only could find this one discussion about this kind of issue, I'll just close this and request some to be un-finaled.
