### ISSUE TITLE
[Suggestion] Add dustRegular oredict to Redstone

### ISSUE THREAD

**Issue by royalmustard** [GregTechCE/GregTech#1616]
**Is your feature request related to a problem? Please describe.**
Redstone not having the dustRegular oredict makes it hard to fully automate ore processing, as redstone now cannot be easily removed with oredict filters.

**Describe the solution you'd like**
Add a dustRegular oredict to redstone, like all other dusts have

**Comment by DStrand1** [comment]
Thank you for opening this issue here. Here is the original issue on Omnifactory repository: https://github.com/OmnifactoryDevs/Omnifactory/issues/747
