### ISSUE TITLE
crafting soft hammer with rubber gives a wooden soft hammer

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#162]
![2018-06-26_21 59 54](https://user-images.githubusercontent.com/13512001/41936595-49f6b3ee-7996-11e8-8202-ee5578f2eea4.png)
image speaks for itself.
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
fixed
