### ISSUE TITLE
extruder bolt recipe in jei switched

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#163]
![2018-06-26_20 21 28](https://user-images.githubusercontent.com/13512001/41936721-caea18c4-7996-11e8-9dbf-fedf8212c9ca.png)
recipe for iron bolts in extruder has the extruder shape in the materials slot and the iron ingot in the extruder shape slot. happens consistently. also checked with a few other materials including tin, and it appears to be happening with them too
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
fixed
