### ISSUE TITLE
[Question] What is the base voltage tier for each craftings?

### ISSUE THREAD

**Issue by yanhaozhe** [GregTechCE/GregTech#1638]
For example, macerators have such recipes with byproducts with a base probability of 14% and each voltage tier 8.5%. I want to know which is the base tier? Is it fixed LV or related to the recipe?

**Comment by galyfray** [comment]
`chanceUsed = chance + (boostPerTier * tier)`

and tier is given in this way : 

```
    public static final int ULV = 0;
    public static final int LV = 1;
    public static final int MV = 2;
    public static final int HV = 3;
    public static final int EV = 4;
    public static final int IV = 5;
    public static final int LuV = 6;
    public static final int ZPM = 7;
    public static final int UV = 8;
    public static final int MAX = 9;
```

this mean if you have a byproduct with a base chance of 14% and each voltage tier makes you gain 8.5% If you made this recipe run on an LV machine you have an effective chance of 22.5%

**Comment by warjort** [comment]
https://omnifactorydevs.github.io/OverclockingCalculator/

lets you see the calculations of chanced outputs in the macerator by tier.
