### ISSUE TITLE
[Question] Why its unable to connect different size of pipes? Why transformers have only one side of output ? So many questions for this mod )

### ISSUE THREAD

**Issue by AndyMel1** [GregTechCE/GregTech#1639]
_Feel free to ask any question regarding this project here._
_If you are in need of quick response Discord may be a better place. As we have quite big community there so you may get response immediately also it works as knowledge hive._
_If you are looking for wiki we current don't have one, there is only available in-game info through tooltips or JEI. But someone on Discord may know what you need._
_If you are looking for API documentation or CT documentation. There is wiki on GitHub which holds some information. For CT documentation there are few pages for GTCE on official CT wiki. Also we have Discord channel for this purpose._

**Comment by galyfray** [comment]
you are supposed to write the question in the corpus of the issue :) 

concerning the transformers I think this was a choice. It may also come from the fact that machines only have one output face and nobody felt the need to change that.

**Comment by warjort** [comment]
Pipes of different sizes do "connect" just not in the way you might expect.

The GTCE fluid pipes actually form multiblock tanks (called a pipe network)
that will automatically push into neighbouring fluid inventories.

Pipes of different sizes and materials (and colours - you can paint them) form different tanks/networks.

To avoid fluid being pushed backwards and forwards between 2 of these pipe networks
there is a rule that the bigger pipes automatically push into the smaller ones and not vice-versa.
If you want fluid to go the other way, you will need a pump cover to reverse the flow.
