### ISSUE TITLE
energy input hatch (LV) uncraftable

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#164]
the energy input hatch (LV) (and probably other things with similar recipes) is uncraftable.
the difference between the energy input hatch and energy output hatch in terms of recipes, is that one has the cable on the right (the output), and one has it on the left (the input). thing is, both of them craft the output hatch.
![2018-06-26_23 04 14](https://user-images.githubusercontent.com/13512001/41936988-bad49620-7997-11e8-94a2-cfdee3630911.png)
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by gerb82** [comment]
bug appears to be consistent across all mirrored recipes in the mod. it is also not limited to recipes with just two items, as it also affects the crafting recipes of the packager and the unpackager
so essentially, every set of two recipes that mirror each-other will have one variant being craftable, and the other being uncraftable. it is the same bug that affected the extruder ring shape and the extruder plate shape. currently only confirmed it where everything except the middle right and middle left slots is the same, and just those two slots are swapped, as i cannot find any recipe that has any other side slots swapped with those of the other side in a different recipe

**Comment by EmosewaPixel** [comment]
Well if they are mirrored, of course it's going to be consistent. I just don't get why they use mirrored recipes for machines and such things.

**Comment by Archengius** [comment]
fixed
