### ISSUE TITLE
I hope to add a machine that converts energy 

### ISSUE THREAD

**Issue by MC-Nirvana** [GregTechCE/GregTech#1642]
I hope to add a machine to convert GTCE energy into energy from other modules. In this way, it can be used with other modules. If you can't add machinery, can you add cable support for Applied Energistics 2 and other modules? 
（I don’t speak English, the above information is filled out by Google Translate ）

**Comment by warjort** [comment]
There already is such a machine in addon projects.

Standalone mod:
https://www.curseforge.com/minecraft/mc-mods/ceu

Gregicality addon project:
https://www.curseforge.com/minecraft/mc-mods/gregicality

NOTE: Curseforge is down when I write this so those links don't work at the moment, try later.
