### ISSUE TITLE
[BUG] Game Crashes when placing redstone near machine

### ISSUE THREAD

**Issue by MofumofuChan** [GregTechCE/GregTech#1644]
**Describe the bug**
I placed a redstone on the side of a Steam Rock Breaker and that caused me game to crash (first crash report) then I tried to open the game again and the game instantly crashed when loading the world (second report), and to see if optifine was the culprit I tried opening the game without it, which resulted in a crash again (third report).

**Versions**
Forge: 14.23.5.2815
GTCE: 1.7.0.387
Modpack: Gregblock (https://www.curseforge.com/minecraft/modpacks/gregblock)

**Setup**
Playing Solo

**Steps To Reproduce**
1) I placed the Steam Rock Breaker
2) I placed the redstone adjacent to it

**Expected behavior**
It should just place the redstone so I could power it

**Crash Reports**
First: https://pastebin.com/e8scZVSP
Second: https://pastebin.com/YJ7RT8GZ
Third: https://pastebin.com/RSEr96UA

**Comment by galyfray** [comment]
an NPE in getCoverAtSide I think this has been already discussed somewhere I will investigate.

**Comment by galyfray** [comment]
you are using an older version of gregtech I it seems this problem has been already fixed

**Comment by galyfray** [comment]
the problem as been fixed in this commit : https://github.com/GregTechCE/GregTech/commit/44b2c6143d2049b750aec8ad0bc38d948b070cf4

**Comment by galyfray** [comment]
please try with this version https://www.curseforge.com/minecraft/mc-mods/gregtechce/files/2704359 it should be fixed (I hope) but too updated so the pack still work

**Comment by galyfray** [comment]
here is a list of older version of GTCE just try if an earlier one work but don't try to update to latest one of the mod in gregblock is abandoned so it won't work 
https://www.curseforge.com/minecraft/mc-mods/gregtechce/files/all?filter-game-version=1738749986:628&page=3

**Comment by MofumofuChan** [comment]
> please try with this version https://www.curseforge.com/minecraft/mc-mods/gregtechce/files/2704359 it should be fixed (I hope) but not too updated so the pack still work

I tried that version (which is the version after the one I have) and it crashes when loading mods. Maybe it could've been that since it wasn't too downloaded it would've been a bit defective, so I tried the next version that had lots of downloads, which was 1.8.1.399. Still same error. I don't know what I can do at this point. I really wish the creator of Gregblock could've updated the modpack.

Crash report: https://pastebin.com/ZQ79u03g

**Comment by million09** [comment]
Gregic Additions is abandoned and no longer updated. Move on to [Gregblock-revamped](https://github.com/programgames/Gregblock-revamped) or [Gregicality Skyblock Edition](https://www.curseforge.com/minecraft/modpacks/gregicality-skyblock-edition). Plenty of bugfixes and new features are waiting for you!

**Comment by LAGIdiot** [comment]
I am going to be completely honest. We are supporting only current version and we are not backporting any changes. Version you are using is from Apr 9, 2019 so it is dead (not just for us).

Now what you can do:
1) look through our repo, find in what version we fix it, use that version in pack you are playing. You will probably also need to update any addon which depends on us (and in your case that addon is dead). Well whole pack you are playing is dead.
2) remove Redstone via some editor and not place it near GTCE (and our addon) machines again
3) start playing new modpack which is not dead
