### ISSUE TITLE
[BUG] No surface material of Kyanite vein and Mica vein

### ISSUE THREAD

**Issue by yanhaozhe** [GregTechCE/GregTech#1646]
When I am trying to upgrade the Coil of the electric furnace, I found the Kandal alloy coil requires mica.

While it is hard for me to find mica veins because there is no surface material so I cannot find them efficiently.

![2021-06-01_23 46 09](https://user-images.githubusercontent.com/54829520/120352932-db01aa80-c333-11eb-97e0-935f4436ac9c.png)

**Comment by warjort** [comment]
First, mica is a gregicality thing so you are reporting this to wrong project.

But, you can change this to whatever you like in config/gregtech/overworld/mica_vein.json
