### ISSUE TITLE
integrated circuits numbers

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#165]
the cap for the configured number in the integrated circuit is 16.
however, some recipes require it to be configured to 24, like the insulated copper cable and a few more (mainly insulated cables from what i've gathered):
![2018-06-26_23 33 03](https://user-images.githubusercontent.com/13512001/41937664-9bb45ad0-7999-11e8-8fb2-37064463fe7d.png)

version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
fixed
