### ISSUE TITLE
[Question] Why does the integrated circuit have its own dedicated JEI tab?

### ISSUE THREAD

**Issue by GManClone** [GregTechCE/GregTech#1653]
It feels quite unnecessary to have a JEI tab just for the integrated circuit, unless there is a good reason to have it there.

**Comment by idcppl** [comment]
It's there so you can see specific recipes for that numbered integrated circuit.

**Comment by eutro** [comment]
https://github.com/GregTechCE/GregTech/pull/1142 made different circuit configurations count as distinct ingredients to JEI. Looking at the usages of a configuration 1 circuit will not show usages of any other configurations.

The tab in JEI makes it possible to navigate to any Integrated Circuit recipe given one, it essentially represents the right-click circuit configuration "recipe".

**Comment by GManClone** [comment]
Is it possible to hide this JEI category through CraftTweaker though?

**Comment by eutro** [comment]
[Yes](https://docs.blamejared.com/1.12/en/Mods/JEI/JEI/#hide-categories), why though?

**Comment by GManClone** [comment]
True, but I don't search GTCE recipes based on circuits anyway. Similarly, some of the JEI categories that EnderIO adds (solar panels and most of its generators) add very little information that I'd rather not have them clog up my JEI tabs.
