### ISSUE TITLE
[BUG] Gregtech Saws cutting Leaves with OreExcavition Issue

### ISSUE THREAD

**Issue by bioastroiner** [GregTechCE/GregTech#1654]
**Describe the bug**
using gt saws with ore excavition (version 1.4.150)  on Leave blocks dosen't cost any duribility
It initially registers as it cost the tool only 1 unit of damage then upon opening a container the duribility resets as the tool haven't recieved any damage at all

**Versions**
Forge: 14.23.5.2855
GTCE: 1.15.0.721
**Modpack** https://www.curseforge.com/minecraft/modpacks/gregicality-skyblock-edition ver:6.0c
THERE ARE ADDONS!:
_**Gregticallity**_ (Related?) ver: 0.22.4.1
_**Gregtech Food Option**_ (Related? dose add limon drop from leaves probably unrelated just to note) ver:0.7.1
**OreExcavition** (Related) ver: 1.4.150

**Setup**
Solo

**Steps To Reproduce**
I used **Bronze Saws** to break the leaves
it's simply as breaking leaves (or any other block?) with saw wouldn't reduce its duribility
1) the first issue is that it would only register 1 block hit
2)as you open a container that duribility will also be ommited and tool **will become undamaged again**
**NOTE that it works on other leaves as well not only oak haven't tried all of the other blocks but they seem to be fine** like Oak Wood

**Screenshots**
it also useful for reproducing the issue
1)using an **undamaged saw (or damaged)** on the **leaves** (I tried it on other blocks and it was **Fine** only leaves)
https://i.imgur.com/0wll8cw.png
2)initial damage (the first issue)
https://i.imgur.com/B6gQmDW.png
3)**opening containers fixes the duribility** make the tool **undamaged** or sets it to its previous duribilty (the second issue)
https://i.imgur.com/B6gQmDW.png

**Comment by warjort** [comment]
This has nothing to do with OreExcavation.

The GTCE saw has special handling so it can be used as a substitute for shears.
This doesn't go through the normal "finished breaking block" code, and so it doesn't apply any damage to the item.

All you are seeing is a "phantom" 1 damage assumed by vanilla code. This is not actually real. 
It will revert to the real (no damage applied) data when the saw is removed from your inventory.

**Comment by warjort** [comment]
In case it is not clear from my answer above, this is a bug. It should be applying damage.
