### ISSUE TITLE
double ashes recipe

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#167]
this one's a bit weird. so the dark ashes obtained from the blast furnace as a byproduct can be crafted into dust that can then be centrifuged. if you put one in you get carbon dust. if you put two in, you get 2 ashe piles. the ashe piles have one recipe: a recipe to make carbon dust. it is the exact same recipe as the recipe the dark ashes have. so essentially... if you put one, you skip a stage. if you put 2: you don't.
![2018-06-26_21 56 47](https://user-images.githubusercontent.com/13512001/41938775-af1ce382-799c-11e8-97d4-9df14fa4d12b.png)
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by EmosewaPixel** [comment]
According to previous GT versions, the first one is the correct one.

**Comment by Archengius** [comment]
fixed
