### ISSUE TITLE
[Suggestion] Update Magic Energy Absorber's text to be more correct

### ISSUE THREAD

**Issue by policiu** [GregTechCE/GregTech#1679]
**Is your feature request related to a problem? Please describe.**
Help/Info text of the Magic Energy is misleading on versions of minecraft with craftable end crystals (minecraft 1.9+).

Current Text:
"Collects energy from ender crystals in 64 blocks ..."

When in reality, the absorber only works on end crystal placed on naturally generated obsidian spikes/pillars. It's a bit frustrating working towards an item and the item not work as the text implied.  

**Describe the solution you'd like**
Easier fix would be to change the text to have the information that the block only works on Ender Crystals placed on top of obsidian spikes/pillars generated in the end.

Make it more concise, but something like this:
"Collects energy from end crystals on obsidian spikes in the end within 64 blocks ..."
That is still missing the information that the obsidian spikes/pillars must be natural generated, but the change would be helpful.

A more difficult fix would be to rework the item.

**Additional context**
Bit of a fun screenshot from when I was testing how this block works after reading through issue #1440 and the code. 

I cleared out the obsidian pillar/spike and placed craftable end crystals. Notice how the far left crystal is not contributing, since it was not placed where an obsidian pillar/spike existed.

![image](https://user-images.githubusercontent.com/1704165/123892127-9c094980-d91f-11eb-908d-5bee20216e10.png)

**Other**

This is a mix of a bug and a feature request. Feature request being a rework of the item.

**Comment by SuperCraftAlex** [comment]
Do you mean that anyone only needs to change the tooltip in language files?

**Comment by policiu** [comment]
I would assume so, since it's the only place where the string is in the code.  Not 100% sure how Minecraft modding/tooltips work, but you might need to make sure the string isn't too long, language not too technical, translate for the other supported languages, etc.
