### ISSUE TITLE
Forever exploding steam boiler

### ISSUE THREAD

**Issue by Bennyboy1695** [GregTechCE/GregTech#168]
When a Steam boiler is inside a FTBUtils claim it will forever explode and won't break, once its unclaimed if its still exploding it manages to drop. I believe this is a fake player issue with the exploding.

**Comment by Archengius** [comment]
it''s not fake player issue, GT doesn't use any players for explosions. it's FTBUtils blame if it disallows explosions without entity source specified. 
I still added explicit setBlockToAir for that, btw
