### ISSUE TITLE
ghost recipes

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#169]
there seem to be a few "ghost recipes" in jei, where the item used for the recipe does not exist, but the recipe and the results do. an example of that is a recipe from the wiremill, that takes air and makes string out of it. i'm pretty sure those recipes are recipes using compatiabilities of the mod that are simply not present, as i remember seeing a similar recipe in the original gregtech that used a mining pipe in the wiremill to make strings. there are a few other similar recipes, i'll update as i re-find them
![2018-06-27_22 08 31](https://user-images.githubusercontent.com/13512001/41994512-554960f4-7a57-11e8-95d1-66ad39d9685c.png)
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by EmosewaPixel** [comment]
Yeah, this was discussed on the Discord yesterday.

**Comment by Archengius** [comment]
fixed
