### ISSUE TITLE
Gregtech Crash on Nether Generation [BUG] 

### ISSUE THREAD

**Issue by AvilionAMillion** [GregTechCE/GregTech#1697]
**Describe the bug**
Gregtech crashes while loading or being in the nether

**Versions**
Forge: 14.23.5.2854
GTCE: 1.17.0.764
_Addons:_ Gregicality v. 0.22.7

**Setup**
Playing Solo
_New world generated:_ Yes

**Steps To Reproduce**
1) Entered the nether
2) Game crash
or
1) Be in the nether
2) Game crash

**Additional context**
Pastebin with crashlog info https://pastebin.com/R1w8RefG

**Comment by warjort** [comment]
I tried this with the same versions of GTCE and Gregicality and had no problems in the nether.

I can tell you the problem with the ore generation where one of the ore populators is returning a "null" block state.
Unfortunately, the error checking is non-existant here so there is no context in the error message in your crash log to say which of the ore definitions is the problem.

**Comment by warjort** [comment]
The first thing to try would be to see if running with the "factory setting" ore definitions fixes the problem.

* rename config/gregtech to something like config/old-gregtech
* restart the game
* create a new world
* go into the nether

This will regenerate the worldgen definitions in config/gregtech using the default settings.

**Comment by warjort** [comment]
> The first thing to try would be to see if running with the "factory setting" ore definitions fixes the problem.

I say this, because these were changed recently to add/alter surface rocks.
The old configs should still work, but...

**Comment by AvilionAMillion** [comment]
> The first thing to try would be to see if running with the "factory setting" ore definitions fixes the problem.
> 
> * rename config/gregtech to something like config/old-gregtech
> * restart the game
> * create a new world
> * go into the nether
> 
> This will regenerate the worldgen definitions in config/gregtech using the default settings.

that seemed to work, thank you.
