### ISSUE TITLE
[BUG] Hot ingot Carrying without damage

### ISSUE THREAD

**Issue by leonbeer** [GregTechCE/GregTech#1699]
**Describe the bug**
In combination with the trash slot mod, or other inventory mods, like random things (inventory cake), Hot ingots will not damage the player if put into these inventories.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.8.4.419
_Modpack: Omnifactory : https://www.curseforge.com/minecraft/modpacks/omnifactory

**Setup**
Solo and Multiplayer applicable

**Steps To Reproduce**
I take a hot ingot out of the blast furnace 
And then i put it into a third party inventory

**Expected behavior**
Expected is, to still get damage from the Hot ingots, even when they are in third party inventories.

**Comment by warjort** [comment]
This sounds like a bug in those mods.

They need to call ItemStack.updateAnimation() for the items in their slots.
That is what GTCE hooks into for the hot ingot damage. It's a kind of item tick.

**Comment by warjort** [comment]
They probably never realised since the main vanilla use of this processing (besides the pickup animation)
is to update minecraft map items. And they only update when they are in the player's hand anyway.
