### ISSUE TITLE
bug allowing conversion of rubber to paper and vise versa

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#170]
the red alloy cables have two recipes. one in the assembler, using rubber and the cables.
the other is in a crafting table, using paper and the cables.
the unpackager has an unpacking recipe for both. so whichever it counts, will be created regardless of the way the cable was made, as it has no way to differentiate.
this should work for all other cables that have both a rubber recipe and another (in this case paper) recipe.
![2018-06-27_22 18 13](https://user-images.githubusercontent.com/13512001/41994774-4472819c-7a58-11e8-9fe3-22cce2ec3124.png)
![2018-06-27_22 18 17](https://user-images.githubusercontent.com/13512001/41994777-4547b07e-7a58-11e8-9d36-875a62d48130.png)
![2018-06-27_22 18 22](https://user-images.githubusercontent.com/13512001/41994778-45ec2370-7a58-11e8-8f68-261e70a7fc3d.png)
version - gregtech-1.12.2-0.4.5.9
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by SuperCoder7979** [comment]
fixed
