### ISSUE TITLE
[BUG] Fluid Regulators not respecting Keep Exact

### ISSUE THREAD

**Issue by Exaxxion** [GregTechCE/GregTech#1705]
Fluid Regulators appear to be ignoring their mode setting and just transferring the maximum amount per second they're allowed to.

**Versions**
GTCE: d9e7ed45 via `./gradlew runClient`

**Setup**
Playing Solo (probably doesn't matter though), new superflat world created

**Steps To Reproduce**
1. Place down an autoclave next to a quantum tank
2. Place a Fluid Regulator on the tank on the side adjacent to the autoclave
3. Set the Fluid Regulator to Export, Flow Rate 1mB/s, Keep Exact: 2mB
4. Fill the quantum tank with some palladium
5. Observe that 1mB of palladium is entering the autoclave each second and it will continue until all of the palladium has entered the autoclave.

**Expected behavior**
The fluid regulator will move 1mB of palladium into the autoclave then stop transferring until the autoclave has no palladium left in its fluid slot.

**Screenshots**
![image](https://user-images.githubusercontent.com/11907282/128589458-06131aad-ad90-4f88-9dab-8761349edb73.png)
![image](https://user-images.githubusercontent.com/11907282/128589465-87fb5ea0-7009-44c1-bcbe-66049200628e.png)

**Comment by eiis1000** [comment]
Alternatively, reproduce using a fluid regulator on an autoclave set to import (I used Pd as well with a ME fluid interface stocking Pd) and keep exact is ignored as well. Seems to take input from the interface in increments of `whatever is set in Keep Exact` per tick.
