### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ewe2** [GregTechCE/GregTech#1719]
**Problem:**
* Missing recipe for Tin Rotor using Rotor Mold

**Solution:**
Add the recipe to Alloy Smelters from Basic (LV) up with Tin Ingots and a Rotor Mold similar to other Rotor Mold recipes and an appropriate number of Ingots.

**Comment by Exaxxion** [comment]
I'm inclined to disagree on this one, as it cheapens the reward of unlocking them via fluid solidification. I'm pretty sure adding such a recipe would allow players to never have to make a rotor by hand.

**Comment by ewe2** [comment]
Huh? You already do make them by hand, they're a required component in electric pumps. I'm looking at the recipe right now, it uses  a tin ring, 4 tin plates, a tin screw, and I'm using wrought iron tools so wrought iron hammer, file and screwdriver. I see no good reason why, if the other molds work with the tin ingots in the alloy smelter, the rotor shouldn't.

**Comment by Exaxxion** [comment]
I think you misunderstood my comment. I'm fully aware there is a manual recipe for rotors. What I'm saying is that adding an alloy smelter recipe for them would make it so you could skip ever having to make them manually.

**Comment by ewe2** [comment]
That doesn't make logical sense if there are recipes for other ingots then, you may as well remove all the others.

**Comment by Exaxxion** [comment]
Quite frankly I agree with you. However, without suggesting that disruptive route, I can just point out that even before considering the rotor mold, not all of the solidifier recipes have (worse) equivalents in an alloy smelter.

The rotor mold was only recently added and it is already a huge quality of life boost, when you earn it by making the proper infrastructure to use it.

**Comment by ewe2** [comment]
OK, so I'll just have to go the fluid extractor->fluid solidifier route with it, I get it now. The questline gives an oblique hint to that, perhaps too oblique for a slowcoach like me :P Thanks, closing.

**Comment by Exaxxion** [comment]
Quests would imply the context of a modpack, whereas this is the repository for GTCE. Modpacks can change things however they want, but GTCE needs to keep itself internally consistent and balanced.
