### ISSUE TITLE
[BUG] Client crashes on loading

### ISSUE THREAD

**Issue by Custom2044** [GregTechCE/GregTech#1725]
I cloned the repo, and used the command
`./gradlew --no-build-cache runClient`
The project compiles and starts, but crashes when loading mods, between step 3 and 4.
I also tried checking out to v1.17.1 and v1.17.0, but I got the same result.

The logs mention a NullPointerException from codechickenlib : [latest.log](https://github.com/GregTechCE/GregTech/files/7360966/latest.log)

**Additional context**
Java version : jdk 1.8.0_181

Gradle properties :
[props.txt](https://github.com/GregTechCE/GregTech/files/7360977/props.txt)

**Comment by warjort** [comment]
You need run the following gradle task:
````
./gradlew setupdecompworkspace
````
This will make sure all the mod dependencies have been remapped to the deobfuscation mapping used by the GTCE build.
(It also generates the source for minecraft so you can see it in your ide).

**Comment by Custom2044** [comment]
It worked, thank you and sorry for the unrelated issue.
