### ISSUE TITLE
Weird shift-clicking in steam machines

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#173]
In Bronze and Steel steam machines, items can be shift+left-clicked only if they are in the top row of the player's inventory. If they're in any other row, they will be moved to the top row. If the top row is full, nothing happens.

**Comment by pyure** [comment]
Possibly related: I couldn't shift-click items OUT of the high pressure steam furnace.

**Comment by Archengius** [comment]
fixed
