### ISSUE TITLE
integrated circuits unconfigureable

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#174]
integrated circuits cannot be configured. rightclicking seems to be doing something, but it does not change their configuration, and it does not open any sort of window.
version - latest commits available when this issue was created
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
configuration works fine, it just doesn't update on client. and it is known.

**Comment by gerb82** [comment]
so how do i configure it if i can't open the window to do so?

**Comment by Archengius** [comment]
it was already fixed, but still not on github

**Comment by gerb82** [comment]
oooooh ok. thanks a lot
