### ISSUE TITLE
server crash in 1.12.2 with the latest gregtechCE

### ISSUE THREAD

**Issue by DAmanc123** [GregTechCE/GregTech#1747]
loaded 260 mods inclunding GTCE,but it crashed,crash report will shown as follow
[crash-2022-10-25_11.57.07-server.txt](https://github.com/GregTechCE/GregTech/files/9857161/crash-2022-10-25_11.57.07-server.txt)

**Comment by Exaxxion** [comment]
This crash report lists `gregicadditions` - which is the mod ID of Shadows of Greg - at the point of failure in the stack trace.

Please report your issue [there](https://github.com/Shadows-of-Fire/Shadows-of-Greg/issues/new), and provide as much detail as you can like what pack you're playing and what was happening just prior to the crash.

**Comment by DAmanc123** [comment]
ok
