### ISSUE TITLE
[BUG] Scanner not working

### ISSUE THREAD

**Issue by marekvac** [GregTechCE/GregTech#1752]
**Describe the bug**
When trying to use scanner, nothing happens.

**Versions**
Forge: 14.23.5.2860
GTCE: 1.12.2-1.17.1.770
_Modpack:_ https://www.technicpack.net/modpack/cp-new-modpack.1961531
_Addons:_ shadows of greg, bunch of other mods. Since I tried it with only GTCE installed, it doesn't matter I think.

**Setup**
Playing Both on server and standalone client
_New world generated_ yes

**Steps To Reproduce**
1) Right click with the charged scanner
2) Nothing happens

**Expected behavior**
Scanner should start scanning..?

**Screenshots**

**Additional context**
Also tried without any other mods, only with GTCE and codechickenlib installed.

**Comment by Exaxxion** [comment]
The scanner doesn't just show what is around generally. You need to right-click a "surface rock" with the scanner and it will tell you what vein it corresponds to.

![2023-04-16_16 10 24](https://user-images.githubusercontent.com/11907282/232348305-21662bf5-c800-4b3e-915d-732643e93aba.png)

**Comment by marekvac** [comment]
Sorry my bad, I have look in the code and I have thought the "surface rock" is a stone, granite etc.. Thank you, and once again sorry for invalid post.
