### ISSUE TITLE
1.16.5 port?

### ISSUE THREAD

**Issue by ArnauGames** [GregTechCE/GregTech#1754]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

_Please fill in as much useful information as possible. Also please remove all unused sections._

**Comment by Leclowndu93150** [comment]
LMAO WHAT

**Comment by Exaxxion** [comment]
There are no plans for a port to other versions. This project is essentially defunct after developer interest moved to GTCEu.
