### ISSUE TITLE
[BUG] server crash upon break of machine

### ISSUE THREAD

**Issue by lonesage1944** [GregTechCE/GregTech#1758]
**Describe the bug**
server crashing upon breaking/opening a steam boiler{precise one is the low pressure vers}

**Versions**
Forge: 47.2.20
GTCE: 
_Modpack:_atm9  vers 0.2.58
addon/datapacks: none
_plugins:_ 
AutomaticBroadcast-1.6.0
BanItem-3.5
BasicQuests-0.5
BisectHosting-bukkit-1.6+
CommunityQuests-2.1.1
Discord-Linker-3.4.2
DiscordSRV-Build-1.27.0
DiscordVoteLog-1.0.0
EssentialsX-2.20.1
ExcellentCrates-5.2.2.1
LagFixer-1.2.24_b62
LPC 
LuckPerms-Bukkit-5.4.121 
LWBack.jar
nightcore-2.5.2.1
nuvotifier.jar
PlaceholderAPI-2.11.5
PlayerAuctions 1.27.3
PlayerLands
SayWelcome
SignShop-4.0.0
Statusbot-18.0-Spigot
TAB v4.1.2
TradeSystem-1.3-SNAPSHOT.
Vault
VotingPlugin
welcome.sk

**Setup**
Playing Multiplayer

**Steps To Reproduce**
-place low pressure boiler
right click it then disconnection crash's server/ breaking the boiler block also crash's the server

1) I thought to try and break it if it was dimensional. maybe
2) And then it didn't matter what dimension it was in
 
[crash-2024-04-27_11.01.43-server.txt](https://github.com/GregTechCE/GregTech/files/15137977/crash-2024-04-27_11.01.43-server.txt)

[crash-2024-04-27_10.28.38-server.txt](https://github.com/GregTechCE/GregTech/files/15137978/crash-2024-04-27_10.28.38-server.txt)

**Comment by Exaxxion** [comment]
All The Mods 9 is a modpack for Minecraft 1.20. This mod exists exclusively on Minecraft 1.12.2.

I believe the project you are looking for in regards to this issue is [GTCEu Modern](https://github.com/GregTechCEu/GregTech-Modern).
