### ISSUE TITLE
[BUG] crash on initializing game

### ISSUE THREAD

**Issue by albiek1** [GregTechCE/GregTech#1763]
Game is crashing while initializing game.

**Versions**
Forge: 14.23.5.2860
GTCE: 1.17.1.770

I assume it's GregtechCE since it's pointing to gregtech/api/recipes/GTRecipeInput but I checked an older version from another modpack and cant find the file in either?

Full log:
[crash-2024-05-18_21.21.36-client.txt](https://github.com/GregTechCE/GregTech/files/15366638/crash-2024-05-18_21.21.36-client.txt)

Edit: Never mind, the issue was with nuclearcraft

**Comment by htmlcsjs** [comment]
nuclearcraft is no longer compatible with GTCE (afaik), instead migrating its inbuilt GT compat to CEu (CE fork that is actually updated and significantly less jank). You can disable the GT compat by setting all the trues in `gtce_recipe_integration` in the nc config to false. (or update to GTCEu, but this means your world is imcompatable)

**Comment by htmlcsjs** [comment]
oh you solved it, nice
