### ISSUE TITLE
[BUG]: Z-Fighting on liquid tanks

### ISSUE THREAD

**Issue by Lolothepro** [GregTechCE/GregTech#1765]
![2024-06-20_17 30 31](https://github.com/GregTechCE/GregTech/assets/68275908/92fa32f5-101d-4d51-8112-2dbaeac65460)
![2024-06-20_17 29 14](https://github.com/GregTechCE/GregTech/assets/68275908/2d0641c6-3f52-4b79-a3a4-d018a62e9851)

NeoForge 21.0.20-beta

**Comment by Exaxxion** [comment]
Please report issues for GTCEu to https://github.com/GregTechCEu/GregTech/issues.
