### ISSUE TITLE
[BUG] GregTech UIs reduce FPS a lot

### ISSUE THREAD

**Issue by Bestsoft101** [GregTechCE/GregTech#1768]
**Describe the bug**
GregTech interfaces reduce FPS a lot more than those of any other mod. See the videos that I added

**Versions**
Forge: 47.2.6
GTCE: 1.2.3.a
_Modpack:_ TerraFirmaGreg https://www.curseforge.com/minecraft/modpacks/terrafirmagreg/files/5394656

**Setup**
Playing on a server hosted on my pc

**Screenshots**

https://github.com/user-attachments/assets/fb9a2708-5986-423f-a49d-c62d95b65f16

Notice how the GregTech crate drops my FPS much more than the TerraFirmaCraft chest, and the larger crate, even though it's empty, reduces my FPS even more

https://github.com/user-attachments/assets/d6d30ab0-5bcb-4bcf-91dc-5042e130b944

At lower FPS the mouse tweaks item dragging doesn't work well

**Comment by Exaxxion** [comment]
GTCE is a mod for Minecraft 1.12.2, the final version of which was released in late 2021.

The modpack you linked is for Minecraft 1.20.1 and states it contains the mod GregTechCEu Modern. This is not the repository for that mod; you should report your findings to https://github.com/GregTechCEu/GregTech-Modern.

**Comment by Bestsoft101** [comment]
my bad
