### ISSUE TITLE
wiremill normal wire recipes not working

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#177]
the normal wire recipes for the wiremill no longer work in the latest commit.
as a result, the extruder is the only currently available way to make wires in a 1 ingot to 2 wires ratio, meaning it is practically impossible until you reach MV machines.
version - latest commits available when this issue was created
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
fixed
