### ISSUE TITLE
electric blast furnace not activating

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#178]
there seems to be no way to start the electrical blast furnace.
it does not work when given power and the required items, and using a rubber hammer puts it in working disabled mode instead of idling mode.
it is assembled correctly, and the input bus has valid items for the recipes inside of it
version - latest commits available when this issue was created
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Archengius** [comment]
![image](https://user-images.githubusercontent.com/36846151/42124989-f9b684ea-7c97-11e8-95e9-bbf871f6de30.png)
works perfectly
