### ISSUE TITLE
steam machines progress bar not syncing properly on server

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#179]
this one's a weird one. the progress bars on steam machines work perfectly fine on singleplayer. on multiplayer though, any relation between them and the actual progress is completely coincidential.
however, they do follow one of a few patterns:
the progress bar will start when you enter the machine
the progress bar will be empty for a few seconds when you enter the machine, and then start at an offset that appears random
the progress bar will be in sync AS LONG as you stay in the machine's interface from the moment it starts
  - the progress bar will be almost in sync, in an offset of about 2 work ticks, meaning it will almost finish 
     when the work is finished, and start around 2 work ticks after work starts. (this one is a subcategory of 
     the last one, and is the only consistent offset one)

important information:
my ping on the server is around 100-140 ms. might be related, doubt it.
waila displays the progress bar correctly, which has enabled me to take those pictures:
![2018-06-30_11 10 40](https://user-images.githubusercontent.com/13512001/42123281-e8e12534-7c57-11e8-9759-63cc1b83e818.png)
![2018-06-30_11 10 41](https://user-images.githubusercontent.com/13512001/42123282-e998853a-7c57-11e8-923b-f5fea14d931c.png)
(as you can see above the machine in the waila display, it displays the actual progress, while the progress bars display it at an offset)
this only happens with steam machines.
version - latest commits available as of the day before creating this issue
forge version - forge-14.23.4.2707 (according to twitch)
crash report - N/A

**Comment by Georggi** [comment]
Well, I tested on a local server with 1ms ping and didn't notice any delay, 2 work ticks is actually 100ms, exactly your ping, so the issue is with that.

**Comment by gerb82** [comment]
it only happens with steam machines. all normal machines work normally, all steam machines bug out like that consistently
