### ISSUE TITLE
Alloy Smelter generates oredict-unfriendly recipes

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#182]
Reproduced with Red Alloy Ingot, small pack with Gregtech and various other mods.

The Alloy Smelter generates 4 recipes for Red Alloy Ingot:
- Redstone Dust + Copper Dust (FactoryTech) => Red Alloy Ingot
- Redstone Dust + Copper Ingot (FactoryTech) => Red Alloy Ingot
- Redstone Dust + Annealed Copper Ingot (GregTech) => Red Alloy Ingot
- Redstone Dust + Annealed Copper Dust (GregTech) => Red Alloy Ingot

Note that where we show "FactoryTech" above, that could be any arbitrarily sourced dust or ingot.  And if a mod has Annealed materials, they may get used there as well.

The recipes do not cycle through oredict possibilities, so if the user has the incorrect mod's dust (GT instead of FactoryTech) the recipe will not work.

**Comment by Archengius** [comment]
fixed

**Comment by pyure** [comment]
I think this is happening for any recipe that can split itself into a Dust or Ingot recipe.
