### ISSUE TITLE
Input hatches can input fluids from any side

### ISSUE THREAD

**Issue by SuperCoder7979** [GregTechCE/GregTech#191]
As the title suggests. Input hatches can have fluids inputted into them from any side, when only the input side should be able to.

**Comment by pyure** [comment]
Is this how GT5 worked?  I don't actually recall but I remember seeing some interesting behaviours from GT5.  

Also, which side should you be able to insert fluid into a Output hatch?  None?

I'm actually interested for a reason: The GT hatches could be used for logistical builds outside of multiblocks sometimes (they were effectively small tanks).

**Comment by leagris** [comment]
I suggest keeping the fluid canning feature of these tanks, and removing the fluid canning machine that is a questionable corked complex device to fill/empty fluid containers.

I also suggest having a single fluid hatch with a single recipe, so you can choose to configure it as:
1. Neutral (default)
2. Input only
3. Output only

Maybe require it to receive power if used stand-alone as a fluid canning machine.

**Comment by Archengius** [comment]
no
