### ISSUE TITLE
(Idea/Feature) minetweaker.

### ISSUE THREAD

**Issue by mightydanp** [GregTechCE/GregTech#192]
Implement mintweaker addon into gregtech community edition. For improved compatibility.

**Comment by Rongmario** [comment]
Already done /thread

**Comment by SuperCoder7979** [comment]
We already have CraftTweaker support

**Comment by mightydanp** [comment]
Have you guys re implamented the harvest level change on the  ores ?

**Comment by mightydanp** [comment]
i should be able to fallow this or is it outdated? 
http://minetweaker3.powerofbytes.com/wiki/Mods:GregTech_Support

**Comment by Rongmario** [comment]
@mightydanp anything on http://minetweaker3.powerofbytes.com is outdated above 1.7.

Documentation is... being worked on...
