### ISSUE TITLE
jei multiblocks broke

### ISSUE THREAD

**Issue by Yoghurt4C** [GregTechCE/GregTech#193]
https://pastebin.com/raw/ZPESYTwx

**Comment by EmosewaPixel** [comment]
But what caused the crash?

**Comment by Yoghurt4C** [comment]
rightclicking on any of the supported multiblock controllers, naturally

**Comment by Exidex** [comment]
Fixed in 353b038d6e10d0747eec86186ac880ebfd456b6f
