### ISSUE TITLE
canning machine cannot take out air from stacks of more than 1 air cells

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#194]
title pretty much explains itself.
with stack of more than one cell:
![2018-07-07_01 13 26](https://user-images.githubusercontent.com/13512001/42402397-2fc0b106-8183-11e8-8f76-e76e039633fc.png)
with a stacksize of 1 cell
![2018-07-07_01 13 31](https://user-images.githubusercontent.com/13512001/42402402-310a1e94-8183-11e8-9933-dc89b8d94d90.png)
might also happen with other liquids, haven't tried yet
edit: consistent across other fluids as well
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by EmosewaPixel** [comment]
I think you should have also tried with other fluids. It cannot possibly be specific to air.

**Comment by gerb82** [comment]
tested, works on all fluids
