### ISSUE TITLE
blast furnaces spawning mobs inside of them

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#196]
as the name would suggest, both the electric blast furnace and the primitive one can spawn mobs inside of them. with the primitive one it is somewhat preventable as it doesn't need to be closed, but that is not the case with the electric one. it is probably also the case with other multiblocks that can fit mobs inside of them.
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by Archengius** [comment]
fixed
