### ISSUE TITLE
primitive blast furnaces accepting charcoal/coal on both slots

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#197]
the primitive blast furnace accepts coal/charcoal on both the slot designated for iron as well as the slot designated for actual fuel. but iron can only enter the slot designated for iron, so it ends up jamming any attempts of automation, and even messing with shiftclicking.
![2018-07-08_01 40 14](https://user-images.githubusercontent.com/13512001/42415227-17559abe-8250-11e8-98c1-9238051464b8.png)
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by Archengius** [comment]
Fuel can only be inputted into fuel slot, anything can be inputed into up slot. is is intended behavior. And you can automate it with timer, people did it even on 1.7.10.
