### ISSUE TITLE
machine designated slots weird behaviour

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#198]
kinda related to issue #197 , but i felt it was deserving of it's own issue, as it is somewhat different.
the following machines supposedly have designated slots for special things:
extruder - extruder shapes
bending machine - integrated circuit
assembling machine - integrated circuits
fluid solidifier (i think that's the name?) - molds
and the list goes on. however, all of these mentioned machines completely disregard the slots the items are inserted into. shiftclicking also inputs into the first empty slot, same goes for automation.
![2018-07-08_01 44 12](https://user-images.githubusercontent.com/13512001/42415246-a7393b90-8250-11e8-9b93-451c575f9a26.png)
![2018-07-08_01 44 17](https://user-images.githubusercontent.com/13512001/42415248-a8341394-8250-11e8-8887-2ffef4eedf41.png)
it feels kind of like a nitpick, but it also feels off that there are designated slots that are then ignored.
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by Archengius** [comment]
there are no "designed slots"

**Comment by Exidex** [comment]
maybe there should be?

**Comment by Archengius** [comment]
no

**Comment by Archengius** [comment]
there are no "machinee designated slots" - they are just slots with overlays, serving as visual tips for players. There won't be any restrictions what to put them, it's recipe-specific. And are not meant to automate machines like extruder with extruder shapes.
