### ISSUE TITLE
anvil costs possibly not registered correctly

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#199]
when you create an anvil, it costs 3 iron blocks and 4 iron ingots. which is 4464 milibuckets. in the fluid solidifier it is registered correctly.
however, putting this same iron anvil in an arc furnace, fluid extractor, etc, will only give 30 ingots/4320 mb
i'm not sure if it is intentional, but it seems weird considering those things are usually the exact amounts from what i've seen so far
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by Archengius** [comment]
fixed
