### ISSUE TITLE
iron nuggets

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#200]
gregtech community edition adds it's own version of iron nuggets, even though minecraft already has it's own version. not sure if it is intended behaviour, but it seems a bit weird to add something that is oredicted to something vanilla already has, without any special capabilities or real differences from the vanilla version.
gregtech version - latest commits as of the 5th of this month
forge version - 14.23.4.2726
crash report - N/A

**Comment by Archengius** [comment]
fixed
