### ISSUE TITLE
Surface rock in water being rendered incorrectly

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#202]
![2018-07-08_16 33 00](https://user-images.githubusercontent.com/34199560/42418143-dff05172-82cc-11e8-8b3c-7c67fd7f7bb3.png)
Mod list:
jei_1.12.2-4.11.0.202
gregtech-1.12.2-0.4.5.9
CodeChickenLib-1.12.2-3.2.0.345-universal
forge1.12.2-14.23.4.2705

**Comment by Archengius** [comment]
rare chunk loading-related issue, can't really think a fix for it

**Comment by Archengius** [comment]
will re-open in case if new details will be added.

**Comment by KrisBigK** [comment]
ways to reproduce:
1.find a surface rock and surround it with blocks
![2018-07-09_07 31 26](https://user-images.githubusercontent.com/34199560/42425088-21260b96-834a-11e8-82b4-fd6792ccf037.png)
2.fill it up with water (except the surface rock)
it should look like this
![2018-07-09_07 36 32](https://user-images.githubusercontent.com/34199560/42425132-d64d5862-834a-11e8-829a-cfaa0cbcc46d.png)
and if the top left block is removed, the water will be rendered, but in a weird way.
![2018-07-09_07 37 51](https://user-images.githubusercontent.com/34199560/42425151-1fa10f86-834b-11e8-8617-d4d274dbd3ca.png)
