### ISSUE TITLE
OrePrefix system does not allow other item types to be added

### ISSUE THREAD

**Issue by Bartz24** [GregTechCE/GregTech#207]
I'm working with TheEmosewaPixel on Gregic Additions, and we have encountered an issue.

We would like to add, for example, Curved Plates.

Since the OrePrefix is an enum, the types of items that can be used with different materials is limited to those only added by GregTech, and addons can't add any more.

Moving away from an enum system would fix this, but that would change a few things.

**Comment by Archengius** [comment]
use EnumHelper to add new values to enum.

**Comment by Bartz24** [comment]
oh thanks!

Looks like I've never needed to modify enums before, thanks for mentioning that!
