### ISSUE TITLE
blast furnace not working without sufficient max power

### ISSUE THREAD

**Issue by dotsofdarkness** [GregTechCE/GregTech#208]
the blast furnace wont work without having the max power equal or above the power required for the recipe not showing any errors indicating that you need to increase the max power for the recipe to work

![thing](https://user-images.githubusercontent.com/41033881/42487436-648ec6fc-8444-11e8-86ff-1e3960a658c4.gif)

**Comment by Archengius** [comment]
because it's not even a error?

**Comment by dotsofdarkness** [comment]
while not an error it still can be confusing for anyone that doent know about that mechanic and no feedback from the blast furnace gui sating that you need more max power
especially since youll need 2 lv energy input hatches when you start out to get the aluminium for better power and someone new wouldnt know this unless they were following a pre made guide saying you need 2 hatches to get the right power

**Comment by SuperCoder7979** [comment]
Having two hatches is a known feature and is implied, as it is taken from GT5u. If you haven't played GT5u, don't worry, we are working on a manual Soon(TM).
