### ISSUE TITLE
Pipe can't be placed as blocks

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#209]
The small steel/bronze pipes can't be placed.

Mod list:
jei_1.12.2-4.11.0.202
gregtech-1.12.2-0.4.5.9
CodeChickenLib-1.12.2-3.2.0.345-universal
forge1.12.2-14.23.4.2705

**Comment by EmosewaPixel** [comment]
They're not implemented yet. Does that look like a placeable pipe to you?

**Comment by KrisBigK** [comment]
I read the tooltip, but I don't think an artist is required in order to add a pipe block.

**Comment by EmosewaPixel** [comment]
Why would there be a non-functional pipe block? There's just no point.

**Comment by Archengius** [comment]
there are no pipes, these are just items used in crafting
