### ISSUE TITLE
Shovels don't accelerate mining gravel ores

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#210]
Mod list:
jei_1.12.2-4.11.0.202
gregtech-1.12.2-0.4.5.9
CodeChickenLib-1.12.2-3.2.0.345-universal
forge1.12.2-14.23.4.2705

**Comment by Rongmario** [comment]
Pickaxes mine them too, right? @KrisBigK

**Comment by KrisBigK** [comment]
So this is another bug. I can't find any speed differences between mining gravel with no tools and mining gravel ores with picks.

**Comment by Archengius** [comment]
fixed
