### ISSUE TITLE
Tools are held as regular items instead of as tools

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#212]
To put is simply,
Here's a Minecraft Pickaxe being held by a player
![image](https://user-images.githubusercontent.com/25333164/42528092-c15ad304-847a-11e8-8ebf-02cd329532cb.png)
And here's a GregTech Pickaxe being held by a player
![image](https://user-images.githubusercontent.com/25333164/42528118-cf0617f2-847a-11e8-9cd2-15147585cba3.png)

**Comment by Archengius** [comment]
fixed
