### ISSUE TITLE
chests shading

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#213]
the shading for the gregtech chests seems to be broken.
![2018-07-11_00 08 37](https://user-images.githubusercontent.com/13512001/42537942-0954d848-849f-11e8-8f85-706675a0a1d1.png)
gt version - latest commits as of the 8th of this month

**Comment by SuperCoder7979** [comment]
OpenGL error, greg had a similar issue and i'll speak to him about it

**Comment by Archengius** [comment]
it's not fucking related to it at all. don't comment things you don't know internally.

**Comment by Archengius** [comment]
partly fixed i guess
