### ISSUE TITLE
Rubber tree sapling has a weird size on ground

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#215]
A rubber tree sapling compared to a normal item
![2018-07-11_07 56 59](https://user-images.githubusercontent.com/34199560/42545126-7674f932-84e8-11e8-9888-c28450851a95.png)

**Comment by SuperCoder7979** [comment]
we can fix this once we have an artist :p

**Comment by Rongmario** [comment]
No, it's on purpose.
