### ISSUE TITLE
Add more torch-crafting recipes

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#217]
In GT5u, sticky resin(the thing you get out of the rubber tree and used to produce rubber) can be used to craft torches, so in GTCE, rubber should be able to craft torches. And, lignite coal should be able to craft torches, too.

**Comment by Rongmario** [comment]
GTCE is not a GT5U port, we do not need to copy every single thing from GT5U nor from any other versions, just FYI.

**Comment by Archengius** [comment]
implemented
