### ISSUE TITLE
Steam macerator outputs 1 crushed ore per ore block

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#218]
The output should be changed to 2 crushed ore per block. Otherwise it is almost worthless to craft.

**Comment by Ezoteric** [comment]
if put it like that, you save you hammer besides that you can skip steam machines altogether anyway :P

**Comment by Archengius** [comment]
fyi bronze macerator does't double ore
and it is not pretended to be used for ore processing
