### ISSUE TITLE
Charcoal block and lignite coal block can't be used as fuel

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#223]
Mod list:
jei_1.12.2-4.11.0.202
gregtech-1.12.2-0.4.5.9
CodeChickenLib-1.12.2-3.2.0.345-universal
industrialcraft-2-2.8.91-ex112
buildcraft-7.99.17
forge1.12.2-14.23.4.2705

**Comment by Archengius** [comment]
fixed
