### ISSUE TITLE
Pickaxes can accelerate mining gravel ores

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#226]

**Comment by Rongmario** [comment]
So is there a reason why this and https://github.com/GregTechCE/GregTech/issues/210 is separate issues? Just combine it into one, change the title?

**Comment by KrisBigK** [comment]
2 bugs in 1 issue might cause only 1 bug being fixed

**Comment by Archengius** [comment]
it's one bug, don't create duplicates
