### ISSUE TITLE
Weird cable recipes

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#227]
Red alloy cables have weird insulation recipes: there are some that use paper and others that use rubber. Putting cables in the unpacker returns rubber plates so this can be used to turn paper into rubber.

**Comment by Rongmario** [comment]
Will fix this along with the paper ring issue.

**Comment by Shattered2909** [comment]
Paper ring issue? You mean the pumps?

**Comment by EmosewaPixel** [comment]
This was fixed quite a while ago. #170
