### ISSUE TITLE
In JEI, input items are listed by quantity instead of the order in the recipe

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#228]
While adding recipes, I noticed that, for machines that have more than one input, in JEI, the input items are listed by quantity instead of the order of the inputs in the recipe.
 For example, here's an Assembler recipe I have:  `RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder().duration(120).EUt(8).inputs(GAMetaItems.GLASS_TUBE.getStackForm(), OreDictUnifier.get(OrePrefix.wireGtSingle, Materials.Copper, 2), new ItemStack(Items.PAPER, 2)).outputs(GAMetaItems.VACUUM_TUBE.getStackForm()).buildAndRegister();`
 And here's how it looks in JEI:
![image](https://user-images.githubusercontent.com/25333164/42776751-4bd34ed2-8938-11e8-90c0-e36aca48f5c2.png)
 
 Here's another, more noticeable example of a recipe in the Circuit Assembler, which acts the same as an assembler, but has 3 more slots:
`GARecipeMaps.CIRCUIT_ASSEMBLER_RECIPES.recipeBuilder().duration(400).EUt(9600).inputs(GAMetaItems.MULTILAYER_FIBER_BOARD.getStackForm(2),MetaItems.CIRCUIT_MASTER.getStackForm(3),GAMetaItems.SMD_DIODE.getStackForm(4),GAMetaItems.NOR.getStackForm(4),GAMetaItems.RAM.getStackForm(4),OreDictUnifier.get(OrePrefix.wireFine,Materials.NiobiumTitanium,6)).fluidInputs(material.getFluid(144 * multiplier)).outputs(GAMetaItems.CRYSTAL_COMPUTER.getStackForm()).buildAndRegister();`
![image](https://user-images.githubusercontent.com/25333164/42776870-a9533e82-8938-11e8-9784-244a752febaf.png)

 While they still work fine, certain recipes just look better when the items are in a particular order.

**Comment by Exidex** [comment]
I think putting recipes in order they were defined will only introduce confusion and it is better to leave it as is

**Comment by EmosewaPixel** [comment]
How? In my mind, this causes more confusion.

**Comment by Exidex** [comment]
Now think how users will see it without knowing what is in the scripts

**Comment by EmosewaPixel** [comment]
It just doesn't look good. It makes the most sense when all types of circuits have an order of the items. In GG5U in all circuit recipes the board was first, then the previous tier of that type of circuit and at the end was the fine wire. Because every tier of circuit takes a different amount of the items, this order can't be maintained.

**Comment by Archengius** [comment]
it's automatic item inputs sorting. intended behavior.
