### ISSUE TITLE
Machine Tooltips don't work properly in JEI

### ISSUE THREAD

**Issue by Zer0Lyfe** [GregTechCE/GregTech#23]
another bug not sure if known:
Machines in JEI doesn't show tool tips properly in JEI
you have to highlight the around the bottom or middle to get the tool tip but top of the box doesn't show a tooltip.

![2018-04-14_17 03 35](https://user-images.githubusercontent.com/28994351/38766829-79c58700-400a-11e8-970b-a37b0a036846.png)
![2018-04-14_17 03 37](https://user-images.githubusercontent.com/28994351/38766830-79faa958-400a-11e8-93be-838cba0f6210.png)

**Comment by Zer0Lyfe** [comment]
This actually happens to most if not all the machines in jei

**Comment by SuperCoder7979** [comment]
This is a known bug

**Comment by Exidex** [comment]
Fixed in cf27baa58c1ba8d9ef64b0f2be86ce968f12ecc4
