### ISSUE TITLE
Crafting failed

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#235]
When crafting items, I found that in some cases, the item crafted was disappeared and the materials used was returned. 
Steps to reproduce (using stone shovel as example):
1. Do like this (birch log can be replaced with something else)

![2018-07-20_14 24 39](https://user-images.githubusercontent.com/34199560/42986721-462c2514-8c29-11e8-822d-5f5a999e3627.png)

2.Press `R` (the show recipe key in JEI) and click `+`
3.throw the crafted shovel out (you should see the item that flies out is the log, not the shovel)
4.exit the crafting table GUI, the materials used when crafting the shovel is returned to your inventory.

Mod list:
gregtech-1.12.2-0.4.7.38
industrialcraft-2-2.8.91-ex112
buildcraft-7.99.17
jei_1.12.2-4.11.0.202
CodeChickenLib-1.12.2-3.2.0.345-universal
forge1.12.2-14.23.4.2705

**Comment by Agrax** [comment]
gregtech-1.12.2-0.4.7.38
industrialcraft-2-2.8.91-ex112

You are totally aware that those are absolutely incompatible and any issue will not be resolved as long as you are using these two mods together?

**Comment by Agrax** [comment]
gregtech-1.12.2-0.4.7.38
industrialcraft-2-2.8.91-ex112

U R aware that those two are incompatible?

**Comment by Archengius** [comment]
GT doesn't change anything related to crafting in general
I don't see anything related to GT here too
