### ISSUE TITLE
Rubber trees can generate in villages

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#236]
Seed: `-2194116220365028180`
x=1673, z=1178
![2018-07-20_14 47 16](https://user-images.githubusercontent.com/34199560/42988500-53f24092-8c2f-11e8-80c3-85bd76789db9.png)
x=2099, z=103
![2018-07-20_14 53 29](https://user-images.githubusercontent.com/34199560/42988503-56292d26-8c2f-11e8-8860-26c3d1861af0.png)

**Comment by TedKnudsen** [comment]
Is this actually a problem?

**Comment by KrisBigK** [comment]
Have you seen vanilla trees generating like that?

**Comment by pyure** [comment]
I see a lot of things in GT that I don't see in Vanilla.  I don't actually mind seeing trees that grow in the vegetable gardens.

**Comment by Ezoteric** [comment]
This should not happen no, just like the water spawn.

**Comment by Archengius** [comment]
and there is nothing can be done about that
