### ISSUE TITLE
Gregtech initial crash with ExtraCells

### ISSUE THREAD

**Issue by stopcraft** [GregTechCE/GregTech#250]
I'll upload full log until 2 hours

I'm setting my own custom server(based on FTB beyond 1.10.2)
I add Gregtech 1.10.2 and Extracells from AE2
Server make a huge amount of log and It repeat same several lines
(log file size over 40000kb)

**Comment by Rongmario** [comment]
GT 1.10.2 isn't supported anymore.

**Comment by EmosewaPixel** [comment]
Additionlly, this is GTCE, not GT5U.

**Comment by stopcraft** [comment]
I'm sorry but what's difference?

**Comment by Rongmario** [comment]
We've updated from a GT5U port from 1.10.2 to be GTCE (re-write) on 1.12.2
