### ISSUE TITLE
Advanced Thermal Centrifuge IV missing?

### ISSUE THREAD

**Issue by CelestialPhoenix** [GregTechCE/GregTech#251]
As per title, Advanced Thermal Centrifuge IV not visible in JEI, and using the sequential ID for that machine [<gregtech:machine:464>] throws some error in CraftTweaker.

![image](https://user-images.githubusercontent.com/9976065/43370121-4b1c48c0-9371-11e8-87de-af56c3249aab.png)

Extract from CT log
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Basic Thermal Centrifuge with name ct_shaped1807461570
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Advanced Thermal Centrifuge with name ct_shaped541571550
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Advanced Thermal Centrifuge II with name ct_shaped-944639134
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Advanced Thermal Centrifuge III with name ct_shaped1832086488
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for unnamed.name with name ct_shaped-1700840921

**Comment by Exidex** [comment]
There is only 4 tiers of Thermal Centrifuge. It is intended
