### ISSUE TITLE
Gas Turbines dont accept steam

### ISSUE THREAD

**Issue by Sebmaster777** [GregTechCE/GregTech#261]
The gas turbines dont accept steam from any source, be it pipes or cells

**Comment by pyure** [comment]
Do you mean steam turbines?

**Comment by EmosewaPixel** [comment]
You need to make sure GregTech steam in the default.

**Comment by Sebmaster777** [comment]
Yes the steam turbines, and what do you mean it needs to be by default?

**Comment by TedKnudsen** [comment]
Some mods register their own steam, and its been known to cause problems.  For instance, older versions of Thermal Foundation (or whichever CofH mod adds steam) are problematic.

In those cases, you can simply update the mods which fixes the problem.

You can also work around it by temporarily removing the mods, loading your world (which can be world-breaking) and then loading the mods back in.

**Comment by pyure** [comment]
Some mods register their own steam, and its been known to cause problems. For instance, older versions of Thermal Foundation (or whichever CofH mod adds steam) are problematic.

In those cases, you can simply update the mods which fixes the problem.

You can also work around it by temporarily removing the mods, loading your world (which can be world-breaking) and then loading the mods back in.

**Comment by Archengius** [comment]
fixed
