### ISSUE TITLE
OreDictUnifier ABCs 

### ISSUE THREAD

**Issue by Yoghurt4C** [GregTechCE/GregTech#264]
`get`, `getAll` and `getUnificated` follow the alphabet, which means that any mod from "a" to "g" has automatic priority over `gregtech` in unification which leads to some very unpleasant visuals
![image](https://user-images.githubusercontent.com/11313954/43995556-2bbee4f0-9db8-11e8-87e1-7123cab97fbd.png)

**Comment by EmosewaPixel** [comment]
Yeah, I think there should be some sort of prioritizer in the config.

**Comment by Archengius** [comment]
they don't follow any alphabet. They use item that was registered in ore dictionary first.

**Comment by codewarrior0** [comment]
Huh, I could have sworn that the line [`keys.sort(Comparator.comparing(a -> a.item.delegate.name().getResourceDomain()));`](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/unification/OreDictUnifier.java#L191) will order the items by mod name.

**Comment by Archengius** [comment]
implemented
