### ISSUE TITLE
Compact Machines compat (forge caps)

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#266]
I talked with Arche abt it like 2 months ago and i told him that i make an issue as soon as beta comes out. So now...

Apparently it should be easy enough, coz GTCE cables use forge caps and MM uses caps too.

Link where you can refer to:
https://github.com/thraaawn/CompactMachines/issues/342

So Arche... make it happen as quick as you feel comfortable. It's not a feature that has to be done for like yesterday :P Thanks in advance

**Comment by Archengius** [comment]
Quoting CM's author

> It makes no sense for me to add compatibility for all the other mods, when all the other mods could just make their mods compatible themselves very easily
