### ISSUE TITLE
Metatools issue

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#269]
Exactly everything can be harvested with everything. Mining gravel with mortar, mining wood with mortar, mining stone with mortar, mining ores with mortar. And the mortar doesn't loose durability, coz it's not a proper mining tool (there's no material native to be harvested by a mortar)

You can mine logs with shovels, machines with scoops, forestry hives with rolling pins. If you don't use a corresponding tool (pickaxe for stone, shovel for dirt) the tool doesn't loose any durability.

tools-mining-everything probably happened when you guys fixed GT-cant-mine-hoppers. It's just a wild guess

**Comment by Archengius** [comment]
fixed
