### ISSUE TITLE
GT Iron Ingot recipes frequently missing

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#271]
**GT**: gregtech-1.12.2-0.5.7.57.jar
**Other mods**: JEI, CCL
**Forge**: 2757

The recipes for some items (Iron Plates) are "frequently" missing.  Problem does not seem to be 100% reproducible: Happens on some instance loads, not on others. 

I've ruled out scripting and non-default configurations.

When things are working, there are JEI tabs for Crafting, Solidifier, Bender, Smelter, Cutting Saw, Extruder, Forge Hammer.  

When it fails, there is only a JEI tab for the Solidifier.

The Crafting recipes do not work when the JEI tab is missing (confirmed)

When it fails, it does not seem to globally affect other metals.  I tested around 15 other metals, and their plate recipes seem to be unaffected.

**Comment by Archengius** [comment]
fixed i guess?
