### ISSUE TITLE
Connecting GT Pipes With Fluids To Input Hatches Of Multiblocks Breaks The Hatches

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#273]
Here's a clip of the issue. As clips are only 30s long, you'll have to continue watching a bit more to see the full issue: https://clips.twitch.tv/PiliableBlitheWallabyRuleFive
 I think the title sums it up nicely. This only occurs with GT pipes.

**Comment by Archengius** [comment]
no longer actual
