### ISSUE TITLE
The Texture for breaking metal tanks gt is missing 

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#274]
Reported by infitech alpha testers.

gregtech-1.12.2-0.5.7.57.jar

![image](https://user-images.githubusercontent.com/8617528/44372166-bb65a400-a4b0-11e8-9b53-b4be7a6b21f3.png)

Breaking-tank particles show purple/black default texture particles.

https://github.com/pyure/infitech-prototype/issues/78

**Comment by Archengius** [comment]
fixed
