### ISSUE TITLE
Crash on GUI when try to select anything in inventory

### ISSUE THREAD

**Issue by Ezoteric** [GregTechCE/GregTech#28]
Example boilers, try to pick up coal to put it in the boiler results in insta crash.

Just build today with latest shit you have.
forge-1.12.2-14.23.2.2611.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
MCMultiPart-2.4.1.jar
jei_1.12.2-4.8.5.159.jar

[fml-client-latest.log](https://github.com/GregTechCE/GregTech/files/1935443/fml-client-latest.log)

**Comment by Exidex** [comment]
Should be fixed in ff11ed5493ab8f33b676b09b64f48be089e747a3
