### ISSUE TITLE
Placing a non-empty GT tank removes its filled-texture

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#281]
**GT-CE**: gregtech-1.12.2-0.5.7.65.jar

Placing a GT tank with fluid in it makes it lose its filled-texture.  Problem seems to be aesthetic-only, and it repairs itself once you put more fluid in it.

Identified by IT3 alpha testers.

https://github.com/pyure/infitech-prototype/issues/88

**Comment by EmosewaPixel** [comment]
...this issue has existed since the mod was put on CurseForge for the first time...

**Comment by Archengius** [comment]
fixed
