### ISSUE TITLE
[Suggestion] Coke oven

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#282]
As the title suggests, we could use an early-mid game charcoal/coke solution.

Charcoal pile has it's pros: not automatable and looks cool, if done correctly

But a coke oven also has it's pros: allows for automation and one can produce a shitty fuel byproduct, creosote (auto-forming mb just like the PBF would be cool, coz shitty multiblocks like a coke oven from Charcoal Pile mod already exist and noone likes the looks of it xD). TY in advance.

**Comment by EmosewaPixel** [comment]
I'm pretty sure they're already planning to add the Charcoal Pit at some point.

**Comment by Agrax** [comment]
Coke oven =/= charcoal pit, Cucksel :P Coke oven makes coke :D
