### ISSUE TITLE
Turbines Don't Display The Correct Stats

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#283]
The Turbines' tooltips, instead of displaying their stats related to power generation (such as efficiency, flow,...), display the regular tool stats.
![image](https://user-images.githubusercontent.com/25333164/44786994-204a8980-ab96-11e8-879a-8a2edb77b4b8.png)

**Comment by Archengius** [comment]
there is no flow in current turbine implementation
added efficiency to display tooltip
