### ISSUE TITLE
Potion Fluids Have Missing Localization

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#284]
![image](https://user-images.githubusercontent.com/25333164/44787112-859e7a80-ab96-11e8-9674-693de7caedbc.png)
Additionally, all the tiers of a potion have the exact same unlocalized name
![image](https://user-images.githubusercontent.com/25333164/44787127-8e8f4c00-ab96-11e8-92b3-541aa7d8f4e3.png)

**Comment by Archengius** [comment]
fixed
