### ISSUE TITLE
world loading causes java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Zer0Lyfe** [GregTechCE/GregTech#29]
Crash Log:
https://gist.github.com/Zer0Lyfe/746e26e7e0065c21f438dff8d65ab2aa
Latest Log:
https://gist.github.com/Zer0Lyfe/4ad771ba09fd15f66d8cd0869261e0a6

**Comment by SuperCoder7979** [comment]
Not our fault, it's galacticraft using the GT api improperly. It's looking for a class that doesn't exist in GTCE. https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/CompatibilityManager.java#L66-L82 this is the broken code.

**Comment by SuperCoder7979** [comment]
I'll add an issue to the galacticraft repo once the alpha comes out

**Comment by Zer0Lyfe** [comment]
OK thank you. Sorry I didn't read it properly.
