### ISSUE TITLE
Ultimate And Plasma Pipes are missing

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#290]
GregTech used to have Ultimate Pipes with a large fluid capacity and Plasma (Superconductor) Pipes with a large heat capacity. It seems that you forget about to add them.

**Comment by Archengius** [comment]
I'm not really sure these should exist. I'll reconsider their need when fusion reactor will be implemented.

**Comment by EmosewaPixel** [comment]
But what about Ultimate Pipes? ;-;
