### ISSUE TITLE
Language Translate

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#291]
Hi,
I'm playing this mod recently. But I'm from China. I don't want to see too much English in my game. So I want to translate it to Chinese. 

I translated some items' name, but I haven't seen them changed in my game. 

```sh
$ jar tf \[GT格雷科技\]gregtech-1.12.2-0.5.7.54.jar | grep "zh_CN.lang"
assets/gregtech/lang/zh_CN.lang
```

Did i have some errors in somewhere?

**Comment by Yoghurt4C** [comment]
lang filename needs to be lowercase

**Comment by Timozer** [comment]
Ok, it worked. Thanks.
