### ISSUE TITLE
Placed Chests Have Broken Shading Until Given A Block Update

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#295]
Here's a chest that was just placed.
![image](https://user-images.githubusercontent.com/25333164/44944307-aeac4e80-add4-11e8-8fef-1d12c3b32e0b.png)
And here's how it looks after a block is placed next to it.
![image](https://user-images.githubusercontent.com/25333164/44944310-c08df180-add4-11e8-8f62-d976d61c4287.png)
However, what's strange is that any chest placed at the same spot afterwards has correct shading. (also, this visual glitch happens when placing it)
![image](https://user-images.githubusercontent.com/25333164/44944323-e1564700-add4-11e8-97f0-a65e8a1dfd29.png)

**Comment by Archengius** [comment]
faxed
