### ISSUE TITLE
Pipe Transfer Rate Doesn't Properly Scale

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#297]
Every tier of pipe takes 2 times more resources than the last, yet it only transfers the amount the tiny one does*tier.
![image](https://user-images.githubusercontent.com/25333164/44944510-a35b2200-add8-11e8-869d-79e7c4c934a5.png)
![image](https://user-images.githubusercontent.com/25333164/44944511-a81fd600-add8-11e8-83d7-a840e63c2c43.png)
![image](https://user-images.githubusercontent.com/25333164/44944520-d2719380-add8-11e8-8184-4d91514b6300.png)
![image](https://user-images.githubusercontent.com/25333164/44944522-d6051a80-add8-11e8-867a-893df29dfeac.png)

**Comment by Archengius** [comment]
faxed
