### ISSUE TITLE
Vanilla Tile Entities Placed In The Place Of Meta Tile Entities Are Invisible

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#299]
As an example, in this block space we have a lathe
![image](https://user-images.githubusercontent.com/25333164/44947019-f3e97400-ae06-11e8-88ff-156167317b16.png)
When I place a vanilla Chest there it becomes invisible
![image](https://user-images.githubusercontent.com/25333164/44947025-095e9e00-ae07-11e8-94db-51aac5c615f8.png)
When I rejoin the world is becomes visible again.
![image](https://user-images.githubusercontent.com/25333164/44947033-1c716e00-ae07-11e8-8925-bdc42c6c71b9.png)

**Comment by Archengius** [comment]
faxed
