### ISSUE TITLE
[Suggestion] Chinese Translation

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#300]
Hi, 

I have made a Chinese translation. Although it is not 100% accurate, and not all of them are translated!
About 90% of it has been translated. Would you like to add it to your project?

**Comment by Rongmario** [comment]
Send a pull request and I will review it :)

**Comment by Timozer** [comment]
I have sent a pull request with an about 99% Chinese translation.

**Comment by Archengius** [comment]
fine
