### ISSUE TITLE
Players Can Get Stuck In Chests

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#307]
If you put a lower slab a block below a GT Chest, you can get inside it and suffocate.
![image](https://user-images.githubusercontent.com/25333164/45087281-9bb3ba00-b105-11e8-9053-bc5aa1326c5c.png)
![image](https://user-images.githubusercontent.com/25333164/45087287-9f474100-b105-11e8-904a-a0071a1c8ca4.png)

**Comment by Exidex** [comment]
Why though?

**Comment by Archengius** [comment]
does it work with vanilal chest?

**Comment by EmosewaPixel** [comment]
Nope
![image](https://user-images.githubusercontent.com/25333164/45114340-09370900-b14d-11e8-82b2-2c08d7226c0a.png)

**Comment by Archengius** [comment]
fixed
