### ISSUE TITLE
[Question] Surface rocks

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#310]
Hi, 
In `gregtech.cfg` file, I don't know the following sentences mean.

```
    # True to enable surface rocks indicating vein under them
    B:enableOreVeinSurfaceRocks=true
```

When I see these blocks, I will mine it vertically downward, but there is no ores.

**Comment by Rongmario** [comment]
There are sometimes false positives.

It also won't spawn directly underneath, there might be a few blocks displacement from the surface rock's x and z position.

**Comment by Archengius** [comment]
there aren't any false positives. Surface rocks generate if at least 0 block of ore exists in the chunk. It doesn't mean ore will spawn directly under surface rock, no. Just that it exists in chunk.
