### ISSUE TITLE
Twitch doesn't import ".worldgen_extracted" file properly

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#311]
As far as I can tell, the **".worldgen_extracted"** is a flag to prevent the regeneration of default worldgen.

Because the file doesn't import, packs are unable to ship custom worldgen without it simply getting destroyed.

After testing, our best guess is that it is (empty?) files beginning with "." which cause the issue.  Removing the "." does allow the file to import (but of course doesn't help prevent the destruction of the custom worldgen)

If confirmed, can we rename the file to remove the dot prefix?

**Comment by pyure** [comment]
I should also clarify: this is only tested with packs that are shipped via the **Create Custom Profile -> Import** process in the twitch app.  I do not know explicitly if it impacts packs installed traditionally via twitch.

**Comment by Rongmario** [comment]
Delete twitch
