### ISSUE TITLE
Question: Basic Steam Turbine doesn't work

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#317]
Hi,
The basic steam  turbine doesn't generate power. Do you know why?

![1](https://user-images.githubusercontent.com/35325451/45467705-7f41fe00-b753-11e8-877d-3f42cb8f8087.png)
![2](https://user-images.githubusercontent.com/35325451/45467708-81a45800-b753-11e8-9a5a-bfb7b2810082.png)
![3](https://user-images.githubusercontent.com/35325451/45467709-82d58500-b753-11e8-8555-f913bc224a2f.png)

**Comment by CrossVas** [comment]
Because Steam Turbine accept only GT steam

**Comment by Timozer** [comment]
No. They are all GT machines. And the pipe is too.

**Comment by Yoghurt4C** [comment]
gtce version?

**Comment by Timozer** [comment]
Yes.

**Comment by Archengius** [comment]
was fixed in recent versions. update GTCE.
