### ISSUE TITLE
Chillies give permanent nausea

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#318]
While the food items are hidden, I wanted to see how implemented they were. After eating a Chili Pepper, I got nausea for a few seconds, but once it reached 0, instead of disappearing, it just stays there as a permanent thing until I die. (it doesn't do anything though, since it's at 0, it's just being displayed)
![image](https://user-images.githubusercontent.com/25333164/45589752-aa7f4580-b92b-11e8-9277-3e50058ca964.png)

**Comment by Rongmario** [comment]
Thought we removed foods?

**Comment by EmosewaPixel** [comment]
No, they're just hidden.
