### ISSUE TITLE
Adding gameplay around explosions/ wire burns

### ISSUE THREAD

**Issue by richardhendricks** [GregTechCE/GregTech#32]
As a way to help ease new players into GT, I suggest adding some more gameplay around explosions vs the insta-boom we have now in GT5U.

This has a couple of parts
* Machines that are being stressed will emit sound/particles/flash red?
* Problems now add stress to a machine
  * ie raining is +1, next to water is +2, next to fire +4, for each difference in tier between supplied voltage and machine voltage +(tier difference squared)
  * For real evil, give Infernal Mobs a tag that gives stress to nearby machines
* LV tier machines are maxStress=4, which gives ~4s warning from rain or overvoltage with MV
* Max stress level is per tier ?
* When no stress is applied to a machine, stress level drops 

Similar mechanic would be nice for wires, with overvoltage/overamperage causing buzzing/particles/red flashing

This would introduce players gradually to GT explosion mechanics, with an opportunity to fix an issue before it causes an explosion.

**Comment by Archengius** [comment]
neither rain nor water doesn't cause machines to explode anymore anyway.
Explosion on overvoltage is thing that player really deserves when he don't control what machines receive.

**Comment by richardhendricks** [comment]
So rainbooms are gone?  That makes me sad.

Voltbooms aren't gone in this case - just slowed down a little.

**Comment by Archengius** [comment]
closed for now

**Comment by Exidex** [comment]
I'd leave it open
