### ISSUE TITLE
[Suggestion] Sifter's sorting

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#320]
Can the sifter's outputs get sorted? Now they are scattered a bit. I liked how you got the sorting: exquisite-> Flawless-> normal -> flawed-> chipped-> dust. In the JEI/NEI, i mean.

Another thing abt sifter: is coal output nerfed that much on purpose? From up to 5 coal and one dust to just one coal and one dust. That's just a question, not a suggestion.

**Comment by Archengius** [comment]
yeah, that can be the case in JEI specifically i guess.
