### ISSUE TITLE
gregtech generation bypass bedrock sometimes

### ISSUE THREAD

**Issue by Wettix** [GregTechCE/GregTech#322]
basalt, marble, black granite and red granite bypass bedrock with basic generation preset of the mod
![2018-09-18_15 56 35](https://user-images.githubusercontent.com/43379174/45693144-bdc52780-bb5c-11e8-9200-adad650f8a61.png)
![2018-09-18_15 55 22](https://user-images.githubusercontent.com/43379174/45693218-e51bf480-bb5c-11e8-8927-e1aaaa4de72f.png)
![2018-09-18_15 56 48](https://user-images.githubusercontent.com/43379174/45693158-c1f14500-bb5c-11e8-98e7-ebb7a5dc8096.png)
![2018-09-18_15 56 53](https://user-images.githubusercontent.com/43379174/45693170-c87fbc80-bb5c-11e8-8aed-e5c3f9d53235.png)

And extremely rarely also ore generation
![2018-09-18_15 42 38](https://user-images.githubusercontent.com/43379174/45693267-ffee6900-bb5c-11e8-95a8-41c81d2eebc6.png)
![2018-09-18_16 05 21](https://user-images.githubusercontent.com/43379174/45693280-067ce080-bb5d-11e8-8da8-108e4c2d4425.png)
in this case we can't break bedrock ore  so not really boring

And last, i have a issue with basic preset of oil generation don't spawn any oil sphere just 2 or 3 oil source when the radius in the config is not the same number (basic is "radius": [4, 6] for heavy oil) if i change fort "radius": [5, 5] i have oil sphere like that should be.
and that's where I saw that the oil could also be passed through if we set radius too high (like 12 - 12)
![2018-09-18_16 24 10](https://user-images.githubusercontent.com/43379174/45694323-5197f300-bb5f-11e8-986a-4db871a5b06b.png)
![2018-09-18_16 24 15](https://user-images.githubusercontent.com/43379174/45694330-578dd400-bb5f-11e8-853f-8a91875cd29b.png)

**Comment by Rongmario** [comment]
Ore generation with bedrock is done on purpose. But not other stones and oil, so that'd need to be fixed.

If you want different generation of oil, you can change it to your own liking. But default is default, won't be changed.

**Comment by Wettix** [comment]
oh ok I did not know about the generation of ores

for oil generation of course, I just wanted to share the fact that on my side with the basic presets she was bizarrely generated as if it was bug ^^

**Comment by Rongmario** [comment]
No problem, thank you. We'll come up with a fix.
