### ISSUE TITLE
Issue with Bauble Integration?

### ISSUE THREAD

**Issue by Blaster5426** [GregTechCE/GregTech#323]
While doing some pack testing, I found an issue with what I believe to be your mod (although the report says otherwise). Crash report: https://pastebin.com/3tdiRyV7. From what I could tell in testing, it was an issue with Greg Tech overriding mods like Embers Rekindled, Dark Utilities and Draconic Evolution's integration with the Baubles API, potentially due to some Baubles found in Greg Tech?

**Comment by Rongmario** [comment]
Not a GT issue

**Comment by Blaster5426** [comment]
I did, all are using the latest versions I could find on their main pages. Can confirm they (on my end) work seperately, and Embers and Draconic work together (took out Dark Utilities anyway), but when GT was added in, it wouldn't even get to the load screen. Unless there's a secret version of Baubles and/ or GT I'm missing, everything's up to date

**Comment by Exidex** [comment]
GTCE doesn't have any baubles integration. There is no mention of GT in stacktrace and you have a lot of other mods in crash log. Please narrow the crash down to GTCE + 1-2 other mods or I'll close the issue as non GT related
