### ISSUE TITLE
Large Boiler Fluid Fuel Consumption

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#327]
Whoops, entered too early.

Pack: Gregblock 1.0.0

I didn't catch the exact time when it used the 200mb of light fuel for the second process (for 400 mb total), but the tank was already showing in excess of 6k buckets of steam. That means in a large boiler (assuming there's a 52% efficiency of steam to EU), 200mb of light fuel produced around 3M worth of steam in the boiler. Not sure if these items are correct.

![image](https://user-images.githubusercontent.com/26587049/45989481-eb710b80-c049-11e8-902f-a5ccc6ebd470.png)

![image](https://user-images.githubusercontent.com/26587049/45989494-f75ccd80-c049-11e8-868b-402a3868616c.png)

**Comment by EmosewaPixel** [comment]
The issue is that diesel fuels in it last 8 times longer instead of 0.25 times.
