### ISSUE TITLE
[Suggestion] Block rotation border guidelines

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#331]
We’ve already talked abt this on Discord, but i think it’s good to put it in a visible place, so you have smth to reference to. So, yeah. Rotating machines sucks atm. BADLY.

**Comment by OvermindDL1** [comment]
> So, yeah. Rotating machines sucks atm.

Doesn't it work here like it does in GT6?  Rotating in GT6 is blissfully easy...

**Comment by OvermindDL1** [comment]
> gt6 ain’t no direction to follow imho

What's bad about how GT6 does it?  It shows a grid to right-click in on hover of an appropriate block with an X marking which side Front is currently facing and all...

**Comment by OvermindDL1** [comment]
> it's just an unhealthy obsession, don't try arguing

Oh I'm just curious if he has a better interface idea!  If he does I'd love to hear it so I could implement it in GT6.  :-)

**Comment by Agrax** [comment]
I just don’t enjoy GT6 as a whole idea. GT5, GT5u and then GTCE. GT6 is not a kind of thing i would ever enjoy. That’s all

**Comment by OvermindDL1** [comment]
> GT6 is not a kind of thing i would ever enjoy

Hmm, that's still not what I asked.  There are a lot of mods I don't like that still have some good ideas, so why would someone discount and not use/borrow those ideas?

Again though, what do you not like about GT6's selection method and how should it be done better?

> I just don’t enjoy GT6 as a whole idea.

Unsure what the 'whole idea' would be, as well as this has nothing to do with this issue itself, so why do you mention this?

**Comment by SuperCoder7979** [comment]
@Agrax just because you don't enjoy it doesn't mean that we can't learn valuable lessons from it. Greg has created new mechanics that work well, so why don't we use them to make GTCE better? just because you think something is bad doesn't mean we can't learn things from it.

**Comment by GregoriusT** [comment]
Okay I cant help but to ask, what is the difference between how I do rotation in GT5 and how I do rotation in GT6? Except for the overlay finally stating which direction the Block faces there is no difference!

**Comment by pyure** [comment]
IC2 Wrench Rotation -> Awful
GT5 Wrench Rotation -> Excellent
GT6 Wrench Rotation -> No idea.  Probably excellent as described above by Greg et al
GT-CE Wrench Rotation -> Not bad.  For purely UI/UX purposes it needs overlay to improve.  Should never open GUI ( Correct me if I'm wrong but I believe it opens gui if you try to rotate into the existing-direction)

**Comment by Agrax** [comment]
So much shit is beeing spilled on me o.O I was simply referring to Yoghurt's comment. But if you insist on me answering to "how can we improve it" then: I like GT5's overlay. I've never played GT6, watched some vids, heard some opinions and to me it seems way overdone, but, uh well... If the overlay is better, it's better. Idc. I want GTCE team to improve smth, not GT6 team to change anything (if i don't like tornadoes, i don't move to Murica. Hence, i don't play GT6). Maybe Exidex has another solution

**Comment by OvermindDL1** [comment]
> smth

If you want to see improved smithing you really should try out GT6, it's whole cauldren system is awesome.  :-)

> So much shit is beeing spilled on me o.O I was simply referring to Yoghurt's comment.

Actually I think people were referencing this:

> A) no, it doesn’t
> B) gt6 ain’t no direction to follow imho

In answer to this question:

> Doesn't it work here like it does in GT6? Rotating in GT6 is blissfully easy...

Which spoke nothing about the gameplay and only the rotating a block capabilities.  Thus your answers of `no, it doesn't` seems to be a lie at this point considering multiple others have come in stating that GT6's rotation 'is' still like GT5/GTCE's, and your answer of `gt6 ain’t no direction to follow imho` seems to be precisely the rotation method that is already being used, so it is already being followed (or rather GTCE and GT6 are both based on Greg's original form in GT5), so your `B` answer doesn't seem to make sense in regards to rotation either?  I think the discrepancy comes from the fact that your answers do not seem to follow from the questions posed but rather seem to be talking about something that is not about this issue #331 itself?  If not that then I'm confused as the answers you've given do not seem to make much sense to me, but I may be missing something (though I'd hope I'm not considering I've re-read the thread a number of times at this point  >.>).

**Comment by Archengius** [comment]
already implemented
