### ISSUE TITLE
Rutile And Almandine Dupe Bug

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#333]
The bug mainly comes from the fact you can hammer regular rutile and almandine into their exquisite versions
![image](https://user-images.githubusercontent.com/25333164/46222700-79523c80-c351-11e8-8ce7-1cb85b728b8e.png)
![image](https://user-images.githubusercontent.com/25333164/46222704-7eaf8700-c351-11e8-8d4a-7c8d234ca637.png)
![image](https://user-images.githubusercontent.com/25333164/46222716-82dba480-c351-11e8-9a91-e95c2b6309af.png)

**Comment by Rongmario** [comment]
Already reported.

**Comment by Exidex** [comment]
not sure what I was fixing in that commit :man_facepalming:
