### ISSUE TITLE
[Suggestion] "UBC - Reworked and Fixed" Compatiblity

### ISSUE THREAD

**Issue by DbpGaming** [GregTechCE/GregTech#334]
gregtech community edition oreveins spawn way less frequently with UBC in fact they barely spawn at all the only spawn in the vanilla stones, which after UBC is basically just bedrock, granite, diorite, and andesite, (and maybe sandstone?) this is obviously an issue for anyone using both mods, it would be nice if we could have gregtech ore types for all of the UBC stones but just having the regular stone ores spawn in the UBC stones would be a big step over this, also believe the GTCE stonetypes don't spawn at all either

**Comment by MrProton657** [comment]
Hi @Rongmario I'm here to ask you how the prosess of adding the compatibility is. Because I started a new world and I saw no gregtech ores there. So I'm really waiting for the compatibility update and I'll be very grateful to you if it would came out fast. Because I cant play without any gregtech ores. So thanks to you and your team for GTCE and happy christmas holidays.

MrProton

**Comment by MrProton657** [comment]
Thanks for reply.
Sorry for taging any people in the project.
I contacted the UBC reworked and fixed developer and I'm just waiting for his reply.
I hope he'll make the improved textures and add them to his future version.
I still have one question: which config option do I have do edit?
So still thank you guys and I hope we get a way to fix that together in the future.
 Greetings,
MrProton

**Comment by MrProton657** [comment]
So which config option in which config file do I have to edit to enable the stone variants to generate with UBC?

**Comment by MrProton657** [comment]
Guys I need help quick!

**Comment by MrProton657** [comment]
So @Rongmario which config option in which config file do I have to edit to enable the stone variants to generate with UBC?

**Comment by Rongmario** [comment]
@MrProton657 check out the wiki page on github.

**Comment by MrProton657** [comment]
I don't really understand what I have to edit, the wiki doesn't helps me out at all. Maybe I'm just too dumb but could you please sent me here the text I need to insert and please explain me where I need to put it in. So please work on the CTStoneTypesRegister too, so it would be a lot easier to fix this bug. Thanks for your help and hopeful future help.

**Comment by Archengius** [comment]
in hold till 1.13

**Comment by Aang23** [comment]
I just tried fixing that in UBC, no luck. 
But that's the only mod having that kind of issues, and UBC handles ores after standard world gen has happened.
No issue when using things like COFHWorld to generates your ores.
Do you know what causes that bug exactly, or any idea ? 

(I'm UBC's dev)

**Comment by Rongmario** [comment]
There are no bugs to fix, if you don't want GT ores to generate; simply remove the json files in gregtech/worldgen

**Comment by Archengius** [comment]
now GT ores generate in UBC stones.
Background compatibility will come to CT in 1.13.
I see no point in keeping this open

**Comment by MrProton657** [comment]
Version of What 1.13? Minecraft? or GTCE?

**Comment by xly2000** [comment]
> 版本1.13是什么？我的世界？还是GTCE？

191 fix

**Comment by Aang23** [comment]
Well, the ore system in UBC was entirely (and is still being) rewritten in 1.13...

**Comment by bookerthegeek** [comment]
I just wish I could have a working example of the config with all the optional arguments so I could make it work for not only UBC but other mods that add stone/sand into the game.
