### ISSUE TITLE
Shaped Saw + Log -> 4 Planks fails if saw damaged

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#337]
Works fine with full-durability saw but not on subsequent attempts.

**gregtech-1.12.2-0.5.9.88.jar** but I don't see recent commits that would address it.

**Comment by EmosewaPixel** [comment]
That does not happen for me.

**Comment by Rongmario** [comment]
Doesn't happen to me.

**Comment by pyure** [comment]
This might be a non-issue.  It has something to do with differing nbt tags.

Guys would it be worthwhile to switch out the recipe for one that ignores nbt and/or uses ore:craftingToolSaw?

**Comment by EmosewaPixel** [comment]
Wait, so are you talking about the recipes in the config or custom CT recipes?

**Comment by Rongmario** [comment]
Please clarify as this maybe linked to https://github.com/GregTechCE/GregTech/issues/335

**Comment by pyure** [comment]
Pixel: Hold on, let me verify :|

**Comment by pyure** [comment]
# Whether to nerf wood crafting to 2 planks from 1 log. Default is false.
        B:nerfWoodCrafting=true

I assume you're referring to this Pixel when you say config.  I have nerfing enabled.  Therefore the 4-plank recipe should only be valid with a saw.  Which it is except for this one saw I have which is missing some nbt tags.

This is my testing world so its possible that the "broken" saw was "cheated" in in some fashion (or I took some other action that broke the nbt), but that shouldn't invalidate the recipe.

I've verified that I don't have any CT scripts involved (which was a good point since at one point I most certainly did have my own CT saw recipes)

**Comment by pyure** [comment]
fwiw:
Good:
<gregtech:meta_tool:5>.withTag({RandomKey: -7052205409467361346 as long, CreatorMost: -4851740336880006341 as long, CraftingComponents: [{id: "gregtech:meta_item_2", Count: 1 as byte, Damage: 7017 as short}, {id: "minecraft:stick", Count: 1 as byte, Damage: 0 as short}], "GT.ToolStats": {PrimaryMaterial: "cobalt", HandleMaterial: "wood", Damage: 560}, CreatorLeast: -8661889087610143795 as long})

Bad:
<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {PrimaryMaterial: "cobalt", HandleMaterial: "wood", Damage: 620}})

**Comment by Exidex** [comment]
where are `RandomKey`, `CreatorMost`, `CraftingComponents` tags from?

**Comment by Exidex** [comment]
what is vanilla GT?

**Comment by EmosewaPixel** [comment]
Those 3 NBT tags

**Comment by Archengius** [comment]
works fine for me on clear GTCE instance.
