### ISSUE TITLE
Slot Order Takes Priority Over Dedicated Fluid Slots

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#338]
So, let's say a machine recipe takes 2 fluids, one's generated fast enough for the recipe and the other one isn't. You put the one that's generated fast enough in the second slot and the one that isn't in the first. When the first slot is empty, the fluid that is generated fast enough goes to it, even though its slot isn't full.

 For example, here I have my ethylene recipe that uses a bucket of ethanol and a bucket of sulfuric acid:
![image](https://user-images.githubusercontent.com/25333164/46250392-6c5d4800-c43a-11e8-980f-aa32400b9897.png)
If I put one bucket of ethanol in the first slot, but I constantly supply it with sulfuric acid, once the recipe starts, the first slot will also start filling up with sulfuric acid:
![image](https://user-images.githubusercontent.com/25333164/46250424-e68dcc80-c43a-11e8-88ca-610d4b5fd13e.png)
Of course, this can easily be avoided by putting them in an order by production speed, but if let's say all the ingredients are produced at a different time, a mess could occur.

**Comment by Vyraal1** [comment]
For what it's worth on this one, the 3rd slot does NOT fill up so for this specific example for some reason: 
![image](https://user-images.githubusercontent.com/26587049/46307497-12b56480-c585-11e8-81ed-debb061d7c67.png)

It seems to be okay. However if something starts to require 3 fluids in a chemical reactor, then a mess will probably occur.

**Comment by Archengius** [comment]
fixed
