### ISSUE TITLE
Battery Buffers not filling up 100%

### ISSUE THREAD

**Issue by ProxyPlayerHD** [GregTechCE/GregTech#339]
I already know why this is a thing. it has to do with the EU Packages, aka Voltages.

for example, i have a LV Battery Buffer with 16 Lithium Batteries in it. none of them will ever be able to fill up to 100 kEU limit because you cannot devide 100,000 by 32. plus battery buffers cannot split the Energy up onto multiple batteries. so when you have 2 small batteries each with 16 EU free they will never fill up even though it can fit the LV 32 EU.

for my LV Buffer this means that out of 1.6 MEU there are only 1.599 MEU full. missing around 280 EU. for LV that is not much of a problem, but when having higher voltages it could mean a lot of wasted energy capacity.

also please start using stuff like kEU (not KEU, kilo is a lowercase k), MEU, etc. or atleast use dots. no-one wants to look at so many zeros. 100000 EU -> 100 kEU or 100.000 EU or both.

lastly, just a question that i didn't saw anywhere. where are the Tier 4 Batteries? i can find any other Tier, from 1 to 8. just 4 is missing. (P.S.: there should be some better documentation, i have for example no idea how to get air, there isn't a machine or Recipe in JEI that seems to create air)

**Comment by Agrax** [comment]
1) you need to make a ct script yourself to grt air
2) lapo crystals (t4) aren’t a thing yet

**Comment by ProxyPlayerHD** [comment]
alright...? and where is the documentation for CT support?

and what about the batteries?

**Comment by SuperCoder7979** [comment]
Tier 4 batteries have not been added yet. As for CT Support, it has not been written down in the wiki yet but if you come to our discord, we can help you with whatever problems you are having :)

**Comment by Agrax** [comment]
https://github.com/NanamiArihara/CraftTweaker-Documentation/blob/master/docs/Mods/GregTechCE/Material.md

**Comment by ProxyPlayerHD** [comment]
well my current sollution was to cheat in a Creative drum full of Air, since i assume it is an Infinite resource anyways

also this still doesn't say anything about the Buffer thing.

**Comment by Archengius** [comment]
use screwdriver to configure fluid output slot filter.
can't see any other issue there.

**Comment by ProxyPlayerHD** [comment]
but the batteries not being able to fill up completely and wasting some capacities?
