### ISSUE TITLE
battery buffers comparator support

### ISSUE THREAD

**Issue by gerb82** [GregTechCE/GregTech#340]
this is a feature suggestion:
for the sake of giving people more control over their setups: people already probably do some sort of automation using redstone.
the idea is to let people read the % of power currently inside of a battery buffer using a comparator.
i know i can already think of one use-case for that involving nuclearcraft, which can make gtce's eu (at least in the modpack gregblock), to shut off the reactor and save on precious fuel when the battery buffer it is filling is full.
it's just a random feature suggestion, but i feel like it can probably be useful for some other things too (shutting off/turning on setups when there's enough power, etc)

**Comment by Agrax** [comment]
There will be a comparator-like machine cover. One for reading fluids and one for reading energy(/rnergy flow) values

**Comment by gerb82** [comment]
ooooooooooh cool
thanks for the heads up on that. looking forward to that update

**Comment by Agrax** [comment]
Oh, and it will emit redstone based on the readings

**Comment by Archengius** [comment]
all machines output % of energy now
