### ISSUE TITLE
Chad + Stone Slabs -> Paper consumes slabs

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#341]
Adding just for tracking; Exidex is already aware of the issue.

**Comment by Exidex** [comment]
I think small chance to loose a slab would make more sense

**Comment by EmosewaPixel** [comment]
Wouldn't that require making a custom type of crafting recipe?

**Comment by Rongmario** [comment]
Its not hard to make a custom type of crafting recipe if you want it to have %chance of not consuming it

**Comment by pyure** [comment]
I'm fine with the small-chance thing in principal.  From a user experience it might be less fun to be able to predict how many recipe operations were going to execute.

That said, I want the %consumption for some other projects anyway if you elect to go ahead :)

**Comment by Rongmario** [comment]
@pyure that might be a bit hard with anything but a mod. You can't do % based ItemStack reuse in the crafting table easily with CT.

**Comment by TedKnudsen** [comment]
Oh.  CT needs to support it natively in order for GT to have a zenmethod for it?  That's a deal-breaker then.

(BTW: fwiw I feel like you could do % reuse in CT via one of IItemStack's transform handlers.  RNG is possible via a clock cheat too.)

**Comment by pyure** [comment]
Brilliant thinking, Ted Knudsen.

**Comment by Rongmario** [comment]
Add a RNG clock to a frozen recipe registered? Doesn't make sense to me.
