### ISSUE TITLE
Cables/Pipes stop working when placed in a 2x2 pattern

### ISSUE THREAD

**Issue by xSkewer** [GregTechCE/GregTech#342]
Pack: GregBlock v1.0.2*
Mod Version: 0.5.9.88
*still occurs outside of GregBlock in a test pack on forge-14.23.4.2765

Cables/Pipes immediately stop working when placed in a pattern like this:
![image](https://user-images.githubusercontent.com/43712386/46263781-acc3d100-c4e1-11e8-9032-0c32d3db9d13.png)
This happens with any square/rectangle shaped pattern.
Anything inside their internal buffer seems to be lost and every single connected pipe/cable breaks individually, meaning they all have to be broken and replaced to fix the issue. Nothing I found said that this is a feature.

Here's a video of the bug:
https://www.youtube.com/watch?v=uqCs51h5_Z4

**Comment by pyure** [comment]
Confirmed with pipes.  Really nasty too: cannot restart the game to fix interconnected pipes.

**Comment by pyure** [comment]
If it contributes anything: The "broken" pipes do not have a TOP tank indicator anymore.
