### ISSUE TITLE
Add a Programming Circuit for Carbon Monoxide vs Carbon Dioxide Chemical Reactor

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#343]
![image](https://user-images.githubusercontent.com/26587049/46291534-c7875b80-c55c-11e8-9d20-a759d5b7fb81.png)

Charcoal / Coal / Charcoal Dust / Coal Dust can be used with 1,000mB of Oxygen to make Carbon monoxide or Carbon Dioxide with 2.000mB, would it be possible to add in a programming circuit to differentiate the recipe modes rather than trying to control chemical amounts?

GTCE Version: 0.5.9.88

**Comment by EmosewaPixel** [comment]
That's from Gregic Additions...

**Comment by Exidex** [comment]
Might consider making recipes require namespace + name like forge/vanilla does it
