### ISSUE TITLE
[Request] Re-add Gem versions of Lapis and remove those of Glass

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#350]
For the Lapotron Crystals in GA, I would need the different versions of Lapis gems. On the other hand, Glass gems are pointless.

**Comment by Rongmario** [comment]
You could generate it yourself?

**Comment by EmosewaPixel** [comment]
But it's Lapis, it makes sense for it to have different versions, as Sodalite and Lazurite.

**Comment by Rongmario** [comment]
Could've provided that reason in the OP :p

**Comment by Archengius** [comment]
added
