### ISSUE TITLE
use plates to cover pipes and prevent connection

### ISSUE THREAD

**Issue by demethan** [GregTechCE/GregTech#352]
Hi, 

You fill big shoes taking this project over.  I say Bravo to you good sir/madame.  

Is there a way that is implemented to cover pipes to prevent connections.  Either with a wrench or plates?

if its to come, I understand.

**Comment by pyure** [comment]
Covers will probably arrive at some point.  But for now I'm given to understand you can separate your infrastructure by spraypainting it different colors.  Red pipes will not connect to Blue pipes, etc.

**Comment by Archengius** [comment]
Covers will arrive, but only functional ones.
Pipes and cables support ForgeMultiPart, use covers from it

**Comment by demethan** [comment]
thanks.
