### ISSUE TITLE
Pipes connection between different sizes. 

### ISSUE THREAD

**Issue by demethan** [GregTechCE/GregTech#353]
Should pipes interconnect between size and types?

**Comment by pyure** [comment]
Its a known issue that they do not.

**Comment by demethan** [comment]
Ok, where is that information that I should have known.

**Comment by pyure** [comment]
Sorry, I wasn't clear: Its known by the devs that they don't connect.  I'm not sure whether they plan to change it.

**Comment by Agrax** [comment]
They plan to make pipes connect between different sizes, but not between different materials

**Comment by Archengius** [comment]
no, unless somebody thinks cool linear and performance friendly algorithm of distributing fluids in such networks
