### ISSUE TITLE
Crash when FMP item hovers over a GT pipe

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#357]
A tester reports that he tried to hover an FMP "cover" over a GT pipe and the game crashes.  Only found to occur with GT blocks.

GT: gregtech-1.12.2-0.5.10.93.jar
https://pastebin.com/3eN1pWTr

I have no idea if this is a bug on GT's side or FMP; I'll bounce the issue to them as necessary.

**Comment by EmosewaPixel** [comment]
This is the issue with FMP we talked about a month ago. It's on FMP's side and it hasn't been fixed for a month.
