### ISSUE TITLE
ENet - Cables not being destroyed when given too many amps

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#359]
2x HV Turbo Diesel Generators are being fed via an 1x Aluminium Cable (rated at EV, 1amp) into an HV Thermal Centrifuge that is consuming two amps of HV. The 1x aluminium cables did not burn up despite having more than 2 amps flow through it.

![image](https://user-images.githubusercontent.com/26587049/46572622-2f6fe480-c957-11e8-95b0-6d0d4f170236.png)

Tested it again with the output of a max battery charger and 3 generators, aluminium cable is still unaffected.

![image](https://user-images.githubusercontent.com/26587049/46572645-a0170100-c957-11e8-833d-bbb9503a7b76.png)

Pack is GregBlock, version 1.1.3

**Comment by SuperCoder7979** [comment]
known bug, the way amps works is dependant on the amount the generator outputs, not the total amount of generators. arch is working on this issue.
