### ISSUE TITLE
Steam Turbine generates massive lag

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#362]
Arch, this is coming from my testers.  If you want, I'm willing to throw together a really vanilla GT environment and try to reproduce it myself.

Apparently the turbine drops users' FPS from 120 to 15.  I don't know if its the turbine or perhaps the e-net itself.

**Forge**: 2749
**GT**: gregtech-1.12.2-0.5.10.93.jar

https://github.com/pyure/infitech-prototype/issues/169

**Comment by pyure** [comment]
Arch, as discussed, you requested either profiling or clean-slate reproduction.  I'm giving the latter.
1) Place a turbine.  
2) Place an (empty) battery buffer to receive power from the turbine
3) FPS should hold steady at this point (120 with vsync off on my machine)
4) Fill turbine with steam cells.  FPS will drop momentarily until the turbine's buffer is filled.
5) Place a battery into the buffer
6) FPS drops significantly (to ~65 for me) and returns to 120 once the turbine runs out of steam

My results in a clean world aren't as drastic as the tester's in a real world, but still significant.

If its helpful, I can tell you that a second turbine/buffer setup does not impact it further.

**Comment by Rongmario** [comment]
It'll be nice to profile it too. But I'll try reproduce this later.

**Comment by Archengius** [comment]
can't seem to reproduce in dev - FPS holds in 110-120

**Comment by pyure** [comment]
Arch, can you humor me and remove FPS limit and see if you get a drop?  Its possible your graphics card is just way better than mine (although Rong's is admittedly still a powerful card)
