### ISSUE TITLE
Diesel -> Cetane Boosted Diesel Values are an energy loss

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#366]
GTCE Version 0.5.10.93

Diesel makes about 96k EU per 200mb. 

![image](https://user-images.githubusercontent.com/26587049/46638388-a90dfb00-cb2e-11e8-9758-547195be4ec4.png)

Cetane Boosted Diesel makes about 144k EU per 200mb.
![image](https://user-images.githubusercontent.com/26587049/46638414-c5119c80-cb2e-11e8-9d3c-9398a535219a.png)

However the production of Cetane requires a full bucket of diesel and only output 500 mb of Cetane
![image](https://user-images.githubusercontent.com/26587049/46638425-dbb7f380-cb2e-11e8-858e-f61b582cd0a8.png)

![image](https://user-images.githubusercontent.com/26587049/46638445-e83c4c00-cb2e-11e8-8e54-f9e9966fa156.png)

This is basically a net energy loss as a full bucket of diesel is 480k EU (96k EU x 1000mb / 200mb) versus half of a bucket of Cetane at 360k EU (144k EU x 500mb /200 mb), not even accounting for processing costs.

**Suggestion**: Increase the cost so its 40mb of tetranitromethane and have it output a full bucket of Cetane Boosted Diesel (which will align with Bio Diesel requiring a full bucket and outputting only 750mb).

**Comment by EmosewaPixel** [comment]
Vyraal, that's all from Gregic Additions.

**Comment by Archengius** [comment]
GA issue
