### ISSUE TITLE
Chemical Reactor Voiding Secondary Byproduct Fluids

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#377]
**Pack:** GregBlock v1.1.3
**GTCE Version:** 0.5.10.93

![image](https://user-images.githubusercontent.com/26587049/46815212-78091280-cd48-11e8-9df0-fecf75f55b07.png)

Given that sample recipe, the chemical reactor will consume inputs as long as there is space for the first output (water), and filling up the secondary byproduct tank/voiding the excess. It seems to only be checking for the first tank has enough space.

**Comment by EmosewaPixel** [comment]
I can't seem to reproduce it with the latest dev build.

**Comment by Vyraal1** [comment]
https://streamable.com/iaj88

Made a video, uhh ignore the music or just mute it. It only seems to happen when the first tank gets drained and becomes completely empty. In this specific setup I have an ME Fluid Import Bus specifically filtering for water.
