### ISSUE TITLE
Ore Generation

### ISSUE THREAD

**Issue by Rongmario** [GregTechCE/GregTech#38]
## General Outline
1. Veins are now randomly shaped ellipsoids
2. They can intersect any bounds, both grid and chunks
3. (CubicChunks Integration): No hardcore height limits
4. Some may have a bigger chance of spawning under sea level/floor
5. Surface rocks indicate vein locations (Optional)
6. Biome influences on vein spawns

## Config Options (need to be discussed)
- JSON Format
### Simple (String):
1. Default Block (surrounding ore)
2. GregTech Ore (matching stone type)
3. OreDictionary Name

### Complex (Object, can include themselves and criterias above, recursive):
1. Random Block State
2. WeightedRandom Block State
3. Per-Stone Type Block State
4. Per-Block Type Block State
5. Custom Marked Block State with Properties

### Vein Layouts:
1, Solid = one criteria group for all blocks in a vein
2. Levelled = different criteria for block positioning inside a vein:
    - Sporadic
    - Primary + Secondary (most rare ore close to center)

### Vein Shapes:
1. Ellipsoid = Min, Max Radius (Randomly Rotated)
2. Spheric = Correct Sphere with Min, Max Radius
3. Plate = Layer-like Generation with little height but very wide

**Comment by OvermindDL1** [comment]
Why not just do it the way that GT6 did it, which will never cause adjacent chunks to generate, can have overlapping layers with ease (and in fact some specialty ores only gen on such overlapping boundaries), multiple rock types, etc... etc...  See screenshots on the GT6 site recently.

**Comment by Rongmario** [comment]
Updated Main post.

@OvermindDL1 Generation is now 'cube based' as we are taking Cubic Chunks into consideration, without CC it'll just generate 16 cubes (16x16x256). And hopefully this way of generating we can escape chunk cascading.

**Comment by OvermindDL1** [comment]
@Rongmario GT6's method is block-by-block based, it does not need to generate sets of blocks at a time but it could even generate each individually and perfectly every time, it is proper noise-based generation and as such will never need to generate any neighbor.
