### ISSUE TITLE
inconsistencies with ores

### ISSUE THREAD

**Issue by Hypsellis** [GregTechCE/GregTech#391]
I noticed some ores from the periodic table are missing in Gregtech. I don't know if it's normal, if they are still waiting to find a use for being included, or if it's a real forgetting. Anyway it would be nice and interesting to add them in future updates, so all the periodic table will be completed, and it will add more depth to GregTech.

- Zirconium
- Hafnium
- Technetium
- Rhenium
- Ruthenium
- Rhodium
- Germanium
- Thallium
- Selenium
- Polonium
- Bromine
- Iodine
- Radium
- Actinium
- Protactiunium
- Neptunium
- Curium

I could add to this list too the Astatine and the Francium, but both are too unstable and radioactive for existing at large dose. The astasine has a life time of 8 hours, and the Francium of 22 minutes.

I don't know why too the Darmstadtiumis included while he has only a life of 3,6 second, so impossible to exist and less be used. The last metal which is aproximately stable in the periodic table is the Curium.

Some ores like the Boron, Phosphrus are missing ingot, nugget, plate, rod, gear.... They are metelloids and are between metals and non metals, and show behavior of both side

And finally, the biggest issue of this mod for me, the color of the ores are totally crazy. I don't if it's something wanted for helping to differentiate the different ores, but for myself it just loses me more than anything else. For a tech mod which try to be the most realistic, give vibrant colors to all metals don't help.

**Comment by Vyraal1** [comment]
There needs to be a balance to both 'realism' and actual functional gameplay. The ores you added, while they sound kinda cool, are probably less fun to implement and a lot less fun to play, you just end up with a bunch of noise without any actual uses. If you can try refining this list to actually give concrete uses as to how these ores could be integrated into the mod, then maybe.

As for the color of the ores, this goes back to the realism issue. If GT wanted to be ultra realistic, it would make sure you drink proper amounts of water, you have proper bowel movements, and cobblestone would always fall. It also DOESN'T help to color every ore realistically, cause then everything would be a vibrant shade of gray.

**Comment by Hypsellis** [comment]
I don't want to force and push anything. I just report some inconsistencies and omissions. I try to help and support this mod in my own way. You are free to do whatever you want. It's your mod not mine.

**Comment by Rongmario** [comment]
Did we ever advertise as a realism-driven mod? Ores are like that so they are identifiable, and somewhat still fit their irl counterpart; if you did want to have them be even more realistic they'd just like extremely bland and look quite the same.

Not every material needs those parts, FYI you could add them via CraftTweaker.

**Comment by Archengius** [comment]
no need in more pointless ores
