### ISSUE TITLE
Pipes With Steam Instakill

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#395]
I think you should lower the damage on pipes a bit. They shouldn't be able to insta-kill you if you're at full health.

**Comment by pyure** [comment]
I don't like making things ez-mode, but you're probably right.  Hot pipes should injure a person not vaporize them.  (I've died so many times to steam pipes)

This is less of a concern if players can just use covers on pipes (can we do that yet?)
