### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by LordHungry** [GregTechCE/GregTech#397]
Hi, i get a crash on my server whenever i start it with gregtech. If i remove it its completely fine, but it also works fine on singleplayer. Does anyone know how to fix this? 

Crash Report:
https://pastebin.com/SQKA1KAk

I am using the latest version, 1.0.117

**Comment by EmosewaPixel** [comment]
Does not sound like you're on the latest version, as that got fixed on the latest version.

**Comment by iamtakingiteasy** [comment]
Doesn't seem like sideness issue.
Could you please attach full server start log?

**Comment by LordHungry** [comment]
https://github.com/LordHungry/Loading/blob/master/startuplog
Is this what you need?

**Comment by iamtakingiteasy** [comment]
Yes. It seems you have lots of coremods, at least one of which is trying to register a non-existing ASM-transformer class and after that point bunch of (probably other) coremods fail to instrument a number of classes, by trying to find methods with incorrect signatures and not handling errors.

I think your modpack is quite fragile at this point and it might be a miracle it worked before adding gregtech, being just a last straw.

However, if you provide full archive of mods (I think configuration files are not needed, just pack of jars), we can bisect coremod causing problems.

**Comment by iamtakingiteasy** [comment]
FYI: when coremod is failing at any point of instrumentation process and not handling such failure correctly, by passing through array of bytes it got to instrument, class it was instrumenting becomes lost for entirety of launch session, because transformer failed to return array of bytes, that should be binary form of instrumented class.

This is one of main reasons why writing coremod is generally discouraged: failure could break not only this coremod itself, but other mods too.

**Comment by LordHungry** [comment]
So i need to send a link to a download with all my mods? It would take about 10 minutes to upload.

**Comment by iamtakingiteasy** [comment]
Yes, so we can find which coremod is offending whole modpack, including gregtech.

**Comment by LordHungry** [comment]
Alright. Is there a specific site i should/need to use to upload it?

**Comment by iamtakingiteasy** [comment]
No requirements for this. Anywhere you like. If unsure, I might suggest https://wetransfer.com

**Comment by LordHungry** [comment]
Alright, im uploading it now.

**Comment by LordHungry** [comment]
https://wetransfer.com/downloads/2865dfd8ecc7261e8886724531d3286b20181017223209/df2f72b8833592919beee4fa8f4ecbb520181017223209/9c492d?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email
I think this is the link for downloading. I haven't used wetransfer before

**Comment by iamtakingiteasy** [comment]
This modpack is a complete mess.
To weed out all incompatible, partially-compatible or outright offending mods a week might be required.
For starters, AdvancedRocketry-1.12.2-1.4.1-104-universal.jar is repsonsible for providing invalid ASM class, however there are numerous errors all over the pack.
Some mods still do invalid transforms, but that is nothing compared to that in pristine state of modpack, some mods fail to configure themselves, some mods provide invalid recipes, some exchange with incompatible properties, some call non-existing methods and block ID space is close to overflowing modulo 4096. 
I do not think i could further assist you with your modpack.

**Comment by Yoghurt4C** [comment]
what a meaningless wall of text
https://github.com/raoulvdberge/refinedstorage/issues/1972
