### ISSUE TITLE
[Suggestion] make GT wrench compatible with other mod

### ISSUE THREAD

**Issue by Wettix** [GregTechCE/GregTech#398]
I don't know if is possible, but that would be nice if we can use GT wrench with other mod like ender io, thermal, applied and co

**Comment by Rongmario** [comment]
To do what?

**Comment by Wettix** [comment]
Because why not? and that would be nice if we couldn't use a different wrench by mod

**Comment by Archengius** [comment]
i will never include 1000 APIs of different mods to make my wrench work with theirs
