### ISSUE TITLE
Battery Buffer graphic bug

### ISSUE THREAD

**Issue by Black0305** [GregTechCE/GregTech#399]
After rotating the output with a wrench the output dot wont change its position. Just a graphic thing.
Edit: Same thing with Steam Turbines and Diesel Generators

**Comment by Vyraal1** [comment]
There needs to be a block update or chunk needs to be re-rendered, placing a torch or something else in the same chunk gets them rendering properly again, not sure if intentional. All other hatches seem to share similar behavior.
