### ISSUE TITLE
Paper Rings in LV Pump Recipe

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#405]
I don't *think* this is intended.  Rings made out of paper probably shouldn't be an option when crafting the LV Pump.

**Comment by EmosewaPixel** [comment]
That's a GA recipe. It's also how it was in GT5U.

**Comment by pyure** [comment]
Closing as non-applicable to the mod.  It didn't occur to me Pixel would port over a broken design element deliberately.
