### ISSUE TITLE
Cannot craft Cobalt Wire-cutters

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#406]
But you can make some other cobalt tools (hammer, file, wrench, saw) and tools from addonz get generated automatically from what I can see.

**Comment by EmosewaPixel** [comment]
That's because there are no cobalt screws/bolts.

**Comment by pyure** [comment]
That makes sense.

**Comment by pyure** [comment]
https://github.com/GregTechCE/GregTech/pull/407
