### ISSUE TITLE
EBF Controller sometimes goes transparent

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#410]
So far we (GT and IT3 staff) have been unable to reproduce this at will, but its happening regularly with our assembly of mods.  I'm going to track notes here in case someone else sees a pattern or has more to contribute.
* Only happens with the EBF so far (single-block machines are unaffected, ditto Multi Smelter and Bronze Boiler)
* Breaking the EBF with a pickaxe while in this state causes many other GT blocks to go transparent OR lose texture
* Breaking the EBF in Creative mode does NOT cause the above behaviour
* Once blocks are "broken" (transparent etc), you can recover by completely closing your instance and restarting minecraft

**Comment by Vyraal1** [comment]
Also going to chime in, have had trouble reproducing this, it mostly occurs after a server restart, but it seems like multiblock controllers that weren't running just got transparent and become "tile.unnamed.name".

![image](https://user-images.githubusercontent.com/26587049/47272815-dc9e4b80-d558-11e8-96e7-1bfc86ae4823.png)

![image](https://user-images.githubusercontent.com/26587049/47272823-e88a0d80-d558-11e8-839b-1567d8892f2c.png)

I actually haven't been able to recover my controllers, this happens to both GA and GTCE multiblocks.

**Comment by EmosewaPixel** [comment]
In other words, they become corrupted.

**Comment by pyure** [comment]
@Archengius, this issue seems to occur with multiblocks that contain Fluid Hatches (Input or Output). 

Our testers can reliably reproduce the problem in a clean pack (GT-CE and JEI) as follows:
1) Create a valid EBF structure that includes a Fluid Input Hatch (or Output Hatch)
2) Exit to main menu
3) Re-enter world
Controller will be in a visibly corrupted state.

We ruled out "# of hatches" being the cause (where a "hatch" is any valid non-casing non-controller block).  
* If you replace the fluid input hatch with another input bus, the controller survives.
* If you replace several heat-proof machine casings with input buses, the controller survives.

**Comment by pyure** [comment]
Negative test:
* Create a valid EBF structure that does not include a Fluid Hatch
* Exit world
* Re-enter world
Controller will be fine.

**Comment by pyure** [comment]
@Vyraal1 see above if you're interested.
