### ISSUE TITLE
Machines Don't Auto-Output To Covered Pipes

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#412]
![image](https://user-images.githubusercontent.com/25333164/47293466-838ef000-d60a-11e8-87c7-2306ca91bc63.png)
![image](https://user-images.githubusercontent.com/25333164/47293473-87227700-d60a-11e8-88cd-117745d7df96.png)
![image](https://user-images.githubusercontent.com/25333164/47293546-b802ac00-d60a-11e8-8346-e6beb8358a97.png)

**Comment by Archengius** [comment]
are other machines doing that? or any modded machines in general

**Comment by EmosewaPixel** [comment]
Huh, indeed
![image](https://user-images.githubusercontent.com/25333164/47352801-f8b9fe00-d6ba-11e8-907d-81a9391ed1c3.png)
Pipes auto-output to covered pipes, but not machines.
