### ISSUE TITLE
Microblock covers don't prevent cable connections logically, only visually.

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#414]
GregTech Community Edition v117

![image](https://user-images.githubusercontent.com/26587049/47323741-1049a600-d62b-11e8-94d0-727f0af52465.png)

![image](https://user-images.githubusercontent.com/26587049/47323733-09bb2e80-d62b-11e8-8d5f-846249033e3e.png)

ModList:
![image](https://user-images.githubusercontent.com/26587049/47323722-0162f380-d62b-11e8-8433-27d8b799d430.png)

The covers didn't prevent the cables from connecting, causing amps to overload the superconductor cable. This was 5 Turbo Diesel Generators, a stone cover, and 1x Superconductor wire.

![2018-10-22_18 46 16](https://user-images.githubusercontent.com/26587049/47323759-1c356800-d62b-11e8-8cf3-3c2adf811a52.png)

![2018-10-22_18 46 19](https://user-images.githubusercontent.com/26587049/47323761-20fa1c00-d62b-11e8-8b2c-5454cfaed2bb.png)

**Comment by TontonTchou** [comment]
Exact same issue with pipes as well, not only cable

**Comment by Archengius** [comment]
cannot reproduce.
