### ISSUE TITLE
Fine Wires have no machine recipes

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#416]
As the title says.

There is only one way: using Wire Cutters.

**Comment by EmosewaPixel** [comment]
They can be made from Rods

**Comment by Shattered2909** [comment]
no, they can't

**Comment by Rongmario** [comment]
Yes they can.

**Comment by Agrax** [comment]
> 
> 
> no, they can't

Yes, they can. You're really wrong

**Comment by Agrax** [comment]
Good. Shat acknowledged his ignorance :P
