### ISSUE TITLE
[Suggestion] Apatite vein surface rocks

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#424]
Bluish-whiteish rocks dropping tiny piles of either apatite or phosphor dust (in the second case pale yellow rocks, but more vibrant than platinum vein surface rocks. Smth more citric, like #a0a03b

**Comment by Rongmario** [comment]
They just take whatever colour the material it is assigned to

**Comment by Agrax** [comment]
- [ ] diamond vein
- [ ] apatite
- [ ] redstone

And others

**Comment by Archengius** [comment]
nope, added for diamond (graphite), other veins are pretty common.
