### ISSUE TITLE
Issues with painted cables

### ISSUE THREAD

**Issue by MainFreak** [GregTechCE/GregTech#427]
Hello. I discovered this while playing that one GregTech Skyblock modpack, but so far I barely touched anything except of normal GregTech so I doubt it is a mod-interaction issue.

I basically tried separating cables with two different sprays:
![grafik](https://user-images.githubusercontent.com/20734190/47965855-61569280-e04c-11e8-92e3-77cedc65ce2e.png)
It seems to work both optically and gameplay wise, however the machines on the green lane did not receive any power whatsoever. Only when recoloring them to white or removing any color they received it again.

The only event worth mentioning before this was a canning machine exploding due to microblocks not isolating a copper cable from it properly but that seems to be already known.
Restarting the client/server did not fix this.

Version of Minecraft: _1.12.2_
Version of Forge: _forge-14.23.5.2768_
Version of GTCE: _gregtech-1.12.2-1.0.117_

If this is a mistake on my end please tell me how to fix this.

**Comment by Archengius** [comment]
cannot reproduce
