### ISSUE TITLE
Craft tweaker error?

### ISSUE THREAD

**Issue by mightydanp** [GregTechCE/GregTech#438]
i am getting this error and i dont know why i re look over the code and it doesnt seem to be wrong ?

> [crafttweaker]: Error executing {[0:crafttweaker]: open_computers.zs}: Bad type on operand stack\nException Details:\n  Location:\n    Open_computers.__script__()V @251: ifnonnull\n  Reason:\n    Type integer (current frame, stack[6]) is not assignable to reference type\n  Current Frame:\n    bci: @251\n    flags: { }\n    locals: { top, 'gregtech/api/recipes/RecipeMap', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/oredict/IOreDictEntry', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack', top, 'crafttweaker/api/item/IItemStack' }\n    stack: { 'gregtech/api/recipes/crafttweaker/CTRecipeBuilder', '[Lcrafttweaker/api/item/IIngredient;', '[Lcrafttweaker/api/item/IIngredient;', integer, null, integer, integer }
> 

`val assembler = mods.gregtech.recipe.RecipeMap.getByName("assembler");

var redstone = <ore:redstone>;
var ironRod = <ore:stickIron>;
var comparator = <ore:comparator>;

var basicEletronicCircuit = <ore:circuitBasic>;
var goodEletronicCircuit = <ore:circuitGood>;
var dataCircuit = <ore:circuitData>;
var dataControlCircuit = <ore:circuitElite>;
var copperWire = <gregtech:cable_copper:0>;
var emeraldDust = <ore:dustEmerald>;

var printedCircuitBoard = <opencomputers:material:4>;
var memory1 = <opencomputers:component:6>;
var transister = <opencomputers:material:6>;
var microchip1 = <opencomputers:material:7>;
var microchip2 = <opencomputers:material:8>;
var microchip3 = <opencomputers:material:9>;
var arithmeticLogicUnit = <opencomputers:material:10>;
var controlUnit = <opencomputers:material:11>;
var cable = <opencomputers:cable:0>;

//Memory (Tier 1)
assembler.recipeBuilder()
    .inputs(microchip1 * 3, printedCircuitBoard * 3)
    .outputs(memory1 * 1)
    .EUt(32)
	.duration(250)
    .buildAndRegister();
	
//Transister
assembler.recipeBuilder()
    .inputs(redstone * 1, stickIron * 3)
    .outputs(transister * 6)
    .EUt(16)
	.duration(500)
    .buildAndRegister();

//Microchip (Tier 1)
assembler.recipeBuilder()
    .inputs(basicEletronicCircuit * 1, transister * 4)
    .outputs(microchip1 * 4)
    .EUt(25)
	.duration(400)
    .buildAndRegister();

//Microchip (Tier 2)
assembler.recipeBuilder()
    .inputs(microchip1 * 1, transister * 8)
    .outputs(memory2 * 4)
    .EUt(25)
	.duration(640)
    .buildAndRegister();
	
//Microchip (Tier 3)
assembler.recipeBuilder()
    .inputs(dataCircuit * 1, transister * 16)
    .outputs(memory3 * 4)
    .EUt(25)
	.duration(800)
    .buildAndRegister();
	
//Arithmetic Logic Unit(ALU)
assembler.recipeBuilder()
    .inputs(comparator * 1, microchip1 * 6)
    .outputs(arithmeticLogicUnit * 1)
    .EUt(24)
	.duration(500)
    .buildAndRegister();
	
//Control Unit(CU)
assembler.recipeBuilder()
    .inputs(dataControlCircuit * 1, transister * 6)
    .outputs(controlUnit * 3)
    .EUt(32)
	.duration(750)
    .buildAndRegister();
	

//Cable 
assembler.recipeBuilder()
    .inputs(copperWire * 8, dustEmerald * 1)
    .outputs(controlUnit * 8)
    .EUt(32)
	.duration(64)
    .buildAndRegister();
	`

**Comment by pyure** [comment]
Can you please wrap that script in `code tags.`

**Comment by pyure** [comment]
Even in that pastebin, there's all kinds of errors.  Are you sure that's what's in your script?
For instance, `var basicEletronicCircuit = ore:circuitBasic;` should be `var basicEletronicCircuit = <ore:circuitBasic>;`

If that's what's legitimately in your script, you should be first learning basic knowledge of crafttweaker scripting (and this wouldn't be the appropriate venue for that)

**Comment by mightydanp** [comment]
oh no. I dont know why but the < and > got deleted when i pasted it maybe i copied the wrong script but the right script looks like this whit that same error. 
https://pastebin.com/brbAHbFH
sorry about that i dont know why that happened.

**Comment by pyure** [comment]
No worries. Next obvious concern is that lines like this
`.inputs(microchip1 * 3, printedCircuitBoard * 3)`
which have a collection need to be arrays, which means square brackets:
`.inputs([microchip1 * 3, printedCircuitBoard * 3])`

**Comment by pyure** [comment]
There doesn't appear to be any real issue here.  If you have any further questions about the syntax, hop onto the discord and ask in the addons channel; someone will assist you there.

**Comment by mightydanp** [comment]
I did as you said and there is still the same error

**Comment by pyure** [comment]
Since its not an actual error in the mod (just your script) you should get help on either the crafttweaker discord or the GT-CE discord.
