### ISSUE TITLE
Invalid amount of recipe outputs. Actual: 2. Should be between 1 and 1 inclusive.

### ISSUE THREAD

**Issue by Zer0Lyfe** [GregTechCE/GregTech#44]
Gregtech version: gregtech-1.12.2-0.1.1.0
ForgeMultipart: ForgeMultipart-1.12.2-2.4.2.58-universal
CodeChickenLib: CodeChickenLib-1.12.2-3.1.8.341-universal

when i run gregtech in a bigger modpack it will cause crashes due to what the title says. It doesn't happen to all wood mods such as traverse but some like thaumcraft, Integrated dynamics, random things and etc.

thaumcraft crash:
https://gist.github.com/Zer0Lyfe/739ed1762bd5f11f83474198a3dd7747

Integrated Dynamics crash:
https://gist.githubusercontent.com/Zer0Lyfe/d36e4f6fbaf73ef82b1e35abfc1292a6/raw/3176a76edb009336a3766dbfdf265d078f0c8589/Integratedcrash.log

If you need me to add more crashes i can do so.

**Comment by Archengius** [comment]
fixed
