### ISSUE TITLE
Cannot make screws out of Quarzite

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#440]
Not PR-ing this since I can't imagine it will get accepted, but due-diligence request anyway: Can you please allow the GENERATE_BOLT_SCREW flag on Quarzite (and other gemMaterial) so that we can leverage those components in custom recipes.  Thanks.

**Comment by pyure** [comment]
Digging further, it seems Certus/Nether Quartz already support bolts/screws, probably because of STD_SOLID, but if that's exposed I don't know how to access it.  I feel like this is probably possible already (and therefore not an issue but a CT channel discussion item) but not certain.

**Comment by EmosewaPixel** [comment]
A screw made from a gem? Where is the logic?

**Comment by pyure** [comment]
No special logic other than the standard "minecraft" or "infitech" or "gregtech", unless you count "pack devs want to use it". 

Worth noting that the other parts that CAN be made from gems (rods, gears) aren't any more logical.

**Comment by EmosewaPixel** [comment]
I now support this as I need gem bolts. :P

**Comment by Archengius** [comment]
no screws from gems
