### ISSUE TITLE
Invalid Recipes (Incompatibility with PrimalCore when LiteLoader is installed) 

### ISSUE THREAD

**Issue by ScienceDrummer** [GregTechCE/GregTech#441]
This is causing my game to crash before the main menu pops up. Please correct me if I'm wrong.

Crash: https://paste.dimdev.org/unuwemafaw.mccrash

Log: https://paste.dimdev.org/tepoqituji.md

**Comment by ScienceDrummer** [comment]
I have recently found out that his is a problem between GTCE and Primal core. Now I'm wondering if I should take this up with the Primal core team as well.

**Comment by Archengius** [comment]
nah, no this is not my issue. For some reason one of your mods makes Items.TORCH == Items.AIR or something like that, because recipes fail to find torch item used as output.

**Comment by Archengius** [comment]
dead issue
