### ISSUE TITLE
Door Recipes Cause Duping

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#442]
You get 3 Iron Doors per 6 Iron
![image](https://user-images.githubusercontent.com/25333164/48660501-f7ce7f00-ea62-11e8-867e-9598c5a2b422.png)
![image](https://user-images.githubusercontent.com/25333164/48660502-fbfa9c80-ea62-11e8-81b9-34152bc31879.png)
But 1 iron door can be processed into 6 iron
![image](https://user-images.githubusercontent.com/25333164/48660506-0a48b880-ea63-11e8-8f5a-22d89b679ad5.png)

You craft 6 planks into 3 doors
![image](https://user-images.githubusercontent.com/25333164/48660517-23516980-ea63-11e8-8fb1-45d0573bac30.png)
You assemble 3 Wooden Doors with one Plank
![image](https://user-images.githubusercontent.com/25333164/48660523-36643980-ea63-11e8-930a-d31ecf980aea.png)
And you process it into 6 wood
![image](https://user-images.githubusercontent.com/25333164/48660526-40863800-ea63-11e8-8b76-8bbc06ef7e4c.png)

**Comment by Quantum64** [comment]
6d67ed968cd475155b58e03830f28d094eed4372
