### ISSUE TITLE
[Suggestion] A Method for changing material stats

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#443]
Could you perhaps adds a method (that preferably works with CraftTweaker) which can be used to change the tool stats of existing materials?

**Comment by Archengius** [comment]
no

**Comment by Agrax** [comment]
„No” is not a reason to reject stuff

**Comment by Archengius** [comment]
GTCE materials are GTCE materials and cannot be changed.
I'm satisfied already by pixel changing my stuff, enough.
