### ISSUE TITLE
about custom ore spawn

### ISSUE THREAD

**Issue by TehporP** [GregTechCE/GregTech#444]
The custom ore spawn are too complicated now.
especially in dimension_filter

**Comment by BlueCreeper160** [comment]
You just have to enter config -> gregtech -> worldgen, open, and choose the dimesion, if you want to add a new vein copy and paste a json file, then open it with notepad and configure it by putting the name of the vein (in the name od the json file ex: amethyst_vein) name of the minerals that will be generated in the vein and the rest you can see it in:
https://ftb.gamepedia.com/GregTech_5/Mining_and_Processing

-> The dimension filter for the nether: ["is_nether"],
     the dimesnion filter for the end is :  ["name:the_end"]
