### ISSUE TITLE
Conveyor Modules don't work (as Cover)

### ISSUE THREAD

**Issue by marcmagus** [GregTechCE/GregTech#445]
Cannot seem to place a Conveyor Module (LV) as a cover on an LV machine. Is the old Cover functionality entirely unimplemented?

If so, at the very least it would be good to have a note in the tooltip (currently "1 Stack every 20 secs (as Cover)") to say the feature isn't implemented yet.

**Comment by Archengius** [comment]
covers are not implemented.
it was said many times
