### ISSUE TITLE
[Suggestion] Item/Type Filter Blocks

### ISSUE THREAD

**Issue by ct-klein** [GregTechCE/GregTech#448]
Similar to how they are in GT5.  Helpful in large ore processing setups.

**Comment by Archengius** [comment]
use proper mods providing filtering and item transport

**Comment by Agrax** [comment]
There are no gt-friendly buffer chests that allow one to specify an exact amount of items to use in a recipe. GTCE buffers did exactly that. The feature is really needed, thus worth considering
