### ISSUE TITLE
[Suggestion] Frames improvement

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#449]
Allow for frames to connect sideways (but be affected by gravity). So you can place like 3-4 blocks away from the frame, but the next block falls on the ground (like sand or gravel)- unless given support from either underneath or from a side. That would allow for some nice-looking catwalks (i love how GTCE frames look)

**Comment by Agrax** [comment]
No. Frames

**Comment by Archengius** [comment]
Implemented.
