### ISSUE TITLE
Multiblock not forming with TorchMaster light inside

### ISSUE THREAD

**Issue by Swabek** [GregTechCE/GregTech#454]
I use the "Feral Flare Latern " by TorchMaster to illuminate my base. The problem is this mod spawns lights in dark areas like inside of multiblocks. This leads to invalid structures cause inside the multiblocks is now an other block then air.... (took hours to find that reason btw)

Never tested it with Arcane Lamp by Thaumcraft in 1.12. but i used the Arcane Lamp in 1.7.10 with gregtech 5 unofficial and had never problems.

Versions:
gregtech-1.12.2-1.0.124
torchmaster_1.12.2-1.6.4.62

![before](https://user-images.githubusercontent.com/44787395/48966179-86e01780-efcc-11e8-8c67-14efcc915818.png)
![after](https://user-images.githubusercontent.com/44787395/48966182-8e9fbc00-efcc-11e8-9d2d-aabff7231919.png)

**Comment by Archengius** [comment]
not my problem - blame mod creating ghost blocks inside of structures.

**Comment by Archengius** [comment]
or tell him to override isAir in his block class so it can be considered air.

**Comment by OvermindDL1** [comment]
@Xalcon Doesn't look like your fault, this mod has a lot of line like ` if(blockState.getBlock() != Blocks.AIR)` and other similar things throughout the multiblock and util related code where it should actually be calling `isAir()` in many places, and in the predicate pattern stuff (that defines the 'shape' of a multiblock) it looks like it literally stuffs `Block.AIR`'s into lambdas and does a direct block comparison with it; so yeah, this mod is highly bugged, whoever closed this did not actually check.

**Comment by Xalcon** [comment]
Thanks for confirming my suspicion. Sadly I barely have any time for my own mods, let alone mods from others - otherwise I would do a pull request to get this issue fixed.

I hope anyone from the devs get around looking into this again.

**Comment by leagris** [comment]
:running_man: :bug:
