### ISSUE TITLE
Machines can't share output(Only tested with coke oven chute and faucet)

### ISSUE THREAD

**Issue by NikolaiM88** [GregTechCE/GregTech#459]
The coke oven faucet and chute, can't be shared between 2 multiblock structures, like you used to be able to with oldschool gregtech multiblocks. Only one of the connected machines will work, and all other machines connected to the outputs of the currently "working" coke oven stops working.

**Comment by pyure** [comment]
NikolaiM88, these are Gregic Additions blocks, not GT-CE.  You should create an issue on their side.

@Archengius this can be closed.

**Comment by EmosewaPixel** [comment]
Technically it is GTCE as it's intentionally disallowing multiblocks to share hatches.

**Comment by pyure** [comment]
My error

**Comment by pyure** [comment]
Yep that was a GT5 mechanic

**Comment by Archengius** [comment]
it will never be the part of GTCE
multiblocks cannot share any hatches or buses.
