### ISSUE TITLE
GT Bracket Handler Errors Aren't Caught By /ct syntax

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#466]
![image](https://user-images.githubusercontent.com/26587049/50452108-22371600-0906-11e9-98ee-6277e23ccdf1.png)

Given that script, `/ct syntax` doesn't show any errors or that it is missing a closing bracket.

**Comment by Archengius** [comment]
because there is no error, you specified metaitem name "plank.jungle); recipes.remove<metaitem:plank.darkoak"
