### ISSUE TITLE
[Idea] Advanced conveyors

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#473]
I understand that you don't want to implement special blocks that act as filters and buffers. What do you think abt COVERS having these abilities? Or smth. Just an idea

**Comment by EmosewaPixel** [comment]
In theory you would be able to do this with Robot Arms, having one arm moving an output to one pipe system and another to another.

**Comment by Agrax** [comment]
The thing we need tho is an ability to separate two routes via one block/item. In GT5 there was a thing called „type filer” allowing you to specify only a part of an oredic. Like „detect and transport everything that has the <oredic:dustTiny*> part”. What we have to do now is to specify 40+ different items via any given mod
