### ISSUE TITLE
Gold Nugget Dupe

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#480]
In the Arc Furnace, one Gold Nugget can be turned into 8
![image](https://user-images.githubusercontent.com/25333164/50701996-dc89f400-104f-11e9-9594-72a9815b473f.png)
It can be pulverized into 8 Small Piles
![image](https://user-images.githubusercontent.com/25333164/50702016-eb70a680-104f-11e9-9d7d-0ee70a536666.png)
And melted into 8 nuggets worth of Gold
![image](https://user-images.githubusercontent.com/25333164/50702034-fc211c80-104f-11e9-99e7-77584d4db835.png)
Anyways, seems to be due to https://github.com/GregTechCE/GregTech/blob/6d67ed968cd475155b58e03830f28d094eed4372/src/main/java/gregtech/loaders/MaterialInfoLoader.java#L46

**Comment by Archengius** [comment]
fixed
