### ISSUE TITLE
【Suggest】Add processing array

### ISSUE THREAD

**Issue by bangbangtangQWQ** [GregTechCE/GregTech#481]
I think some of the single-box machines in the game don't meet some of my needs. We need some multi-block structures that can be batch processed.

**Comment by Agrax** [comment]
Okay, so multiblock versions of single-block machines ARE planned, in the future. For now Arch wants to finish the early and the mid-game.

Multiblocks will get added as soon as Arch is satisfied with LV-EV. Multiblocks are IV+, but there's at least industrial grinder planned. Maybe more. Not a clue. But wait patiently. Arch works every 1-2 months for one week. Now he's gonna add covers, one month forward and he's gonna add something completely different, but insanely awesome.

Oh, and don't forget there's Gregic Additions, which adds some more depth to the experience with some questionable choices, but who cares

**Comment by bangbangtangQWQ** [comment]
Thank you, I think I will look forward to it.

**Comment by Archengius** [comment]
high tier multiblocks are planned
