### ISSUE TITLE
IElectricItem issues

### ISSUE THREAD

**Issue by LemADEC** [GregTechCE/GregTech#483]
As of 1.12.2-1.0.124, I've noted 2 issues related to the Electric Item capability while integrating it with my WarpDrive mod:
1- the IElectricItem interface is missing a way to read the current stored energy, at least I couldn't find a direct one. Consider adding an equivalent to getEnergyStored() from IEnergyContainer.

2- the discharge should split energy consumption between elements of the stack, or reject if batteries are stacked. For example, if I have 2 HV batteries charged with 10k EU, then I discharge 2K EU, the result is 2 HV batteries charged with 8k EU each. I was expecting 9k EU each.
Consider dividing the discharged amount by the stack size or prevent discharging stacked batteries.
The same happens while charging, actually providing free energy.

**Comment by roboderpy** [comment]
Your container slots shouldn't normally accept stacked batteries, as it is done in regular gtce containers

**Comment by LemADEC** [comment]
Player's inventory accepts stacked batteries

**Comment by LemADEC** [comment]
I'm using batteries from player inventory. The latest doesn't restrict stack size.
In comparison with IC2, their RE-batteries and Charging RE batteries are both stackable and provide a similar IElectricItem interface. Their implementation will only accept to consume energy from non-stacked batteries unlike GTCE which doesn't.
