### ISSUE TITLE
changeEnergy in EnergyContainerBatteryBuffer ignores number's sign

### ISSUE THREAD

**Issue by roboderpy** [GregTechCE/GregTech#488]
Calling it with negative values will charge up batteries inside.

https://github.com/GregTechCE/GregTech/blob/41c0cc85b000b840f61e6700735940dc260b3386/src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java#L168-L172

**Comment by Archengius** [comment]
because it's CHANGE energy, and that's how it works?

**Comment by Archengius** [comment]
why do you need to call changeEnergy at all?

**Comment by roboderpy** [comment]
Maybe because i can't call `acceptEnergyFromNetwork` from place where my logic perform operations? (e.g. universal electricity machinery/other meanings)

And in your own API you do call `changeEnergy` with negative values.
https://github.com/GregTechCE/GregTech/blob/41c0cc85b000b840f61e6700735940dc260b3386/src/main/java/gregtech/api/capability/IEnergyContainer.java#L61-L67

**Comment by Archengius** [comment]
changeEnergy is designed to be called with negative values, yeah. This is a bug in implementation of battery buffer.
I don't get where you logic perform operations. In fact, addEnergy/removeEnergy/changeEnergy are all methods that should be called by machine tile entity itself to manipulate its energy.
And i guess you're using it for a different reason, which i don't get.
