### ISSUE TITLE
Worldgen

### ISSUE THREAD

**Issue by Techlone** [GregTechCE/GregTech#5]
Plan to create the awesome worldgen
1. Refuse from the 3x3 square generation and generate ore deposits in random places.
2. The chunked generation of ore deposits to reduce cascading world gen issues.
3. Ore bodies (tubes, viens, clusters, layers)
4. The biomes influence - ores appear in all biomes but certain ores have higher chance to spawn in certain biomes
5. Make the worldgen configuration (json)
6. Testing and balancing

**Comment by richardhendricks** [comment]
I am interested in contributing, if possible.  I did a separate chunkified oregen for GTNH GT5U that retains the layered oreveins.  Be nice to have biome tag oregen, and dimension specific configuration files of oreveins.

https://github.com/Glitchfiend/BiomesOPlenty/blob/8dc8f466d7b5430e9ab69cefc78c27cc20064a48/src/main/java/biomesoplenty/common/init/ModBiomes.java#L391

https://github.com/GTNewHorizons/NewHorizons/issues/2516

I would prefer separate files vs a giant worldgeneration.cfg file, if that matters.

**Comment by Krysinski** [comment]
@lawremi Please, help GT-CE to incorporate your ideas about Geologica)). It is possible to port Geologica to 1.12.2 MC?

**Comment by lawremi** [comment]
It would be fairly easy to port Geologica to 1.12, and you are of course free to incorporate anything from PFAA into GT-CE, although ideally we should try to keep things modular.

Taking a step back, both PFAA and GT define a material-based system for ore generation and processing. It would be cool we could separate out a shared material registry, sort of a higher-level ore dictionary. Then there could be modues that manifest those materials as ore blocks, and modules that generate ore blocks in the world. Another type of module provides machines that can determine their recipes algorithmically from the material definitions.

This is the first I've heard of GT-CE, and I'm excited about it. The world does need GT running on modern versions of Minecraft. But there is a greater opportunity here. We could define a modding framework for advanced industrial Minecraft. Like a specialized, industrial version of Forge. Mod pack authors are often challenged to integrate large, monolithic industrial mods like GT. A common framework, and a more modular approach to mod development in general, would alleviate that problem. It would also enable modders to extend specific aspects of the system, without having to interface with specific mod APIs, or reinvent the wheel.

**Comment by Krysinski** [comment]
Judging from my experience of using GT5U together with PFAA, there is no sense in inventing the generation of ores separately in GT-CE. If you are familiar with the fashion of PFAA and you have some suggestions on how to change it, then write [here](https://github.com/lawremi/PerFabricaAdAstra/issues/60)
