### ISSUE TITLE
how to buid fusion reactor?

### ISSUE THREAD

**Issue by matyklugDebbuged** [GregTechCE/GregTech#504]

**Comment by Archengius** [comment]
There is no fusion reactor in GTCE. If you're interested in GT5U-alike fusion reactor, use addon like Gregic Additions.

**Comment by matyklugDebbuged** [comment]
But why you have fusion reactor components?

**Comment by CelestialPhoenix** [comment]
Because the mod is a work in progress, and the reactor is a planned feature to be added at some point in the future.

**Comment by matyklugDebbuged** [comment]
> Because the mod is a work in progress, and the reactor is a planned feature to be added at some point in the future.


Okay, thanks!
