### ISSUE TITLE
Impossible to use fluid fuels in large bronze boiler?

### ISSUE THREAD

**Issue by hughesdylan** [GregTechCE/GregTech#508]
Large bronze boilers have a defined structure that has 1 solid in 1 liquid in 1 out... So... It doesn't seem possible currently to use Semifluid fuels with it? 

Not sure if this is intended behavior, probable operator error.

**Comment by Vyraal1** [comment]
Not if I understand, even with one liquid input hatch, you can still pump in semi-fluid fuels in there for the boiler? Also the multiblock is pretty modular, where ever there are firebox casings, you can put in another input hatch/bus.

**Comment by Archengius** [comment]
>you can put in another input bus/hatch
