### ISSUE TITLE
NBT Packet Size Kicks/Disconnects from Server

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#515]
This is starting to affect a lot of midgame testers (MV to HV) on FTB Interactions. Personally I encountered this issue on GregBlock as well and had trouble connecting to the server or would get random kicks due to packet issues. The only real common connection between the two was GTCE.

Using Tickprofiler's packet profiler, I asked an afflicted player to log into his base and got packets as large as this: 
![image](https://user-images.githubusercontent.com/26587049/51333020-e5fd5e00-1a4a-11e9-9888-74b10138b2a5.png)

Is there an alternative to sending strings over the network? Whenever a player get's a large enough array of machines, they just get disconnected from the server and require anywhere from 2-6 login attempts to get back in.

**Comment by Archengius** [comment]
nobody sends strings over network, my packet coding is just using raw byte arrays, i don't really see the problem here.

**Comment by Shadows-of-Fire** [comment]
You send a lot of strings over the network.
For each meta tile entity in the world:
One string per MTETrait attatched to that tile: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L605
One string per cover attatched to that tile: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/MetaTileEntity.java#L613
One string for each tile entity, to send their name: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java#L172

And then a series of extra abstracted data which may or may not be necessary, but I haven't traced that back to a source yet.

**Comment by Archengius** [comment]
i'm not going to use IDs when they are unnecessary. These strings get compressed just fine with chunk data packet.

**Comment by Shadows-of-Fire** [comment]
These types of data should instead be consolidated into a registry `net.minecraftforge.registries.ForgeRegistry` which can be created by the `net.minecraftforge.registries.RegistryBuilder`.  These registries provide a backing ID map that is automatically managed, which means you don't have to do anything other than use the registry.

These strings are not getting compressed enough, or the sizes of those packets would not be so enormous.

**Comment by Archengius** [comment]
i don't really think it's exactly these strings to blame. And side of such registries sent on login will be pretty big too.

**Comment by Archengius** [comment]
I will do some experiments with these IDs in spare time, though.

**Comment by Shadows-of-Fire** [comment]
It may not entirely be just strings (but the meta tile entity structure is certainly ensuring that a lot of them go through), but I am not currently at an IDE to look for further sources of data use.

**Comment by CanisArtorus** [comment]
Now my GregBlock server hanging itself to death occasionally when a player tries to join makes sense.
All the Initial sync data getting wrapped in PlayerChunkMapEntry was taking over 60 seconds and triggering the watchdog killer thread. 

We are at the cusp of HV, using an array of high-pressure steam lava boilers to distill and de-sour Light fuel to run Large Steel boilers for a large set of both basic and advanced machines.

It's a Nodecraft unit with 5GB RAM and 3.3GHz Xeon processor.

**Comment by Archengius** [comment]
Don't care what server it is, if it hands, there is a log, and you didn't
provide it


пт, 18 янв. 2019 г., 6:44 Alexander James notifications@github.com:

**Comment by Archengius** [comment]
no feedback, considering fixed
