### ISSUE TITLE
All Refined Storage patterns for auto-crafting Cables and Wires cause a crash when viewed.

### ISSUE THREAD

**Issue by Damien-Reave** [GregTechCE/GregTech#517]
**Issue description:**
Making a Refined Storage pattern where any wire or cable from GregTech Community Edition is the sole output (meaning the image of the wire or cable will display when shift is held) causes a crash when the game tries to render the wire or cable. This happen when shift is held when the pattern is in the player's inventory, or if the pattern is sitting on the ground in the world and is in the player's view, or if the pattern is stored inside of a Crafter.

**Steps to reproduce:**
Reproducible by creating a pattern as so described and hitting shift.

Version:

Minecraft: 1.12.2
Forge: 14.23.5.2796
Refined Storage: 1.6.12
GregtechCE: 1.0.124

**Does this issue occur on a server? [yes/no]**

Unknown, tested only in SP

I reported it initially to the Refined Storage Dev (raoulvdberge) and he said this:

_I suggest you report it to GregTech, looking at the stacktrace, it seems they are the cause. RS isn't doing anything nonstandard in the pattern rendering, and it works fine with all other items._

**If a (crash)log is relevant for this issue, link it here:**
Here's a couple of the crash reports

https://paste.dimdev.org/acajesenak.mccrash

https://paste.dimdev.org/wakahuwuya.mccrash

https://paste.dimdev.org/fociwajibu.mccrash

https://paste.dimdev.org/owisilanuf.mccrash

**Edit:**

Patterns for making Machine Casings in an Assembler don't cause a crash, but they also don't render the image of the Casing and they don't actually work. The pattern won't even go into a Crafter.

**Comment by Rongmario** [comment]
Your 2nd and 3rd link are the same, did you mis-paste one?

**Comment by Damien-Reave** [comment]
No, just pasted one twice. I could generate some more crash reports if you like but its very easy to replicate the crash.

**Comment by Rongmario** [comment]
No that's fine, more wouldn't necessarily help.

**Comment by Archengius** [comment]
You'll be surprised, but i don't see anything related to GTCE in the stacktrace. If RS is still incompatible with rendering hooks CCL uses, it's their problem, not mine.
Check with some machine block to make sure it's RS issue.

**Comment by XXxinsanityxX** [comment]
I got some different crash reports from the ones above it might be more helpful, the setup is the same as the one presented above i also tried with machine blocks and they render fine, the machine casings don't render at all and you also get a crash with fluid pipes and insulated cables.
https://paste.dimdev.org/qizizoyate.sql
https://paste.dimdev.org/legolixoyi.sql

**Comment by Damien-Reave** [comment]
Okay. Looks like it is an RS issue then. It doesn't support CCL. Raoulvdberge says he has no intention of doing bug fixes for "weeks and maybe months" so I'll just switch to AE2.

Thank you!

**Comment by FoxZOolm** [comment]
work fine on ae2... (hack warning : sometime tool damage be neg value)
with RF try use gtce wiremil....
AE2 can be totally controled with OC... very useful with GTCE ore automation ;o)

**Comment by Archengius** [comment]
closing now because there is no real intention to fix it on my side
