### ISSUE TITLE
The Default Mode Of Covers Is Import?

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#522]
Most of the time people use covers for outputting rather than inputting, so the default state of the covers should be export.

**Comment by WarlordWossman** [comment]
at least in 1.7 export meant it _exports_ from the pipe network, not sure if the terms are reversed now

**Comment by EmosewaPixel** [comment]
Oh, completely forgot about that one. I feel as though it should be mentioned somewhere.

**Comment by EmosewaPixel** [comment]
Actually, with some testing I got to the conclusion that that isn't the case. The modes are corresponding to the machine the covers are on.
