### ISSUE TITLE
Recipes That Have Too Much Fluid In An Output Slot Don't Work Even Though The Output Can Be Split Between Multiple Slots

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#523]
I'm referring to this recipe in particular:
![image](https://user-images.githubusercontent.com/25333164/51427609-2949ff00-1bfa-11e9-88e6-488113e96a2d.png)
 With the change of the fluid slot capacity it should work, however, because it has 40 buckets of Nitrogen as the output it doesn't, 
![image](https://user-images.githubusercontent.com/25333164/51427628-5a2a3400-1bfa-11e9-8c6f-3c3f50e24efa.png)
even though it could in theory split it between 2 slots like this
![image](https://user-images.githubusercontent.com/25333164/51427630-64e4c900-1bfa-11e9-903f-38697dbad68e.png)

**Comment by Archengius** [comment]
Seems like you don't understand how it works. It cannot fucking split fluids, one fluid slot is exactly for one fluid type.
I raised the limit of output slot tanks through.
