### ISSUE TITLE
Config file doesn't update when changing the configs in Mod Menu

### ISSUE THREAD

**Issue by Zer0Lyfe** [GregTechCE/GregTech#528]
I have noticed that when you change the config in the Minecraft mod list config it won't sync the changes with the file as i had the same problem in my mod.

To do the bug: 
1. Change the config in minecraft and apply it
![2019-01-20 14_37_52-window](https://user-images.githubusercontent.com/28994351/51436086-3251d380-1cc1-11e9-9464-5551bd99df87.png)
2. check the gregtech.cfg and it doesn't change the file. 
![2019-01-20 14_38_10-window](https://user-images.githubusercontent.com/28994351/51436098-6927e980-1cc1-11e9-9d99-422242e9b4b5.png)

I have found a fix for this. I don't know if it suits you guys but putting static in between the public and void the onConfigChangedEvent will fix it.

The Image shows the fix.
![2019-01-20 14_43_47-window](https://user-images.githubusercontent.com/28994351/51436120-d63b7f00-1cc1-11e9-8328-0880fbaff931.png)

**Comment by GregTecher** [comment]
By the way, Please delete the System.out.println("FindRecipe call") in RecipeMapWorkableHandler : )
It takes up quite a lot of time.
