### ISSUE TITLE
[suggestion] config for tanks

### ISSUE THREAD

**Issue by WarlordWossman** [GregTechCE/GregTech#530]
Basically a config for tanks to lose the fluid when broken into item form, would be very helpful for pack balance.

**Comment by Archengius** [comment]
nope, these tanks won't loose fluid. they're pretty small compared to other mods portable storage. If you feel that even it is too easy for you, well, you can always tweak the recipe.

**Comment by WarlordWossman** [comment]
I guess I will just have to use other mods tanks then and disable these, I want to focus on automated transport in my modpack and if a player can bring 36 times the tank size of fluid by hand there would never be a reason to set up a rail line with tank carts.

I know other mods have more OP tanks, but it's not like I am using them.
