### ISSUE TITLE
Rotor durability drops too fast

### ISSUE THREAD

**Issue by omsfuk** [GregTechCE/GregTech#531]
according to
```
damageApplied = (float) (DAMAGE_PER_INTERACT * relativeSpeed);
relativeRotorSpeed = 0.01 : currentRotorSpeed / (NORMAL_MAXIMUM_SPEED * 1.0)
```
assume relativeRotorSpeed = 1, then 3dur/t, which represents an osmium rotor with 76800 durability can only be used for about 76800 / 3 / 20 = 1280s = 21min

I don't know if it's a bug or if you did it on purpose.
if latter, please allow me to mourn for gregtech players : P

Sorry for my bad english.

**Comment by omsfuk** [comment]
sorry, I have to bother you again. 
* At present, the plasma rotor has changed from 21min to 29hour, which seems to have increased many times. But this is still too difficult.
* what does 29hours mean? Suppose I have 100 large turbines, then within 29 hours, I need to stop all the turbine and replace the rotor one by one manually. 
* This job cannot be automated by AE because no things can be placed in front of the RotorHolder, otherwise the turbine will stop working.

This is just a little bit of my opinion about the balance of the game. If you feel inappropriate, please ignore it.

Thank you.

**Comment by Archengius** [comment]
first of all, you should never have 100 large turbines, and turbines will never be automatable, neither scalable source of energy. 
However, 29 hours is still pretty small value. I'll play with it later, but don't expect better efficiency last longer.

**Comment by EmosewaPixel** [comment]
29h is enough. It shouldn't be something you leave and never have to think about again. If that were the case they wouldn't have durability.

**Comment by Archengius** [comment]
no, that's just too much even for one turbine. 6 days is enough.
