### ISSUE TITLE
Weird smeltings

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#532]
pyure/infitech-prototype#318

Just like there. Those are unnecessary, autocreated smelting recipes

**Comment by Archengius** [comment]
still can't reproduce

**Comment by Agrax** [comment]
I have @pyure...

**Comment by pyure** [comment]
Ah, I didn't realize.  Then, the next step would be to isolate how to reproduce with just GT-CE, or failing that, which mod collision is causing the problem.
