### ISSUE TITLE
Extruder not working

### ISSUE THREAD

**Issue by OnionGirl69** [GregTechCE/GregTech#533]
The extruder takes in power but does not process ressources, I tried with many materials and extruder shapes, it just doesn't start up.

**Comment by LAGIdiot** [comment]
I don't think this needs to be answered after all that time, but just for sake of it. Nearly all Extruder recipes require MV+ tier of machine. You are probably using LV one. In current version GTCE have minimal machine tier for recipe indication in JEI.
