### ISSUE TITLE
Many electrolyser recipes won't work

### ISSUE THREAD

**Issue by OnionGirl69** [GregTechCE/GregTech#534]
I tried with redstone, cinnabar and pitchblende and they won't work. However salt's recipe seems to work.

**Comment by LAGIdiot** [comment]
I don't think this needs to be answered after all that time, but just for sake of it. Your problem is that you are trying to use MV+ recipes in LV Electrolyzer. In current version GTCE have minimal machine tier for recipe indication in JEI.
