### ISSUE TITLE
all or most of this mod's item can be turned into sticks

### ISSUE THREAD

**Issue by Rubijox** [GregTechCE/GregTech#536]
https://i.imgur.com/z5RBbW9.jpg

 the second recipe in the image shows a recipe for sticks using random gregtech items in a Mekanism Precision sawmill(it scrolls through a lot of them, doesnt seem to show block-type items though)

Modlist: https://pastebin.com/PCNJ4wCJ (sorry its really messy, if you know a better way to make a list of all my mods please tell me :) )

If you need any additionnal info feel free to ask

**Comment by Agrax** [comment]
It is mekanism fault.

mekanism.common.integration.OreDictManager#init

````for(ItemStack ore : OreDictionary.getOres("plankWood"))

		{

			if(ore.getHasSubtypes())

			{

				ItemStack wildStack = new ItemStack(ore.getItem(), 1, OreDictionary.WILDCARD_VALUE);


				if(!Recipe.PRECISION_SAWMILL.containsRecipe(wildStack))

				{

					RecipeHandler.addPrecisionSawmillRecipe(wildStack, new ItemStack(Items.STICK, 6), new ItemStack(MekanismItems.Sawdust), 0.25);

				}

			}

			else {

				RecipeHandler.addPrecisionSawmillRecipe(StackUtils.size(ore, 1), new ItemStack(Items.STICK, 6), new ItemStack(MekanismItems.Sawdust), 0.25);

			}

		}
`
Mekanism uses wildcard on sub-typed items which have metadata, and doesn't use it for normal items

I guess ores.getHasSubtypes() should be inverted

**Comment by thiakil** [comment]
@Agrax @Archengius what is the item ID in question?

**Comment by Archengius** [comment]
What do you mean? Item id is not important here, main problem is Melanism
using OreDictionary.WILDCARD_VALUE on items with subtypes while iterating
ore dictionary.

**Comment by thiakil** [comment]
For testing purposes.

**Comment by Archengius** [comment]
gregtech:meta_item_1, don't remember meta. Search for Wood Plate.
