### ISSUE TITLE
Issue/question thread to avoid spam

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#54]
- [x] Theres no recipe for insulting 16x wires.
- [x] Is it intended that many machines (transformers and non-multiblock processing ones) require a lower tier casing? If not, that is also a bug.
- [x] Tungstensteel ingots can be made from dust without freezing, while making tungstensteel from dust makes hot ingots which cannot be frozen (Freezer has only 1 recipe which is broken)
- [x] Tooltips for Multiblocks to explain shapes?
- [x] Glass and nether star lenses are considered to be red
- [x] Tier 8 battery is made from 8 tier 6 batteries - intended or not? Tier 7 is ZPM.
- [x] Red Alloy cables have LV in their tooltip even tho their voltage is ULV
- [x] No recipe for turning integrated circuits back into normal ones, neither for configuration
- [x] Basic circuits have no crafting recipes but are needed for machines
- [x] Multiblock Sawmill?
- [x] Mercury fluid made from nothing in the fluid extractor
- [x] ULV hull takes lead cables which are LV, why not red alloy ones?
- [x] Things like the graphite cell cannot be created because they don't have recipes with solid materials.
- [x] Cadmium batteries?
- [x] You should probably rename "Rubber" to Resin to avoid confusion
- [x] Plantball does not have a proper name

**Comment by Archengius** [comment]
> Things like the graphite cell cannot be created because they don't have recipes with solid materials.
This is outdated never used thing. There aren't any graphite cells.

> No recipe for turning integrated circuits back into normal ones, neither for configuration
You cannot turn them back into normal circuits. Configuration is performed via right click.

> Cadmium batteries?
There batteries exist, what's wrong with them?

> You should probably rename "Rubber" to Resin to avoid confusion
I don't see any point doing so, taking in account that doing it will break ore dictionary support,

**Comment by SuperCoder7979** [comment]
> No recipe for insulating 16x wires
Vanilla gregtech never had 16x cables. They were added by GTNH because they wanted it.

**Comment by Archengius** [comment]
Sawmill and all multiblock theme will come later.
