### ISSUE TITLE
GTCE 1.0.124 Why shouldn't this blast furnace design work?

### ISSUE THREAD

**Issue by MFernflower** [GregTechCE/GregTech#541]
If I build a blast furnace with this exact design the machine will say it's idling and reports it's heat capacity but will not draw power or cook anything 

Also notice how the input hatches are at 0 despite being feed MV power

Why isn't this design functioning? 
![2019-01-31_23 51 18](https://user-images.githubusercontent.com/3164942/52103647-b9058b00-25b4-11e9-83fa-1a1b480b785e.png)

![2019-01-31_23 51 09](https://user-images.githubusercontent.com/3164942/52103510-fd445b80-25b3-11e9-988e-623c4f5eb154.png)
![2019-01-31_23 51 13](https://user-images.githubusercontent.com/3164942/52103511-fd445b80-25b3-11e9-9a8a-706ff7db20ef.png)
![2019-01-31_23 59 20](https://user-images.githubusercontent.com/3164942/52103564-4b595f00-25b4-11e9-8b58-757aaa92f807.png)
-dd4707d3f6b3.png)
![2019-01-31_23 51 20](https://user-images.githubusercontent.com/3164942/52103513-fd445b80-25b3-11e9-941a-ff9bb8209718.png)

![2019-01-31_23 59 23](https://user-images.githubusercontent.com/3164942/52103596-6deb7800-25b4-11e9-923d-d4b35dc8c0b1.png)

**Comment by okyloky9** [comment]
You need a wrench to turn the buffers the right way. At the moment, they're not outputting through the wire.
Shift right click the buffer on the wire side with it and it will send power through the correct way.

**Comment by Archengius** [comment]
exactly. will make it more noticable in the next release

**Comment by MFernflower** [comment]
@Archengius Even just changing the texture to include a small blue dot on the cable side or something would be of benefit
