### ISSUE TITLE
GTCE + IC2 recipies wire conflict

### ISSUE THREAD

**Issue by nailfor** [GregTechCE/GregTech#545]
I have installed IC2 and GTCE together, but when i try craft the tin wire, i can't do that, one tin plate with cutter gives me tin cablle from IC2, not from GTCE for any place in crafttable

**Comment by Archengius** [comment]
And it's your problem. Change recipes via CT if you wish to play with both mods together.

**Comment by Agrax** [comment]
Or even better: don't use IC2 <3

**Comment by nailfor** [comment]
I can't. It need to EMT https://minecraft.curseforge.com/projects/im-crossover

IC2 recepts hold in self config files.. try to change it.
