### ISSUE TITLE
Crash when placing low voltage battery buffer in world

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#55]
**Mod Version**: gregtech-1.12.2-0.1.3.1
**Forge Version**: 14.23.2.2.2637

Cheated the 1-slot buffer into hand, attempted to place it in world.  Crash occurs instantly.  World is subsequently inaccessible due to placed block.

https://pastebin.com/PWc9KTC1

**Comment by Archengius** [comment]
Use newer version of CCL.

**Comment by pyure** [comment]
Confirmed.
