### ISSUE TITLE
[Suggestion] Close chest key

### ISSUE THREAD

**Issue by Trochu** [GregTechCE/GregTech#550]
Hello there!

I am really dissapointed GregTech chests can't be closed by [INVENTORY] key like vanilla ones. Can you set GT chests to be closable by [INVENTORY] key? Cause it is possible to close them only with [ESC] key.

Thanks :)

**Comment by TheonlyTazz** [comment]
Also future suggestion:

Add a support for inventory tweaks?

**Comment by Archengius** [comment]
also future suggestion: can you lookup other issues before writing some dumb suggestions?
