### ISSUE TITLE
Tool Durability Calculations

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#551]
![image](https://user-images.githubusercontent.com/26587049/52436289-ee910380-2ae1-11e9-90b3-7dfbdf1f200e.png)

GTCE build 164

After the update with the reduction in GT Tool durability, it seems like the consumption amounts did not change. The picture above shows 6 cobblestone mined with a Cobalt Pickaxe, using 10 durability per block.

**Comment by Archengius** [comment]
first of all, nobody fucking reduced any durability.
secondly, durability is multiplied by 10, and it's not even a issue.

**Comment by Archengius** [comment]
actually, i just forgot to readd durability multiplier
