### ISSUE TITLE
[Issue] BoP oilgen problem

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#553]
Apparently BoP worldgen is interfering with GTCE's oilgen. Can't find any oil (even with GTCE's default settings)

**Comment by Archengius** [comment]
oil springs are pretty rare, not all oil sources have them, so search underground
not my problem anyways

**Comment by Agrax** [comment]
You know i searched underground? Like in /gamemode 3? Unless you’ve changed smth. In the previous update oil springs were abundant as all hells. If you want i can /gamemode 3 you on the server so that you can prove me im wrong

**Comment by Archengius** [comment]
test on clean instance, i don't see problems right now.

**Comment by Agrax** [comment]
Okay. I’ll try that

**Comment by Agrax** [comment]
The issue is me. Closing that, coz im just retarded
