### ISSUE TITLE
Electrolyzer processing times are extremely high in v166

### ISSUE THREAD

**Issue by Saereth** [GregTechCE/GregTech#554]
After updating we noticed the processing time on many key processes had gone up significantly. 100 minutes to process bauxite, 26 minutes to process glauconite etc. 

Also the Use (pressing U while hoovering over the machine in JEI) for the electrolyzer and many other GT machines (centrifuge, assembler etc) no longer show up in JEI, although if you check the uses of the dusts you can see the recipe that way.

https://imgur.com/a/S3N3GkP

We are using the 1.0.3 patcher and GA, although Multidementhunter reported in discord it was happening in his instance of v166 as well without crafttweaker or GA/patcher

**Comment by Rongmario** [comment]
getProtons() method wasn't reverted properly in the commit https://github.com/GregTechCE/GregTech/commit/e623b71ce5bafe91a9f2d16dc1aa1bcd112a4558.
