### ISSUE TITLE
Oil gen borked.

### ISSUE THREAD

**Issue by assasin172** [GregTechCE/GregTech#555]
Hey, today I decided to test in my custom pack, new fresh world and got greeted with this view.

images: https://imgur.com/a/cKewNxE

- Light oil springing from 255 height.

I could't find any config for surface oil gen so might be just random issue. (default world gen)

**Comment by Archengius** [comment]
and you are sure you're using latest?

**Comment by assasin172** [comment]
I had gregtech-1.12.2-1.5.15.165 as I see there is 166 now. WIll try if it persists.

**Comment by assasin172** [comment]
Issue fixed by going to 166. 

LOCK
