### ISSUE TITLE
[Request] Give crushed, purified ore and dusts their own item id's

### ISSUE THREAD

**Issue by WaffleMan0310** [GregTechCE/GregTech#559]
I have noticed an issue with trying to do automatic ore processing. All of the dusts (tiny, small, full) and crushed and purified ores are all meta items from the same ID. This makes it very difficult to differentiate without filtering for each individual dust/ore. Which given the sheer amount of ores in GregTech is quite a lot of filtering. The only workaround I have found is the ore dictionary export bus from ExtraCells which allows for ore dictionary wild cards. (crushed* for example) If they had their own IDs I could ignore the metadata and have general filtering of dusts, ores, etc. I haven't looked into how the mod if programmed but if possible this would be most appreciated.

**Comment by Archengius** [comment]
1) different IDs won't help you with filtering - ignore metadata only works for tools and is cheating for other items
2) we have Ore Dictionary Filter cover and upgrade for conveyor cover.
3) this is not backward compatible and creates ton of allocated IDs
4) no

**Comment by WaffleMan0310** [comment]
Ops didn't even think of the backward compatible part. I was playing the mod as part of a pack (GregBlock) and it doesn't have the most recent version. Guess I'll manually update, conveyor cover sounds like the way to go. Thanks for replying.
