### ISSUE TITLE
Exception loading model for variant forgemultipartcbe:multipart_block#normal

### ISSUE THREAD

**Issue by WoozyMasta** [GregTechCE/GregTech#561]
Hi, when I try to compile from commit b709cbf251dbba0bafca3805d616fd89b12628dc crashes with an  `Exception loading model for variant forgemultipartcbe:multipart_block#normal`

Most likely, I'm doing something wrong, I just executed the buildClient recipe from forgegradle

trace https://pastebin.com/raw/jNXkBMxi

**Comment by Archengius** [comment]
1) what you titled is not a crash reason
2) crash reason is CCL-specific and is probably indicates broken dev environment. Use launching from IDE.

**Comment by WoozyMasta** [comment]
@Archengius , but I run from IDE (IntelliJ IDEA 2018.3.3)

   * got the last status of the project
   * prepared the environment via `build.gradle`
   * do gradle task `runClien`

If it helps, here’s the full log from the IDE, running `runClient --stacktrace` https://pastebin.com/raw/mwD79V40

**Comment by Archengius** [comment]
you run gradle task runClient, not launch GradleStart from IntelliJ's run menu.
