### ISSUE TITLE
Multismelter Goes Idle When Input Bus is Full

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#562]
Have the input bus of a multismelter pull from a constant source of ores (eg a large chest of graphite ores). After the multismelter input bus fills up, the multismelter goes idle after 1-2 operations while there are still unprocessed valid inputs in the input bus.

**Comment by Rongmario** [comment]
Not sure what the multismelter behavior should be right now but currently it seems like the machine will stop finding recipe if:

currentItemsEngaged is more or equal to maxItemsLimit and maxItemsLimit is determined by 16 * heatingCoilLevel
