### ISSUE TITLE
Plutonium 244?

### ISSUE THREAD

**Issue by LordPINE** [GregTechCE/GregTech#565]
It seems that GTCE has Plutonium 244 as a byproduct from uranium, and for radon production, while GT5u has Plutonium 239. Which means that one of them is probably incorrect, and I'm guessing it's the GTCE one. Maybe this should be changed to match GT5u?

**Comment by Archengius** [comment]
nobody cares about these numbers, and i don't really know which one is correct
if you want things to "match GT5u", go play on 1.7.10 with GT5U
