### ISSUE TITLE
GLState leak when an invalid machine is placed and rendered in world

### ISSUE THREAD

**Issue by roboderpy** [GregTechCE/GregTech#566]
![pic1](https://i.dbotthepony.ru/2019/02/javaw_2019-02-15_16-35-29-b21983d.png)
![pic2](https://i.dbotthepony.ru/2019/02/javaw_2019-02-15_16-36-08-abee7cc.png)

The easy way™ to reproduce:
1. Install gregic additions
2. put down it's machine (coke oven for example)
3. save world and exit game and delete gregic additions
4. start game and load the save

The hard way™ to reproduce:
1. load pre 1.3 GTCE world with GTCE 1.5 installed

**Comment by Archengius** [comment]
5. break invalid machine

**Comment by roboderpy** [comment]
[world save to reproduce the issue](https://i.dbotthepony.ru/2019/02/gtce-glstate-leak.7z)
[video](https://i.dbotthepony.ru/2019/02/2019-02-15%2017-00-09.mkv)
