### ISSUE TITLE
Fluid pipe failure

### ISSUE THREAD

**Issue by mcmso** [GregTechCE/GregTech#569]
The interflow pipe will collapse
I'm not very good at English

[crash-2019-02-16_08.06.14-server.txt](https://github.com/GregTechCE/GregTech/files/2871384/crash-2019-02-16_08.06.14-server.txt)

**Comment by WazWaz** [comment]
I found that installing Forge Multipart fixes this.

https://minecraft.curseforge.com/projects/forge-multipart-cbe
