### ISSUE TITLE
GregTech Oregen does not work

### ISSUE THREAD

**Issue by ProfessorCool** [GregTechCE/GregTech#57]
As of Gregtech 1.4.1, Gregtech does not create any ores. I checked for ores in a 32 by 32 chunk area after removing all vanilla ores. 

![image](https://user-images.githubusercontent.com/37518092/40809564-2000b19c-64e8-11e8-8b99-144a6c71f3da.png)

**Comment by Exidex** [comment]
Does it work in 0.1.3.1?

**Comment by Ezoteric** [comment]
for me it didn't work on all version from alpha including the last few patches before it.

Just my 2 cents.
even tested it on a clean MC setup newest everything needed to run GTCE
