### ISSUE TITLE
Crafted frames have wrong metaid

### ISSUE THREAD

**Issue by roboderpy** [GregTechCE/GregTech#571]
![scr](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_07-51-05-c52d0dc.png)
![scr](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_07-53-42-7012818.png)
![scr](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_07-56-37-a914d8a.png)
![scr](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_07-56-41-7eecc5c.png)
![scr](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_07-56-54-43382db.png)

**Comment by Rongmario** [comment]
Happens in vanilla crafting table too?

**Comment by roboderpy** [comment]
in every crafting table

**Comment by Damien-Reave** [comment]
Happens with Steel Frames as well
