### ISSUE TITLE
Rapidly looking around and clicking on machines in multiplayer produce exceptions serverside

### ISSUE THREAD

**Issue by roboderpy** [GregTechCE/GregTech#572]
...and does not open machine's inventory
![pic](https://i.dbotthepony.ru/2019/02/javaw_2019-02-16_14-41-32-1e5896d.png)
[video with reprodution](https://i.dbotthepony.ru/Videos/2019-02-16%2014-42-49.mkv)

**Comment by Archengius** [comment]
check latest versions before reporting shitty issues that were fixed already.
