### ISSUE TITLE
[Bug] GameCrash after opening Enderio Conduit selection interface connected to Gregtech machines/cable

### ISSUE THREAD

**Issue by TheonlyTazz** [GregTechCE/GregTech#573]
#### Issue Description:

Game crashed after trying to open the "side-selection" of an ender fluid conduit.
Conduit was between 2 Gregtech machines and a Golden HV coated Cable

#### What happens:
Shift-Left Click the Cable -> Crash to Desktop

#### What you expected to happen:
Open the Selection screen. Issue probably due to Gregtech cable not rendering. Unknown if this is fixable on Gregtech's side or Enderio.

#### Steps to reproduce:

1.Shift-Left Click the Cable 
2.Crash to Desktop
3. ????
...
5. Restart Minecraft

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
1.12.2-5.0.40

- EnderCore:
1.12.2-0.5.45

Gregtech Community Edition:
1.12.2-1.5.17.167

- Minecraft:
1.12.2

- Forge:
Forge-14.23.5.2795

- SpongeForge? 
no

- Optifine? 
no

- Single Player and/or Server? 
Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/TkwzGswt

Related Github issues:
https://github.com/SleepyTrousers/EnderIO/issues/5041
![image](https://user-images.githubusercontent.com/3908847/52899808-8b445700-31ee-11e9-8681-d8c0f781f53e.png)

**Comment by Archengius** [comment]
i didn't get what exactly EIO tried to render, but seems like it was a cable with invalid metadata.

**Comment by Archengius** [comment]
i can fix crash when rendering an invalid cable item, but that won't fix EIO trying to render it

**Comment by HenryLoenwind** [comment]
It's an itemstack representation of the block. The code here is quite old and uses getItemDropped+damageDropped, so you get a very basic item. I'll probably update it to use pickBlock, but still, an item render should not crash for the "naked" item ;)
