### ISSUE TITLE
[Bug] Crash to Desktop after trying to break a 16x Silver Cable with wrench

### ISSUE THREAD

**Issue by TheonlyTazz** [GregTechCE/GregTech#576]
#### Issue Description:
Game Crashed to Desktop after i tried to break a Cable.
my game froze with that error message on the left so i managed to Screenshot it

#### Steps to reproduce:
1.Break Cable
2.Crash to Desktop
3. ????
...
5. Restart Minecraft

#### Affected Versions (Do _not_ use "latest"):

*Gregtech Community Edition:
  1.12.2-1.5.17.167

* Minecraft:
  1.12.2

* Forge:
  Forge-14.23.5.2795

* SpongeForge?
  no

* Optifine?
  no

* Single Player and/or Server?
  Server

#### Your most recent log file where the issue was present:
https://pastebin.com/5aythtqH

![image](https://user-images.githubusercontent.com/3908847/52910750-58f13300-329c-11e9-9ff8-a2585b3ae3d7.png)

**Comment by Archengius** [comment]
did you place that cable *before* updating to latest version of GTCE?

**Comment by TheonlyTazz** [comment]
No, I'm testing the Betapack from Vyraal and Sae (FTB:Interactions). I'll report back when they update the pack and if the issue continues

**Comment by Vyraal1** [comment]
This is on the latest version of GTCE available on CurseForge
