### ISSUE TITLE
Center multiblock viewer

### ISSUE THREAD

**Issue by willis936** [GregTechCE/GregTech#577]
I noticed that when rotating the multiblock viewer it doesn't spin around the center of the multiblocks.  Could it be changed so that when rotating multiblocks it is centered?

**Comment by Archengius** [comment]
did you test on latest?

**Comment by willis936** [comment]
When I made the bug report I had only checked 1.12.2-1.0.124.

I just checked latest (1.12.2-1.5.17.167).  The issue is still present.

![2019-02-17_08 51 34_crop](https://user-images.githubusercontent.com/13720625/52914065-e2e7ce80-3291-11e9-9749-b4d45277b291.png)

![2019-02-17_08 51 39_crop](https://user-images.githubusercontent.com/13720625/52914067-e5e2bf00-3291-11e9-972c-7b8dbad72181.png)

**Comment by Archengius** [comment]
latest on CF doesn't mean latest commit. And it is fixed in latest commit
