### ISSUE TITLE
Glue and Graphene

### ISSUE THREAD

**Issue by BlueCreeper160** [GregTechCE/GregTech#579]
I was searching utilities about the graphite dust and i see a recipe that use 8 graphite dust, 1 silicon foil and 250mB of glue to craft a small pile of graphene dust. The glue (i think) is unobtainable.

so why don't add a recipe from glue (recipes in GT5 https://ftbwiki.org/Glue_(GregTech_5) ) and add utilities to the glue and graphene?

**Comment by Archengius** [comment]
it is obtainable with GA. not going to change that before chemistry merging.
you can always add recipe via CT

**Comment by Rongmario** [comment]
Better come soon, not everyone uses that mod :^)
