### ISSUE TITLE
Suggestion: GTCE Plant Balls In-World Bonemealing

### ISSUE THREAD

**Issue by Vyraal1** [GregTechCE/GregTech#581]
Would it be possible to give them bone-mealing functionality? To give them additional use aside from just a crafting ingredient.

**Comment by Rongmario** [comment]
In vanilla GT, considering they're gotten (with chancedOutput) from dirt and other similar items from processing it might be OP. With GA I believe you can even process saplings and plants to get a guaranteed output, its even more OP.

**Comment by Archengius** [comment]
nah, no, looks weird

**Comment by Yoghurt4C** [comment]
you can use other mods (scavenger/ct) to add that functionality to almost any item
