### ISSUE TITLE
[1.12.2-1.5.20.179] Crash on dedicated server - Pipe

### ISSUE THREAD

**Issue by LotuxPunk** [GregTechCE/GregTech#589]
https://pastebin.com/WJiFrDTh

**Comment by Archengius** [comment]
install FMP, pipes currently don't work without it

**Comment by LotuxPunk** [comment]
Maybe good to add a dependency on Curse in this case.

**Comment by Archengius** [comment]
it is already an optional dependency.

**Comment by LotuxPunk** [comment]
IMO, it's more a required dependency, because it's a hard dependency. Or load your stuff dynamically by getting is the FMP is loaded or not.

**Comment by Archengius** [comment]
1) don't tell me what to do
2) it's not a hard dependency
3) it already works dynamically but classloading issues in forge borks it

**Comment by LotuxPunk** [comment]
It's was just a suggestion. Do what you want ! If it wasn't a hard dependency, I wouldn't have had a crash report.

Have a nice day!
