### ISSUE TITLE
Ores spawning in sand village structures

### ISSUE THREAD

**Issue by LAGIdiot** [GregTechCE/GregTech#59]
With new ore gen there is an issue with ores spawning in sand village structures. See attached pictures for better idea.

Running latest version (3c357d7d9e6549566a46d0421a57acb956b25054 | built from source)

![2018-06-01_16 09 29](https://user-images.githubusercontent.com/3093101/40845809-0cfd85d6-65b8-11e8-8102-b5eba14feb69.png)
![2018-06-01_16 14 38](https://user-images.githubusercontent.com/3093101/40845810-0d1bca8c-65b8-11e8-8d6c-0aaa1ef2f05f.png)

**Comment by Speiger** [comment]
@Archengius Actually its possible to fix. Just check if the ore generates in a structure boundingbox.
You can access these even without asm, but would require reflection to dynamicly collect them. (At least would fix vannilla issues).

**Comment by Speiger** [comment]
or ask greg how he fixed it in GT6
