### ISSUE TITLE
Paper recipe does not show in JEI

### ISSUE THREAD

**Issue by WazWaz** [GregTechCE/GregTech#590]
The slab-chad-slab recipe for paper does not show up in JEI. I only found it by finding bug reports here about it breaking at some point. I can't see any way anyone could discover this recipe otherwise, and since both the cutting saw and the chemical bath (the only JEI-listed way of making paper) require paper to make, it seemed that paper from the stronghold library was the intended initial source.

**Comment by Archengius** [comment]
fixed
