### ISSUE TITLE
Custom Ore Generation?

### ISSUE THREAD

**Issue by MechanosG** [GregTechCE/GregTech#596]
So, it's my understanding from looking through the git source, and reading other closed issues, that you can add custom ore veins by simply adding another json to the applicable worldgen folder.  However, I've ran some tests attempting to do so, at least 10 times now, and I can't seem to get extra veins to show up.  I don't know if I'm doing something wrong, or getting unlucky, or what is going on.

My last attempt, I decided to clear out everything previously tried and to go with something simple, just so I can confirm the vein it spawning.  This is what I tried:

```
 {
   "weight": 1000,
   "density": 0.6,
   "max_height": 150,
   "min_height": 40,
 
   "generator": {
     "type": "ellipsoid",
     "radius": [6, 6]
   },
   "filler": {
     "type": "simple",
     "value": {
       "type": "weight_random",
       "values": [
         {
           "weight": 100,
           "value": "ore:diamond",
         }
       ]
     }
   }
 }
```

I named the file custom_diamond_vein.json, and placed it in config\gregtech\worldgen\overworld\.  I expected a weight value this high to spawn diamond veins fairly often, but I haven't seen a single vein.  All default veins are working correctly, including the normal graphite/diamond vein.

Any ideas as to what I'm doing wrong?  Or if maybe I'm just getting extraordinarily unlucky and not coming across the vein despite it's weight?  Could too high a value of weight do bad things maybe?

Also, should I get this working, is GT:CE capable of spawning other mod's ores out of curiosity?  I noticed code for spawning ore based on blocks, and see examples in existing jsons such as "value": { "block": "gregtech:mineral", "variant": "basalt" } or "value": "block:gregtech:fluid.oil_light".  Could I use either of these to say, spawn a vein containing rockhounding_oretiers:coal_ores:2?

Using GT:CE 1.5.20.179 on 1.12.2.

**Comment by pyure** [comment]
Hi MechanosG:
* There's an error in your json.  You should always validate your json in something like jsonlint.com (extra comma after diamond)
* Test by removing other jsons.  Yours would be the only one left
* Yes you can add ores from other mods.

**Comment by MechanosG** [comment]
**facepalm**

Lol that comma.  Ok thank you.

**Comment by MechanosG** [comment]
It's mostly working now.  How do I use a numerical meta ID for ores though?  When I tested this:
```
				{
					"weight": 50,
					"value": "ore:diamond"
				},
				{
					"weight": 50,
					"value": "block:rockhounding_oretiers:coal_ores:2"
				}
```
only the diamond ore would spawn.  However, when I tested this:
```
				{
					"weight": 50,
					"value": "ore:diamond"
				},
				{
					"weight": 50,
					"value": {
						"block": "rockhounding_oretiers:coal_ores",
						"variant": 2
					}
				}
```
the coal_ores would spawn, but it used the metaID 0 instead of 2, spawning the wrong ore.  I assume that means the variant variable only passes along strings for the meta name.  But is it possible to pass on the 2 instead somehow?

**Comment by pyure** [comment]
I'm actually not sure.  However, if the ore is in an oredict you can use oredict:xxxx instead.

https://github.com/GregTechCE/GregTech/wiki/Worldgen-Block-Supplier

(And you can add it to an oredict via crafttweaker if you need to)

**Comment by MechanosG** [comment]
That wiki is useful.  I wish I would have thought to look there before spending hours looking through the source myself.  Most mods don't make very good usage of the github wiki so I got out of the habit of looking.

Alright so, other than the numerical metaID thing (if anyone else happens to know the answer to that) I have one last question.  Are GT:CE veins, by design, limited to how close they can be together?  I experimented with trying to make some smaller pockets of low end coal, in pretty small vein sizes, with all other veins disabled.  But to my surprise, it would generate my one little vein, then there would be a huge gap before the next vein would eventually spawn.  I didn't see anything on the wiki that looked like it had any effect on this.  I tested adding "count_as_vein": false, thinking that might treat it as a glob of stone and bypass the vein limitation.  But that didn't seem to do much.  I did find a config option in gregtech.cfg that says
   ``` # Specifies min amount of veins in section
    I:minVeinsInSection=0```
but I don't know if that's related or not.

My intention is to keep GT:CE's ore balance and veins, but also give players some small non-important veins thrown here and there to mine, especially early game when people are still basement mining.  I was hoping to do this with GT:CE's ore generator, as the last one I attempted to use along side it (Realistic Ore Veins) was extremely inefficient and lag inducing.  If I can't, it's no biggy, I'll just have to try and find a decent ore generating mod to run along side GT:CE just for this special purpose.  But for efficiency reasons, I need to find out if GT:CE can handle it first or not.

**Comment by Archengius** [comment]
1) you cannot specify metadata, use blockstate block specification (you have blockstate printed out when looking at block in game with F3 enabled)
2) veins are generated per sections, section is 3x3 chunk size, and amount of ores in section is minVeinsInSection + random(additionalVeinsInSection). countAsVein tells whenever your vein should be included into this amount, or additional vein should be generated instead to increment it.
3) vein size doesn't affect generation rate, vein sizes or proximity isn't taken into account at all.
