### ISSUE TITLE
Enchantment fatal error

### ISSUE THREAD

**Issue by byalexeykh** [GregTechCE/GregTech#597]
Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2815
GregTech version: gregtech-1.12.2-1.5.20.179

Other mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleCore, Aroma1997Core, AromaBackup, AromaBackuprecovery, Backpack, Baubles, Botania, ChickenChunks, Clumps, CodeChicken Lib, CoroUtil Library, Emoticons, Extended Mod Config, Extended Renderer, FTB Library, Forestry, Gravestone Mod, GregTech Community Edition, Hammer Core, Immersive Engineering, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Lycanites Arctic Mobs, Lycanites Demon Mobs, Lycanites Desert Mobs, Lycanites Elemental Mobs, Lycanites Forest Mobs, Lycanites Freshwater Mobs, Lycanites Inferno Mobs, Lycanites Jungle Mobs, Lycanites Mobs, Lycanites Mountain Mobs, Lycanites Plains Mobs, Lycanites Saltwater Mobs, Lycanites Shadow Mobs, Lycanites Swamp Mobs, Mantle, Morpheus, NetherPortalFix, OMLib, Open Modular Turrets, Pam's HarvestCraft, Railcraft, Realistic Item Drops, Recurrent Complex, Sampling Performance Profiler, Secret Rooms 5, SecretRooms Hooks, Special AI, Spice of Life: Carrot Edition, SpongeForge, Tinkers' Construct, Tree Chopper, YABBA, Zombie Awareness.

Logs: https://paste.dimdev.org/acinapaleg.mccrash

P.S.

There is some variable that has a null value in itself, and minecraft crashes with a JavaNullException error.

**Comment by byalexeykh** [comment]
EDIT 1:

I found that the error is caused by Bane of Arthropods enchant

**Comment by byalexeykh** [comment]
Are you serious? :D  You give a link to a topic that I opened, in which I
was given a link to this topic. The circle is closed. This is not a sponge
problem. This is a problem with your mod, your mod throws JavaNullException
error. Maybe I could fix it myself, but the file is encoded into a .class
format.

ср, 6 мар. 2019 г., 22:52 Archengius <notifications@github.com>:

**Comment by Archengius** [comment]
I didn't get what you mean, but issue is mixed in latest commit, so I
closed it.
