### ISSUE TITLE
[Suggestion] more top info

### ISSUE THREAD

**Issue by GregTecher** [GregTechCE/GregTech#599]
![image](https://user-images.githubusercontent.com/46837124/53619932-0f093500-3c2c-11e9-9041-610548a88cf3.png)

We need progressTime & power display, just like above : )
-- From an old Greg Technology Co., Ltd employee (not me : )

PS: The picture above was the evidence of #598

**Comment by Archengius** [comment]
we don't, progress is enough for most of users, and other things are advanced stats
