### ISSUE TITLE
What is our work now?

### ISSUE THREAD

**Issue by LasmGratel** [GregTechCE/GregTech#6]
I'm looking forward to contributing to your project, but I couldn't find any TODOs or other things.

Could you make a completely TODO list?

**Comment by 3TUSK** [comment]
Might be worth mentioning that it's better to talk it on [Discord](https://discord.gg/7qqsmX7)...

**Comment by SuperCoder7979** [comment]
So, right now a bunch of texture related things have to be done:

- Break up the electric machine GUIs into separate texture (look at what I did in the commit history for bronze and steel)
- Change the JSONs for the tools to use their texture and copy+paste missing tool textures from GT5u when needed (I'm currently working on this)
- Add the high pressure steam machines using code and changing the resource locations to use the steel textures

Unfortunately, most of this is a lot of copy+pasting but if you wish to contribute go right ahead! I recommend looking through the code to see how it works before making any changes.

**Comment by Exidex** [comment]
Look various issues to find subject to contribute
