### ISSUE TITLE
Needed Circuit Name Changes

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#612]
Data Control Circuits - Crystalprocessor Assembly
Energy Flow Circuit - Nanoprocessor Assembly
Advanced Circuit Parts - Microprocessor
Advanced Circuit - Integrated Processor
Basic Electronic Circuit - Integrated Logic Circuit

 That's what their names should have been in GA, but for some reason overriden resources don't show up outside the dev environment.

**Comment by Archengius** [comment]
I'm not going to change names or mimic GA circuits, localization is written from scratch.

**Comment by EmosewaPixel** [comment]
🤷‍♂️ They don't logically make sense, but you do you, I guess
