### ISSUE TITLE
How can I upgrade my machine?

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#614]
I can use steam to generate electronic to support LV machines.
Now I want to upgrade my machines. However, MV machines require Aluminum(铝), however, I can only get dust but not ingot or plate, so that I cannot get aluminum ingots. The blast furnace also requires aluminum plates because of the MV machine blocks.
How can I break the loop?

**Comment by Archengius** [comment]
blast furnace doesn't require aluminium

**Comment by 15103875d** [comment]
![04](https://user-images.githubusercontent.com/43509783/53980073-5f135a80-414a-11e9-8065-fe14de64b99b.jpg)
![03](https://user-images.githubusercontent.com/43509783/53980075-5f135a80-414a-11e9-9016-7c9ed37e45e5.jpg)
I've tried to use more generator or using another energy input hatch, it still doesn't work

**Comment by Archengius** [comment]
because hatch accepts only 2 amps and you input 6 amps, and 2 amps are not enough. cable is also too long and won't keep voltage high enough for processing

**Comment by CelestialPhoenix** [comment]
You can use multiple hatches.
Also watch your cable length, or the power loss on cables will drop your generator output below what the furnace needs

**Comment by 15103875d** [comment]
Many thanks, it works well. 
By the way, can you give me the data about the efficiency and conversion rate between steam and electronic? ( i.e. How much steam can generate 1 EU via a basic turbine) Because I found it is different from that in GT5.
Another question is can we have the batteries before I get the first aluminum ingot?
Thank you for your cooperation.
