### ISSUE TITLE
The blast furnace still cannot work

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#615]
As is shown in graph, the furnace still cannot work and shown 'work paused'

I used LV energy input hack in the back of the furnace, however, it does not revieve any energy from my generator.

![01](https://user-images.githubusercontent.com/43509783/53979292-5a4da700-4148-11e9-862e-a4a9aba318a5.JPG)
![02](https://user-images.githubusercontent.com/43509783/53979294-5c176a80-4148-11e9-96de-8cf5b707122f.jpg)

**Comment by Archengius** [comment]
aluminium recipe requires 120 EU/t, while your setup gives 30 EU/t only. Please don't spam question issues. You can still reply to closed ones.
