### ISSUE TITLE
Conflicting And Duplicating Chemical Reactor Recipes

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#617]
It seems that when adding my chemistry you forgot to add Circuits to some recipes and remove some old recipes that didn't have them. These include:
 - Distilled Water (without a Circuit conflicts with the Methanol, Acetic Acid, Phosphoric Acid, Rocket 
Fuel, Dinitrogen Tetroxide and Nitric Acid recipe)
![image](https://user-images.githubusercontent.com/25333164/53989091-6e33e180-4125-11e9-9968-1d1e1dcad12e.png)
 - Methane (currently has a recipe with and one without a Circuit, which conflicts with the Methanol and Acetic Acid recipe) 
![image](https://user-images.githubusercontent.com/25333164/53989231-cec31e80-4125-11e9-817f-c6116f0f38d6.png)
 - Nitrogen Dioxide (also currently has a recipe with and without a Circuit, which conflicts with the Dinitrogen Tetroxide and Nitric Acid recipe)
![image](https://user-images.githubusercontent.com/25333164/53989396-25305d00-4126-11e9-9f85-78bdeb978505.png)

**Comment by Archengius** [comment]
I don't have first recipe with clear GTCE.
