### ISSUE TITLE
Many ores lack prosessing recipes for ore washing and thermal centrifuge.

### ISSUE THREAD

**Issue by SiblisCu** [GregTechCE/GregTech#62]
Gregtech version: 1.12.2-0.1.5.1

Looking in JEI many ores lack recipes to (haven't built the machine jet and tested in them):
- process crushed ore
- obtain an process purified ore
- obtain an process purified pile of dust
- obtain impure pile of dust

I found this happens for this ores at least (the ones I've found so far, I've only inspected about 15 ores so far):
- galena
- grosullar
- spessartite
- pyrolusite
- redstone
- cassiterite(1)

(1) JEI shows two versions of every cassiterite block and item.

**Comment by Archengius** [comment]
fixed
