### ISSUE TITLE
The Extruders Require The Wrong Components

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#620]
As currently machine recipes are generated based on the number of the machine in the array instead of the actual tier of the machine itself, the Extruders take the crafting ingredients of the previous tier
![image](https://user-images.githubusercontent.com/25333164/53996949-a265cd00-413a-11e9-9449-bc8800ed2f8b.png)

 I would have simply kept the array of 4 elements, had the first one a null and made nulls skipable by the machine recipe generator, so the system stays pretty much the same.

**Comment by Exidex** [comment]
I would have simply added lv extruder back lol
