### ISSUE TITLE
suggestion: add a scroll bar for chests as tables of them are too wayyyyyy long

### ISSUE THREAD

**Issue by MCTian-mi** [GregTechCE/GregTech#622]
as the pic shows

![ApuqOg](https://user-images.githubusercontent.com/35869948/54072846-437b9180-42bb-11e9-984b-f1a5a8e0bbdc.png)

**Comment by WarlordWossman** [comment]
I actually think scrollbars are inconvenient as you cannot see everything at once which is annoying, esp since a lot of mods already add scroll wheel actions for moving items around.

**Comment by EmosewaPixel** [comment]
My suggestion is that as all the mods that add bigger chests do it, after a certain height start expanding the GUI horizontally.

**Comment by MCTian-mi** [comment]
yes,like actually addition

**Comment by Archengius** [comment]
naaaaaaah
