### ISSUE TITLE
Covered Pipes Don't Output To Machines

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#629]
![image](https://user-images.githubusercontent.com/25333164/54207533-9bdcaa00-44da-11e9-85f4-4c1757cd35f0.png)
![image](https://user-images.githubusercontent.com/25333164/54207541-9f703100-44da-11e9-939e-6d8b74c9ad49.png)

**Comment by 15103875d** [comment]
Could you please tell me what mod can make it visible that fluid in machines or pipes? I thought it helps a lot.
