### ISSUE TITLE
1 Block Wire Connections Don't Transfer Power

### ISSUE THREAD

**Issue by ProfessorCool** [GregTechCE/GregTech#63]
When power from a generator is being transferred to a battery buffer, it does not work if one cable is inbetween, as such:
![image](https://user-images.githubusercontent.com/37518092/40891675-5ffb2f32-6747-11e8-94ab-f3dfd15f8a10.png)

However, this works fine when there is either no wires (direct machine contact), or 2+ wires.

**Comment by Archengius** [comment]
read commit descriptions. it's already fixed in dev.
