### ISSUE TITLE
Can I take the fluid back that I put it in the machines

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#641]
Sometime I may pure wrong fluid to the machines and I want to put it back. Can I make it?
In addition, there are one or two buttons in the machines. Is that valid? How does it/they work?
![Untitled](https://user-images.githubusercontent.com/43509783/54443735-2abc2180-477c-11e9-96df-6756ab8ba7e6.png)

**Comment by Archengius** [comment]
buttons are auto-output for items/fluids
no, you cannot take fluid back from inputs

**Comment by alfuken** [comment]
Shouldn't you be able to do that with a plunger?..
