### ISSUE TITLE
Coke oven hatches are non functional

### ISSUE THREAD

**Issue by Saereth** [GregTechCE/GregTech#646]
![image](https://user-images.githubusercontent.com/9200909/54468342-ed4a9a80-4761-11e9-8b98-70621c5712ed.png)

no cables attach and The one probe reports it has not having an internal tank or inventory

**Comment by WarlordWossman** [comment]
Are you using the GA coke oven controller or is it just retextured on your end?
Only tested the GTCE coke oven on the first version it was included and hoppers worked fine afaik.

**Comment by Saereth** [comment]
nope, using this one
![image](https://user-images.githubusercontent.com/9200909/54468639-0f91e780-4765-11e9-8ad5-5ad38a883ba6.png)

**Comment by Shadows-of-Fire** [comment]
The texture may be different due to lingering assets in SoG, which are in the GT namespace and are overriding those ones.

**Comment by Archengius** [comment]
first of all, hatches can only be placed on the center of multiblock faces, and structure you provided is not formed.
