### ISSUE TITLE
Rubber Wood doesn't respect config option nerfWoodCrafting

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#649]
nerfStickCrafting is fine (Rubber turns into Jungle planks)

Tested in clean instance.

**Comment by Archengius** [comment]
because it's not registered as logWood

**Comment by pyure** [comment]
"because it's not registered as logWood and that's how I want it"
"because it's not registered as logWood, I'll correct it, thanks"
"idc" 
?

**Comment by Archengius** [comment]
i'm not going to correct it, because rubber wood cannot be used as ordinary wood, and that setting affects only logWood crafting recipes.

**Comment by pyure** [comment]
Alright
