### ISSUE TITLE
1 hit mob killing?

### ISSUE THREAD

**Issue by trilexcom** [GregTechCE/GregTech#65]
Forge : 2707

when i am on the server i can kill mobs by 1 hit, other players on the server that doesn't happen to them. 

Crashlog : https://gist.github.com/trilexcom/80172a1b2147309a321ffe7e599d4f37

Server Logs : https://github.com/GregTechCE/GregTech/files/2066604/latest.log
Server Log Zip file : https://github.com/GregTechCE/GregTech/files/2066605/2018-06-03-7.log.gz

**Comment by Archengius** [comment]
seems interesting, will try to investigate soon

**Comment by Archengius** [comment]
doesn't happen with me, can't confirm.
seems to be tools related issue.

**Comment by Rongmario** [comment]
e99999 - Today at 00:32
combat is normal until i use GT weapons then i can one hit kill anything open hand

**Comment by Rongmario** [comment]
Go through this method in ToolMetaItem.java:

``@Override
    public Multimap<String, AttributeModifier> getAttributeModifiers(EntityEquipmentSlot slot, ItemStack stack) {
        T metaValueItem = getItem(stack);
        if(metaValueItem != null && slot == EntityEquipmentSlot.MAINHAND) {
            IToolStats toolStats = metaValueItem.getToolStats();
            if (toolStats == null) {
                return HashMultimap.create();
            }
            SolidMaterial baseMaterial = getPrimaryMaterial(stack);
            float attackDamage = toolStats.getBaseDamage(stack) + (baseMaterial == null ? 0 : baseMaterial.harvestLevel);
            float attackSpeed = toolStats.getAttackSpeed(stack);

            HashMultimap<String, AttributeModifier> modifiers = HashMultimap.create();
            modifiers.put(SharedMonsterAttributes.ATTACK_DAMAGE.getName(), new AttributeModifier("Weapon modifier", attackDamage, 0));
            modifiers.put(SharedMonsterAttributes.ATTACK_SPEED.getName(), new AttributeModifier("Weapon modifier", attackSpeed, 0));
            return modifiers;
        }
        return HashMultimap.create();
}

**Comment by Archengius** [comment]
fixed
