### ISSUE TITLE
electrolyse red alloy dust inconsistancy

### ISSUE THREAD

**Issue by sinopike** [GregTechCE/GregTech#651]
1 cu + 4 redstone =alloy smelter=> 1 red alloy
5 red alloy =electrolysis=>1 cu + 4 redstone

**Comment by Archengius** [comment]
you get less than you put, and that's normal.

**Comment by sinopike** [comment]
normal but inconsistent, removing the electrolysis could be an improvement. Besides most other GT material are produced without loss with the right machine.
