### ISSUE TITLE
Increasing difficulty of game? 

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#653]
I just updated the version of this mod. However, I found some crafting tables were changed especially for the electronic circuits. I found the advanced electronic circuit need Ga and the players can get Ga by finding Zinc Ore. While I cannot find the generation of Zinc Ore in both game and config files.   
Is it a bug? Or just increase the difficulty of this mod.

Another one is about the cost of electricity. In NEI, washing 1 unit of crushed magnetite ore with water requires 6400 EU in total and cost 20 secs. In basic ore washer, only 6400EU required. But in an advaned one, it cost about 12800 EU. Why the electricity cost doubled and the time cost halved?

**Comment by Archengius** [comment]
1) You can get gallium from electrolyzing sphalerite or processing bauxite.
2) recipes requiring less EU/t than machine can provide are overclocked, energy consumption is multiplied by 4 and recipe duration is divided by 2

**Comment by 15103875d** [comment]
Many thanks. How huge changes are.
Is there any table for the distribution of ores?

**Comment by Archengius** [comment]
which changes? overclocking was always like that, and gallium was always like that too.
no, no distributions.

**Comment by 15103875d** [comment]
I used to use v1.5 but now v1.6. So I found the differences in crafting circuits. LOL
