### ISSUE TITLE
Rename "Advanced Circuit" item to avoid confusion

### ISSUE THREAD

**Issue by CelestialPhoenix** [GregTechCE/GregTech#656]
As per title
Item in question is metaitem:circuit.advanced
(<gregtech:meta_item_2:32490>)

Running Gtech 1.6.3.358

**Comment by CelestialPhoenix** [comment]
Just saw the uses for 'Advanced circuit' in JEI- this is actually a tier 2 circuit, with the tier 3 being the 'Processor Assembly'

Would suggest a rename to 'Improved circuit' or similar

**Comment by Archengius** [comment]
no
