### ISSUE TITLE
How can I make my first basic centrifuge?

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#658]
After v1.6 updates, the crafting of basic circuits became more difficult. One of the material is Coated Circuit Board, which required Rubber.
However, the only way to get rubber is using centrifuge itself. So is it a deadlock if I play with pure GTCE?.

![image](https://user-images.githubusercontent.com/43509783/54510616-100ac800-4989-11e9-9508-2a115a155b6a.png)

**Comment by Archengius** [comment]
Rubber Wood drops Rubber when harvested.
