### ISSUE TITLE
Ore spawning issue

### ISSUE THREAD

**Issue by Unknown700** [GregTechCE/GregTech#659]
Is ores suposed to spawn in veins because for me all vannilla ores like vannilla iron and diamond spawn and no gregtech veins. Is this a bug. Or can this be chanced somehow. Also i have instaled just Gt ce Ic2 codechicken lib and JEI so i don't think any of the mods cause the problem.

**Comment by Archengius** [comment]
Vanilla ore spawn can be disabled in config.

**Comment by Unknown700** [comment]
wich config? all i have is a config file named "worldgen_extracted" and the other configs seems to be for custom ore gen.

**Comment by Archengius** [comment]
config/gregtech.cfg
