### ISSUE TITLE
Eu to volts and vise versa

### ISSUE THREAD

**Issue by Unknown700** [GregTechCE/GregTech#664]
Is there a anything that lets you convert EU to GTCE energy? If not can it be added?

**Comment by Agrax** [comment]
GTCE uses EU. Ofc not IC2 eu, but that's intended. GTCE is not meant to be played with IndustrialCraft 2

**Comment by EmosewaPixel** [comment]
No, never

**Comment by Unknown700** [comment]
last question. I heared someone talk abaout an addon for this. Does this addon exist and if so can you say the name?

**Comment by pyure** [comment]
Two known addons:
* CEU adds transformer blocks to convert energy between RF(FE) and GT
* Gregic Additions is a general content-adding mod

**Comment by Unknown700** [comment]
ok thankyou @pyure , that awsners my question

**Comment by Agrax** [comment]
But the CEU author thinks abt adding IC2 support. The issue is... it’s not as easy
