### ISSUE TITLE
[Bug] Bucket recipe

### ISSUE THREAD

**Issue by LostDGod** [GregTechCE/GregTech#665]
This is what my bucket recipe looks like: 
![bucket](https://user-images.githubusercontent.com/13785053/54720817-4a768f80-4b58-11e9-879b-faeff63d9115.jpg)
It was like this in 1.6.2 and I updated to 1.6.4, rechecked the mod's dependencies and tried to load a new world with as less mods as possible, yet nothing worked. The only thing I haven't tried was updating forge because this version is compatible with all my mods and updating further breaks one of them.
version - gregtech-1.12.2-1.6.4.365
forge version - forge1.12.2-14.23.5.2784
crash report - N/A

**Comment by Agrax** [comment]
What’s wrong with the recipe? Looks fine to me

**Comment by LostDGod** [comment]
You're right. I only installed this mod because it was a requirement for another mod and I hadn't read much about it so I didn't know it made vanilla changes. Testing on creative mode with a max durability darmstadtium hammer I could make 1 iron bucket but then it wouldn't let me make another once the hammer's durability had fallen from 100%. This however seems to be some sort of mistake on my part because now that I've read a bit about the mod and tried again everything seems to be working fine so far.
This mod is much more fascinating than I had previously expected! I thank everyone who has worked on it so far and apologize for opening this useless issue when the issue was clearly on my end. Please close it.

**Comment by Agrax** [comment]
Glad you’re enjoying GTCE. It’s a really complicated mod, that’s best to be played in a modpack. I can suggest that you either play InfiTech 3 or FTB Interactions to get the full GT experience
