### ISSUE TITLE
There's still an Ashes>Carbon recipe

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#668]
![image](https://user-images.githubusercontent.com/25333164/54820925-fe833200-4ca0-11e9-8961-5c919bf2a509.png)
It should only have the first recipe that gives many small dusts

**Comment by Archengius** [comment]
not an issue on clean GTCE

**Comment by EmosewaPixel** [comment]
I did. The recipe exists because Ashes doesn't have the DISABLE_DECOMPOSITION flag.
