### ISSUE TITLE
2 Water recipes in the Electrolyzer

### ISSUE THREAD

**Issue by ProxyPlayerHD** [GregTechCE/GregTech#669]
title says it. for some reason there are 2 completely identical recipes for the electrolyzer that take in water and output Hydrogen and Oxygen

the only difference between them is the amount of energy they need. one requires 45000 EU the other only 2160 EU (which is a lot more reasonable)
![2019-03-22_20-32-15](https://user-images.githubusercontent.com/13576843/54848468-9b65bf80-4ce1-11e9-8dda-c8405a2484ea.gif)

**Comment by EmosewaPixel** [comment]
Same goes for Distilled Water

**Comment by Archengius** [comment]
you're right, except that correct one is first because water electrolyzing is expensive

**Comment by ProxyPlayerHD** [comment]
dammit. anyways, glad i was able to somewhat help i guess
