### ISSUE TITLE
A List of bugs/possibly unimplemented stuff and questions

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#67]
So 2 days ago I compiled the mod myself and found quite a few bugs, but didn't report them because I thought perhaps they simply weren't implemented yet. Seeing that the mod was publicly released, here's a list:
- [x] Cells seem to have a part of their texture missing and quite a few don't display the fluid's color on the front of the texture (mainly on molten metals)
![image](https://user-images.githubusercontent.com/25333164/40938699-d8a7ed98-6842-11e8-9864-55f71b24880f.png)
![image](https://user-images.githubusercontent.com/25333164/40938786-1478def4-6843-11e8-8300-e104bc6b12af.png)
- [x] These 2 Blast Furnace recipes
![image](https://user-images.githubusercontent.com/25333164/40938936-901c7610-6843-11e8-9784-80f311923577.png)
![image](https://user-images.githubusercontent.com/25333164/40938940-937765ae-6843-11e8-8055-3df5aeb0884e.png)
- [x] This one's more of a question. How are you supposed to get Rough Iron? Originally it was by smelting and iron nugget.
![image](https://user-images.githubusercontent.com/25333164/40939077-eb4286d8-6843-11e8-91a9-7c4751bb3859.png)
- [x] There is no (obvious) way of figuring out multiblocks. Originally, the required blocks were a tooltip on the main block and there was a button to visualize it in the GUI (I was expecting at least the former to be implemented)
![image](https://user-images.githubusercontent.com/25333164/40939183-3c0f7030-6844-11e8-970c-87850a1b21f0.png)
 - [x] There are tier V-VII (with two tier VIs) Electric Pumps that are uncraftable (the 5th one has a recipe, but the LuV Electric Piston required for it is uncraftable)
 - [x] A lot of Oil-related stuff is missing (the Cracker (unless you don't plan on bringing that back, seeing that there is no Cracker, in which case, you should remove the Cracked and Sulfuric Oils and Sulfuric Gas) and the Oil recipes in the Distillation Tower)
 - [x] ?
![image](https://user-images.githubusercontent.com/25333164/40940412-f9a41b0c-6847-11e8-8e88-37959ae081ec.png)
 - [x] Fusion Machine Casings have no/broken textures and the tier 2 one doesn't have a recipe (although I see the fusion stuff isn't really implemented anyways)
![image](https://user-images.githubusercontent.com/25333164/40940557-781e29e6-6848-11e8-997a-11ad0f6759f0.png)
 - [x] On the third JEI page for pulverizing ores, after the basalt version, there's a version of the ore with a missing texture (I'm guessing either the base texture is messed up, or you added stuff to the ore dict by mistake)
![image](https://user-images.githubusercontent.com/25333164/40941371-eab1745c-684a-11e8-9b04-9aaf0d0a5200.png)
 - [x] There is no way of turning Oil Sands into Oil and it probably shouldn't be treated as a regular Ore
![image](https://user-images.githubusercontent.com/25333164/40965387-d64528a2-68ad-11e8-93a2-ca80a8dc49b5.png)
 - [x] The Steam Alloy Smelter doesn't seem to work (when full with steam), yet it has recipes in JEI. This is progression-breaking. Also, I noticed there is no recipe for Red Alloy that uses a Copper/Annealed Copper Ingot.
![image](https://user-images.githubusercontent.com/25333164/40967590-b6046bb0-68b3-11e8-82e5-14339d4a8d3c.png)
 - [x] You can't click the progress bar to view all the recipe for said machine in JEI. It's simply a nice feature that many mods have.
![image](https://user-images.githubusercontent.com/25333164/40967927-a2e1b92e-68b4-11e8-9319-c90656e46d09.png)

 And that pretty much covers it for now. I will be adding game/progression-breaking bugs and unimplemented things as I go. I see Pure and Impure Dusts from ores that aren't pure metal being unobtainable was fixed, which 2 days ago was something I quickly noticed, so that's great. Good job guys. I can't wait till the mod gets out of alpha.

**Comment by Archengius** [comment]
fixed

**Comment by EmosewaPixel** [comment]
So in terms of issues, the first, fifth and second to last one weren't fixed. Additionally, Oil can't even be distilled in the distillery now.
