### ISSUE TITLE
Crash randomly while playing

### ISSUE THREAD

**Issue by ProxyPlayerHD** [GregTechCE/GregTech#670]
thanks to VanillaFix the game doesn't actually crash, but usually it would've

[LOG](https://pastebin.com/H9xyTym3)

all the required Information should be in there

**Comment by Archengius** [comment]
are you on latest? that was fixed already

**Comment by ProxyPlayerHD** [comment]
it was on the newest version

i updated before launching the pack (which was a few hours ago)
