### ISSUE TITLE
Petition to rename GTCE to ArchTech

### ISSUE THREAD

**Issue by x88888888** [GregTechCE/GregTech#671]
Basically just the repo and curseforge page could be renamed. Why you might ask? Because this mod has absolutely nothing to do with the community since you're the only one contributing to the mod and you aren't willing to listen to anyone's advice. If you decide to close this issue right upon seeing it(which you probably will) I won't care, but it will prove my point.

**Comment by Vyraal1** [comment]
Listening != Accepting everything

**Comment by Agrax** [comment]
Stirring the shit <3

**Comment by Archengius** [comment]
You didn't give any advice tho, and i didn't hear exact advices that were given and ignored.
