### ISSUE TITLE
Reinforced Stone Doesn't Have An Item Block

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#672]
I don't see why you'd want it not to have an item, so I'm assuming this is a bug.

**Comment by Archengius** [comment]
because it is made by spraying foam on a metal frame?

**Comment by EmosewaPixel** [comment]
What does that have anything to do with it? Without it having an item form you can't move it, so if you wanted to do so you'd be wasting at least 7 iron ingots. Furthermore, IC2's has an item form.

**Comment by Archengius** [comment]
1 frame costs 1.8 iron ingots, and it's not much to loose. I don't give a shit what IC2 has, it's GTCE and not IC2.
