### ISSUE TITLE
No Tetrahedrite Ore generation

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#673]
I found that the config file says it only appears in places whose height > 50. However, I cannot find any tetrahedrite ore...

**Comment by Archengius** [comment]
It does but pretty rarely

**Comment by 15103875d** [comment]
What kinds of terrains does it appear? Or it will appear in all terrains?
I found the Mn ores are also rare...

**Comment by Archengius** [comment]
all terrains. i'll probably add priorities and mn as byproduct, because currently i'm re-designing ore usability in general. thanks for advice.

**Comment by 15103875d** [comment]
Yep. Because Sb is necessary for batteries. Too rare of ores could make it too difficult to play

**Comment by Archengius** [comment]
it is a byproduct or bornite which is pretty common.

**Comment by 15103875d** [comment]
Thx. I found the cuprite can offer it.
