### ISSUE TITLE
The air cannot be collect by tubes

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#674]
![2019-03-24_23 22 13](https://user-images.githubusercontent.com/43509783/54881507-bc6a1400-4e8b-11e9-875d-51a59b8a5292.png)
I've tried to collect air via air collector and output it to a tank. However, if I use tube to collect air from the tank, it does not work. In addition, the air in the tank reduced but there is no tube contains air.

**Comment by Archengius** [comment]
because you are in creative mode.
