### ISSUE TITLE
Rubber Trees sometimes forget how to produce rubber

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#681]
Posting this cuz multiple people have reported it, but I'm not sure how to reproduce it.

Possibly the trees lose the capability when server restarts (not yet tested)

**Comment by Archengius** [comment]
they don't loose anything, just looked up source code

**Comment by pyure** [comment]
User AkiraSomethingOrOther was able to reproduce this with just Gregtech.  Can you please revisit?
