### ISSUE TITLE
Distillation Tower seen haven't no input hatch in displayed help

### ISSUE THREAD

**Issue by FoxZOolm** [GregTechCE/GregTech#682]
'Lo,
I try to make the distillation tower (survival).
but in the displayed helper I don't found where place the input hatch ?
I try to make it like gt5u (https://ftb.gamepedia.com/Distillation_Tower_(GregTech_5_Unofficial))
but it always says "incorrect structure".
What's I'm doing wrong ?
(no error log, sponged)

**Comment by Archengius** [comment]
bottom center. look carefully

**Comment by FoxZOolm** [comment]
well no.. I don't see it ???
I see only output hatch, output bus, input energy hatch and controler...
but noooooo input hatch for liquid... I'm so blind ?
I had tested all bottom possibility
![2019-03-27_23 27 04](https://user-images.githubusercontent.com/6440815/55119223-eec47d00-50e8-11e9-9be3-c5829a9a83fd.jpg)
 without succes

gregtech-1.12.2-1.6.4.365 forge 14.23.5.2814 (needed by RailCraft)

**Comment by FoxZOolm** [comment]
I found it ! my bad !
running perfectly :+1:
