### ISSUE TITLE
Cable issues

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#685]
- tin wire + rubber - assembler -> tin cable (probably autogenerated)
- tin cable - macerator -> tin dust + rubber dust (a result of the earlier recipe)
- you can separate bigger cables into smaller ones (doesn't make sense tbh)

Those are weird recipes which are either cheaty workarounds or autogenerated trash recipes.

**Comment by Archengius** [comment]
Fixed

**Comment by Kanzuke117** [comment]
FTB:Integrations just updated to include these changes and I'm missing cable splitting/joining a lot already. Could we at least get a way to strip the rubber/wool from cables so they aren't immediately worthless if we need to up the amperage of a machine line or something.

**Comment by hobnob11** [comment]
could i suggest using the unpackager for this, since the packager can wrap wires
