### ISSUE TITLE
Two electrolysis crafting of water

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#686]
One costs 45000 EU with power 30EU/t, last 75 seconds.
The other costs only 2160 EU with power 30EU/t, last 3.6 seconds.

**Comment by Archengius** [comment]
are you on latest?

**Comment by Archengius** [comment]
i'll start banning people reporting issues which are invalid on latest version soon and not looking up closed issues

**Comment by 15103875d** [comment]
sry. I'll update it
