### ISSUE TITLE
Only one vein is generated per ore per section, ignoring minVeinsInSection setting

### ISSUE THREAD

**Issue by alfuken** [GregTechCE/GregTech#688]
If you set `minVeinsInSection` around 200 or so, and set all ore config entries radius to 1-2 (so they all fit), you'd expect to have at least 200 small chunks of ore in section (3x3 chunks area). But instead it does not generate more than one ore deposit group per section, without reaching minimum 200.

**Comment by Archengius** [comment]
exactly, and that's how it work

**Comment by alfuken** [comment]
Well, one would expect to see 200 deposits, if 200 is set as a minimum. Current behaviour is not really obvious. But if that's not a bug, then ok, I can accept it.
