### ISSUE TITLE
Unimplemented features/bugs

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#69]
- [x] There's no recipe for an advanced compressor IV at all, but there are 2 recipes for an adv. compressor III
- [x] HV, Luv, ZPM, Max rotor holders don't have a recipe, what is weird, bcoz UV rotor holer does own one
- [x] Advanced pumps VI through VII (VIII?) don't have recipes. UV pump is called "advanced pump VI", when it should be called "advanced pump VII" and the MAX one should be called "advanced pump VIII"
- [x] Blocks of aluminium, cobalt, copper, platinum, nickel, praseodymium, scandium, samarium, holmium, silicon, iridium, indium, lead, lithium, magnesium, manganese, invar, glauconite sand, silver, titanium, tin, wrought iron, graphite, soldering alloy, stainless steel, steel and antimony don't have recipes

**Comment by Archengius** [comment]
blocks do have recipes

**Comment by Archengius** [comment]
fixed
