### ISSUE TITLE
No ‘Sort’ button for large chests.

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#690]
For those chests whose capacity is larger than 90, the 'sort' button could not be found due to the arrangement.
![2019-03-31_03 05 01](https://user-images.githubusercontent.com/43509783/55280532-d9a65300-5361-11e9-9e49-5e63ffe013de.png)

**Comment by Archengius** [comment]
use larger screen, chest itself is too large

**Comment by Exidex** [comment]
oof

**Comment by quizzmaster** [comment]
> use larger screen, chest itself is too large

you easily could have changed the gui to fit to smaller screens.
