### ISSUE TITLE
[suggestion] Pipe outlines allowing to put covers in different directions

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#691]
For now i can only put a cover on the side im looking at. Would be cool if pipes had the same outline system as machines do so that:
- i can put covers on pipes without destroying other mods’ machines
- use a screwdriver „remotely” on the pipe, by clicking on the corresponding corner i can open the cover GUI. That’s a QoL improvement

**Comment by Archengius** [comment]
Fixed
