### ISSUE TITLE
Empty Cells should stack with New Cells

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#696]
Once a cell is emptied of liquid, it should revert to the same state as a New cell (no nbt).

**Comment by Archengius** [comment]
nope

**Comment by pyure** [comment]
Why?

**Comment by Archengius** [comment]
Because it's forge standard fluid handler implementation issue, and I have
no wish to mess with it

**Comment by pyure** [comment]
That's fair, thanks.
