### ISSUE TITLE
Galena Ore composition and usages make no sense

### ISSUE THREAD

**Issue by BitsBytesGaming** [GregTechCE/GregTech#699]
Galena Ore is commonly just PbS (lead (II) sulfide) with minor silver impurities, while in this mod it is Pb3Ag2S, which makes no sense because lead and silver would not intrinsically bond with themselves. Galena ore is a mixture of mostly (~98%) PbS with maximum ~1-2% Ag and negligible amounts of other impurities such as iron, copper, and cadmium.

Additionally, there is no recipe to convert galena dust into lead ingots via direct smelting, even though (IRL) thermal composition of PbS can be generalized as follows:

2 PbS + 3 O2 → 2 PbO + 2 SO2
PbO + C → Pb + CO

**Comment by Archengius** [comment]
it's not real life, and galena ore is primary source of silver.
this is not going to change.

**Comment by BitsBytesGaming** [comment]
Please explain why there is silver ore then

**Comment by Archengius** [comment]
because it is sporadic in galena vein
