### ISSUE TITLE
Add direct smelting for coal, lignite, Tetrahedrite, Magnetite, etc

### ISSUE THREAD

**Issue by ProfessorCool** [GregTechCE/GregTech#70]
On Gregtech 1.7.2, most direct smeltables do not have smelting recipes. Currently, these don't have recipes:

- Coal
- Brown Limonite
- Yellow Limonite
- Tin
- Cassiterite
- Tetrahedrite
- Copper
- Stibnite
- Pyrite
- Sphalerite
- Chalcopyrite
- Malachite
- Cinnabar
- Garnierite
- Cobaltite
- Pentlandite
- Sheldonite
- Molybdenum
- Molybdenite
- Pyrolusite
- Magnesite

Additionally, for all of the ore varieties that do smelt properly, if it is not a pure stone ore, but for example ore in andesite or granite, the ore does not smelt. These ores seem to only work in netherrack, gravel, or in smooth stone.

I used the GregTech 5 Mining and Processing wiki for information on what should direct smelt.

**Comment by Archengius** [comment]
done
