### ISSUE TITLE
[Suggestion] Level 4 batteries

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#701]
Dear developer,  I suggest that the level 4 batteries and corresponding boxes could be added to the mod. Since that most machines have its EV version, which corresponds to 2048EU/t. If lv4 batteries can be applied, it could be more convenient for the users.

**Comment by Black0305** [comment]
Lapotron Crystal is level 4 battery and it is in the game already

**Comment by Archengius** [comment]
see above

**Comment by 15103875d** [comment]
Another question.
Can the hatches of multi-block machines be replaced with high voltage ones?
and
Can the block be replaced with hatches?
