### ISSUE TITLE
NPE  CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by ProsperCraft** [GregTechCE/GregTech#703]
https://gist.github.com/ProsperCraft/c288fb7b54cb874d2baedfae70eef6f2

gregtech-1.12.2-1.6.9.382
Forge 2814

Modpack- https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by Archengius** [comment]
No idea what's going on there, probably another mod issue

**Comment by KaneHart** [comment]
@ProsperCraft ever figure it out?

**Comment by ProsperCraft** [comment]
Have not been testing, lately.

**Comment by Blazer4Hire** [comment]
I have found that the mod that causes this error to be spammed in the chat is SGCraft. I don't know why yet, but what I do know is that having SGCraft installed will cause the error to show up.
