### ISSUE TITLE
Invalid Wood Slab Recipes + Cannot ignore invalid recipes in dev environment

### ISSUE THREAD

**Issue by TheLMiffy1111** [GregTechCE/GregTech#705]
GregTech seems to be unable to generate Cutting Saw recipes for certain planks if their slab counterparts do not exist. Found this error while updating mods for JAOPCA.

I know crashing Minecraft when invalid recipes exist in dev is intended, but please somehow make ignoring these errors possible without editing variables.

**Comment by Archengius** [comment]
no crashlog, no invalid recipe stack traces, closed.

**Comment by TheLMiffy1111** [comment]
what about the second part

**Comment by Archengius** [comment]
it is intended and won't be changed
