### ISSUE TITLE
Railcraft coke oven now produces textureless creosote after adding Gregtech.

### ISSUE THREAD

**Issue by ProsperCraft** [GregTechCE/GregTech#706]
After adding Gregtech to my Modpack- https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

The existing creosote in containers has turned to have no texture, the creosote in the world now looks different but has a texture.

![2019-04-03_10 10 24](https://user-images.githubusercontent.com/4427684/55494908-f90add80-55f8-11e9-86af-f0b18f5bd021.png)
![2019-04-03_10 10 36](https://user-images.githubusercontent.com/4427684/55494909-f90add80-55f8-11e9-9638-830b2d6ac30c.png)

**Comment by Archengius** [comment]
give log

**Comment by ProsperCraft** [comment]
[DrTARDIS2Serverlog.zip](https://github.com/GregTechCE/GregTech/files/3039813/DrTARDIS2Serverlog.zip)

**Comment by Archengius** [comment]
cannot reproduce

**Comment by ProsperCraft** [comment]
Did you try in a server/client situation? because that is where it happens.

**Comment by Archengius** [comment]
server has nothing to do with textures

**Comment by Archengius** [comment]
and you didn't provide client log at all also

**Comment by ProsperCraft** [comment]
https://github.com/Railcraft/Railcraft/issues/1746

**Comment by ProsperCraft** [comment]
Unable to reproduce in single player, here are the logs from the client logging in to the server.

[ClientLlogs.zip](https://github.com/GregTechCE/GregTech/files/3055333/ClientLlogs.zip)

**Comment by Archengius** [comment]
then fluid-related issues caused by duplicate fluids which is not gtce issue
