### ISSUE TITLE
Steam is missing a texture.

### ISSUE THREAD

**Issue by ProsperCraft** [GregTechCE/GregTech#708]
![2019-04-03_21 07 05](https://user-images.githubusercontent.com/4427684/55527031-9810f300-5654-11e9-807b-6b61b28f74a2.png)

gregtech-1.12.2-1.6.9.382

Forge 2824

Modpack - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by ProsperCraft** [comment]
MIght be related to https://github.com/GregTechCE/GregTech/issues/706

**Comment by Archengius** [comment]
cannot reproduce in dev
