### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#71]
- [x] There seem to be 2 different IV Compressors in JEI. Both the EV and the IV recipes make IV Compressors.
- [ ] There is an Electrolyzer recipe that turns 141 Zeolite into things. That is obviously not possible. One with 66 Bentonite as well.
- [x] There are 2 different recipes for turning Hydrogen Sulfide into Sulfuric Acid. One uses 2000 Water and one uses 4000 Water.

**Comment by Archengius** [comment]
only way second can be fixed is adding second input slot. it's not issue of recipe itself, but zeolite that contains components in unusual amount and proportions.

**Comment by Archengius** [comment]
let's pretend that zeolite and bentonite are possible to electrolyze only in multiblock :p
