### ISSUE TITLE
Multiplayer server not updating clients on pipe placement.

### ISSUE THREAD

**Issue by ProsperCraft** [GregTechCE/GregTech#710]
When another player places a pipe, I can not see it, but I can see the bounding box if I look directly at it.  When I place it, I see it, but he can not.

gregtech-1.12.2-1.6.9.382

![2019-04-03_23 11 34](https://user-images.githubusercontent.com/4427684/55531066-07431300-5666-11e9-9e25-602abb470ee1.png)

**Comment by ProsperCraft** [comment]
Redrawing chunks with F3+a does not show them, but a full relog does.

**Comment by Annwan** [comment]
I'm using version gregtech-1.12.2-1.8.1.399 and despite it should have been fixed since GTCE 1.7.0 I'm experiencing, me and a friend of mine, the same issue
