### ISSUE TITLE
How does the pumps(machine) works?

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#714]
I found some oilfields and use the pumps to help me collect oil.
While sometimes it seems to stop to work. And the only difference between the three machine pumps is the frequency of collecting.
How deep could a pump dig? Can I collect all oil by putting a pump on the ground?

**Comment by Archengius** [comment]
dig depth is unlimited, and yes, you can. difference in tiers is speed only.

**Comment by 15103875d** [comment]
So what does the range 32*32 means? the radius or diameter? It seems asymmetric if the diameter is 32.
