### ISSUE TITLE
The pump(machine) seems to stop working when it dig to the bedrock

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#717]
The pump stops working at the bottom of the drill hole although most oil exists under it.

![2019-04-07_17 57 40](https://user-images.githubusercontent.com/43509783/55681913-c5b0b180-595e-11e9-9371-b1a2f4a46329.png)
![2019-04-07_17 57 51](https://user-images.githubusercontent.com/43509783/55681916-c77a7500-595e-11e9-81c4-953eeba2ba9d.png)
The pump seems to stop working at this moment. 
However, if I re-enter the server, it can collect some oil and stops again after it

**Comment by Archengius** [comment]
cannot reproduce, dare to describe a little bit more?
