### ISSUE TITLE
[Suggestion] Tiny Cell

### ISSUE THREAD

**Issue by Ar4093** [GregTechCE/GregTech#721]
Since a couple of recipes use 144mB of a resource that might be produced in other quantities (1000mB etc.), for example Ethylene, it would be nice to have a smaller cell type that can hold 144 mB.
This would mostly be to reduce wasted fluids since fluids can't be retrieved from input tanks, so they could be made from some mid-game material like stainless steel.

**Comment by Archengius** [comment]
in latest releases you can retrieve fluids from input tanks
