### ISSUE TITLE
Chainsaw issue

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#724]
Cutting down a 2x2 spruce. When the energy goes out, the tool breaks (dissapears) without even leaving the lunchbox. First of all, that's retarded, because the tool had more than 90% durability. It just went out of juice, not durability. It shouldn't ever break in that case :/

Most probably it doesn't leave a tool box, because:
1.  it has almost full durability
2. Power acts like a temporary durability, so the tool thinks it has zero durability
3. I use it on very tall trees. Let's assume it has the energy to cut down 10 more blocks of wood, but the tree is 15 blocks tall. So it depletes the energy, but then the energy goes to negaitves (built-in treecapitator makes sure it chops down the whole tree). Energy cannot be negative, so the game removes the tool.

Those are just my assumptions

(Tested on .387)

**Comment by Agrax** [comment]
Just used up whole durability of a chainsaw, 40% of energy left. The tool broke without leaving a tool box

**Comment by Black0305** [comment]
Same problem with the JackHammer. Tool just dissappears after it runs out of energy, regardless of the durability.
(version .387)
