### ISSUE TITLE
The Branch Cutter doesn't work as it should

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#726]
The Branch Cutter is supposed to give Leaves a 100% chance of dropping a Sapling. This currently isn't the case.

**Comment by Archengius** [comment]
Good point, will remove that useless tool i guess.

**Comment by Agrax** [comment]
Speakin of tools: You could either remove the electrical screwdriver or actually give it a recipe. I'd prefer the latter

**Comment by jnaset** [comment]
Don't kill the branch cutter!  It'd be so nice to have an alternative to the forestry grafter and its 10-use durability.
