### ISSUE TITLE
Smelting recipes still incomplete

### ISSUE THREAD

**Issue by ProfessorCool** [GregTechCE/GregTech#73]
A lot of direct smelting recipes were addressed in #70, but there are still 3 ores that don't smelt directly in their pure stone states. Those being:
- Tin
- Copper
- Molybdenum

Strangely enough, tin and copper ores smelt properly when in netherrack, gravel, end stone, or sand, but not in smooth stone, or other stone variants (ore dictionary issue?). Molybdenum ore does not smelt into molybdenum in any form.

Additionally, for every other ore in GT, only only one form of every oredictionary name smelts properly (only smooth stone from ore[insert ore name] and only standard sand from oreSand[insert ore name]).

**Comment by Rongmario** [comment]
How are you getting Molybdenum ore may I ask? Only Molybdenite is being generated?

**Comment by ProfessorCool** [comment]
Ah, I didn't realize it didn't generate. I was just going off the old wiki, and the fact that it's in Gregtech CE. I think all the rest stands however.

**Comment by Rongmario** [comment]
No worries. Some ores just don't generate or exist anymore, such as molybdenite, plutonium, phosphate, sheldonite and such.

**Comment by Archengius** [comment]
ore dictionary issue.

**Comment by Archengius** [comment]
however, i have one idea
