### ISSUE TITLE
[Suggestion] Rubbers

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#731]
Higher tier cables needing better insulations. You brought styrene-butadiene rubber, silicone rubber n'stuff, but haven't actually implemented them as possible rubbers.

Common rubber- LV-HV
Styrene-butadiene- LV- LuV (but LV-HV are cheaper)
Silicone rubber- LV-MAX (but LV-LuV are cheaper and LV-HV are twice as cheap)

Additionally UV and MAX used foils of the proper material and smth else (but i might be totally wrong)

**Comment by RedCorpIndustry** [comment]
This is a good idea, gives more uses to these higher-tier rubbers.
