### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by kobliznik** [GregTechCE/GregTech#734]
Hello!

There is a missing texture when ore nugget is spawned in water on surface:

![2019-04-12_15 15 41](https://user-images.githubusercontent.com/8217189/56041030-0ed67c00-5d38-11e9-85d8-374617a13dc2.png)

![2019-04-12_15 33 19](https://user-images.githubusercontent.com/8217189/56041155-58bf6200-5d38-11e9-8a0e-885d5d484340.png)

Minecraft version: 1.12.2
Forge version: 14.23.5.2768
GT CE version: 1.6.2.189

**Comment by Agrax** [comment]
> GT CE version: 1.6.2.189

Dafuq? Don't you ever play such outdated versions:
https://minecraft.curseforge.com/projects/gregtechce/files/2697605

This is the newest one. Your version is 200 versions outta date

**Comment by kobliznik** [comment]
Fixed. I totally forgot to update mod for a long time. Thanks!
