### ISSUE TITLE
[Suggestion] Disassembling machines

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#735]
A way to disassemble machines and pipes into their most basic components (dusts? ingots? components like motors and cables?)

**Comment by BlueCreeper160** [comment]
Nice idea.

**Comment by Archengius** [comment]
Nope for machines.

**Comment by Archengius** [comment]
Done for pipes btw

**Comment by Agrax** [comment]
So what to do with old machines? Like with the bronze ones?

**Comment by Archengius** [comment]
nothing. store them. idk. implementing component-based recycling is difficult and doesn't worth the trouble.

**Comment by Agrax** [comment]
Then make it smeltable into ingots/nuggets...

**Comment by Archengius** [comment]
and imagine if somebody adds different recipe for some machine? how would i calculate how much materials machine should give after recycling? building complex graph of crafting dependencies between materials just to implement some retarded feature that won't be used on 9/10 of the machines?
I repeat again, machine WILL NOT be recyclable IN ANY WAY.

**Comment by Agrax** [comment]
I mean... Someone *has* to do it. Whether it’s you or packdevs

**Comment by Black0305** [comment]
Not sure why someone has to do it. Like 99% of mods dont have a way to disassemble things

**Comment by Archengius** [comment]
Nobody has to do it.
How often do you disassemble machines from other mods? How many mods allow
you to do that for their machines? How do they handle it?

However, if you would describe a way to implement such feature that way it
would:
A) work for all ways machines and their components are created.
B) not cause any regressions of current functionality or bring additional
overhead.
you're welcome.

**Comment by Agrax** [comment]
Well then. It’s up to packdevs :)

**Comment by Archengius** [comment]
Give solution that follows two criteria above and it wi be implemented.

**Comment by Agrax** [comment]
A) idc nuff
B) im 2 dumb to think of smth
C) packdevs can do that non-dynamically, but it’s fine
