### ISSUE TITLE
No Radon recipe?

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#736]
I've upgraded my server to v1.7.0 and find there is no recipe for Radon(Rn), which means I cannot upgrade my machine to EV level.
Are there any other ways for recipe EV level machine? Or you may need to add the recipe of Radon.

**Comment by BlueCreeper160** [comment]
So strange, the recipe of radon is here:
https://ftbwiki.org/Radon_(GregTech_5)

-6 plutonium ingots in a chemical reactor makes 6 plutonium dust and 100mb of radon

**Comment by BlueCreeper160** [comment]
I see... There's not radon recipe
