### ISSUE TITLE
[Suggestion] Isotopes

### ISSUE THREAD

**Issue by BlueCreeper160** [GregTechCE/GregTech#737]
For a better compat with Nuclearcraft, and just only 1 or 2, (the plutonium has 1).

**Comment by kotelkonrad** [comment]
nuclearcraft <3 gregtech best friend

**Comment by Agrax** [comment]
You can use the CT integration to add pretty much anything you want to GTCE

**Comment by BlueCreeper160** [comment]
> You can use the CT integration to add pretty much anything you want to GTCE. I hope i helped.

I use this to create an ingot from the material?
var ingotMaterial = MaterialRegistry.createIngotMaterial(2052, "boron11", 0x1a2f3e, "ingot", 1);

**Comment by CelestialPhoenix** [comment]
1) You can use a colour picker. (just whack 'colour picker' into your browser/search engine)- you might need a bit of trial and error to get the right match.

2) You can look it up in game- use F3+H for advanced tooltips, or type `m/t hand` while holding an item of that material. Its the last 3 digits of the metadata. So `<gregtech:meta_item_1:3623>` is for material 623.
IDs 001-500 are used by stock Gtech. Unless something changed, I think the range is limited to 001-999

With your script- try using "shiny" or "dull" for your iconSet.

**Comment by Agrax** [comment]
500-999 are free to use if you’re not using GA, which uses id range 800-999

**Comment by BlueCreeper160** [comment]
> With your script- try using "shiny" or "dull" for your iconSet.
-Can I use metallic, opal, ruby, etc.?

**Comment by BlueCreeper160** [comment]
> 1. You can use a colour picker. (just whack 'colour picker' into your browser/search engine)- you might need a bit of trial and error to get the right match.

Is in RGB format or antoher?

**Comment by CelestialPhoenix** [comment]
> > With your script- try using "shiny" or "dull" for your iconSet.
> 
> -Can I use metallic, opal, ruby, etc.?

I guess it'll work at the technical level, but there might not be a full set of icons for each one. (gemstone icon set might not have an ingot texture).


> > 1. You can use a colour picker. (just whack 'colour picker' into your browser/search engine)- you might need a bit of trial and error to get the right match.
> 
> Is in RGB format or antoher?

RGB value

**Comment by BlueCreeper160** [comment]
If I want to create an ore. What would be the ID range. The same?

**Comment by CelestialPhoenix** [comment]
> If I want to create an ore. What would be the ID range. The same?

Its all done in the same script; you'll use the add flags function to generate the extras.
https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Material/

```
#Psudobrookite
val gempsudobrookite = MaterialRegistry.createGemMaterial(624, "psudobrookite", 0x1B1B1B, "gem_horizontal", 3, [<material:iron>*1, <material:rutile>*1, <material:oxygen>*3], 1.0, 0);
gempsudobrookite.addFlags("GENERATE_ORE");
```

**Comment by BlueCreeper160** [comment]
WHOOOHOOO!!

![2019-04-14_16 06 21](https://user-images.githubusercontent.com/46793684/56099194-53485000-5ecf-11e9-959f-9f10e4e603e3.png)

**Comment by BlueCreeper160** [comment]
Why it's says material.exitonium?

**Comment by BlueCreeper160** [comment]
It's time to create isotopes (probably more)!!

**Comment by Agrax** [comment]
`Why it's says material.exitonium?`

You need to add an entry in the lang file, like that:

https://github.com/pyure/infitech-prototype/blob/master/resources/gregtech/lang/en_us.lang
