### ISSUE TITLE
Crash while loading. (Can't even get in game)

### ISSUE THREAD

**Issue by ScienceDrummer** [GregTechCE/GregTech#738]
VanillaFix says it's Gregtech. Tell me if wrong otherwise. 

Crash Report: https://paste.dimdev.org/orovakuxab.mccrash

Log: https://paste.dimdev.org/uralayimok.md

**Comment by BlueCreeper160** [comment]
Yes, It's say Gregtech. But I'm not sure if is gregtech the problem.

**Comment by ScienceDrummer** [comment]
Well if it isn't GregTech's problem, at least they'll point me to where I need to report it.

**Comment by Archengius** [comment]
no idea what is causing that, but it's not something that can be solved on GTCE side.

**Comment by ScienceDrummer** [comment]
It appeared to be a FoamFix issue, so I'll take it up with them.
