### ISSUE TITLE
Some machines reingest fluids immediately after exporting them

### ISSUE THREAD

**Issue by jnaset** [GregTechCE/GregTech#741]
In some cases machines which can export fluids and have recipes using the same fluids they export as inputs, can immediately reingest the fluid after exporting it to a pipe.  This happens frequently to me using the chemical reactor to desulfinate light fuel -- the light fuel gets pushed into a pipe and then immediately flows back in (the same side it was pushed from) as an ingredient to the hydro-cracked light fuel recipe.

A work-around for this behavior is disabling the machine's export function and using a pump cover instead.

To prevent this from occuring, machines could reject pipe input from the side of the machine that it is pushing fluids out of.

**Comment by codewarrior0** [comment]
Back in GT5, the output side initially did not accept input and needed a whack with a Screwdriver to "Allow input from output side".
