### ISSUE TITLE
[Suggestion]rubber suits

### ISSUE THREAD

**Issue by ppoozl** [GregTechCE/GregTech#742]
Since GTCE doesn't request IC2 for dependency. Can you add rubber suits to GTCE so that I can avoid taking damage from having hot ingots?

**Comment by jnaset** [comment]
On the topic of armor items we used to have from IC2, is there any chance of implementing the Nano Suit?

**Comment by Agrax** [comment]
Quantum/nano was an addon to IC2, called GraviSuite.

And ofc, such things will be added eventually. The thing is there’s literally one programmer and that means the team is heavily under-staffed, resulting in the project taking, unfortunately, longer to be fully developped. There’s a lot of thongs that need implementation and there’s only so much Archengius can do on his own.

**Comment by Proha5** [comment]
**Agrax**, Archengiu is inadequate.
I posted bug in discord and him baned me. (i can't acces to GTCE discord anymore)
I post the bug to github (https://github.com/GregTechCE/GregTech/issues/834)  and he closed the post. Why? i not understand. What did I do wrong for him?
Players, never post any bugs for GTCE. This man may ban you. Without reason.

**Comment by MineTech123** [comment]
IC2 and GTCE are separate mods now so just do something else

**Comment by Archengius** [comment]
btw i've just re-read title and no, you will always have damage from hot ingots because you shouldn't be carrying them with bare hands
