### ISSUE TITLE
Rendering issue causing spam in chat and console

### ISSUE THREAD

**Issue by ArchitektRadim** [GregTechCE/GregTech#744]
![1](https://user-images.githubusercontent.com/45514318/56096874-ca8cdc80-5eed-11e9-8a83-46d0b9f00f89.png)
![2](https://user-images.githubusercontent.com/45514318/56096876-cd87cd00-5eed-11e9-8943-bce2505adb0f.png)
![3](https://user-images.githubusercontent.com/45514318/56096877-cf519080-5eed-11e9-9ca7-b06dbb563817.png)

It seems like major CClib-GTCE problem. I am using the newest version of GTCE and CClib also. I haven't found any way to disable these glithy underwater metal cubes, so I'm posting it here...
The game is actually unplayable with this, because of massive chat spam - message for every "gregtech.common.blocks.surfacerock.BlockSurfaceRockFlooded" being rendered.
My modlist: https://pasteboard.co/Ia83LVF.png

Edit: OptiFine fixes it well

**Comment by Archengius** [comment]
you didn't provide even full log. Closed.
