### ISSUE TITLE
java.lang.VerifyError: JVMVRFY012 while editing machine recipes by CT in the latest version of GTCE

### ISSUE THREAD

**Issue by MaxWuhy** [GregTechCE/GregTech#746]
my .zs file:
https://paste.ubuntu.com/p/hgSNW5vywc/
crafttweaker.log:
https://paste.ubuntu.com/p/NTSMtYjs8x/
the same scripts work with gregtech-1.12.2-1.6.7.377,but throw out an error with 1.7.0.384
I'm using openjdk

**Comment by Archengius** [comment]
either CT or your JDK build issue
