### ISSUE TITLE
Suggestion: Display current recipe's overclocked EU/t in machine GUI

### ISSUE THREAD

**Issue by jnaset** [GregTechCE/GregTech#749]
I'm never quite sure machines decided to overclock or not... And in the case of the EBF it would give additional confirmation about the free overclock provided by higher heat.

It would be nice, then, if the current recipe's EU/t, taking into account overclocking, could be displayed in the machine's GUI.  (Might need to wait for an opportunity to overhaul the machine GUIs to have room to put it though)

**Comment by Agrax** [comment]
A) better coils don’t overclock in GTCE :)
B) machine ALWAYS overclock if they have a room for that (for now). So... Everything below and equal to 8 overclocks (4x the energy usage, 2x less time) at LV. If you have a recipe using 18 eu/t, it’ll overclock only at MV+ (72 eu/t out of 128 eu/t available). Simple maths

**Comment by Archengius** [comment]
no need to pollute machine GUI even more
