### ISSUE TITLE
Input Hatch tier gets incremented within controller GUI

### ISSUE THREAD

**Issue by Rongmario** [GregTechCE/GregTech#75]
Look at top left + in GUI
![Look at top left + in GUI](https://user-images.githubusercontent.com/3684700/41056508-f9793ec2-69f6-11e8-9735-1f1f9a8c346f.png)

**Comment by SuperCoder7979** [comment]
Energy hatches can input 2 amps. so that is 512EU * 2amps = 1024. So it's not a bug, it's a feature! ;)

**Comment by Antifluxfield** [comment]
@SuperCoder7979 I think the point is that: it's 512V * 2A = 1024EU/t. This result is the [power](https://en.wikipedia.org/wiki/Power_(physics)), not the [voltage](https://en.wikipedia.org/wiki/Voltage), but EV is the tier of voltage, not power.
