### ISSUE TITLE
Glass ore missing texture

### ISSUE THREAD

**Issue by BlueCreeper160** [GregTechCE/GregTech#753]
I do this:
`var glass = <material:glass>;
glass.addFlags(["GENERATE_ORE"]);` but some items like crushed, purified and centrifuged glass have a missing texture.

-Why I created glass ore? I don't know.

**Comment by Agrax** [comment]
I believe it’s caused by the lack of glass ore in the GLASS type iconset. Most probably intended as no sane person would ever mine glass from under the ground

**Comment by Archengius** [comment]
Not all iconsets have all textures, don't do dumb things
