### ISSUE TITLE
Electricity not behaving as expected

### ISSUE THREAD

**Issue by TheBugler** [GregTechCE/GregTech#754]
From what I understand, in GTCE, P=IV, where P=EU/t, I=Amperage, and V=Voltage.
For example: when trying to power the thermal centrifuge crushed sapphire ore recipe (2A, 32V, 48EU/t) I should be able to use 2 steam turbines to satisfy this (2 x 1A x 32V = 64EU/t). However hooking 2 steam turbines directly to a thermal centrifuge does not satisfy this recipe, and the buffer decreases. The same goes for a battery buffer with 2 batteries inside. I would expect an output of (2A x 32V = 64 EU/t) more than enough to power the 48 EU/t requirement of the recipe.

Am I missing something obvious?
I have posted some screenshots of my setups below
The first uses 2 batt buffers with 2 batteries each, and powers the centrifuge fine, but the second uses one battery buffer with 4 batteries. Is this because of the "packet" system? In the first case I assume each batt buffer is sending individual 2A, 32V packets that can be accepted by the centrifuge, but the second is sending 4A, 32V packets that are halved when they enter the centrifuge because it can only accept 2A?
![2019-04-16_13 32 17](https://user-images.githubusercontent.com/49694947/56236414-87e71380-6057-11e9-9814-4897fcc7511a.png)
![2019-04-16_13 37 07](https://user-images.githubusercontent.com/49694947/56236415-87e71380-6057-11e9-9903-7393e5d9ad5a.png)
![2019-04-16_13 31 52](https://user-images.githubusercontent.com/49694947/56236416-87e71380-6057-11e9-871d-ed265fbba57b.png)

**Comment by Vyraal1** [comment]
Just confirmed this also happens in an instance with GT 387

**Issue**
You need 4x LV diesel generators with a 4x cable to power an LV Thermal Centrifuge to turn Crushed Green Sapphire into Aluminium.
