### ISSUE TITLE
Can I control the RPM of rotors?

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#756]
For large gas turbines, can I control the RPM of rotors? because 6000 RPM cost too much fuel and I don't need such high powers? I tried to use the pump cover plates to control the input speed of fuel, however, that may make the machine halt due to the different frequency of input and cost of fuel.

**Comment by Vyraal1** [comment]
I dont think this should be implemented, turbines have uncontrollable fuel costs as one of their biggest weaknesses, and this would relatively really nerf the multiblock diesel engine, which has more precise fuel controls.

**Comment by Archengius** [comment]
no you can't
