### ISSUE TITLE
Steam Electrolysis should be same as Water Electrolysis

### ISSUE THREAD

**Issue by TedKnudsen** [GregTechCE/GregTech#758]
**GT**: gregtech-1.12.2-1.7.0.387.jar

Steam can still be electrolyzed into Hydrogen/Oxygen for just ~2K eu.  At that rate, its monstrously more efficient to just ignore steam turbines completely and burn the extracted hydrogen in a gas turbine.

Related to #686 I believe.

**Comment by Vyraal1** [comment]
For what it's worth I think this auto generated recipe should just be removed entirely, it just doesn't fit appropriately.
