### ISSUE TITLE
Amperage inconsistencies

### ISSUE THREAD

**Issue by jnaset** [GregTechCE/GregTech#766]
There currently exists a discrepancy in the way power is supplied to machines with enough room to accept multiple packets of energy per tick.  The machines themselves do not seem to have a limit on amperage, as they are able to draw a packet of energy each from several sources on attached wires.  (https://youtu.be/vBY41C1FdEQ?t=778 is a video showing this behavior, where a machine needing more than 1 packet per tick is drawing from two generators)

However when there is a source of energy capable of supplying multiple packets per tick, the same machine that could request several packets from different sources is not able to request equivalent packets from the multi-amp source.  Examples of such sources are step-down transformers and the 4, 9, and 16-amp battery buffers.

There should be consistency in the behavior of power sources on a wire regardless of how the total amperage is distributed among them.

**Comment by Archengius** [comment]
recipes requiring several amperes are removed now. Closed.
