### ISSUE TITLE
Possible Typo In Pump(item) assembly recipe

### ISSUE THREAD

**Issue by MatthewCOwen** [GregTechCE/GregTech#776]
Assembling Machine recipes for pumps(items) take 628mb of the required molten metal. 628 does not factor nicely from 144mb. I assume 628mb is a typo from 648mb which translates to 4.5 ingots worth of material
![2019-04-25_17 07 59](https://user-images.githubusercontent.com/16054364/56775628-c0d06800-677c-11e9-984a-deeae6b5835f.png)

**Comment by Agrax** [comment]
If i am not totally mistaken, it's either a GA recipe or a custom one. Doesn't seem like a native GTCE recipe. That beeing said, you should probably either post on:
a) your modpack maker bugtracker
OR
b) Gregic Additions bugtracker (if you're using this addon)

**Comment by Archengius** [comment]
ga recipe, closed
