### ISSUE TITLE
[Suggestion] Machine Arrays

### ISSUE THREAD

**Issue by xtake** [GregTechCE/GregTech#777]
There should be a machine which combines a lot of lower tier machines into one. (Multiblock or something). 
I know this was already a bit talked about in the discord but it would be really good for server performance. And compacting designs to just make them look better. For engame fusion reactors and stuff it would be really nice to have. How it is implemented dsn't really matter to me.
It could be like mid game EV/IV or something and you could maybe make the cost quite high.

**Comment by Archengius** [comment]
Multiblock variants of some machines are planned.
Processing array as one-for-all decision is not going to happen. It's usage nullifies most design challenges while making real arrays of machines.
