### ISSUE TITLE
compat: certus crystal

### ISSUE THREAD

**Issue by sinopike** [GregTechCE/GregTech#778]
Currently there is a vein for certus crystal but no way to obtain charged version from it. 
This material is useless unless AE2 is installed, but it lacks charged variant so that it cannot replace regular AE2 crystal ore.
My suggestion is that either this vein is removed or a way to obtain charged version is added. This can be done by adding a charged ore into the vein or an electrolyzer recipe like in GT5 (see https://ftb.gamepedia.com/Mod_Compatibility_(GregTech_5) )

**Comment by WarlordWossman** [comment]
Why does it have to be removed otherwise? I am using certus quartz in recipes and don't have AE2 installed.
And it's also 1 recipe, you could just add that using CT...

**Comment by Agrax** [comment]
Use CraftTweaker. Dunno, put a common version in the magnetizer to make it charged or w/e

**Comment by Archengius** [comment]
doesn't AE2 provide a way to produce charged certus quart itself?

**Comment by sinopike** [comment]
The AE2 charger requires charged certus to build, so if the oregen is disabled... 
Yes everything can be done with CT but this one seems like should be there by defult.

**Comment by Archengius** [comment]
No it shouldn't
