### ISSUE TITLE
[Suggestion] Tool rack

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#779]
So... GT tools don't always work with other mods' tool racks. I know it's these mods issue, not GT itself, but these mods are for the most part dead (Biblio, Reliquiary). A simple suggestion to add a tool rack that works with GT tools. Might be even tiered:
T1 (wood)- one tool, T2(bronze)- 2 tools, T3(steel)- 4 tools, T4 (stainless steel)- 8 tools (or smth)

**Comment by Archengius** [comment]
any use case for such block?

**Comment by WarlordWossman** [comment]
I am not really missing something like that, usually using item frames if I want tools on the wall.

**Comment by Agrax** [comment]
*shrug* Quicker access to tools. I mean, if you don’t think it’s crucial, you can close the topic easily ;)

**Comment by WarlordWossman** [comment]
keep in mind he wants to add something similar to the forestry worktable, that will probably make tool crafting way easier anyways I assume

**Comment by Archengius** [comment]
i'm terrible at visuals, so nope
