### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#78]
- [x] There is no EV Centrifuge
- [x] Only 2 Implosion compressor recipes. Are Iridium Reinforced Plates going to be a thing?
- [x] There is a Vacuum Freezer recipe turning Water into nothing
- [x] There is a Chemical Reactor recipe turning 1 Silicon Dust + 144 mb Epichlorohydrin into nothing
- [x] There are Machine Casing recipes for those that create 3 when made manually but only 1 through Assembler:
Heat Proof Machine Casing
Frost Proof Machine Casing
Solid Steel Machine Casing
Clean Stainless Steel Casing
Stable Titanium Machine Casing
Robust Tungstensteel Machine Casing
Steel Turbine Casing (That probably should have another name because it is made from Magnalium and Blue Steel)
Titanium Turbine Casing
Stainless Turbine Casing
Tungstensteel Turbine Casing
- [x] The Niobium-Titanium Alloy is just called Niobium-
- [x] 12x Wires/Cables have wrong Amperage values
- [x] Pulverizing Insulated Cables gives Ashes instead of Rubber
- [x] No Rubber Dust from Slime Blocks?

**Comment by temp1011** [comment]
- Vacuum freezer should turn water into liquid ice but that doesn't seem to be in game.
- Similarly, chemical reactor recipe should produce liquid silicone but there isn't any in game. There is liquid silicon though (hmm).
Seems for some things fluids are a bit bugged. Maybe it's fixed somewhere.

**Comment by SuperCoder7979** [comment]
https://github.com/GregTechCE/GregTech/commit/91bbfba6c91f84c37c43614625aaaae6bbf00b30 fixed these
