### ISSUE TITLE
multiple fluid output failing

### ISSUE THREAD

**Issue by sinopike** [GregTechCE/GregTech#783]
when a centrifuge process refinery gas into methane and LPG, the former went to first slot and is pumped out via pump cover. however LPG in the second slot failed to be extracted via pump cover.
However a chemical reactor can export H2S and refinery gas out via different side's pump covers. Is this a problem with centrifuge only?

**Comment by Archengius** [comment]
pump cover extracts anything as long as there is space in destination fluid handler.
double check your setup, use fluid filters to filter output fluids and separate them.
you can also click with fluid containers in gui to fill them.

**Comment by sinopike** [comment]
it seems that multiple pump covers on one machine does not work

**Comment by Archengius** [comment]
they do work fine, provide setup where they don't
