### ISSUE TITLE
Multiblock Pattern JEI Improvements. 

### ISSUE THREAD

**Issue by KaneHart** [GregTechCE/GregTech#785]
First off I love GTCE as someone played many years of GT on and off this one the best stable versions I think I have ever played and this even compared to Greg's work himself sorry :P

I'm a bit of a slow and blind man so ignore me if this not a issue to most people.

I like to see a way to move the Muiltiblock JEI Pattern up and down to easily see the slices. If this is hard or a trouble issue maybe an option while in slice mode to get an extra say 10-15 degree angel so you get a better view of the slice.

Image example on how it's hard to see all the blocks:
https://i.imgur.com/Rv60UHQ.png

My other suggestion if possible is some sort of basic Part List. This way people can hover over it and get detailed parts list a good example of this would be from Modular Machinery:
https://i.imgur.com/NakyGBk.png

Thank you for your time and have a wonderful day :)

**Comment by SuperSandro2000** [comment]
![](https://i.imgur.com/Rv60UHQ.png)
![](https://i.imgur.com/NakyGBk.png)

**Comment by Archengius** [comment]
you can hold shift to rotate vertically.
Part list is not going to happen, because gtce machine parts are very interchangable.

**Comment by SuperSandro2000** [comment]
The rotation is clunky and ofcenter.

**Comment by KaneHart** [comment]
Awesome that works well. Thanks :)
