### ISSUE TITLE
Minecraft crashed (and kept crashing) because of some weird interaction between a machine and redstone

### ISSUE THREAD

**Issue by zTotto** [GregTechCE/GregTech#787]
[crash-2019-04-29_19.30.58-client.txt](https://github.com/GregTechCE/GregTech/files/3128884/crash-2019-04-29_19.30.58-client.txt)
I just broke a block and my game crashed until i edited the world with mcedit to remove redstone

**Comment by Archengius** [comment]
1/1 warning do not report issues that was fixed in latest versions
