### ISSUE TITLE
Granite block mining becomes harder with ores embedded

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#789]
Ore + Granite seems to always have diamond-pick level mining for no reason.

Granite itself seems fine.  Ores seems fine.  Combination of them makes no sense.

https://github.com/pyure/infitech-prototype/issues/499

**Comment by Archengius** [comment]
because black granite has diamond level and it's not going to change

**Comment by pyure** [comment]
That's dumb.

**Comment by WarlordWossman** [comment]
@Archengius you know this is about the vanilla granite with ores in it right?

**Comment by Archengius** [comment]
Which is still baked to the black granite material. As i said earlier, i'd better remove these ore variants altogether instead of building special cases like that

**Comment by pyure** [comment]
Re-opening this per conversation with LAGIdiot.  We want this to be revisited.
