### ISSUE TITLE
Literally unplayable

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#79]
![2018-06-07_01 36 11](https://user-images.githubusercontent.com/35029480/41070439-2fcc786c-69f3-11e8-8cc1-31e3cd6431db.png)

Superconductors have a loss. What the fuck.

**Comment by SuperCoder7979** [comment]
"It's a coolant loss" - GregoriusT

**Comment by EmosewaPixel** [comment]
If it had no loss, that'd be breaking the laws of physics.

**Comment by SuperCoder7979** [comment]
You don't get superconductors until like UV so a 1 EU/block loss at that point is practically undetectable
