### ISSUE TITLE
[Minor] FistsOfFlesh-1.3.1 config required when used with GTCE

### ISSUE THREAD

**Issue by alxcool** [GregTechCE/GregTech#792]
Description
FistsOfFlesh-1.3.1
gregtech-1.12.2-1.7.1.394
CodeChickenLib-1.12.2-3.2.2.353-universal

.# List of blocks that will not be affected by the mod.
.# wrong-tool speed modifiers

Every meta tools work but drop nothing. 
Expected behavior, Breaking a Cable block with a wire-cutter would drop the item.

Sorry for that issue, I probably forgot to properly configure Fist o flesh, or I don't know how to properly use it.

https://minecraft.curseforge.com/projects/fists-of-flesh

So for now, I will remove fists o flesh from my list of active mods. I let you know later on if I find a way to use this mod with GTCE without creating an issue! Note : This issue could be closed if required.

**Comment by Archengius** [comment]
not gtce issue in any way, contact FOF author
