### ISSUE TITLE
Input Bus does not recognize Integrated Circuit configurations

### ISSUE THREAD

**Issue by thinseal** [GregTechCE/GregTech#795]
![image](https://user-images.githubusercontent.com/30489768/57116522-47420680-6d88-11e9-9b9e-f9e3bc6cc581.png)

The Integrated Circuit configuration in the input bus of blast furnace seems to be useless.
With configuration #1, the Si dust still turns into Si ingot

**Comment by Archengius** [comment]
it does, check on latest before submitting issue
