### ISSUE TITLE
Startup crash with JAOPCA, OreDictInit, and/or WrapUp (wrapup)

### ISSUE THREAD

**Issue by warrenher** [GregTechCE/GregTech#796]
Here's the crash log: https://paste.dimdev.org/fexoteveci.mccrash
Everything after "gregtech-1.12.2-1.7.0.387" causes a startup crash just like the one I posted. 
_(I know that VanillaFix does not suspect gregtech, however, the moment I add the latest version of GTCE to the modpack, this very crash happens. I, currently, am using GTCE 1.7.10.387, which, weirdly enough, is working flawlessly)_

**Comment by Archengius** [comment]
Recipe builder.chancedOutput signature changed, so mods need to update. Keeping old method is not possible, because it can't behave like it did and how mod authors expected it to, due to overclocking boosting mechanic change. So, please report to mod authors.

**Comment by warrenher** [comment]
The latest version of JAOPCA fixed it.
