### ISSUE TITLE
High tier brewery require LV pump

### ISSUE THREAD

**Issue by sinopike** [GregTechCE/GregTech#799]
should be requiring higher tier pumps as well

**Comment by Agrax** [comment]
Do you mean „a hv brewery recipe requires an lv pump as a component”?

**Comment by sinopike** [comment]
yes

**Comment by Agrax** [comment]
https://github.com/GregTechCE/GregTech/blob/715aaa8cd20f5092f35fa7eede876689a420e455/src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java#L364

Most likely borked here. For some reason
