### ISSUE TITLE
Where can this mod be downloaded?

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#8]
The download link in README.md does not work.
I searched in CurseForge and I can't find anything related to GTCE.
Are there any releases yet or any download links? I'm quite interested in this.

**Comment by n0099** [comment]
GTCE now is still rewriting for 1.12.2.
Latest playable version for 1.10.2 is 5.10.41, which lastest buildable commit is @acf3374, but 5.10.41 have many bugs such as transformer can't upgrade voltage and l10n haven't implement https://github.com/GregTechCE/GregTech/blob/03f6c9e2f98ec136c34506180cd7170bb39dcae0/src/main/java/gregtech/api/util/GT_LanguageManager.java

**Comment by SuperCoder7979** [comment]
Yup there is no build for 1.12.2 yet, that curseforge link was temporary when I wrote the readme.

**Comment by KrisBigK** [comment]
Then should I report bugs of 5.10.41 here?

**Comment by KrisBigK** [comment]
I'm playing 5.10.41 for a few months, but there is no problem with the transformer. The transformer will switch automatically between steping-up and steping-down if connected in the E-net correctly. I like this very much because it can prevent unnecessary explosions. Please keep it as a feature.

**Comment by SuperCoder7979** [comment]
5.10.41 is not supported, please do not report bugs here. This is for GTCE only, when it is finished.
