### ISSUE TITLE
Random registry of materials with compressed block & and other similar blocks

### ISSUE THREAD

**Issue by Antifluxfield** [GregTechCE/GregTech#80]
Totally the same issue as https://github.com/Blood-Asp/GT5-Unofficial/pull/1290

> because materials order will never change

- in d4d01012e03ae057a8ccac9539fa73262938847b

Nope. Let me show you a direct example that how the order of materials changes:
[DummyGTAddon1-1.0.zip](https://github.com/GregTechCE/GregTech/files/2081506/DummyGTAddon1-1.0.zip)

[DummyGTAddon2-1.0.zip](https://github.com/GregTechCE/GregTech/files/2081505/DummyGTAddon2-1.0.zip)

Firstly install the second dummy addon, place an "Alien Metal" block on the ground; and then take the first one. That block will magically change into "Exotic Alloy" block, which is the result of the changing order.

**Comment by Archengius** [comment]
i don't see where material ids change in given commit
and no, i will not do 3 times more blocks just because of that

**Comment by Antifluxfield** [comment]
OK.
