### ISSUE TITLE
Gas turbine does not work

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#810]
The gas turbine does not work even I put fuel in the input hatch.
This problem will occur in both survival and creative modes.

![2019-05-07_21 26 49](https://user-images.githubusercontent.com/43509783/57302988-ef502a80-710e-11e9-83ae-9e3a8ee0aa52.png)
![2019-05-07_21 26 55](https://user-images.githubusercontent.com/43509783/57302989-efe8c100-710e-11e9-9e89-bc80adeaa437.png)

**Comment by SergeyAn70** [comment]
strange phrase ...
Changelog
1.8.0
Bug fixes and tool improvements
**Nerfed large turbine to the ground so you will never use it again.**
Some other improvements.
I stopped all production. please fix

**Comment by Gombado** [comment]
It's super player unfriendly that the turbine is still buildable while theres not a single reference for the multiblock not working.
