### ISSUE TITLE
[Suggestion] Better Gem Automation

### ISSUE THREAD

**Issue by MineTech123** [GregTechCE/GregTech#811]
Can you add a new OreDict to all the crushed gems because it’s easier to automate using filters and pipes from other mods like Thermal Expansion

**Comment by Archengius** [comment]
no

**Comment by Agrax** [comment]
Yup. Use „gem*”. That makes it filter out everything that has the part „gem” in it ie. gemFlawlessRuby, gemExquisiteOlivine etc
