### ISSUE TITLE
As of build 398 No turbines recognize any fuel input and do not work

### ISSUE THREAD

**Issue by Saereth** [GregTechCE/GregTech#816]
I believe this issue may be relevant
https://github.com/GregTechCE/GregTech/issues/810

version 394 everything worked fine, version 398+ turbines no longer recognize they have fuel in the input hatch.

https://cdn.discordapp.com/attachments/459037806769995797/576450188718374942/unknown.png
https://cdn.discordapp.com/attachments/459037806769995797/576450239624511489/unknown.png

**Comment by daddy77gaming** [comment]
Adding to this after some testing. 

In SSP turbines work fine.
On a server turbines wont recognize fluid inputs.

**Comment by Saereth** [comment]
my tests were done in SSP and didnt work either

**Comment by SergeyAn70** [comment]
Странная фраза ... 
Changelog 
1.8.0 
Исправления ошибок и улучшения инструментов 
Nerfed большая турбина на землю, так что вы никогда не будете использовать его снова. 
Некоторые другие улучшения. 
Я остановил все производство. пожалуйста исправьте

**Comment by daddy77gaming** [comment]
for the non-russian speaking amongst us..

Changelog
1.8.0 

Nerfed large turbine to the ground so you will never use it again.


Raises the question if you neft them to the ground so they will never be used, why not plain remove them instead of breaking them, will prevent a lot of players a ton of frustation figuring out how to get the thing to work.

**Comment by xenon54xenon54** [comment]
i doubt the turbines were supposed to be broken in the update. otherwise, they would have been removed, and the nerfs would have been unnecessary. hopefully a bug fix for this comes out in the next few days.

**Comment by daddy77gaming** [comment]
A reaction from a dev would be welcome here..

**Comment by Archengius** [comment]
duplicate
