### ISSUE TITLE
Exploding Coal Boilers full of water

### ISSUE THREAD

**Issue by ShaneCourtrille** [GregTechCE/GregTech#819]
3 out of the 5 times I've had coal boilers run out of coal dust (but NOT water -- they are full of water) they would explode within a minute after I gave them some additional coal dust (playing FTB Interactions).  

And yes I'm positive they were full of water because I got very careful about checking that after the first time I had one explode on me.  Based on the timing I wonder if they use up the first bit of water and then get refilled to top but they think they are empty at the time?

**Comment by georgeYrjo** [comment]
did you build the boiler over chunk borders? IIRC Gregtech, and perhaps GTCE multiblocks might not work properly if built over chunk borders. I might be completely wrong though, and chunk borders don't matter to multiblocks.

**Comment by ShaneCourtrille** [comment]
Sorry I should have been more explicit.  My problem is with the single block Small Steam Boiler. I switched to single block High Pressure Steam Boiler and haven't had the problem again so it seems to be specific to the most basic steam boiler.
