### ISSUE TITLE
Crash when Mortar runs out of durability

### ISSUE THREAD

**Issue by davqvist** [GregTechCE/GregTech#82]
GTCE 0.2.0.2
Forge 2707

I had a Flint Mortar that is nearly broken and I had several Copper Ingots in the Crafting Table to turn them into dust, I shift clicked so that the mortar ran out of durability half way through, I got a crash.

https://hastebin.com/kopubogama.cs

**Comment by EmosewaPixel** [comment]
It's not just the Mortar, it's every tool. What I find strange is that, when I was testing making plates with the hammer, it actually stopped crafting when it was low on durability. I'm guessing there's no check for it running out of durability.

**Comment by temp1011** [comment]
I think this might actually be a bug with recipes.

**Comment by temp1011** [comment]
My crash: https://paste.fedoraproject.org/paste/lvZ8SjSqsYeJslJAB4Fsew. Seems to be a problem with getting the remaining durability, maybe because this uses NBT rather than meta to store it.

**Comment by temp1011** [comment]
This is the problem https://github.com/GregTechCE/GregTech/blob/2768d0290a3c7826d115405badca1c5fab2fa070/src/main/scala/gregtech/api/items/toolitem/ToolMetaItem.java#L131-L142. I can fix it with custom recipe but I still need to finish working on it.

**Comment by temp1011** [comment]
This is fixed for non electric tools by https://github.com/GregTechCE/GregTech/pull/102. Electric tools will still cause a crash.
