### ISSUE TITLE
Bugged texture |MP server|

### ISSUE THREAD

**Issue by kobliznik** [GregTechCE/GregTech#823]
Hello

there is a bugged texture of every pipe and wire. If you place ANY pipe or wire, others will not see it properly.

Pipe placed by myself:

![2019-05-12_17 47 41](https://user-images.githubusercontent.com/8217189/57584698-93a2ea00-74de-11e9-922c-c4594761c3d1.png)

Others will see:
![2019-05-12_17 39 30](https://user-images.githubusercontent.com/8217189/57584689-61918800-74de-11e9-9f22-41e38abfa3b6.png)

MC version: 1.12.2
GT version: 1.8.1.399
Forge version: 14.23.5.2768

**Comment by HonzaVinCZ** [comment]
@Archengius could you give us info if it will be fixed please? Or do you need some more info?

**Comment by Archengius** [comment]
works fine in latest gtce
