### ISSUE TITLE
[Suggestion+Question] Plasma Generators

### ISSUE THREAD

**Issue by MineTech123** [GregTechCE/GregTech#829]
Are the Plasma Generators from GT5 coming back? 
In case if you’re confused with the Plasma Turbine I’m taking about these https://ftb.gamepedia.com/Plasma_Generator_(GregTech_5_Unofficial)

**Comment by Agrax** [comment]
A) there’s no GTCE way to make plasma, so *useless*
B) single block plasma generators? 99,999% sure that the answer is *hell, no*

**Comment by MineTech123** [comment]
Oops meant to send this to Gregicadditions

**Comment by Agrax** [comment]
Pixel doesn’t update GA anymore. Look for Shadows of Greg

**Comment by MineTech123** [comment]
Ok so SOG I guess
