### ISSUE TITLE
How to get Bronze?

### ISSUE THREAD

**Issue by davqvist** [GregTechCE/GregTech#83]
GTCE 0.2.0.2
Forge 2707

Usually in Gregtech you turn 3 Copper Dust and 1 Tin Dust into 3 Bronze Dust to get your first Bronze. But there is no way to get Bronze early game as far as I can see. There is a recipe with Tetrahedrite Dust instead of Copper Dust, but that doesn't help as Tetrahedrite melts into Copper as well in a Furnace.

**Comment by Archengius** [comment]
have you tried 3 copper and 1 tin dust recipe? it is still there

**Comment by davqvist** [comment]
The only recipe that is there is 3 Tetrahedrite Dust + 1 Copper Dust like I said above. Or you mean it works, but isn't in JEI?

**Comment by temp1011** [comment]
The recipe for bronze from copper and tin dust is there, it just doesn't show up in JEI.

**Comment by EmosewaPixel** [comment]
Well, probably because it doesn't work: 
![image](https://user-images.githubusercontent.com/25333164/41202986-978f1ab4-6cd1-11e8-913c-dae2216c7458.png)

**Comment by temp1011** [comment]
![bronze](https://user-images.githubusercontent.com/34900092/41203310-04f7eb94-6ccd-11e8-8559-f5c750237fd4.png)
hmm. Maybe it's something in a newer update/not released yet?

**Comment by davqvist** [comment]
That is a recipe added by Thermal

**Comment by EmosewaPixel** [comment]
Thermal is an optional dependency, but does that include the GT recipe being disabled?

**Comment by temp1011** [comment]
@davqvist is right, without CoFH mods the recipe doesn't work. I just didn't realise because a bunch of mods are in the dev environment for some reason. There is a mixer recipe for the dust though strangely...

**Comment by EmosewaPixel** [comment]
Yeah, I don't get why TF and TD are optional dependencies.

**Comment by EmosewaPixel** [comment]
So there were simply 2 recipes overriding each other? Huh.

**Comment by temp1011** [comment]
I think the registry just doesn't accept duplicate keys. I'm surprised nothing turned up in logs about it (at least I didn't see anything).

**Comment by EmosewaPixel** [comment]
Yeah, I was thinking the same.

**Comment by Archengius** [comment]
fixed
