### ISSUE TITLE
Naquadah Reactor Issue + Mk4 Fusion Reactor Design 

### ISSUE THREAD

**Issue by mstapelberg** [GregTechCE/GregTech#830]
Hello, 

First off, I tried asking this question in the Discord and was IP Banned. A brief explanation would be appreciated for that. 

Back to the question: 
I have tried using the Naquadah Reactor, and used Enriched Naquadah Bolts like the Wiki Suggested, furthermore I also inputted liquid enriched Naquadah, via fuel cells. Despite trying these methods, I was unable to get power out. The machine did light up. I made sure I had the wires rated for EV Tier, and were on the small gray circle port.

![image](https://user-images.githubusercontent.com/35986272/57963752-4320f780-78f7-11e9-9c88-3f58ae704ac4.png)

Is the Naquadah Reactor Broken? 

Also, I am working on a realistic Fusion Reactor addon, based on MIT's SPARC, a project I work on. My plan was to use a Fortran or C++ Wrapper for Java to do the heavy numerical calculations. Would this at all be compatible with Gregtech's code? I would like to use the YBCO materials, Hydrogen Isotopes, and other materials that your mod offers. 

Sent a request on Discord if you would like to talk more about the suggestion.
Thanks.

**Comment by Archengius** [comment]
GTCE doesn't have Naquadah reactor, it is added by one of the add-ons. Read #faq before writing reports.

**Comment by mstapelberg** [comment]
Okay thanks. It showed up under Gregtech Community Edition in JEI so I thought it was a project of yours. I'll talk to the people at GT Additions.

RE: FAQ
Are you talking about this? 
https://github.com/GregTechCE/GregTech/wiki/Frequently-Asked-Questions

I read that link before posting and besides taking what JEI said at face value, I did not believe I broke any of those rules.  

Could I please get unbanned on Discord?

Thanks again for your patience.

**Comment by Archengius** [comment]
it has huge red tooltip ADDED BY: GREGIC ADDITIONS. 
No, i'm talking about #faq channel in discord you should've read before asking anything

**Comment by mstapelberg** [comment]
Negative on that tooltip, at least for my Modpack. However It does now show Gregic Additions if I go into the actual recipe and mouse over the finished block. 

Ok. Well I would like to see which rule I violated there, could you please unban me so I can check?

Thanks.
