### ISSUE TITLE
Microblocks from Forge Microblocks are incredibly bugged with pipes and cables.

### ISSUE THREAD

**Issue by SuperKael** [GregTechCE/GregTech#831]
Pipes and cables that have microblocks on them are incredibly broken, and have all kinds of crazy results. I tried to use a cover to prevent a cable from connecting to a machine - it seemed to work, but it turned out that the entire network of cables had become non-functional, and wasn't transferring power. I tried to use a cover to prevent a pipe from connecting to a high pressure boiler in an undesired place, and after a relog the boiler was invisible, and TheOneProbe called it a "null.unnamed.name". I tried breaking it, it dropped nothing, and it semi-permanently corrupted my game, causing most GregTech blocks to lose their ItemBlock textures, causing many of the things in my inventory to turn invisible, among many other weird effects of this "corruption state". Restarting the entire game is the only fix (relogging didn't help.) Note that I did check the consoles in both of these incidents, but found nothing at all. And of course, even if none of these crazy things happen, microblocks are still totally unable to prevent connections between cables/pipes and machines. Please note that the "corruption state" incident occurred on a server, while the cable network failing thing I have experienced in both multiplayer and singleplayer. All of these I have experienced in the latest version of GregTechCE for GregBlock, which currently is version "1.7.0.387"

**Comment by Archengius** [comment]
GregBlock is outdated 
Issues related to fmp won't be fixed
