### ISSUE TITLE
When applying Ore Dictionary Filter to EV Robotic Arm, entire stack gets consumed

### ISSUE THREAD

**Issue by Orichlol** [GregTechCE/GregTech#833]
If you shift click a stack of Ore Dictionary Filters into the Robotic Arm, the entire stack gets consumed and converted into 1.

**Comment by Agrax** [comment]
Into one stack? 64 items get converted into 64 items? Is that really a bug?

**Comment by Kreestijan** [comment]
No, 64 items into 1 item, that's the bug. Had it happen to me as well.
