### ISSUE TITLE
OreExcavating with axe blows up durability

### ISSUE THREAD

**Issue by Xetaxheb** [GregTechCE/GregTech#836]
As title, if you try and oreexcavate a tree the axe will just plummet in durability instead of what it would cost to hack at it normally

Probably trying to subtract the axes calculations per-log instead of once

**Comment by Archengius** [comment]
It does 1 damage/block like normal use

**Comment by Xetaxheb** [comment]
well except it doesn't..? it's eating a quarter+ of an axe durability in one small oak tree if I oreexcavate, versus about 5 blocks worth if I chop normally (with GTCE axe felling the tree). If I tried to take out a moderate size tree the entire axe would poof whereas if I don't oreexcavate that same size tree it does maybe 1/6th of the axes durability.

**Comment by Xetaxheb** [comment]
aka: it seems to take exponentially more durability the bigger the tree is, because it's probably GTCE code triggering the entire trees worth of damage on every single log instead of 1 damage/block; so it does (TREE_SIZE damage)/block
