### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Blazer4Hire** [GregTechCE/GregTech#837]
I honestly do not know why it is crashing, I am still trying to find the mod causing it. There was a message on the screen that said that the crash may be because of incompatibility with the mod and to report it.
[crash-2019-05-21_17.46.33-client.txt](https://github.com/GregTechCE/GregTech/files/3204714/crash-2019-05-21_17.46.33-client.txt)

Edit: I apologize for my stupidity, all I had to do was go to coremod.Optomizeblockpos in config.foamfix.config and set it to false. It was throwing an illegal placement error something and it was because I had that setting set to true not false.

**Comment by Agrax** [comment]
Does it work now? If it does, please consider closing the issue. Thank you kindly
