### ISSUE TITLE
Lignite Coal

### ISSUE THREAD

**Issue by davqvist** [GregTechCE/GregTech#84]
GTCE 0.2.0.2
Forge 2707

I can't remember if Lignite Coal used to drop Lignite Coal items from mining or if you had to smelt the ore, but you get the ore now and the furnace melts it into Dust which has no use, meaning Lignite Coal has no use atm. Lignite Coal item is also not visible in JEI and seems to be completely missing.

**Comment by EmosewaPixel** [comment]
I'm guessing the recipe generation system just gives dust when there isn't another item, such as the Lignite Coal, which is missing.

**Comment by Archengius** [comment]
fixed
