### ISSUE TITLE
Quality of life, make white items in recipes stick out more (texture changes?)

### ISSUE THREAD

**Issue by daddy77gaming** [GregTechCE/GregTech#842]
With certain components having the same color as background ( plastic board for example), and only needing 1 for a craft it's easy to overlook, miss them in the recipe. Adding a denotation of 1 to those would make them stand out better in any recipe.

**Comment by daddy77gaming** [comment]
Ok, so change of title, bc i guess it's just minecraft client not adding the 1 denotation in crafts.. make them white item's shaded or something to have them pop out more

**Comment by Archengius** [comment]
they have borders pretty noticable
