### ISSUE TITLE
Blocking pipe next to boiler with cover corrupts world

### ISSUE THREAD

**Issue by josiah-roberts** [GregTechCE/GregTech#843]
**Repro case:**  
Small coal boiler, with pipes attached like in the screenshot. Get the boiler running and outputting steam, then cut off the flow with a cover on the side.

Type of tank/fluid sink is irrelevant.

**Result:**  
Game/server crashes, world is corrupted such that game instantly crashes on loading these chunks in the future.

Happens both in standalone client and client/server setup.

**Logs:**  
https://pastebin.com/HqLr3hn9

**Screenshot:**  
![image](https://user-images.githubusercontent.com/37082009/58434198-49d60a00-806f-11e9-979d-6aed8457995c.png)

**Comment by Archengius** [comment]
forge multipart issue, already reported

**Comment by josiah-roberts** [comment]
For reference, duplicate of https://github.com/TheCBProject/ForgeMultipart/issues/56
