### ISSUE TITLE
Possible pump (machine) leak

### ISSUE THREAD

**Issue by schliip** [GregTechCE/GregTech#846]
I placed an EV pump in my base a while ago to clear some lava and light oil.

While running for a couple days or so, it became steadily laggier when looking at it (through walls, forgot it was there) until I was getting about 1 fps whenever I looked in its direction. The pump was powered and able to output throughout. Removing the pump fixed the lag, but also broke GT item and block display until restart.

Newest GTCE version

**Comment by Agrax** [comment]
We need log from when the machine was lagging.

Please, consider recreating the issue and giving us the entire MC log. Thank you very much

**Comment by schliip** [comment]
While the machine is running, nothing in particular shows up in the log, and LagGoggles doesn't show anything either. Everything except FPS is normal. 
I haven't managed to reproduce it, but I have backups of the world with the pump on it (Omnifactory 1.0.4) that I wouldn't mind uploading.
The pump no longer has any fluid to pump, but it's still lagging
Since it only lags when looking at the actual pump block, I suspect it might have something to do with the visual pipes that extend below it.
![image](https://user-images.githubusercontent.com/34576051/58764159-fa418380-8531-11e9-8afb-ea51d749e7ba.png)

**Comment by schliip** [comment]
Full log
I opened the world, looked at the pump, looked away, paused and copied the log.
[pump log.txt](https://github.com/GregTechCE/GregTech/files/3245840/pump.log.txt)

**Comment by Cyprex** [comment]
I've been having the same issue, here's a profiler snapshot made with JVisualVM: https://files.catbox.moe/le4cyg.nps
![Screenshot_20190610_171654](https://user-images.githubusercontent.com/35031555/59205763-d15d6600-8ba3-11e9-9955-94940d549dcd.png)

**Comment by IChris2698I** [comment]
I don't have much useful information to add, but I had this issue as well on Omnifactory 1.0.5. I had an MV pump, powered by a 4x MV CEF, with lava transferred via EnderIO ender fluid conduits. The pump was placed on netherrack (no space below it), had been working for about a day (no issue when first placed), and while looking at the pump my FPS was 1. No TPS issues visible on `/cofh tps`. When I broke the pump, my FPS went back to a solid 60.
