### ISSUE TITLE
Small Bronze Pipe recipe

### ISSUE THREAD

**Issue by davqvist** [GregTechCE/GregTech#85]
GTCE 0.2.0.2
Forge 2707

I know pipes are not functional yet and only for crafting recipes, but the crafting recipe seems be wrong and I doubt it is intentional. In Gregtech you get 1 Huge, 2 Large, 4 Normal. 6 Small and 8 Tiny Pipes from 6 plates. But you get in GTCE only 2 Small Pipes making all the starting machines quite expensive.

**Comment by Archengius** [comment]
Because they're not small, they're normal ones.

**Comment by davqvist** [comment]
I am maximum confused now. If you look here, the recipe used Small Bronze Pipes https://ftb.gamepedia.com/Steam_Forge_Hammer

And the Pipes are even labeled "Small Bronze Pipes" and not "Normal Bronze Pipes" and even what it would be the case the recipe should be 4 not 2. 

Can you explain this to me?

**Comment by Archengius** [comment]
ah, now i get what you mean. that's why there is only one bronze pipe item, and it is used in place of both normal and small pipes.

**Comment by davqvist** [comment]
I know. What I am trying to say is, that - let's say the Steam Forge Hammer is double as expensive as it used to be, which is quite a difference (26 instead of 14 Bronze Plates)
