### ISSUE TITLE
Pipe rendering not working multiplayer

### ISSUE THREAD

**Issue by Annwan** [GregTechCE/GregTech#850]
Hello
Playing on multiplayer with some friend, we noticed some strange rendering issues
Some pipes placed by other players does not appears and the game only shows the hitbox wireframe if looking directly at the said pipe

reloading all chunks `<F3> + A` does nothing

The invisible pipes are shown only if relogged to the server

Seems related to issue #710 but I'm using v1.8.1.399 and it should have been fixed since v1.7.0

**Comment by Archengius** [comment]
fixed in 6a9e723563c82905ca1983ae40f9f823bb8078c1
