### ISSUE TITLE
What is the best way to damage GTCE tools using the API?

### ISSUE THREAD

**Issue by codetaylor** [GregTechCE/GregTech#851]
I'm currently using `GTUtility.doDamageItem` to damage GTCE tools, but it looks like the method [might be scheduled for removal](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/util/GTUtility.java#L273).

How should I be using the api to damage GTCE tools?

**Comment by Archengius** [comment]
cast to IToolItem and call damageTool
