### ISSUE TITLE
[Suggestion] Better surface nugget model, and Poor ores

### ISSUE THREAD

**Issue by MechanosG** [GregTechCE/GregTech#854]
First, the surface nuggets.  GT:CE is a really nice looking mod.  It's ore generation is not only aesthetically pleasing, but also detailed.  Yet the surface nuggets are...  a small cube.  I would like to see something more like https://minecraft.curseforge.com/projects/simple-ore-samples/images or https://minecraft.curseforge.com/projects/geolosys/images , just to be a bit more immersive.
(If you had permission to use either of those models, would you?)

Secondly, poor ores.  They were in GT5, but perhaps not used to their full potential?  What I propose is smaller veins (as opposed to just random 1 ore spots) of these poor ores spawned in a separate random'ish algorithm, to be bumped into while random mining without a surface sample.  If that's too much to ask, then..  even just including the poor ores so that players can manually set up the spawning, would also work.  I'm looking at them as a way to obtain early game resources (mostly tin/copper/iron) when setting up your first bronze machines/tools, for players doing their first initial basement mining, and players that get unlucky and don't have copper/tin veins near their base.  I have used MMD Orespawn to simulate this, and it makes the underground feel a lot less empty.  But it would be great if GT:CE had this option built in, and would go a long way for players new to GT:CE.

**Comment by Archengius** [comment]
open separate issue with new surface nugget model, if you want it to be more immersive.

you can already simulate vanilla alike ore veins via oregen configuration system. there won't be any built-in presets for small ores.

**Comment by MechanosG** [comment]
Alright.  I wasn't suggesting "vanilla alike" ore veins.  I was suggesting the small ores from GT5, even if they don't spawn by default.  But ok.  I'll see about that surface nugget model.
