### ISSUE TITLE
Poor Server Performance

### ISSUE THREAD

**Issue by TheFlash787** [GregTechCE/GregTech#857]
Hey! I'm having an issue where a lot of the ticktime is being used by the GTCE machines that are on the server. This causes great difficulty for servers, and I'm wondering if there is anything you can do to optimise this in the code. I understand that you manage your machines and tools as almost 'one' entity and then applying an unsafe damage tag onto it, which isn't the best way nowadays.

**Steps to reproduce:**
1: Have a server
2: Allow players to use GTCE machines as they were intended in their bases
3: Watch as many machines cause lag, **even when the machines aren't even in use**.

![](https://i.imgur.com/y4y5DQU.png)
![](https://i.imgur.com/5bKIgAl.png)
![](https://i.imgur.com/CJsjLV1.png)

**Comment by Archengius** [comment]
you didn't provide version, latest one is broken performance-wise.

**Comment by TheFlash787** [comment]
Sorry. The version is **181.399**.

I will also add that it only appears to be assemblers causing the lag (as mentioned before, even when not in use). 

I would also recommend the use of issue templates, to ensure that people do not miss out important details that you would like added.

**Comment by Archengius** [comment]
then issue is not known, but information you provided is not enough to retrieve any useful info.

**Comment by TheFlash787** [comment]
@Archengius I have provided you with my observations, that is the most that I'm able to do.

**Comment by TheFlash787** [comment]
I would kindly ask that you re-open this issue, and look into the code to see if there are any leaks that could be causing this performance drop. I **have** mentioned that it only appears to occur with assemblers that are not in use. Could the mod be checking to run the recipe, but is failing each time because it doesn't have the necessary resources?

Your cooperation would be required for this, I understand.

**Comment by Archengius** [comment]
i repeat: information you provided is not enough to retrieve any useful info.
i looked up code quickly and no, it couldn't.

**Comment by TheFlash787** [comment]
What information are you looking for? I can see what I can provide.

**Comment by Archengius** [comment]
JVisualVM performance tracing data

**Comment by Agrax** [comment]
Well, i’ve seen it myself with just fluids left in the assembler tank. Just leave some soldering material in the assembler tank and voillà- you’ve got yourself a machine causing 2000 microseconds of lag

**Comment by TheFlash787** [comment]
![](https://i.imgur.com/sbQmC3P.png)
