### ISSUE TITLE
Issues in the Steam Age

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#86]
- [x] The Bronze Alloy Smelter, Forge Hammer and Macerator simply do not work.
- [x] The Coal Boilers create a full Dust of Dark Ashes instead of a Tiny Pile (as it was in previous GregTech versions)
![image](https://user-images.githubusercontent.com/25333164/41166484-9c0f2170-6b40-11e8-88ba-b3dc540ade75.png)
![image](https://user-images.githubusercontent.com/25333164/41166590-e849eee4-6b40-11e8-8cd6-288b239d85f9.png)
- [x] The High Pressure Lava Boiler lets Lava Buckets pass when it's full on Lava. It should keep them in the input slot (yes, I know it's very minor, but it can mess up systems)
![image](https://user-images.githubusercontent.com/25333164/41166648-152ad41e-6b41-11e8-94e6-12f7b289805a.png)
- [x] The High Pressure Alloy Smelter makes plates whenever there are 2 of the first ingot
![image](https://user-images.githubusercontent.com/25333164/41166704-40dfb494-6b41-11e8-9bb5-963785ee47a9.png)
![image](https://user-images.githubusercontent.com/25333164/41166839-8832b422-6b41-11e8-9def-ca24ed2770fa.png)
![image](https://user-images.githubusercontent.com/25333164/41166857-936f109c-6b41-11e8-85d8-944f49275451.png)
- [x] As already mentioned in #83 , Bronze Dust uses Tetrahedrite instead of Copper Dust.
![image](https://user-images.githubusercontent.com/25333164/41166926-c58b539c-6b41-11e8-94bf-8d8e68d37a6f.png)
P.S. please actually fix them before checking them off this time (sorry for being so passive-aggressive).

**Comment by Archengius** [comment]
i simply broke this again, not "checked off"

**Comment by EmosewaPixel** [comment]
Huh, fair enough.

**Comment by pyure** [comment]
Fwiw, when attempting to reproduce the High Pressure Alloy Smelter behaviour, I got 2Tin => 1 Tin Gear rather than 1 Plate as indicated above.

**Comment by Archengius** [comment]
wow fixed

**Comment by Rongmario** [comment]
Woah what the fuck is that all checked OFF?!?!?!
