### ISSUE TITLE
Allow input from output side should be on by default

### ISSUE THREAD

**Issue by nyronium** [GregTechCE/GregTech#861]
Apparently, two month ago "allowInputFromOutputSide" was introduced in `SimpleMachineMetaTileEntity.java`.
While this can be configured with the screwdriver, it is very counter-intuitive that it is disabled by default, as one would not suspect this to be a feature that can be enabled.

More problematic is, that previously this functionality was on by default. Now it requires to adjust a lot of machines and contraptions that rely on that feature (e.g. single ME Interface on machiene with auto output into it)

As most machines accept inputs from any side, this behavior seems odd, and therefore I hope that the default may be changed to be more intuitive.

**Comment by Agrax** [comment]
#741 there was a completely sane reason for this change. Read it and you will understand, hopefully. Thank you for your contribution to the subject anyways

**Comment by nyronium** [comment]
Ah i see, thanks for the clarification. Yet I still think that there is a fundamental design flaw here, and it would be great if we could attempt to solve it more -eeh- "properly". It seems all workaround-y now.

If i have understood it correctly, this behavior is actually an issue of the machine-pipe interaction and not a single component's fault.

I think GTCE differs from most mods here (not at all in a bad way), as the extract action is controlled by the machine opposed to  the pipe, as it is in most other mods (ThermalExpansion, EnderIO, etc.), which let the pipes control both the extract and the insert selection, which eliminates the issue.
So the issue only exists when using pipes that actively push with machines that actively extract.

Regarding that GTCE adheres to a "close to reality" design, I want to make a suggestion.
It seems to me like the component that is missing is a "one-way valve", basically something that restricts fluid flow direction in pipes, and therefore also the inserting capabilities.

I guess it would be a lot more intuitive to be able to "configure" the pipe into this state.
Additionally, GTCE machines with an active output side could automatically set newly attached gtce pipes  to be in "one-way valve mode" away from the machine.
Ideally, only newly pipes that were not configured before would become a valve. Then the pipes could still be locked, in case re-feeding is intended.

```
   +─────────────+                                                                                                                                           
  /             /|                                                                                                                                           
 /             / |     +─────────────+─────────────+                                                                                                         
+─────────────+  |    />/           /             /|                                                                                                         
|             |─>|   +─────────────+─────────────+ |                                                                                                         
|   I'm  a    |─>|   |>|           |             | |                                                                                                         
|             |─>|   |>|           |             | |                                                                                                         
|M A C H I N E|  +   |>|           |             | +                                                                                                         
|             | /    |>|           |             |/                                                                                                          
|             |/     +─────────────+─────────────+                                                                                                           
+─────────────+       ↑                                                                                                                                      
                      +───── Active "valve" on the machine side (allows input from machines, but the pipe never pushes that way)                             
                                                                                                                                                             
For completeness?:                                                                                                                                           
                                                                                                                                                             
   +─────────────+                                                                                                                                           
  /             /|                                                                                                                                           
 /             / |     +─────────────+─────────────+                                                                                                         
+─────────────+  |    /</           /             /|                                                                                                         
|             |  |   +─────────────+─────────────+ |                                                                                                         
|   I'm  a    |  |   |<|           |             | |                                                                                                         
|             |  |   |<|           |             | |                                                                                                         
|M A C H I N E|  +   |<|           |             | +                                                                                                         
|             | /    |<|           |             |/                                                                                                          
|             |/     +─────────────+─────────────+                                                                                                           
+─────────────+       ↑                                                                                                                                      
                      +───── Active "valve" (allows the pipe to output into the machine, but not the machine to input into the pipe)                         


```

This way, other mods could still use in-output on all sides, and GTCE pipes would also behave nicely.

**Comment by Agrax** [comment]
1) it doesn’t differ. In many mods there is a way for machines to push outputs on their own. In GT you have two ways to extract:
- automated machine outputting
- pump covers
2) You’re wrong. Search for a „shutter module” or w/e it’s called. It’s a one-way valve. 

Another thing is that both mechanics „don’t allow” and „allow” are implemented. With all the knowledge abt GT Archie has, he has decided that the default mode should be „disallow”. It’s not that hard to whack a side with a wrench to allow it, so i don’t understand your issue here. Sorry, mate. Good thing im not a dev- im just trying to be helpful and explain the reasoning behind such a change. If Arch gets to read the post, he might have totally different opinion, so don’t really listen to my rambling

**Comment by nyronium** [comment]
Let me clarify: The issue is not really that GTCE is lacking the feature, but that I think there is a way to minimize required user interaction for both cases. So it's just a improvement suggestion from my side - obviously the owner of this repo can do whatever he likes.

It was just an idea to increase usability, because even though simply clicking with a screwdriver is somewhat "verry simple", it still is quite a hassle to do it for hundreds of machines, which stopped functioning because of the change, until they get reconfigured by hand.
So the update just shifted the cases in which a machine needs to be manually configured to another group of machine usages.

My proposal is a possible solution which requires no interaction in either case.
I have no demand that my idea will be integrated, I just wanted to share it.

**Comment by pyure** [comment]
If allow-input-by-default is enabled, I'll have to "fix" it with a screwdriver for hundreds of machines, just sayin.  I don't want things flying into my outputs w/o my explicit permission.  That's how GT works.

**Comment by leagris** [comment]
Default would not apply to already crafted machines because if it works like in GT5, machine tile settings are already into NBT data when it is crafted.

**Comment by pyure** [comment]
Someone's gonna have to do all that extra clicking regardless (in this case during initial setup)
