### ISSUE TITLE
Axes/Chainsaws don't chop down entire tree

### ISSUE THREAD

**Issue by philwilei** [GregTechCE/GregTech#862]
gregtech-1.12.2-1.8.3.418
gregtech-1.12.2-1.8.3.416

This is basically the same as #636 and applies to both axes and chainsaws.
I tested the two most recent versions and both have this issue.
The axe breaks single blocks when sneaking, but doesn't break blocks when **not** sneaking. This isn't affected by material choice / level of the chainsaw.

**Comment by Archengius** [comment]
Was fixed in the latest CF release
