### ISSUE TITLE
[Suggestion] Meta arrows

### ISSUE THREAD

**Issue by Agrax** [GregTechCE/GregTech#863]
Basically arrows as meta-tools. Kindof? Purpose? Better vanilla arrows. More dmg and innate enchantments like... Dunno, radioactive or smth

Tip+ stick + feather

Tip:
1. Rod + file = 2 tips
2. Rod in a lathe = 4 tips
3. Ingot in an extruder = 12 tips

Plus maybe glass arrows? Less dmg, but can be filled with potions in a fluid filler. Whaddya think, Archie?

**Comment by leagris** [comment]
Do you have real use case of Gregtech arrows, I mean those that existed in GT5 for 1.7.10?
Well, I am sure skeleton throwing you radioactive arrows had some fun aspect.
But player taking time to deal with micro-crafting hoops, technical infrastructure with power sources, machines, logistical chains to produce good amount of arrows, would likely not bother any-more with fighting mobs, and would have likely done so; already with better or cheaper alternatives.
There are probably more tech oriented ways to produce more appealing weapons based on Gregtech as add-ons companion mods. Like energy powered/laser/whatever-beam/plasma rifles, shock-wave EMP devices, force-field, magnetic canon, defence turrets, seeker missiles, robotic guards… plenty of other options that would fit better with Gregtech style and be more appealing than bows and arrows.

**Comment by Agrax** [comment]
Well, you can make counter-suggestions. I did this suggestion, cuz i was fond of GT5-u arrows. Not mentioning that Arch is a person that’s able to implement them in an even more interesting manner

**Comment by liquidblur** [comment]
I for the love of all things greg hope any "energy powered/laser/whatever-beam/plasma rifles, shock-wave EMP devices, force-field, magnetic canon, defence turrets, seeker missiles, robotic guards" never make their way into any version of gregtech. Id be ok with seeing a hunting style rifle as a replacement to the bow but even that I question

**Comment by Agrax** [comment]
ICBM v2.0 :)

**Comment by liquidblur** [comment]
which is already a thing for 1.12.2 so highly recommend Leagris go download that mod to work along side gregtech, if gregtech starts to add heavy non-server friendly crap IE missiles and explosions, youll start to see server/mudpack devs just removing them on their side to prevent server lag and allow their players to ACTUALLY enjoy playing the mudpack/server they created for there players

**Comment by Archengius** [comment]
I like most of @leagris suggestions and they will fit better than meta arrows.
Closing this for now, saved leagris suggestions in separate issue.

**Comment by Agrax** [comment]
GT: ICBM, but okay. It’s your mod
