### ISSUE TITLE
Cannot craft GT cables

### ISSUE THREAD

**Issue by Rameron** [GregTechCE/GregTech#864]
Hello.

May someone explain me why I cannot to craft GT cables and instead of this I received IC2 cables? How can I fix that?

Thanks.

**Comment by Archengius** [comment]
remove IC2

**Comment by Rameron** [comment]
> remove IC2

But it's not the solution, there are no ways to fix it somehow else?

**Comment by Archengius** [comment]
yes. change recipe via CraftTweaker
