### ISSUE TITLE
Wires crash in refined storage patterns

### ISSUE THREAD

**Issue by AGithub457** [GregTechCE/GregTech#866]
Any wires put in a refined storage pattern crash. It seems that one of the CodeChickenLib hooks haven't been implemented correctly with them.

[Crash report 1](https://pastebin.com/hapLkp6G)
[Crash report 2](https://pastebin.com/PpeMN2zP)
[Crash image from VanillaFix](https://imgur.com/a/7gp1AqX)

Let me know if you need any more info!

**Comment by Archengius** [comment]
RefinedStorage problem. will not be fixed.

**Comment by AGithub457** [comment]
Well refined storage dev is saying it's your issue. Can you explain more why it's a RS issue instead?

**Comment by Archengius** [comment]
no. lookup closed issues instead.

**Comment by liquidblur** [comment]
https://github.com/GregTechCE/GregTech/issues/517#issue-400474570

**Comment by Archengius** [comment]
Perhaps you got me wrong, or I wasn't clear enough in previous issues, or
you can't read, or both. It will not be fixed. I don't give a shit about
it, because the way that mod does rendering is not supported, and I can do
FUCKING NOTHING to repair things on my side. So stop trying to make me
think it's my problem, it's not.

**Comment by liquidblur** [comment]
Oh no that was to him to read why it's not something on your end. People dont like to research so I did it for him. My apologies

**Comment by AGithub457** [comment]
I did stumble upon that, but there were no concrete information in that. I talked with other developers, and they also told me to ask in a new issue so we don't clutter the old one, or potentially have it ignored.

**Comment by liquidblur** [comment]
It's a RS issue. As this isnt a thing in AE2. Needs to be taken up with Rs devs or you need to switch to AE2

**Comment by AGithub457** [comment]
Perfect, I'll go to the RS dev and talk to him about it. You guys really don't have to be so rude. I fully understand that you guys get asked this a lot, and I'm sorry for pestering you, but when both issue threads point fingers at each other and don't give any evidence as to why, how are we left to handle it? I needed more info, and you have finally given it to me, thank you. The other issue had no concrete information.

**Comment by pyure** [comment]
Guys, plural?  Just Archengius, generally.  He has difficulties working with other people.
