### ISSUE TITLE
Robot Arm cover with Oredict filter lose transfer amount when reloading

### ISSUE THREAD

**Issue by mpapushin** [GregTechCE/GregTech#867]
When a robot arm is used as a cover with either no filter or an oredict filter, on either supply exact or keep exact mode, the transfer size option does not get saved after a reload, and gets reset back to 1 every time.

Tested in GTCE 1.12.2-1.8.1.399

**Comment by liquidblur** [comment]
Gtce us current on 1.8.3.418. Please try to repeat the issue/bug on latest build

**Comment by mpapushin** [comment]
My mistake on checking wrong mods folder, original test was 1.8.3.416, not 1.8.1.399.

Tested again after updating to 1.8.3.418, same problem persists.

**Comment by mfkG** [comment]
I have the exact same Problem. FTB:I with GTCE 1.8.3.418
