### ISSUE TITLE
What did you do with electricity in new GT?

### ISSUE THREAD

**Issue by TheDarkDnKTv** [GregTechCE/GregTech#869]
I made a simple circuit, how shown bellow:
![2019-06-25_12 51 15](https://user-images.githubusercontent.com/42381105/60088795-ef040100-9747-11e9-9765-67c4667e652b.png)
In this case i can provide 4A of current to network through 4x cable, then i have 4 consumers with 1A input. Why the cable is burned, if it is imposible to go 2A through? Then iu need to do all my wiring with 4x? In this version electricity is fully broken and working very strange and unexpected.
![2019-06-25_12 53 32](https://user-images.githubusercontent.com/42381105/60088986-40ac8b80-9748-11e9-9e5c-03b3688c3aed.png)

**Comment by Agrax** [comment]
You didn’t even provide the version number, bruh

**Comment by TheDarkDnKTv** [comment]
My fault.
Forge: 1.12.2-14.23.5.2836
GTCE: 1.12.2-1.7.0.387
What else do you need?

**Comment by Kanzuke117** [comment]
You need to update, I believe this is one of the cable-burning issues explicitly fixed in a recent update

**Comment by Agrax** [comment]
Well, he *could*, but the newest version is kind of broken on so many different levels, he *shouldn’t*. Performance, axes, crashes... Should i go on?

**Comment by Archengius** [comment]
1/1 warning, watch your language.
Was fixed in latest version.
