### ISSUE TITLE
Centrifuged Olivine Ore - Manganese instead of Magnesium

### ISSUE THREAD

**Issue by mellamokb** [GregTechCE/GregTech#873]
The recipe for pulverizing "Centrifuged Olivine Ore" shows in JEI as a 14% chance secondary output of Manganese dust. That doesn't make sense, because the other olivine recipes output magnesium, and the chemical formula is Mg, not Mn.  It looks like a bug in that particular recipe, it should be outputing secondary magnesium dust instead.  Thanks!

**Comment by Archengius** [comment]
magnesium = compound of olivine
manganese = byproduct of refining olivine ore
nothing wrong there
