### ISSUE TITLE
[Suggestion] Sorting machine/Router block

### ISSUE THREAD

**Issue by XXxinsanityxX** [GregTechCE/GregTech#877]
In mid to late game setups you have to set up multiple machines to do big batch crafts for example if i want to make 200 casings for some distillation towers, im going to have to make about 400 plates so for that i will have lets say 4 bending machines doing the job using a chest as a buffer and from the chest pipe them to the different machines using some kind of round robin, my suggestion is to add some sort of sorting machine or something like the old router block from factorization to be able to simplify these kinds of setups.

**Comment by Agrax** [comment]
GT is not meant to be played alone. Use RFTools or AE2. Thank you for the suggestion tho. Let us see what Arch says abt it

**Comment by pyure** [comment]
The GT chest exists to perform the sorting function in conjunction with appropriate covers (conveyors, robotic arms, etc).  If you have ideas on how to make those modules more useful, I recommend suggesting ideas/changes there.
