### ISSUE TITLE
Oil visuals

### ISSUE THREAD

**Issue by TheRealMineTech246** [GregTechCE/GregTech#878]
GT oil seems to go invisible when it's underwater so is that like a visual bug?

also I just found out yesterday that MineTech123 was my little bother and I'm very sorry if you got frustrated by him and we use the same IP so today I tried joining GTCE discord since GT is my fav mod so pls unban you wont see or hear my annoying little brother ever again

**Comment by Archengius** [comment]
fluids are not visible while in one of them
