### ISSUE TITLE
Fatal error when joining server after adding any new mod. 

### ISSUE THREAD

**Issue by 3036Macloud** [GregTechCE/GregTech#88]
After adding a new mod to server and client, it doesn't matter which type I get a fatal error when attempting to join server. The only way I've found to fix the error and actually log in is to delete world and create a new one.

This is the start of the error -
[Netty Client IO #1/ERROR] [FML]: The fluid liquid.vanadium (specified as gregtech:liquid.vanadium) is missing from this instance - it will be removed.
This is the client log.
[latest.log](https://github.com/GregTechCE/GregTech/files/2086901/latest.log)

**Comment by Archengius** [comment]
it's not caused by any mod - it's some issue with vanadium

**Comment by Archengius** [comment]
fixed
