### ISSUE TITLE
[Bug] Washing crushed ore in cauldron

### ISSUE THREAD

**Issue by TheDarkDnKTv** [GregTechCE/GregTech#880]
When washing any crushed ore in cauldron, dropped not Purified ore, but centrifuged instead.
Is it ok?0 Because in GT5 was purified.

**Comment by Agrax** [comment]
What modpack?

**Comment by TheDarkDnKTv** [comment]
Custom. I think problem here: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/items/MetaItem1.java on 51

**Comment by Kanzuke117** [comment]
I've never tried using the cauldron on crushed ore, only dusts, but this may be an intentional change. After all, the intended process is to use the ore washer then centrifuge, the cauldron being a lower tech shortcut that doesn't give you any byproducts
