### ISSUE TITLE
Client crash when breaking pipe

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#881]
gregtech-1.12.2-1.8.4.419.jar

Broke 3 polyethylene pipes which contained water.  When I broke the one that was connected to the bottom of a Mixer, crash occurred.

https://pastebin.com/cmNtBGa5

> java.lang.NullPointerException: Unexpected error
>     at gregtech.common.render.FluidPipeRenderer.getPipeColor(FluidPipeRenderer.java:148)
>     at gregtech.common.render.FluidPipeRenderer.getParticleTexture(FluidPipeRenderer.java:281)
>     at gregtech.common.pipelike.fluidpipe.BlockFluidPipe.getParticleTexture(BlockFluidPipe.java:199)
>     at gregtech.api.block.BlockCustomParticle.addHitEffects(BlockCustomParticle.java:39)
>     at net.minecraft.client.particle.ParticleManager.addBlockHitEffects(ParticleManager.java:501)
>     at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1482)
>     at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2268)
>     at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
>     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
>     at net.minecraft.client.main.Main.main(SourceFile:123)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ionin-code** [comment]
Any updates on this issue? I get this error when breaking empty bronze pipe (GT: CE v. 418)
