### ISSUE TITLE
Client crash when placing pipe

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#882]
gregtech-1.12.2-1.8.4.419.jar

https://pastebin.com/LujmZeSN

When trying to place a pipe from bottom face.  I don't recall if I was placing it to bottom face of machine or another pipe.  I can try to isolate that if you need it.

> java.util.NoSuchElementException: key not found: down
>     at scala.collection.MapLike$class.default(MapLike.scala:228)
>     at scala.collection.AbstractMap.default(Map.scala:59)
>     at scala.collection.MapLike$class.apply(MapLike.scala:141)
>     at scala.collection.AbstractMap.apply(Map.scala:59)
>     at codechicken.multipart.TileMultipart.getCapability(TileMultipart.scala:593)
>     at gregtech.common.pipelike.fluidpipe.BlockFluidPipe.getActiveVisualConnections(BlockFluidPipe.java:103)
>     at gregtech.api.pipenet.block.BlockPipe.getActualConnections(BlockPipe.java:431)
>     at gregtech.api.pipenet.block.BlockPipe.getCollisionBox(BlockPipe.java:467)
>     at gregtech.api.pipenet.block.BlockPipe.func_180636_a(BlockPipe.java:321)
>     at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:461)
>     at net.minecraft.world.World.func_147447_a(World.java:1087)
>     at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
>     at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:357)
>     at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1241)
>     at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
>     at net.minecraft.client.main.Main.main(SourceFile:123)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by pyure** [comment]
This one also crashes client for anyone in the vicinity.

**Comment by Archengius** [comment]
Lookup closed issues before openiylng new one.
Lookup which mod is last in the stack trace.
This is fucking FMP bug.

**Comment by pyure** [comment]
Did look it up.  If I can't find it because you don't provide the information properly, its your fucking problem.  Quit embarrassing yourself.
