### ISSUE TITLE
Smart Filter concept.

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#884]
Idea for a new filter.  It would restrict passage of items to those that can be satisfied by valid recipes, in valid quantities, factoring in any already existing ingredients.

Example:  
- If placed on an electrolyzer, it would allow bauxite in multiples of 39.
- If placed on a chemical reactor with a configuration circuit that already has water in it, it would allow sulfur dust.

Possibly more work than its worth.

**Comment by Archengius** [comment]
Implemented for electrolyzer and centrifuge recipes.
