### ISSUE TITLE
[Question] Large steam turbine consumption

### ISSUE THREAD

**Issue by TheDarkDnKTv** [GregTechCE/GregTech#886]
How i can calculate steam consumption for large steam turbines? I'm testing it on my polygon, and one steel boiler not enough for one large turbine. How much steam does it consume? Why so much?

**Comment by Archengius** [comment]
Because it yields 8192 EU and consumes steam equivalent of that by standard rate?

**Comment by TheDarkDnKTv** [comment]
It will be nice, if will be possible to control rotor speed by steam thread, like it was in GT5u :(

**Comment by Archengius** [comment]
you cannot control rotor speed in real turbines.
so no.

**Comment by TheDarkDnKTv** [comment]
Are you sure? The less gas you feed, the lower the impeller speed. It is works in all type of turbine. If you not belive me, so how airplanes can control speed? You can see for yourself in this video: https://www.youtube.com/watch?v=UGn27IkWOqU&t=744
You need just add a dependency of rotor speed from amount of steam per tick. Forgive me for arguing with you.
