### ISSUE TITLE
Sodium Hydroxide Recipe

### ISSUE THREAD

**Issue by xenon54xenon54** [GregTechCE/GregTech#887]
Sodium dust can be reacted with water in the chemical reactor to yield 1 sodium hydroxide and 1B of hydrogen. The chemical equation (treating all solids in terms of moles and a bucket of fluid as a mole) should be Na + H2O -> NaOH + H. Therefore, electrolyzing 1 mole of NaOH from this reaction should yield 1 mole of sodium, 1 mole of oxygen, and 1 mole of hydrogen. This is not the case. 3 'piles' of NaOH must be electrolyzed to yield 1 'pile' of sodium, and a mole of oxygen and hydrogen. So by reacting 3 sodium dust with 3 buckets of water, 3 buckets of hydrogen are produced, and if the resulting sodium hydroxide is electrolyzed, an additional bucket of hydrogen and oxygen are produced and one sodium dust, but if the chemical equation is balanced, there should be 3 buckets of oxygen, 3 buckets of hydrogen, and 3 sodium dust. This can be fixed by turning the 1 sodium hydroxide produced from the initial reaction into 3.

This issue can be closed if the 66% loss during electrolysis is intended for balance or something.

**Comment by TheDarkDnKTv** [comment]
just need to remove half an bucket of hydrogen from output, it will nerf

**Comment by xenon54xenon54** [comment]
nvm, sodium hydroxide electrolysis removed entirely in latest versions
