### ISSUE TITLE
Amps may not be burning up wires

### ISSUE THREAD

**Issue by Lilylicious** [GregTechCE/GregTech#889]
Assumptions: Diesel Generators produce 1A each. CEU's accept 2A per battery slot. (Based on GT5).

I'm able to use 16 [tier] generators for a single 16 slot [tier] CEU. All 16 generators can use a single line of 1x HV cable, regardless of amp limit.

Using a [tier+1] CEU allows 64 [tier] generators, all of which still work on a single line of 1x cables.

Assuming that generators should generate 1A, something is wrong. Might be an issue with amperesUsed in [AcceptEnergyFromNetwork](https://github.com/GregTechCE/GregTech/blob/b08798a71702b3b67d4edbc0953282e264c48138/src/main/java/gregtech/common/pipelike/cable/tile/CableEnergyContainer.java#L33) or [DispatchEnergyToNode](https://github.com/GregTechCE/GregTech/blob/b08798a71702b3b67d4edbc0953282e264c48138/src/main/java/gregtech/common/pipelike/cable/tile/CableEnergyContainer.java#L71)

Edit: Forgot to mention that I was measuring the power output of the CEU using a power monitor from Ender IO, and I was dumping everything into an energy trash can, so the CEU was not filling up and disabling generators.

**Comment by Archengius** [comment]
no GTCE version, closed

**Comment by Lilylicious** [comment]
gregtech-1.12.2-1.8.4.419.jar
