### ISSUE TITLE
[Suggestion] Allow machine controller cover to toggle overclocking on/off

### ISSUE THREAD

**Issue by Valdevon** [GregTechCE/GregTech#892]
There is currently no way to disable overclocking on multiblock machines such as the EBF (unless I missed something).

It would be also be nice to be able turn overclocking off automatically and could provide some niche automation usage (like disabling overclocking on your ore processing line temporarily when you are running out of power)

**Comment by Archengius** [comment]
very niche usage. more widespread one would be just disabling it.
