### ISSUE TITLE
Bug : can't pull items from CEF/CEU

### ISSUE THREAD

**Issue by SimonGhislain** [GregTechCE/GregTech#893]
Hi.
I would like to send empty batteries from CEF/CEU to my main power production using enderchests. I tried with enderIO item conduits, hoppers, logistic pipes, etc. I can insert batteries in CEF/CEU this way, but there is no extraction possible. Probably because the CEF/CEU is like the input of a machine. Could that be fixed?

**Comment by Archengius** [comment]
could you report issues to the right mod? do you know that CEU/CEF are added by an addon?
