### ISSUE TITLE
[Issue] Pipes error

### ISSUE THREAD

**Issue by HonzaVinCZ** [GregTechCE/GregTech#894]
Hello, Archengius.
We're reporting this problem what we've been talking on Discord.
[https://media.discordapp.net/attachments/567981531025375244/596808763336556555/unknown.png?width=1202&height=549](url)

Pipe used was Medium Bronze Pipe.
Problem is that my mate could not see that pipe and he saw it just as tile.pipe.name. When he broke that thing, his client crashed.

**Comment by kobliznik** [comment]
![adadad](https://user-images.githubusercontent.com/8217189/60745338-19409480-9f7a-11e9-869c-fe4cb109c7d9.png)
![unknown](https://user-images.githubusercontent.com/8217189/60745339-19409480-9f7a-11e9-9747-5e3bf9a018bc.png)

**Comment by Black0305** [comment]
Are you on newest version?

**Comment by HonzaVinCZ** [comment]
Yes, we are.

**Comment by MasterEnderman** [comment]
I think i have a similar issue on my server as well, but it occurs while the pipe is placed that one client crashes.
Crash-Report: https://paste.dimdev.org/ulohucigeg.mccrash

**Comment by Archengius** [comment]
cannot reproduce on latest

**Comment by Archengius** [comment]
wait, think i found out the specific case when it happens
