### ISSUE TITLE
[Suggestion] Allow electical cable de-rating

### ISSUE THREAD

**Issue by Matakor** [GregTechCE/GregTech#896]
Example would be using hv cables with lv machines, it should allow for much higher amperage (a realistic electrical take, even). 

I am using multiple lv machines on 4x hv (silver) cabling, and of course it goes up in flames. Considering the tier of cable, this shouldn't be an issue at all. Instead, the 512eu with 4amp should convert to 32eu with 64amp, if using a 1:1 ratio, but it wouldn't be bad even if it was a 1:4 (round for fractional?) ratio loss with amp conversion. In that case, 4x hv should be able to accept 32eu/t with 16amp.

**Comment by Agrax** [comment]
No. It’s not how GT works

**Comment by Archengius** [comment]
use transformers
