### ISSUE TITLE
allow fluid cells to absorb arbitrary amount of fluid

### ISSUE THREAD

**Issue by SaculRennorb** [GregTechCE/GregTech#897]
might be a bug, might be a feature. I was glad to see that gtce had the (universal) fluid cells from ic2 and saw that the filled ones have 1000mb in their tooltip. Should have seen my confusion when trying to get like 36mb of something out of a machine and it doesn't work. Strangely tho, tanks from enderio and thermal work perfectly fine for that...
I saw the rejected issue with the tiny cells, but I would say they should just be able to hold any amount of fluid. Up to their max ofc, at wich point they work just like they do now, stackable and all that.

**Comment by Archengius** [comment]
no they shouldn't

**Comment by Kanzuke117** [comment]
Steel and Tungstensteel Cells work for this purpose, for any 36mb transferring needs

**Comment by SaculRennorb** [comment]
@Archengius is there a technical reason why they shouldn't work that way, or just because thats what you want them to be?

**Comment by Archengius** [comment]
Second.
