### ISSUE TITLE
[Suggestion] Higher output slot number on Mixer and Chemical Reactor

### ISSUE THREAD

**Issue by Invincible92** [GregTechCE/GregTech#900]
Hi Arch,

Do you think it could be possible to expand the amount of output slots that the Mixer and the Chemical Reactor present?

Right now (in v. 419) the Mixer has 4 item inputs + 2 fluid inputs and 1 item output + 1 fluid output, while the Chemical reactor has 2 item inputs + 3 fluid inputs and 1 item output + 2 fluid outputs.

I am thinking about 4 item outputs  and 2 fluid ones (or 2 item outputs and 2 fluid outputs) in the Mixer and 4 item outputs and 3 fluid ones (or 2 item and 3 fluid outputs) in the Chemical Reactor. What are your thoughts in this matter?

This would allow buffering inside the machines or processing while the buffer is emptied. Also, it would allow users (and modpack makers too) to add a higher variety of recipes on those machines.

Thanks for your kind attention.

**Comment by Archengius** [comment]
No. Mixer mixes ingredients, it cannot give 4 item outputs by definition

**Comment by Invincible92** [comment]
And what about the chemical reactor?

**Comment by Archengius** [comment]
that's just too much. chemical reactor is already too big

**Comment by Agrax** [comment]
The assembler is not that small either
