### ISSUE TITLE
Wrench misbehaves in custom recipes

### ISSUE THREAD

**Issue by 42Rundas** [GregTechCE/GregTech#901]
Hello, I'm using CraftTweaker to modify certain recipes in my modpack.
But when I try to use <ore:craftingToolWrench> in one of them, the wrench must be at full durability for the recipe to work. I tried to add ".anyDamage()" for the wrench but that gives a scrip-error. 

Also another thing which technically belongs to Shadows of Greg (an expansion mod) but maybe someone here knows a solution to this, since the syntax in CraftTweaker is nearly if not completely the same.

SoG adds the Assembly Line (a multiblock) and I want to turn Forestry's Sturdy Casing into an Impregnated Casing using Honey and Seed Oil. 
This was my attempt here:

val assembly_line = RecipeMap.getByName("assembly_line");
assembly_line.recipeBuilder().inputs(<forestry:sturdy_machine> * 1).fluidInputs([<liquid:seed.oil> * 1000, <liquid:for.honey> * 1000]).outputs(<forestry:impregnated_casing> * 1).duration(20).EUt(32).buildAndRegister();

I get no script errors, the recipe just isn't added.
This issue is also posted on the SoG GitHub page.
Any help is appreciated
Rundas

Edit: the <> are not displayed for whatever reason

**Comment by Archengius** [comment]
CT bug, use raw item id + meta instead for now

**Comment by 42Rundas** [comment]
But doesn't that mean I can only use one wrench (for example iron)?
Or is this related to the second problem?
If no that means there is no solution for it atm?
Sorry for being not that experienced xD

**Comment by Archengius** [comment]
Wrench material is NBT, so no, it doesn't

**Comment by 42Rundas** [comment]
Ah ok, I just use <gregtech:meta_tool:8> and leave away the .withTag part.
Thank you.
Anything for the second problem?
