### ISSUE TITLE
CCL error rendering block

### ISSUE THREAD

**Issue by lampyr** [GregTechCE/GregTech#906]
Hello i have this spam in my console:

[16:29:00] [Chunk Batcher 15/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:765, y:61, z:41
  Block Class:   class gregtech.common.blocks.surfacerock.BlockSurfaceRockFlooded
  Registry Name: gregtech:surface_rock_flooded_0
  Metadata:      7
  State:         gregtech:surface_rock_flooded_0[level=0,material=iron]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null

java.lang.NullPointerException: null

log: https://pastebin.com/bWApFjWu

**Comment by Archengius** [comment]
not a full log
