### ISSUE TITLE
How to remove a recipe from the Assembler which uses a programmed circuit

### ISSUE THREAD

**Issue by 42Rundas** [GregTechCE/GregTech#908]
Hello, just asking how you remove a recipe which uses a programmed circuit from the Assembler.'
Because neither this "assembler.findRecipe(16, [<ore:plateSteel>*8 ,<gregtech:meta_item_1:32766>.withTag({Configuration: 8})],null).remove()"
or this "assembler.findRecipe(16[<ore:plateSteel>*8],<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).remove()" works. This is the LV Machine Casing btw. Any help is appreciated.
Rundas

**Comment by Archengius** [comment]
show recipe in JEI

**Comment by 42Rundas** [comment]
If I do that, I get the one which is crafted by hand using a wrench, or the one in the Assembler.
The first is already modified correctly. But the second one makes problems. But maybe I just don't get what you mean by "show recipe in JEI" :D

**Comment by Archengius** [comment]
show recipe screenshot as in JEI

**Comment by CelestialPhoenix** [comment]
`val theassembler as RecipeMap = RecipeMap.getByName("assembler");`

`theassembler.findRecipe(16, [<ore:plateSteel>.firstItem * 8, <metaitem:circuit.integrated>.withTag({Configuration: 8})], null).remove();`

Of note; don't use the internal ID (`/mt hand`) for Gtech stuff- those are generated automatically and can change during Gtech updates. Ore dict or Metaitem (from `/gregtech util hand`) is recommended.

**Comment by 42Rundas** [comment]
Thanks, that fixed it. Also that was like the fastest response to an opened issue I got so far.
Really quick 👌
