### ISSUE TITLE
Robotic Arm "Keep Exact" broken in HEAD

### ISSUE THREAD

**Issue by predakanga** [GregTechCE/GregTech#910]
In HEAD (currently c674dd3), the robotic arm's Keep Exact feature does not seem to function at all.

Replication steps:
1. Build from git revision c674dd3 or install [CI build](https://gitlab.com/GregTechCE/GregTech/-/jobs/245934078/artifacts/file/build/libs/gregtech-1.12.2-1.8.4.425.jar)
2. Create a new test world
3. Place down an Advanced Electric Furnace and Advanced Diesel Generator with fuel (or other power supply)
4. Place a chest on one side of the electric furnace, filled with cobblestone
5. Apply a Robotic Arm (MV) to the same side of the electric furnace
6. Configure the Robotic Arm with a screwdriver as follows:
    - Mode: Import
    - Keep Exact
    - 10 items
7. Remove any cobblestone from the furnace's input and confirm that it is not refilled

I have also tested this with the addition of an item filter in whitelist mode with the same results. Have not yet tested whether an Oredict filter experiences the same problem.

**Comment by Archengius** [comment]
Did you put item type to keep in filter attached to robot arm?

**Comment by predakanga** [comment]
Yes.

I tried it without a filter (worked in 1.8.4, does not work in HEAD) and with a Item Filter set to whitelist 10 cobble (worked in 1.8.4, does not work in HEAD).

I didn't test a Item Filter set to blacklist or an Oredict Filter in either whitelist or blacklist.

**Comment by predakanga** [comment]
(happy to do any debugging needed, but I couldn't get a debug environment working)

**Comment by predakanga** [comment]
Just ran a few more tests; it doesn't work in blacklist mode or with the Ore Dictionary Filter either.

Also forgot to mention, I'm testing on the Omnifactory 1.2.1 pack with only GregTech upgraded as mentioned.

**Comment by SimonGhislain** [comment]
Hello,
I wanted to upload a new bug but it's probably related to this one. 
The "transfer exact" number set on a Ore Dictionnary Filter inside a Robotic Arm works fine, but resets to 1 after every restart (loading of world).

Replication steps :

1. Place a MV Packager
2. Place a MV Robotic Arm as a cover, then click it with a screwdriver
3. Set it to import, and speed = 18 items/tick
4. Add a Ore Dictionnary filter in the filter slot
5. Set it to "dustTiny*", white list.
6. Set the "transfer exact" number to 18 items.
7. Works fine. Do do something else, Return, click with a screwdriver, value still at 18 items.
8. Exit your world, get to Minecraft Main Screen, than reload your world.
9. Click with a screwdriver : the import speed (robotic arm) is still 18 items/tick but the Ore Dictionnary "transfer exact" number is reset to 1.

**Comment by predakanga** [comment]
@SimonGhislain You’re probably better off filing a new bug for that.

This bug refers to changes that haven’t been released yet (robotic arm has had a major rewrite since the last release, that rewrite is what this bug is about).

If you’re experiencing your bug in a released version, it’s probably unrelated

**Comment by SimonGhislain** [comment]
> @SimonGhislain You’re probably better off filing a new bug for that.
> 
> This bug refers to changes that haven’t been released yet (robotic arm has had a major rewrite since the last release, that rewrite is what this bug is about).
> 
> If you’re experiencing your bug in a released version, it’s probably unrelated

Ok, thanks, and sorry for the confusion. I opened a new bug.
