### ISSUE TITLE
Shapeless conversion problem (even with metadata)

### ISSUE THREAD

**Issue by 42Rundas** [GregTechCE/GregTech#912]
Hello, I'm back again xD
This time I want to a Wrought Iron block convertible by hand into 9 ingots.
Therefore I added this shapeless recipe:
"recipes.addShapeless("WIIngot", <gregtech:meta_item_1:10197>*9, [<gregtech:compressed_8:15>]);"
The recipe is added and shown correctly in JEI, but when placing the block into a crafting grid nothing appears.
Any help is appreciated
Rundas

**Comment by CelestialPhoenix** [comment]
If you're using CraftTweaker you need to put triangle brackets around the items.
`recipes.addShapeless("WIIngot", <gregtech:meta_item_1:10197>*9, [<gregtech:compressed_8:15>]);`

**Comment by 42Rundas** [comment]
For some reason, these brackets are not displayed when I copy the recipe xD.
They are here but not displayed.
Otherwise, crafttweaker spits out a script error :D

**Comment by leagris** [comment]
> For some reason, these brackets are not displayed when I copy the recipe xD.
> They are here but not displayed.
> Otherwise, crafttweaker spits out a script error :D

bloc quote your recipe/code fragment with:
Three back ticks alone ```ZenScript before first line of code

Three back ticks alone ``` after last line of code

Like this:

```ZenScript
````ZenScript
recipes.addShapeless(
  "WIIngot",
  <gregtech:meta_item_1:10197>*9,
  [<gregtech:compressed_8:15>]
);
``` 
```

**Comment by 42Rundas** [comment]
Ah, thanks. That will take care of this inconvenience^^

**Comment by Agrax** [comment]
Don’tcha ever use the gregtech:meta_item syntax. Either use oredicts or /gt util hand syntax. Using the „basic” syntax for GTCE is highly unrecommended

**Comment by 42Rundas** [comment]
Ok, but when I use this "gregtech:compressed_8 (Metadata:15)" as the input (Wrought Iron Block)
I get a script error. And the ingots are already using the meta-syntax. At least I believe so due to the "meta_item" there.
Sorry for being somewhat dumb.

**Comment by leagris** [comment]
@42Rundas  https://github.com/GregTechCE/GregTech/issues/912#issuecomment-511229187

**Comment by 42Rundas** [comment]
The brackets are here so no need for copying the whole recipe again^^

**Comment by Agrax** [comment]
Rather: `<ore:ingotWroughtIron>` as an input or `<ore:blockWroughtIron>.firstItem`, as an output.

For things that don’t have an oredict, Arch prepared such a syntax <meta:motor.lv>

**Comment by 42Rundas** [comment]
You made a small mistake I guess. I wanna turn a block into 9 ingots not the other way around.
But even changing the recipe like this doesn't fix the problem.
`recipes.addShapeless("WIIngot", <ore:ingotWroughtIron>.firstItem*9, [<ore:blockWroughtIron>]);`

**Comment by Agrax** [comment]
Uhm... Because there should be such a recipe by default? All GT blocks are made by hand and reconverted back to ingots in the exactly same way

**Comment by 42Rundas** [comment]
Oh, then I have another mod installed which overwrites the recipe for whatever reason.
I'll figure out which one it does and then try to change some configs.
Thanks to anyone who helped me, but this will probably no be the last question I have :D

**Comment by Agrax** [comment]
Try running GT on it’s own and check if the issue persists by any means
