### ISSUE TITLE
Steam Macerator/High Pressure Steam Macerator same speed?

### ISSUE THREAD

**Issue by MechanosG** [GregTechCE/GregTech#914]
So I'm doing some testing with gregtech-1.12.2-1.8.3.416 (yes I'll be updating soon), and I decided to test a Steam Macerator vs a High Pressure Steam Macerator side by side.  I put an equal amount of graphite ore into both (16 each), and they appear to be grinding ore at the same exact speed?  They finished at the same time.  Both are being supplied with a constant source of steam and I've tested different pipes to make sure they have enough throughput.  So I assume this must be a bug?  

I haven't haven't tested to see if other high pressure machines are acting the same and running at bronze steam machine speeds, so I don't know if this specific to the macerator or not.  But I figured I'd report it.

**Comment by Archengius** [comment]
Ore crushing uses 12 EU/t. Only difference between HP and non-HP is that HP is allowed to overclock. 12 EU/t is too much for overclocking, so they run on same speed

**Comment by Agrax** [comment]
Well, this sucks :P

**Comment by MechanosG** [comment]
I see.  Maybe I should take this opportunity to suggest that HP Steam machines be more useful in some way then?  I was wrongly assuming they would work similar to GT5's description of high pressure machines, where you get like..  (don't quote me on exact numbers) X% speed boost at Y% more steam cost.  These examples off FTB wiki seem to have a 100% speed boost at 50% more steam usage per item.

https://ftb.gamepedia.com/Steam_Macerator
https://ftb.gamepedia.com/High_Pressure_Macerator

https://ftb.gamepedia.com/Steam_Furnace
https://ftb.gamepedia.com/High_Pressure_Furnace

**Comment by Archengius** [comment]
Discussion moved to #1324 I guess.
