### ISSUE TITLE
Pump can't work

### ISSUE THREAD

**Issue by debilh** [GregTechCE/GregTech#916]
I want to collect some lava in the hell,the first run was very successful,but when I change a place to collect the lava again.The pump can't run any more.

Also,if the pump was placed too long,when I look at it will happen a huge fps less

**Comment by Agrax** [comment]
What version of GregTech Community Edition? Were you trying it just by itself or in a modpack?

**Comment by debilh** [comment]
It is a modpack,the pump can work in most of time,expert the hell.
The gregTech version:1.8.1.399

I try to update the version to solve this problem,but when I done it,the server was uable to enter.

**Comment by Agrax** [comment]
Well, what modpack is that, if i can ask?

**Comment by debilh** [comment]
Here are them:
Advanced+Solar+Panels
Allmprovements
Applecore
Chamelon
ChickenChunks
CodeChickenLib
CookingForBlockheads
DupeFixer
EnderStorage
extrautil2
exutilfix
furniture
foamfix
gregtech
industrialcraft2
jei
Mentle
NoMoreRecipeConflict
Pam's+HarvestCraft
Phosphor
plustic
randompatches
SpiceOfLife
StorageDrawers
TConstrust
tmel
twilightforest
VanillaFix
Wawla

**Comment by Agrax** [comment]
So it’s your own modpack, an unnamed one?

**Comment by debilh** [comment]
yep

**Comment by Shchu4ka** [comment]
Same thing at the modpack Infitech3
Pump placed in Ocean biome, after some hours pipe goes to bottom and server freeeeeze =)

**Comment by Archengius** [comment]
Was fixed by recent PR i believe
