### ISSUE TITLE
Multiple Fluids in Pyrolyse Oven

### ISSUE THREAD

**Issue by 42Rundas** [GregTechCE/GregTech#920]
Just a question: Can the Pyrolyse Oven have multiple fluids as in-/output?
Because when I do that, the custom recipe will not be added into the game. But also no script error will occur.

**Comment by Agrax** [comment]
It can’t. Just count them in-game slots

**Comment by 42Rundas** [comment]
Ok. I got this idea because the multiblock still forms when it has multiple fluid inputs/outputs.
Thanks
