### ISSUE TITLE
Graphics: Floating Bronze Chest

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#923]
![image](https://user-images.githubusercontent.com/8617528/61753394-2f719180-ad7d-11e9-8821-90f08e5ce92e.png)

It moves around on a 3d plane as if its distance from actor isn't quite what it seems: If I slide to the left, the chest will be in the middle of that walkway.

**gregtech-1.12.2-1.8.4.419.jar**

**Comment by pyure** [comment]
Chest is a visual artifact only; you cannot interact with it.

**Comment by pyure** [comment]
Did some more testing with this, got at least a bit of useful information.
* The chest seen is a representation of a GT chest in that chunk being used as a buffer.  
* I tried removing its covers (conveyors, filters), moving it a few blocks away, etc, and it still turned into a ghost-floating chest when you were not looking directly at the real location of the chest.
* The real chest turns into an invisible box when it is in ghost-mode
* Replacing the chest with a different type (say, Titanium) has the same problem
* Chests in other chunks do NOT have this problem.
* Placing a GT Pipe does NOT have this problem

**Comment by Archengius** [comment]
Fixed by other mod dev

**Comment by BorisMulder** [comment]
As in the above issue, the Fancy Fluid storage mod might be a cause of this. Disabling that mod if you have it fixed it for me since there are no updates yet. So if anyone still has this issue, check if you use that mod.
