### ISSUE TITLE
Robotic Arm "Supply Exact" value resets to 1 on World load

### ISSUE THREAD

**Issue by SimonGhislain** [GregTechCE/GregTech#924]
Hello,
The "Supply Exact" number set on a Robotic Arm works fine, but resets to 1 after every restart (loading of world).

Tested on : Single Player World, ModPack : OmniFactory

Replication steps :

1. Place a MV Packager
2. Place a MV Robotic Arm as a cover, then click it with a screwdriver
3. Set it to import, and speed = 18 items/tick
4. Add a Ore Dictionnary filter in the filter slot
5. Set it to "dustTiny*", white list.
6. Set the "Supply Exact" number to 18 items.
7. Put a GregTech chest next to the packager (on the robotic arm side), Fill it with various tiny dusts.
8. Works fine. Do do something else, Return, click with a screwdriver, value still at 18 items.
9. Exit your world, get to Minecraft Main Screen, then reload your world.
10. Click with a screwdriver : the Robotic Arm import speed is still 18 items/tick but the "Supply Exact" number is reset to 1.

This gets pretty annoying the more these kinds of setup are troughout your base.

**Comment by malakai97** [comment]
It appears this value just isn't saved to or loaded from NBT. I'll try to test this theory out tonight if nobody else gets to it first.

**Comment by Blood-Asp** [comment]
https://github.com/GregTechCE/GregTech/issues/867

**Comment by malakai97** [comment]
That is indeed the fix that I was going to suggest. I'm not sure if master is ready yet, but if not I could create a PR backporting this to 1.8.4, so that it can be released asap. Should I do that?

**Comment by choekstr** [comment]
Can confirm this is STILL an issue as of gregtech-1.12.2-1.8.4.419 (Omnifactory 1.2.1).  There are links that refer back to it being fixed back in June and 1.8.3.x versions which was either fixed and rebroke or was not actually fixed with the commit [c674dd3 ](https://github.com/GregTechCE/GregTech/commit/c674dd30780fe4d52f7394ff968fa3f884dd8c7e)

Robotic arm using Supply Exact still resets each time I restart the server (obviously SMP) using 1.8.4.419

**Comment by Blood-Asp** [comment]
The 419 build is from 27.06, the commit you linked is from 05.07.
There is no official build out with that fix yet.

**Comment by choekstr** [comment]
and yet that commit references 867 that you referenced here:
Fixed robotic arm not saving global transfer limit slider value. Closes #867.

**Comment by Blood-Asp** [comment]
yes... #867 was fixed after the last release. check the dates.

**Comment by choekstr** [comment]
ahh, gotcha.  I'm sorted now, just mistook jun and jul.

**Comment by Archengius** [comment]
works fine in latest commit

**Comment by daniel-dsouza** [comment]
I'm seeing this issue after restarting my Omnifactory server.

Omnifactory 1.2.2, mod version: gregtech-1.12.2-1.8.4.419.jar

**Comment by eutropius225** [comment]
Yes, the version Omnifactory uses is very old.

**Comment by LAGIdiot** [comment]
Thank you for replying to this thread. This issue was fixed months ago. But Omnifactory is using old version which may change soon...

**Comment by daniel-dsouza** [comment]
> 
> 
> Thank you for replying to this thread. This issue was fixed months ago. But Omnifactory is using old version which may change soon...

looks like someone [beat me to it](https://github.com/OmnifactoryDevs/Omnifactory/issues/205)!
