### ISSUE TITLE
Repeated Crashing with bronze pipe and drum

### ISSUE THREAD

**Issue by bdkuhman** [GregTechCE/GregTech#926]
This started with an Unexpected Error crash after placing a bronze pipe from my group of bronze machines to a Tungstensteel Drum
Now, upon reloading the world, a Ticking block entity crash occurs.

Using FTB Interactions 1.9.1 with GregTechCE updated to 1.12.2-1.8.4.419

First crash:
[crash-2019-07-23_23.15.09-client.txt](https://github.com/GregTechCE/GregTech/files/3428545/crash-2019-07-23_23.15.09-client.txt)

Second Crash:
[crash-2019-07-24_12.29.16-server.txt](https://github.com/GregTechCE/GregTech/files/3428547/crash-2019-07-24_12.29.16-server.txt)

**Comment by Archengius** [comment]
First crash is fixed in master and not related at all to second crash. 
Second crash is ForgeMultipart issue, report accordingly
