### ISSUE TITLE
Shutter modules cause server and client side crashes

### ISSUE THREAD

**Issue by tonalom** [GregTechCE/GregTech#927]
Spongeversion: _spongeforge-1.12.2-2825-7.1.7-RC3768

Forgeversion: forge-1.12.2-14.23.5.2838

Server crash log: https://pastebin.com/MSD7gb9w

Description: Whenever a player attempts to break a pipe with a shutter module installed , the server will instantly crash. Coupled with that, whenever a player stands on a pipe with a shutter module installed, the player will enter a disconnection loop to the server until moved away from the pipe.

**Comment by Archengius** [comment]
1/1 warning your version is outdated
