### ISSUE TITLE
After giving a player a gregtech:machine block, every tile entity is invisible.

### ISSUE THREAD

**Issue by MayusYT** [GregTechCE/GregTech#928]
![](https://i.imgur.com/RLvPz65.png)
![](https://i.imgur.com/SSteDQb.png)

Self explanatory. See title.

Version is 1.12.2-1.8.4.419.
Modpack is Omnifactory.

**Comment by Archengius** [comment]
Do not do it then. I'm surprised you haven't insta crashed with invalid machine item

**Comment by Archengius** [comment]
cannot reproduce
