### ISSUE TITLE
Importing new materials crashes the game

### ISSUE THREAD

**Issue by 42Rundas** [GregTechCE/GregTech#932]
Hello,
I use CraftTweaker to import "Tough Alloy" and "Magnesium Diboride" from NuclearCraft in order to make magnetic rods and fine wires respectively. Therefore I created this:
```
val magnesiumDiboride = MaterialRegistry.createIngotMaterial(715, "magnesium_diboride", 0x1a1a1a, "dull", 2);
magnesiumDiboride.addFlags(["GENERATE_FINE_WIRE"]);

val toughAlloy = MaterialRegistry.createIngotMaterial(716, "tough_alloy", 0x1a1a1a, "dull", 2);
toughAlloy.addFlags(["GENERATE_MAGNETIC_ROD"]);
```

But on every start, the game crashes with an exception caught from CraftTweaker.

Edit: It seems, that the addFlag is the problem. Without these, everything is fine.

Any help is appreciated.
Rundas

**Comment by hottentottententententoonstelling** [comment]
That's because these flags are not valid, see https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Material/#material-generation-flags for a list of valid flags

**Comment by 42Rundas** [comment]
Ah, I see.
Is there a way of creating the fine wire and magnetic rod somehow else?

**Comment by hottentottententententoonstelling** [comment]
@42Rundas add recipes to the corresponding machines and/or add crafting recipes

**Comment by 42Rundas** [comment]
How do think I can add a recipe for an item which doesn't even exist?

**Comment by hottentottententententoonstelling** [comment]
Use the material icon-set see: https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Material/#material-icon-set. In your case you should use FINE and MAGNETIC

**Comment by 42Rundas** [comment]
Ok, I'll give that a try.
Thanks man :D
