### ISSUE TITLE
why tungsten-containing materials electrolyzing requires 1920 EV?

### ISSUE THREAD

**Issue by xilowei920** [GregTechCE/GregTech#935]
There is some code in file DecompositionRecipeHandler
`
  //tungsten-containing materials electrolyzing requires 1920
        if (components.contains(Materials.Tungsten))
            return 1920; //EV voltage (tungstate and scheelite electrolyzing)
`
1920EV need "Molecular Disintegrator E-4908" which Recipe need TungstenSteel wire.

It seems to be a bug!? please fix it.

**Comment by Archengius** [comment]
1920 EU needs titanium, not tungsten.
