### ISSUE TITLE
Assembler with integrated circuit inside causes lag

### ISSUE THREAD

**Issue by Cyl18** [GregTechCE/GregTech#937]
![image](https://user-images.githubusercontent.com/14993992/62889624-51ef3d00-bd74-11e9-9391-f8bbbe1c116a.png)
![image](https://user-images.githubusercontent.com/14993992/62889664-6a5f5780-bd74-11e9-9472-150b97005dc4.png)

**Comment by Folanlron** [comment]
Something I have noticed with this, the assembler only lag's if a Fluid + Circuit is left inside, I've been running my auto crafting setup, as the system needs cables/circuits/hulls, rubber/plastic/soldering alloy is melted down, doesn't cause as much lag, but my guess is that the system is trying too constantly "poll" looking for crafting recipes with those conditions...
