### ISSUE TITLE
[Suggestion] Add remaining tiers of solar panels

### ISSUE THREAD

**Issue by XXxinsanityxX** [GregTechCE/GregTech#941]
They can be uncraftable in vanilla GTCE, but as long as they exist in game users and modpack devs can add the recipe for them and use them if they desire, if a recipe is given to them in my opinion they should be gated at least 2 tiers above their level of power, as an example if you want 1 lv solar you will require HV materials and components and so on for the remaining tiers.

**Comment by Archengius** [comment]
no. that's against of balance rules for them
