### ISSUE TITLE
Crash during preInit baked models

### ISSUE THREAD

**Issue by DarkYuan** [GregTechCE/GregTech#942]
I had FTB: Interactions installed on a server, but updated GTCE to latest to fix the lumberjack issue. Version 1.8.4.419 worked fine, but the new version just released (432) is throwing this error on the server:

```
Description: Exception in server tick loop
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Community Edition (gregtech)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
	at gregtech.GregTechMod.onPreInit(GregTechMod.java:100)
...
```
[https://pastebin.com/t2C908Ft](https://pastebin.com/t2C908Ft)

**Comment by Archengius** [comment]
fixed in 1.8.5
