### ISSUE TITLE
crash with  gtce *432

### ISSUE THREAD

**Issue by Krysinski** [GregTechCE/GregTech#943]
work fine with *419 ver, but with *432 get crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.219.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-32.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  gtce2oc (gtce2oc-1.12.2-1.4.jar)
  BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 8/21/19 12:31 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Community Edition (gregtech)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at gregtech.api.util.ModCompatibility$RefinedStorage.<init>(ModCompatibility.java:53)
	at gregtech.api.util.ModCompatibility.initCompat(ModCompatibility.java:20)
	at gregtech.GregTechMod.onInit(GregTechMod.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.5.0-2-amd64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2152600400 bytes (2052 MB) / 3438804992 bytes (3279 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 8 total; -XX:+AggressiveOpts -XX:MaxMetaspaceSize=512m -XX:+UseFastAccessorMethods -XX:+UseFastEmptyMethods -Xverify:none -Xms512M -Xmx6144M -XX:+UseParallelGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 105 mods loaded, 105 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                               | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                         | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCHI  | mcp                               | 9.42              | minecraft.jar                                        | None                                     |
	| LCHI  | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                             | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | advancedrocketrycore              | 1                 | minecraft.jar                                        | None                                     |
	| LCHI  | micdoodlecore                     |                   | minecraft.jar                                        | None                                     |
	| LCHI  | opencomputers|core                | 1.7.4.153         | minecraft.jar                                        | None                                     |
	| LCHI  | gtce2oc                           | 1.4               | minecraft.jar                                        | None                                     |
	| LCHI  | randompatches                     | 1.12.2-1.17.2.1   | randompatches-1.12.2-1.17.2.1.jar                    | None                                     |
	| LCHI  | ic2                               | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | libvulpes                         | 0.4.0.-56         | LibVulpes-1.12.2-0.4.0-56-universal.jar              | None                                     |
	| LCHI  | advancedrocketry                  | 1.5.0.-139        | AdvancedRocketry-1.12.2-1.5.0-139-universal.jar      | None                                     |
	| LCHI  | aquaculture                       | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                         | None                                     |
	| LCHI  | biggerpacketsplz                  | 1.2               | biggerpacketsplz-since1.8-1.2.jar                    | 266588b191a3e2974a4a577f282858a3bc07da42 |
	| LCHI  | catwalks                          | 1.12.2-4.0.44     | catwalks-1.12.2-4.0.44.jar                           | None                                     |
	| LCHI  | ceramics                          | 1.12-1.3.7        | Ceramics-1.12-1.3.7.jar                              | None                                     |
	| LCHI  | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | crafttweaker                      | 4.1.17            | CraftTweaker2-1.12-4.1.17.jar                        | None                                     |
	| LCHI  | forgemultipartcbe                 | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | jei                               | 4.15.0.269        | jei_1.12.2-4.15.0.269.jar                            | None                                     |
	| LCHE  | gregtech                          | 1.8.4.432         | gregtech-1.12.2-1.8.4.432.jar                        | None                                     |
	| LCH   | ceu                               | 1.0.4.1           | CEU-1.12.2-1.0.4.1.jar                               | None                                     |
	| LCH   | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| LCH   | chisel                            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCH   | immersiveengineering              | 0.12-89           | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | compositegear                     | 1.12.2            | CompositeGear-1.12.2-1.7.1.jar                       | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.17.jar                        | None                                     |
	| LCH   | discordintegration                | 3.0.4             | DiscordIntegration-mc1.12.2-3.0.5.jar                | None                                     |
	| LCH   | dynamictrees                      | 1.12.2-0.9.5      | DynamicTrees-1.12.2-0.9.5.jar                        | None                                     |
	| LCH   | harvestcraft                      | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCH   | dynamictreesphc                   | 1.12.2-1.4.2      | DynamicTreesPHC-1.12.2-1.4.2.jar                     | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.59     | EnderCore-1.12.2-0.5.59.jar                          | None                                     |
	| LCH   | enderio                           | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderiointegrationtic             | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderiobase                       | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderioconduits                   | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | opencomputers                     | 1.7.4.153         | OpenComputers-MC1.12.2-1.7.4.153.jar                 | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | refinedstorage                    | 1.6.15            | refinedstorage-1.6.15.jar                            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | enderioconduitsrefinedstorage     | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderiointegrationforestry        | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderiointegrationticlate         | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | ftblib                            | 5.4.3.130         | FTBLib-5.4.3.130.jar                                 | None                                     |
	| LCH   | enderiomachines                   | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderiopowertools                 | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LCH   | enderstorage                      | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | engineersdoors                    | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar                     | None                                     |
	| LCH   | fastleafdecay                     | v14               | FastLeafDecay-v14.jar                                | None                                     |
	| LCH   | forgelin                          | 1.8.2             | Forgelin-1.8.2.jar                                   | None                                     |
	| LCH   | microblockcbe                     | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LCH   | minecraftmultipartcbe             | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LCH   | ftbutilities                      | 5.4.0.100         | FTBUtilities-5.4.0.100.jar                           | None                                     |
	| LCH   | cfm                               | 6.3.0             | furniture-6.3.0-1.12.2.jar                           | None                                     |
	| LCH   | futureminecraf                    | 1.2.1.1           | FutureVersionsV1.2.1.1.jar                           | None                                     |
	| LCH   | galacticraftcore                  | 4.0.2.219         | GalacticraftCore-1.12.2-4.0.2.219.jar                | None                                     |
	| LCH   | galacticraftplanets               | 4.0.2.219         | Galacticraft-Planets-1.12.2-4.0.2.219.jar            | None                                     |
	| LCH   | gravestone                        | 1.10.1            | gravestone-1.10.1.jar                                | None                                     |
	| LCH   | immersivecables                   | 1.3.2             | ImmersiveCables-1.12.2-1.3.2.jar                     | None                                     |
	| LCH   | immersivepetroleum                | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| LCH   | trackapi                          | 1.1               | TrackAPI-1.1_1.12.jar                                | None                                     |
	| LCH   | immersiverailroading              | 1.6.1             | ImmersiveRailroading-1.6.1_1.12-1138.jar             | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.1.383  | Mekanism-1.12.2-9.8.1.383.jar                        | None                                     |
	| LCH   | tesla                             | 1.0.63            | Tesla-1.12.2-1.0.63.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | teslacorelib                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar           | None                                     |
	| LCH   | nuclearcraft                      | 2.17b             | NuclearCraft-2.17b-1.12.2.jar                        | None                                     |
	| LCH   | integrationforegoing              | 1.12.2-1.9        | IntegrationForegoing-1.12.2-1.9.jar                  | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | mekanismgenerators                | 1.12.2-9.8.1.383  | MekanismGenerators-1.12.2-9.8.1.383.jar              | None                                     |
	| LCH   | mekores                           | 2.0.7             | mekores-2.0.7.jar                                    | None                                     |
	| LCH   | tbone                             | v1.6.8+mc1.12.2   | TBone-v1.6.8+mc1.12.2.jar                            | None                                     |
	| LCH   | metalchests                       | v6.0.1+mc1.12.2   | MetalChests-v6.0.1+mc1.12.2.jar                      | None                                     |
	| LCH   | mtrm                              | 1.2.2.30          | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar           | None                                     |
	| LCH   | mjrlegendslib                     | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | morpheus                          | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                              | None                                     |
	| LCH   | mrtjpcore                         | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar              | None                                     |
	| LCH   | omlib                             | 3.1.3-246         | omlib-1.12.2-3.1.3-246.jar                           | None                                     |
	| LCH   | ompd                              | 3.1.0-55          | ompd-1.12.2-3.1.0-55.jar                             | None                                     |
	| LCH   | openmodularturrets                | 3.1.3-355         | openmodularturrets-1.12.2-3.1.3-355.jar              | None                                     |
	| LCH   | opensecurity                      | 1.0-32            | OpenSecurity-MC1.12.2-1.0-32.jar                     | None                                     |
	| LCH   | placebo                           | 1.6.0             | Placebo-1.12.2-1.6.0.jar                             | None                                     |
	| LCH   | planetprogression                 | 1.12.2-0.3.7      | PlanetProgression-1.12.2-0.3.7.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | plants2                           | 2.10.7            | Plants-1.12.2-2.10.7.jar                             | None                                     |
	| LCH   | shetiphiancore                    | 3.5.9             | shetiphiancore-1.12.0-3.5.9.jar                      | None                                     |
	| LCH   | platforms                         | 1.4.6             | platforms-1.12.0-1.4.6.jar                           | None                                     |
	| LCH   | projectred-core                   | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar                  | None                                     |
	| LCH   | projectred-compat                 | 1.0               | ProjectRed-1.12.2-4.9.1.92-compat.jar                | None                                     |
	| LCH   | projectred-integration            | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| LCH   | projectred-transmission           | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| LCH   | projectred-fabrication            | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-fabrication.jar           | None                                     |
	| LCH   | projectred-illumination           | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-lighting.jar              | None                                     |
	| LCH   | projectred-expansion              | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| LCH   | projectred-relocation             | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| LCH   | projectred-transportation         | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| LCH   | projectred-exploration            | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-world.jar                 | None                                     |
	| LCH   | reborncore                        | 3.14.1.457        | RebornCore-1.12.2-3.14.1.457-universal.jar           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | rebornstorage                     | 1.0.0             | RebornStorage-1.12.2-3.3.4.85.jar                    | None                                     |
	| LCH   | storagedrawers                    | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar                      | None                                     |
	| LCH   | storagedrawersextra               | @VERSION@         | StorageDrawersExtras-1.12-3.1.0.jar                  | None                                     |
	| LCH   | vtb                               | 2.0.0             | VillagerTradingBan-2.0.0.6-universal.jar             | None                                     |
	| LCH   | weirdinggadget                    | 1.0               | weirdinggadget-1.12.2-2.1.16-universal.jar           | None                                     |
	| LCH   | xtones                            | 1.12-1.0.8-11     | Xtones-1.12-1.0.8-11.jar                             | None                                     |
	| LCH   | zettaindustries                   | 1.3               | zettaindustries-1.3-1.12.2-161.jar                   | None                                     |
	| LCH   | industrialwires                   | 1.7-36            | IndustrialWires-1.7-36.jar                           | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCH   | teslacorelib_registries           | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                     | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.219.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SoundUnpack (OpenSecurity-MC1.12.2-1.0-32.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  mekanism.coremod.KeybindingMigrationHelper
gtce2oc (gtce2oc-1.12.2-1.4.jar)
  org.eientei.gtce2oc.GTCE2OCTransformer
BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.14.1.457
		Runtime Debofucsation 1
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'

**Comment by Archengius** [comment]
refined storage issue

**Comment by raoulvdberge** [comment]
How is this a refined storage issue?

Last stacktrace element is in gregtech.api.util.ModCompatibility$RefinedStorage

**Comment by Archengius** [comment]
Reflection internals retrieving method types crash on your ItemPattern because your addInformation method is not marked client only and has net/minecraft/client/util/ITooltipFlag type argument which is missing on server side, resulting in reflection crash. While i've already fixed it on my side by doing some checks, it's still issue in your code and will potentially cause more problems.
