### ISSUE TITLE
GT Tank Output to Bottom

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#944]
Suggestion:
Wrench/Screwdriver/Hammer bottom face of a GT Tank in order to make it output fluids to bottom automatically (gravity).  Wooden at 25 mb/s, etc (tier)

Suddenly GT tanks are kind of awesome cuz they stack (albeit in one direction) and have the RC-Iron-Tank "trick" of outputting to bottom face.

**Comment by Archengius** [comment]
Closed in favour of multiblock tanks
