### ISSUE TITLE
Macerator output multiplier also applied in orewasher

### ISSUE THREAD

**Issue by Blood-Asp** [GregTechCE/GregTech#948]
The ores that output more crushed ores from ore, also have multiplied byproduct output from washing. 
As result processing for example lapis ore outputs ~1,5x as much lazurite than lapis. Having more byproduct than main product seems wrong to me.
![image](https://user-images.githubusercontent.com/8116649/63640187-94cae200-c69d-11e9-99f6-687e76dc4e5b.png)

**Comment by Archengius** [comment]
you're right, but honestly i have no idea how to balance that kind of changes

**Comment by Blood-Asp** [comment]
I would not use the multiplier there at all since it was already applied in the prior maceration step and carries down from there.

**Comment by Archengius** [comment]
Fixed in latest
