### ISSUE TITLE
Max voltage transformer having wrong ultimate voltage

### ISSUE THREAD

**Issue by Blood-Asp** [GregTechCE/GregTech#949]
The max transformers ultimate voltage is 1/4 of max voltage, but correct value would be 1/4096.
In GT5 the max transformer also had 4096 Amp on the lower voltage side to compensate for that.
![image](https://user-images.githubusercontent.com/8116649/63640261-4e29b780-c69e-11e9-8e4d-cbc8a03cc6cf.png)

**Comment by Archengius** [comment]
easier to remove MAX tier altogether 🤷‍♂

**Comment by Blood-Asp** [comment]
At the current point i certainly agree. 
In GT5U i used the max tier only a single time. When feeding crazy amounts of energy into GT from other mods. In that case Reikas Reactorcraft turbines that produced 100+ mio EU/t.

**Comment by Agrax** [comment]
But then there’s a problem if someone uses DE in a pack :D

**Comment by Blood-Asp** [comment]
Not really. DE produces RF and that can be send trough multiple converters creating multiple amps of EU. Reactorcraft could directly output EU and that at an higher voltage as UV, so no way of splitting into more amps without max voltage.
