### ISSUE TITLE
Crash with buildcraft in post-init

### ISSUE THREAD

**Issue by AlexIIL** [GregTechCE/GregTech#95]
See BuildCraft/BuildCraft#4194 and [#4195](https://github.com/BuildCraft/BuildCraft/issues/4195) - full crash report link: https://github.com/BuildCraft/BuildCraft/files/2087248/crash-2018-06-09_21.47.58-client.txt.

Essentially I think what's happening is that one of the stacks calls `BlockLogGT.func_176203_a` (`BlockLogGT.getStateFromMeta`) with a meta value equal to `OreDictionary.WILDCARD_VALUE` (32767). This is then divided by 4 to give `8191`. I think this might be fixable by changing the line from
````java
.withProperty(LOG_AXIS, EnumAxis.values()[meta / 4])
````
to
````java
.withProperty(LOG_AXIS, EnumAxis.values()[meta / 4 % EnumAxis.values().length])
````
to ensure that strange positive values for meta don't go outside the range. Alternately you could handle it  inside of 
https://github.com/GregTechCE/GregTech/blob/1a6122fefae1a99e0354a9b78bb6398b985fe36c/src/main/scala/gregtech/common/CommonProxy.java#L110-L117

and bring the value of `stack.getMetadata()` to between 0 to 15. ~~However that wouldn't handle the case where `meta = 15` as then `meta/4 = 3`, which is outside the bounds of the size-3 array.~~

**Comment by temp1011** [comment]
Sounds good. I'm by no means experienced with this codebase though. Maybe check for wildcard value and use `EnumAxis.NONE`?

**Comment by AlexIIL** [comment]
I'm not sure, and I've only looked over the code for 5 mins so you can probably ignore my examples if they don't work. In addition i think LOG_AXIS might include none, so that's one of my suggestions made useless.

**Comment by Rongmario** [comment]
This happens with newest versions of BC and GT: https://paste.dimdev.org/fujoqorawu.mccrash
