### ISSUE TITLE
Suggestion: Robot Arm Style Settings for Pumps

### ISSUE THREAD

**Issue by Exaxxion** [GregTechCE/GregTech#952]
Crafting can often require very particular fractional-bucket quantities of fluids. It would be extremely useful to be able to route fluids precisely with pumps like you can items with Robot Arms.

The main use cases would be stocking multiple machines with the same fluid to parallelize crafting without having portions left over in them, and to avoid putting more than necessary into fluid input hatches for multiblock structures like the EBF since it is impossible to extract fluid out of them once inserted.

Opening this ticket in response to https://github.com/GregTechCE/GregTech/issues/793#issuecomment-527245036.

**Comment by Ethryan** [comment]
Fluid Regulator from GT5?

**Comment by Agrax** [comment]
No need for a new cover when the current one can do it just fine with the fluid filter mod installed in it. IF Arch decides this idea sounds good
