### ISSUE TITLE
crash when looking up facade in jei with logistic pipes

### ISSUE THREAD

**Issue by robjw95** [GregTechCE/GregTech#953]
With logistic pipes install, I get the following crash when searching looking through facades in jei
[crash-2019-09-03_05.04.29-client.txt](https://github.com/GregTechCE/GregTech/files/3568777/crash-2019-09-03_05.04.29-client.txt)

**Comment by Archengius** [comment]
LP seems to have invalid/speci model for one of its simple blocks, which can be made into covers. I'll blacklist it, however I have no idea what is that block.
