### ISSUE TITLE
Conflicting SMD recipes create normal diodes

### ISSUE THREAD

**Issue by Anthios314** [GregTechCE/GregTech#954]
Tis I, Anthios. Today, I was setting up an electrolyzer in the modpack omnifactory. the circuits used a bunch of SMD transistors and SMD diodes, which I had crafted. However, because of the recipes used, they crossed and ended up creating normal diodes, something completely unwanted. 

![2019-09-08_11 34 10](https://user-images.githubusercontent.com/55056986/64490624-ca8ad180-d22c-11e9-80ac-4f63cb2bebb4.png)
This is the SMD diode recipie

![2019-09-08_11 34 14](https://user-images.githubusercontent.com/55056986/64490635-ebebbd80-d22c-11e9-9515-37ae1d4dc183.png)
This is the SMD transistor recipie

![2019-09-08_11 34 25](https://user-images.githubusercontent.com/55056986/64490637-f6a65280-d22c-11e9-9033-9e9bedfea5d1.png)
This is a normal diode recipie, in the assembler.

![2019-09-08_11 35 12](https://user-images.githubusercontent.com/55056986/64490640-045bd800-d22d-11e9-8dd1-7c8a5e71418f.png)
And this is what you end up with when you dump all the items in simultaneously (say, AE2)

As a result, this has wrecked my attempts at making microprocessor arrays and other circuits. I wonder why there is no programmed circuit that can tell the assembler to not make diodes. Please fix. 

Omnifactory version: 1.2.1
GregTech version: gregtech-1.12.2-1.8.4.419

**Comment by Archengius** [comment]
there is no bug there. you dumped ingredients which make up 3 different things into one machine, and machine selected one recipe it found first.
Use dedicated machines for different recipes.

**Comment by Anthios314** [comment]
I have figured out a solution that involves none of the above:

set the ME interfaces that input materials into the assembler to use "blocking mode", where they basically dont put items into the assembler if theres anything in it. 

costs nothing, requires no coding, and the system doesn't break.

**Comment by Blood-Asp** [comment]
The last time i tried the blocking mode of AE2 did not work on GTCE machines. 

Did that change or did you test it actually working?

**Comment by Anthios314** [comment]
well... its been 3 days and it hasn't broke, so I'm calling this a win.
