### ISSUE TITLE
[Suggestion] Config option to hide filled containers

### ISSUE THREAD

**Issue by XXxinsanityxX** [GregTechCE/GregTech#955]
A config to hide the diferent filled variants of the different tanks and cells from JEI like how you have only empty batteries instead of empty and full.

**Comment by HiggsBonbon** [comment]
There is an addon mod for JEI that hides items with no recipes, I'm not sure if that would cover what you're thinking of but I'd say it's worth taking a look at.
[link](https://www.curseforge.com/minecraft/mc-mods/jei-hider)

**Comment by Archengius** [comment]
Use JEI addon designed specifically for that. Currently, no other mods have such option and i see no reason why it should be added to GTCE.

**Comment by Samrel556** [comment]
Both thermal foundation and pressure pipes have config options to hide filled versions of their containers. Also the JEI hiding addon does not hide the fluid cells because they are used in filling and emptying recipes added by the thermal series and ender io.
