### ISSUE TITLE
Bronze tank as steam buffer cause lag.

### ISSUE THREAD

**Issue by CraftMarine** [GregTechCE/GregTech#956]
Hi I have some lag issue with a simple steam setup.
4 solar steam boiler in row connected to small bronze pipe and connected to a bronze tank.
On the other side, 4 pipe connected to steam machines.
There is a lv pump on the tank in order to extract steam into the side of machines.

Filling up / extracting steam in this tank cause lag / fps drop (200 to 40)

Configuration : 
i5 8400
20Go RAM (7 allocated)
GTX1050Ti
SSD M2 NVMe 500Go

**Comment by Archengius** [comment]
should work perfectly now.
