### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Aminion** [GregTechCE/GregTech#959]
[crash-2019-09-17_21.55.32-client.txt](https://github.com/GregTechCE/GregTech/files/3623024/crash-2019-09-17_21.55.32-client.txt)

**Comment by RedCorpIndustry** [comment]
It would be a good idea to add some more details. What were you doing when the crash occurred? It appears to be something involving a fluid pipe.

**Comment by Archengius** [comment]
Outdated gtce
