### ISSUE TITLE
Fine wires not shown in JEI

### ISSUE THREAD

**Issue by IcedReaper** [GregTechCE/GregTech#960]
Hi,
I'm having an issue where the fine wires are not shown in JEI.

Screenshot: https://imgur.com/rGLPVC3

Forge: 23.5.2847
Gregtech: 1.8.6.437
JEI: 4.15.0.268

// Edit: It's also the case in the current beta version 1.8.8.440.

**Comment by Archengius** [comment]
not my issue, your JEI is 6 months old

**Comment by IcedReaper** [comment]
I updated JEI to the latest beta version 4.15.0.289 and the fine wires are still not visible in JEI.

**Comment by IcedReaper** [comment]
You were correct. It was a problem on my end. I had hidden all filled tanks and somehow now all tool parts, the fine wires and a few other parts were hidden.
I thought I had checked the hidden parts before, but apparently not.
