### ISSUE TITLE
Robotic arm item count - behaviour issue

### ISSUE THREAD

**Issue by BorisMulder** [GregTechCE/GregTech#961]
When I adjust my robotic arm cover, the numbers (not the items/sec one but the other one) behave strangely.
- If I set it to keep exact, it will automatically set the count to 1024 items (see first image). I then have to click 1023 times on the "-" button if I want it to keep exactly 1 item in, which seems a bit useless.
- For supply exact it has a maximum of 64 so 63 times clicking is a bit better, but still...
- When I set it to Transfer Any, it displays some huge negative number (see second image). When I click on + it will go to 1, then when I click on - again it stays on one.

It would actually be nice if they all just started at 1 right away and/or if it was possible to just type in a number instead of using these buttons.

![afbeelding](https://user-images.githubusercontent.com/4689209/65389848-74ed1380-dd5a-11e9-9318-b87ff1e5c6df.png)

![afbeelding](https://user-images.githubusercontent.com/4689209/65389841-63a40700-dd5a-11e9-81a8-8e5655109a9a.png)

**Comment by Archengius** [comment]
(pro tip: you can use shift to click faster)
