### ISSUE TITLE
Does not play well with Applied Energistics 2

### ISSUE THREAD

**Issue by GGothicRide** [GregTechCE/GregTech#962]
As the title describes, roughly when you shift + left click a recipe in JEI onto the pattern terminal, it tends to default the circuits being used in the machinery crafting recipes to circuits you cannot obtain or craft and even the use ore dictionary button doesnt work in this manner

modpack : Omnifactory
http://prntscr.com/p9hzkg

also there seems to be a bad mod interaction between these 2 mods as applied energistics will cause massive lag and constant stuttering with gregtech

**Comment by Blood-Asp** [comment]
How should AE2 know whats the right oredict item? It does have that problem with every oredict, not only GTCE. To add to that, the circuits in Omnifactory are heavily tweaked and most of them added by the mod author, not original GTCE.

Also the lag of AE2 does happen without GTCE, it only means that the recipes have too many steps with too many items. Especially bad if you have an crafting loop that happens easily in omnifactory with the microminers. If you add a lot of automated crafting requests to that the lag goes trough the roof.

The only issue i every noticed with AE2 and GTCE is that the interfaces can't see the input slots and inserts the crafting materials on good luck making usage of blocking mode impossible.

**Comment by Archengius** [comment]
No issues here. Indeed, AE2 doesn't know which exact circuit to insert. And that's AE2 issue, not gregtech.
