### ISSUE TITLE
[Suggestion] Distillation tower

### ISSUE THREAD

**Issue by TheDarkDnKTv** [GregTechCE/GregTech#964]
You do not think that the speed and volume of processing of Distillation tower to small? It is impossible to use Gas turbines, because to power one big rubine you needed 256 distillators.... It is costs expensive, but more useless then small distillators. There is only one recipe where it makes sense to use Distillation tower - Ethanol producing. Please review the distillation tower.

**Comment by Archengius** [comment]
in which is it "more useless"? unlike distillery, it gives you ALL products, and works 2 times faster than distillery. I see no problems here.

**Comment by TheDarkDnKTv** [comment]
ok, how to use big gas turbine? where can you offer to receive fuel in such volume?

**Comment by Archengius** [comment]
no idea, i personally want to remove large turbines entirely.

**Comment by Agrax** [comment]
Don’t. It’s a really, really horrible idea. Those are the only viable energy producers

**Comment by TheDarkDnKTv** [comment]
If large turbines will be removed, so it will be impossible to use more than HV tiers of machines. Already lagging on our server with 50+ machine on autocraft... If turbines will be removed, amount of tileentity will increase to 100+ what will make game unplayable.

**Comment by Agrax** [comment]
If+ were* but other than that i agree. You need at least 2 HV turbines to run one EV machine. Assume you have 30 EV machines= ca 61-65 generators (due to the cable loss). 65+30= 65 ticking entities

**Comment by Archengius** [comment]
you need at least 0.33 of Large Diesel Engine to run one EV
100 tile entities is nothing. if that's exactly gtce machines which lag, it's an issue and should be reported.

**Comment by TheDarkDnKTv** [comment]
YES there is exactly GTCE machines, BUT it not beacause code is bad, it is becasue minecraft cannot handle so much ticking entityties. On our server we have 3 large bases with big working automatization of GTCE + AE. When summary amount of tileentyties getting more than 200+, server's main thread starting to freeze. It shows like 19.8 tps, but AE requests is glitching enough.
IT is MAIN reason why for running fusion reactor in GT5u was added processing arrays, to decrease amount of tileenityies from 16 to 1. So, i think removing large tubines is bad thing. Also for my server i multiply outputs of dist.columns about 8-16 times, cause i do not want to build 256 distillators to run one generator 8192eu/t. One more thing, i builded latest code from git, and there is bug with ForgeMultiparts, i do not know, maybe because code wasn't completed when i am bulding, but covers now to working on cables...

**Comment by TheDarkDnKTv** [comment]
>  works 2 times faster than distillery
It is not true, from code you have same recipes for one-block distillators and dist.column. I checked mu JEI and the time and amounts in recipes was same for both machines. That's why i said what dist.columns useless, yea actually it is gives you tons of byproducts, but you cant put all this liquids into turbine, beacse turbine not burnig it fully, and some amount of gases stay in input hatch.

**Comment by Archengius** [comment]
200 is still very little. It should be profiled to be fixed.
