### ISSUE TITLE
Steam Alloy Smelter not working consistently

### ISSUE THREAD

**Issue by Sixdd6** [GregTechCE/GregTech#965]
Steam Alloy Smelter will smelt the first operation fine then refuse to smelt after that. Breaking the block and replacing it allows it to smelt 1 operation again and then it refuses to smelt after. Tested using a Small Steam Coal Boiler with 1 bronze pipe connected between the boiler and machine.

Minecraft 1.12.2
Forge 14.23.5.2847
GTCE 1.8.8.440

**Comment by Archengius** [comment]
Output facing should not be blocked

**Comment by Sixdd6** [comment]
Sorry but I don't understand. There is no indication as to where an "output" is or what side it is on. Also what output, the steam boiler? the alloy smelter? Please give a detailed answer so I can understand.

**Comment by PapierZylinder** [comment]
All steam machines have a output on the backside of the block to vent steam. They dont work if they cant vent said steam. So what Arch meant was that you most likely blocked the backside of the machines with a block which prevents them from venting steam and therefore they cant work correctly.

**Comment by Archengius** [comment]
Every steam powered machine has venting side. After each recipe, machine
emits exhausts from it, unless it is blocked by solid block on that side.
Failure to release exhaust will make machine stall.
Visually venting side has gray square on it.

**Comment by Sixdd6** [comment]
Ah, that makes it much more clear, thank you both for the detailed explanation. I am new to GregTech so I was unaware. Much appreciated.

**Comment by Agrax** [comment]
Doesn’t the OF questline explain it tho?

**Comment by Sixdd6** [comment]
There's a questline?

**Comment by MechanicalCraft86** [comment]
Agrax I don’t think he’s playing Omnifactory

**Comment by Sixdd6** [comment]
Ah, no I'm actually making my own modpack. Just playing through things before I start writing my own docs so I know how things work.

**Comment by MechanicalCraft86** [comment]
If so then that’s something to add as tips in your custom questline

**Comment by Sixdd6** [comment]
Indeed it is.

**Comment by Agrax** [comment]
You should never make modpacks with mods you don't know well. At least imho
