### ISSUE TITLE
Energy convert

### ISSUE THREAD

**Issue by Macgraf** [GregTechCE/GregTech#968]
Hello, I play with IC2, AE2, I'm trying to convert energy like this https://sun9-70.userapi.com/c857428/v857428709/7b252/yYOnEwW7ZdY.jpg But nothing works.

**Comment by Agrax** [comment]
Use an addon called CEU. AE2 didn’t add a compatibility for for GTCE eu

**Comment by Macgraf** [comment]
Thank!
