### ISSUE TITLE
Locked Safe missing container texture

### ISSUE THREAD

**Issue by HonzaVinCZ** [GregTechCE/GregTech#969]
Hello Archengius. I found this missing texture in Locked Safe container.
No error in console when Locked Safe is placed.
MC Version: 1.12.2
GTCE Version: 1.12.2 1.8.8.440
Forge Version: 1.12.2 14.23.5.2838

![2019-10-14_21 00 42](https://user-images.githubusercontent.com/29098779/66776686-3fee5f80-eec7-11e9-9eaf-2c9597cb6f0c.png)
![2019-10-14_21 01 14](https://user-images.githubusercontent.com/29098779/66776688-3fee5f80-eec7-11e9-9097-0103def2b963.png)
![2019-10-14_21 01 16](https://user-images.githubusercontent.com/29098779/66776689-4086f600-eec7-11e9-9573-23da88623b9f.png)
![2019-10-14_21 01 20](https://user-images.githubusercontent.com/29098779/66776690-4086f600-eec7-11e9-9800-1db016988495.png)

**Comment by Archengius** [comment]
Update GTCE.
