### ISSUE TITLE
Bug: AE2 Fluid Interface and GTCE pump cover or input hatch

### ISSUE THREAD

**Issue by SinThetaC** [GregTechCE/GregTech#970]
Scenario 1:
I have an LV input hatch facing upwards, and on that face I have a fluid interface. When I put a bucket of argon into that interface (so that the system supplies fluid), argon appeared in the interface and the input hatch even though there was no argon in the system.
Scenario 2:
I have an IV chemical reactor, and on the left face I have a fluid interface supplying oxygen and butadiene, and an IV pump inputting those fluids into the chemical reactor (Styrene was coming from another chemical reactor above this reactor). When the machine was running, I noticed that the butadiene was not running out even though my system was devoid of it. I suspect it was the same deal with the oxygen as well, although I had so much oxygen it was impossible to tell.
Scenario 3: IV Chemical Reactor doing stuff with naphtha, same deal as Scenario 2 where the hydrogen and the sulfuric naphtha didn't run out, same pump and same settings (except fluid interface supplying H and sulfuric naphtha)

**Comment by SinThetaC** [comment]
I'll keep testing until I have a way to reproduce this bug consistently

**Comment by Archengius** [comment]
I don't understand you.
What do you mean by "run out"? Do machines not use fluids? Or do they don't accept them?

**Comment by SinThetaC** [comment]
It seems like the IV pump tries to pull out more fluid than the me system has.
Answering your question, the me system runs out of fluid as in when I look in the fluid terminal, where it shows all the fluids that are in the system, there is no butadiene. However, the chemical reactor and the fluid interface was still full on butadiene, and was never running out. The chemical reactor itself is working fine, I believe, and this bug mainly comes from the way GTCE machines accept fluid and/or how AE2 supplies fluid to the fluid interface.
I suspect that the machines are using fluids properly, but the bug might be based off of how ae2 supplies fluid to fluid interfaces.
Scenario 2: (screenshots)
https://cdn.discordapp.com/attachments/564248854363635722/633495490851373056/unknown.png
https://cdn.discordapp.com/attachments/564248854363635722/633495530735140867/unknown.png
https://cdn.discordapp.com/attachments/564248854363635722/633495574900899870/unknown.png

It also seems like this bug has been discovered by another person, and they found a way to reproduce this bug:
1) create a small AE network with a power source and an energy acceptor
2) attach a fluid terminal and two fluid storage buses on top of an aqueous accumulator and any gregtech machine that accepts fluid as an input
3) fill the gregtech machine input with the fluid to be duped
4) extract infinite fluid from the terminal with tanks or buckets or whatever
5) remove the aqueous accumulator from the network, the fluid is no longer extractable
Link to the message:
https://discordapp.com/channels/564247906991996928/564248854363635722/631164118014885899

**Comment by SinThetaC** [comment]
It seems like it also involves a fluid storage bus on an aqueous accumulator from Thermal Expansion as well. Both the method above to replicate the bug, and my me system, includes a fluid storage bus on an aqueous accumulator.
