### ISSUE TITLE
[Suggestion] Add the Chest Buffer and Super Buffer from GT5

### ISSUE THREAD

**Issue by Tacete** [GregTechCE/GregTech#971]
Issue - It is very hard if not impossible to automate compacting tiny piles of dust that come as a byproduct from ore processing.

I am sure other fixes for this issue have been suggested.  GT5 had blocks called a chest buffer and super buffer.  These allowed item input and, when powered, auto output.  The Super Buffer had no GUI and could hold up to 256 stacks of items.  Using a screwdriver on the face of the block would set the EXACT number of items that it would auto output at a time.  This means you could pump in all of the types of tiny pile of dust you wanted and set the output face that touched the packager to exactly 9 items and it would never put fewer items into the machine "clogging" it.

The sheer number of tiny piles generated through macerating, washing and thermal centrifuging ores quickly fills output buffers stopping processing and it is very irritating.  There are also few mods that allow for this kind of precise item movement.

**Comment by Tacete** [comment]
I though a robot arm would do it but it seme

**Comment by Archengius** [comment]
Robot arm can indeed do it in transfer exact mode.

**Comment by Tacete** [comment]
Yes I saw that.  It seems like the LV robot arm has a small issue with the "supply exact" function.   It wont transfer if the number is greater than 8.  Might be intentional.

**Comment by Archengius** [comment]
Not really, it just do it slower at high rates.
