### ISSUE TITLE
Axe treecapicator does not work with trees from Natura and IC2

### ISSUE THREAD

**Issue by CelestialPhoenix** [GregTechCE/GregTech#973]
Treecapicator function does not work with these trees- the axe just breaks one log at a time.

Natura (4.3.2.69)
IC2 (2.8.70-ex112) 

Running Gregtech 1.8.9.457
(this issue also occured in the previous release of Gtech)
Forge 14.23.5.2838

**Comment by Archengius** [comment]
treecapitator only works either on BlockAbstractLog blocks or blocks registered as logWood in ore dictionary. Not my issue.
