### ISSUE TITLE
Issue when breaking Charset Barrels

### ISSUE THREAD

**Issue by XXxinsanityxX** [GregTechCE/GregTech#974]
I found this minor bug the game does not crash when this happens but if you use the Vanillafix mod you get a notification saying that it did crash, here is the report it generated:

https://paste.dimdev.org/ticunalomi.rb

This happens when you use a GT axe on a Charset barrel with stuff inside, not sure if the issue is with GT axes or with the barrels, if the Vanillafix mod is not installed it just behaves weird and it doesn't break the block.

**Comment by Archengius** [comment]
Charset issue. It passes null to the method which requests non-null argument.
