### ISSUE TITLE
Flint Axe does not work

### ISSUE THREAD

**Issue by Syvio** [GregTechCE/GregTech#982]
The Flint axe in the very beginning of the game. wich should help you cut down the Trees faster than just Block for Block is not working at all. you can craft it but it does nothing.

**Comment by Archengius** [comment]
GTCE Version?

**Comment by Syvio** [comment]
yes exactly. its the GTCE version were you craft the axe with 3 Flints and two wooden sticks.

**Comment by Archengius** [comment]
Provide GTCE version number. Similar bug was fixed like 20 versions ago.

**Comment by Syvio** [comment]
yes exactly. its the GTCE version were you craft the axe with 3 Flints and two wooden sticks.

**Comment by Syvio** [comment]
it is the GCTE version 1.12.2

**Comment by Agrax** [comment]
GTCE is 1.12 only. You have to say which version of GTCE 1.12 is it... Like .257, .357 or the newest: .465

You check that in your mods folder. Three last digits
