### ISSUE TITLE
Placing Bronze Pipe generates (fake) Aluminium Pipe

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#983]
![image](https://user-images.githubusercontent.com/8617528/68550926-860ae600-03d5-11ea-9f6a-0cc099506365.png)

If I right-click a pipe onto this tank, it places an "Aluminium Pipe", which I'm guessing is a case of a missing id# (Aluminium being a default).  

Doesn't happen if I shift-right-click.

If I remove the pipe, I get a normal bronze pipe back.

**Comment by sinopike** [comment]
Happened too me once when placing a wire which transforms into fake aluminium wire.

**Comment by HonzaVinCZ** [comment]
Can confirm that with large steel pipe. Happens sometimes when pipe is placed and connects to something else. If I break that thing and place again, it shows it correctly.

**Comment by LAGIdiot** [comment]
Looking...if problem is still present.

**Comment by LAGIdiot** [comment]
**Version:**
1.9.1 (dev build on 3bfb9c4a87a8e19b7ec75afb690c1dc530a3539a)
**Environment:**
GTCE dev; existing world used (from same version)
**Outcome:**
Bug confirmed

**Comment by BorisMulder** [comment]
I had the same issue with a polyethylene pipe but when I broke the block it actually dropped an aluminium pipe
