### ISSUE TITLE
crash when creating a world

### ISSUE THREAD

**Issue by lampyr** [GregTechCE/GregTech#988]
hi i test a modified modpack and after adding GregTechCE and other mod relating to GregTechCE i got this crash but i can't find the solution for this crash.

crash log : https://gist.github.com/lampyr/a45f2af1af1ae69b7618f59f0d5bd901
log cut because too many text: https://gist.github.com/lampyr/4917e049a2061d88d537a6c857693682
thank you in advance for your help.

**Comment by Agrax** [comment]
I see you’ve added Gregic Additons. This addon doesn’t work with most of the recent versions

**Comment by lampyr** [comment]
It is shadow of greg, i don't have have gregic additions. But i will test without shadow of greg.

**Comment by lampyr** [comment]
Hi after 3 days of test i have find it is this: https://www.curseforge.com/minecraft/mc-mods/arcanum/files/2636463

and i will delete this mod because i think it is not develop anymore and it is private.
