### ISSUE TITLE
Strange bug with GregTech and Buildcraft 

### ISSUE THREAD

**Issue by MadRatSRP** [GregTechCE/GregTech#99]
[crash-2018-06-09_21.47.58-client.txt](https://github.com/GregTechCE/GregTech/files/2087652/crash-2018-06-09_21.47.58-client.txt)

**Comment by AlexIIL** [comment]
Oh, sorry, I reported this yesterday as #95. I might not have linked them properly together though.

**Comment by MadRatSRP** [comment]
Thank you :)

**Comment by AlexIIL** [comment]
So maybe close this?

**Comment by Archengius** [comment]
duplicate
