### ISSUE TITLE
A question about the old battery

### ISSUE THREAD

**Issue by Slix919509299** [GregTechCE/GregTech#990]
When using the battery box to charge the battery, the battery can always charge regardless of the upper limit, so that the green bar can always grow or even exceed the game interface
The mod version used is : gregtech-1.12.2-1.7.1.394
I know that this bug may have been fixed in the new version, but I have modified a lot of composition on the server. If I upgrade to the new version directly, it will lead to confusion in the technology line
Finally, please forgive me for my poor English because I am not from an English speaking country            This is the text translated by the translator
![QG@Y C(EDW_~41TZTQ3G~(6](https://user-images.githubusercontent.com/48668570/69204107-f9a0b600-0b80-11ea-9de6-7a825447e3a5.png)

**Comment by pyure** [comment]
What exactly are you asking for?  If you're asking if its fixed in a new version, you should be able to back up your stuff and test a new version to confirm.

**Comment by Archengius** [comment]
Yes it was fixed 20 versions ago.
